### ISSUE TITLE
Connecting to AWS Postgresql got error when running acapy

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1026]
I'm trying to run my acapy to connect to an AWS postgreSQL by using the below flags:
```
--wallet-type indy 
--wallet-storage-type postgre_storage
--wallet-storage-config "{\"url":\"{aws postgreSQL endpoint}:{port}}\", \"wallet-scheme\":\"multiWalletSingleTable\"}"
--wallet-storage-creds "{\"account\":\"postgres\",\"password\":\"{mypassword when creating the aws postgresql}\", \"admin_account\":\"postgres\",\"admin_password\":\"{mypassword when creating the aws postgresql}\"
```

On the AWS postgresql, i've only setup a simple DB without having any default tables.

When running the acapy command, got below errors:
```
Successfully built 08e6ee62bb1d
Successfully tagged aries-cloudagent-run:latest
2021-03-15 21:56:03,979 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: http://{my vm ip}:9000/genesis
2021-03-15 21:56:03,992 aries_cloudagent.core.profile INFO Create profile manager: indy
2021-03-15 21:56:04,000 aries_cloudagent.indy.sdk.wallet_plugin INFO Checking input postgres storage_config and storage_creds arguments
2021-03-15 21:56:04,001 aries_cloudagent.indy.sdk.wallet_plugin INFO Initializing postgres wallet
2021-03-15 21:58:13,457 aries_cloudagent.indy.sdk.wallet_plugin ERROR Error unable to configure postgres stg: 210
2021-03-15 21:58:13,490 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<run_loop.<locals>.init() done, defined at /home/indy/aries_cloudagent/commands/start.py:69> exception=SystemExit(1,)>
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/commands/start.py", line 101, in run_loop
    loop.run_forever()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
    self._run_once()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 1462, in _run_once
    handle._run()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/indy/aries_cloudagent/core/conductor.py", line 91, in setup
    self.root_profile, self.setup_public_did = await wallet_config(context)
  File "/home/indy/aries_cloudagent/config/wallet.py", line 40, in wallet_config
    profile = await mgr.open(context, profile_cfg)
  File "/home/indy/aries_cloudagent/indy/sdk/profile.py", line 160, in open
    indy_config = IndyWalletConfig(config)
  File "/home/indy/aries_cloudagent/indy/sdk/wallet_setup.py", line 61, in __init__
    load_postgres_plugin(self.storage_config, self.storage_creds)
  File "/home/indy/aries_cloudagent/indy/sdk/wallet_plugin.py", line 60, in load_postgres_plugin
    raise SystemExit(1)
SystemExit: 1
```

Don't know the reason why?

**Comment by ianco** [comment]
Is your postgres database using https?  This is not currently supported.

Long story but I can point you to an old PR - https://github.com/hyperledger/indy-sdk/pull/2157

I could never get this code to work, and no one has had time to pursue it ...

**Comment by yunxi-zhang** [comment]
Hello @ianco, I don't see any https required when i connect to AWS postgresql. When i use pgadmin tool to connect to it, no need to put any SSL config. The endpoint is like this format: {db name}.{random string}.eu-west-2.rds.amazonaws.com

**Comment by yunxi-zhang** [comment]
@ianco , found out my silly mistake by putting the wrong port number. Acapy runs with AWS postgresql now.

**Comment by ianco** [comment]
Great!!!
