### ISSUE TITLE
Register-Nym: Status Code: 422: Unprocessable Entity (missing data)

### ISSUE THREAD

**Issue by markwormgoor** [hyperledger/aries-cloudagent-python#1037]
I'm working on building a controller. I'm using the Node.JS sample to build on. Most of the functions work just fine, but I'm having an odd challenge with /ledger/register-nym. The POST request returns a 422: Unprocessable Entity. The ACA-Py logs show me the data is missing, but it's not (see the third line with the body). Using the same data on the Swagger UI works just fine. 

Note: I'm using a multi-tenancy setup. The token should be fine (it's the right token for a wallet which has the Endorser DID already registered on the ledger). Besides - I have seen other error messages if I make a mistake there - and as said, this token does work when using it on the Swagger UI.

```
wallets  | 2021-03-18 10:53:54,362 aries_cloudagent.admin.server DEBUG Incoming request: POST /ledger/register-nym
wallets  | 2021-03-18 10:53:54,362 aries_cloudagent.admin.server DEBUG Match info: <MatchInfo {}: <ResourceRoute [POST] <PlainResource  /ledger/register-nym> -> <function register_ledger_nym at 0x7f1e522bf158>>
wallets  | 2021-03-18 10:53:54,363 aries_cloudagent.admin.server DEBUG Body: {"did":"ASzfMxF3WYxje1PgdsR1Jy","verkey":"69gBCJBtCZLiab4SB54Z6Tx3P9fVPjqkzkLiACmrRfxV","alias":"Test app 10"}
wallets  | 
wallets  | =================
wallets  | 2021-03-18 10:53:54,364 aries_cloudagent.admin.server ERROR Handler error with exception: Unprocessable Entity
wallets  | Traceback (most recent call last):
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/webargs/asyncparser.py", line 90, in parse
wallets  |     result = schema.load(parsed)
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
wallets  |     data, many=many, partial=partial, unknown=unknown, postprocess=True
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
wallets  |     raise exc
wallets  | marshmallow.exceptions.ValidationError: {'did': ['Missing data for required field.'], 'verkey': ['Missing data for required field.']}
wallets  | 
wallets  | During handling of the above exception, another exception occurred:
wallets  | 
wallets  | Traceback (most recent call last):
wallets  |   File "/home/indy/aries_cloudagent/admin/server.py", line 164, in ready_middleware
wallets  |     return await handler(request)
wallets  |   File "/home/indy/aries_cloudagent/admin/server.py", line 201, in debug_middleware
wallets  |     return await handler(request)
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 34, in validation_middleware
wallets  |     schema["schema"], request, locations=schema["locations"]
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/webargs/asyncparser.py", line 95, in parse
wallets  |     error, req, schema, error_status_code, error_headers
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/webargs/asyncparser.py", line 108, in _on_validation_error
wallets  |     await error_handler(error, req, schema, error_status_code, error_headers)
wallets  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/webargs/aiohttpparser.py", line 166, in handle_error
wallets  |     content_type="application/json",
wallets  | aiohttp.web_exceptions.HTTPUnprocessableEntity: Unprocessable Entity
```

Just for reference, doing the exact same thing with a post to /multitenancy/wallet works just fine.
```
wallets  | 2021-03-18 10:53:53,184 aries_cloudagent.admin.server DEBUG Incoming request: POST /multitenancy/wallet
wallets  | 2021-03-18 10:53:53,184 aries_cloudagent.admin.server DEBUG Match info: <MatchInfo {}: <ResourceRoute [POST] <PlainResource  /multitenancy/wallet> -> <function wallet_create at 0x7f1e521660d0>>
wallets  | 2021-03-18 10:53:53,185 aries_cloudagent.admin.server DEBUG Body: {"image_url":"","key_management_mode":"managed","label":"Test app 10","wallet_dispatch_type":"default","wallet_key":"6KN1QuA1ZFs6Hs9TU0Nd90Ob","wallet_name":"testapp10@testapp","wallet_type":"indy","wallet_webhook_urls":["http://localhost:3000/webhooks"]}
wallets  | 2021-03-18 10:53:53,186 indy.non_secrets DEBUG open_wallet_search: >>> wallet_handle: 2, type_: 'wallet_record', query_json: '{"wallet_name": "testapp10@testapp"}', options_json: '{"retrieveRecords": true, "retrieveTotalCount": false, "retrieveType": false, "retrieveValue": true, "retrieveTags": false}'
wallets  | 2021-03-18 10:53:53,187 indy.non_secrets DEBUG open_wallet_search: Creating callback
wallets  | 2021-03-18 10:53:53,187 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
wallets  | 2021-03-18 10:53:53,187 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x7f1e486a52a0>
wallets  | 2021-03-18 10:53:53,187 indy.libindy DEBUG do_call: >>> name: indy_open_wallet_search, args: (c_int(2), c_char_p(139768168671712), c_char_p(139768040736240), c_char_p(139768206036816), <CFunctionType object at 0x7f1e486a52a0>)
```

**Comment by markwormgoor** [comment]
Note: I'm now also getting this in another function. It seems to have something to with how I post the data. I've tried posting "querystring" encoded data as application/x-www-form-urlencoded and I've tried posting the data in json format as application/json. The results are the same as above. Plus, it is working to create a wallet. Any thoughts on where this is going wrong?

**Comment by markwormgoor** [comment]
Attached is a simple JS file to troubleshoot the issue. I can't seem to find a way to get this to work. Again, no challenges via Swagger with the exact same call and DID. 

[troubleshoot.js.gz](https://github.com/hyperledger/aries-cloudagent-python/files/6170949/troubleshoot.js.gz)

**Comment by swcurran** [comment]
@amanji -- can you help out with this one?  Thanks!

**Comment by swcurran** [comment]
Sorry there was no follow up on this one -- or at least not recorded.  There was likely something local that caused the problem, so closing the issue.
