### ISSUE TITLE
Issue with proof request in Alice/Faber demo

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-cloudagent-python#106]
Currently, the Alice agent fails to locate any credentials, and submits a proof request that doesn't satisfy the requested predicates. This raises the following stack trace:

```
Faber      |     presentation_exchange: {'initiator': 'self', 'presentation_exchange_id': 'a50e9559-212d-450b-ab1d-15c592424bea', 'created_at': '2019-07-30 19:55:43.916985Z', 'thread_id': '66d4316a-50f3-48cd-868d-63fa8d0870c3', 'state': 'presentation_received', 'updated_at': '2019-07-30 19:55:44.542454Z', 'connection_id': 'ac7b9fd1-01a0-4d01-9e66-06c0fdcbce81', 'presentation_request': {'name': 'Proof of Education', 'version': '1.0', 'nonce': '335553867215326759012706530774249534678', 'requested_attributes': {'0c22daa1-662b-44bf-a2a9-859bd2de05bc': {'name': 'name', 'restrictions': [{'issuer_did': 'XL136n65jZBRBkPdvhcbQq'}]}, 'd7bf6d6b-5ca5-4cc4-b2f7-b0a61bd5260b': {'name': 'date', 'restrictions': [{'issuer_did': 'XL136n65jZBRBkPdvhcbQq'}]}, '6c668aed-6e8d-487a-b93b-9c248e9d3dba': {'name': 'degree', 'restrictions': [{'issuer_did': 'XL136n65jZBRBkPdvhcbQq'}]}, 'e21fdb65-8bec-4c58-823e-1d9950b809a4': {'name': 'self_attested_thing'}}, 'requested_predicates': {'b69652e8-63ba-4174-9f05-1494cfb83c07': {'name': 'age', 'p_type': '>=', 'p_value': 18}}}, 'presentation': {'proof': {'proofs': [], 'aggregated_proof': {'c_hash': '99712488383094640367300548209429701069832811062852723912148300184323887867262', 'c_list': []}}, 'requested_proof': {'revealed_attrs': {}, 'self_attested_attrs': {'d7bf6d6b-5ca5-4cc4-b2f7-b0a61bd5260b': 'my self-attested value', '0c22daa1-662b-44bf-a2a9-859bd2de05bc': 'my self-attested value', 'e21fdb65-8bec-4c58-823e-1d9950b809a4': 'my self-attested value', '6c668aed-6e8d-487a-b93b-9c248e9d3dba': 'my self-attested value'}, 'unrevealed_attrs': {}, 'predicates': {}}, 'identifiers': []}}
Faber      | 
Faber      | 2019-07-30 19:55:44,663 aiohttp.server ERROR Error handling request
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
Faber      |     resp = await task
Faber      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
Faber      |     resp = await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/messaging/presentations/routes.py", line 311, in presentation_exchange_verify_credential_presentation
Faber      |     presentation_exchange_record
Faber      |   File "/home/indy/aries_cloudagent/messaging/presentations/manager.py", line 276, in verify_presentation
Faber      |     presentation_request, presentation, schemas, credential_definitions
Faber      |   File "/home/indy/aries_cloudagent/verifier/indy.py", line 44, in verify_presentation
Faber      |     json.dumps({}),
Faber      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/indy/anoncreds.py", line 1390, in verifier_verify_proof
Faber      |     verifier_verify_proof.cb)
Faber      | indy.error.IndyError: (<ErrorCode.CommonInvalidStructure: 113>, {'backtrace': '', 'message': 'Error: Invalid structure\n  Caused by: Requested predicates {"b69652e8-63ba-4174-9f05-1494cfb83c07"} do not correspond to received {}\n'})
```

**Comment by andrewwhitehead** [comment]
Resolved via #108
