### ISSUE TITLE
Is Indy strictly required?

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1127]
I was reworking some integration tests for the resolver plugins today and ran into the following error when the `indy` extra of ACA-Py was not installed and `python3-indy` wasn't already installed in the environment:

```
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 74, in <module>
    main(sys.argv)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 71, in main
    run(args)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 64, in run
    run_command(command, args)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/__init__.py", line 36, in run_command
    module = load_command(command) or load_command("help")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/__init__.py", line 31, in load_command
    return import_module(module_path)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 16, in <module>
    from ..core.conductor import Conductor
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 17, in <module>
    from ..config.default_context import ContextBuilder
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/default_context.py", line 16, in <module>
    from ..ledger.indy import IndySdkLedgerPool, IndySdkLedgerPoolProvider
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 14, in <module>
    import indy.ledger
ModuleNotFoundError: No module named 'indy'
```

To reproduce, you can use the following Dockerfile:
```Dockerfile
FROM bcgovimages/von-image:py36-1.15-1

RUN pip install aries-cloudagent
RUN yes | pip uninstall python3-indy

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
```

I then built and ran the container with:
```
$ docker build -t acapy-test .
$ docker run --rm -it acapy-test start -it http 0.0.0.0 3000 -ot http -e http://localhost:3000 --no-ledger
```

We don't intend Indy to be strictly required, do we?

**Comment by dbluhm** [comment]
@TimoGlastra it looks like the offending line might have been introduced with multi-tenancy changes in December

**Comment by ianco** [comment]
"indy" is an "extra". I think you need to install something like `pip install aries-cloudagent[indy, bbs]`

**Comment by dbluhm** [comment]
Yep, I'm aware, and am taking that approach in my integration tests as a workaround. My question is: is something really an "extra" if it doesn't work without installing the extra? Or in other words, shouldn't this work without installing the `indy` and `bbs` extras?
