### ISSUE TITLE
Are BBS dependencies strictly required?

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1128]
Recently reworking integration tests in the resolver plugins that pull from the main branch, I ran into the following error:

```
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 74, in <module>
    main(sys.argv)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 71, in main
    run(args)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 64, in run
    run_command(command, args)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/__init__.py", line 36, in run_command
    module = load_command(command) or load_command("help")
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/__init__.py", line 31, in load_command
    return import_module(module_path)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 16, in <module>
    from ..core.conductor import Conductor
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 17, in <module>
    from ..config.default_context import ContextBuilder
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/default_context.py", line 16, in <module>
    from ..ledger.indy import IndySdkLedgerPool, IndySdkLedgerPoolProvider
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 29, in <module>
    from ..wallet.indy import IndySdkWallet
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 20, in <module>
    from ..did.did_key import DIDKey
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/did/did_key.py", line 7, in <module>
    from ..vc.ld_proofs.constants import DID_V1_CONTEXT_URL
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/__init__.py", line 1, in <module>
    from .ld_proofs import sign, verify, derive
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/ld_proofs.py", line 7, in <module>
    from .ProofSet import ProofSet
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/ProofSet.py", line 10, in <module>
    from .purposes.ProofPurpose import ProofPurpose
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/purposes/__init__.py", line 1, in <module>
    from .ProofPurpose import ProofPurpose
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/purposes/ProofPurpose.py", line 8, in <module>
    from ..suites import LinkedDataProof
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/suites/__init__.py", line 6, in <module>
    from .BbsBlsSignatureProof2020 import BbsBlsSignatureProof2020
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignatureProof2020.py", line 7, in <module>
    from ursa_bbs_signatures import (
ModuleNotFoundError: No module named 'ursa_bbs_signatures'
```

It would seem that installing requirements from `requirements.bbs.txt` is required; is this intentional?

To reproduce, the following docker file may be used:
```Dockerfile
FROM bcgovimages/von-image:py36-1.15-1

RUN pip install git+https://github.com/hyperledger/aries-cloudagent-python@main

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
```

I then built and ran the container with:
```
$ docker build -t acapy-test .
$ docker run --rm -it acapy-test start -it http 0.0.0.0 3000 -ot http -e http://localhost:3000 --no-ledger
```

**Comment by dbluhm** [comment]
cc @TimoGlastra

**Comment by ianco** [comment]
... or `pip install aries-cloudagent[indy, bbs]@git+https://github.com/hyperledger/aries-cloudagent-python@main`

(not sure of the exact syntax, but the "extras" need to be specified)

**Comment by TimoGlastra** [comment]
It is definitely the intention it can be run without BBS, therefore the separate `requirements.bbs.txt`. Will look into this today
