### ISSUE TITLE
aca-py failing to open wallet

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#113]
This is with the latest master release of aca-py. I had the same problem with the previous release so its not a new bug but I pulled the latest version to see if the new version fixed it but it didn't. The bug is triggered when I supply a --seed parameter. It does not error when I do not supply a seed but then I can't create any schema etc on the ledger because no public DID.

Here is the invocation and debug console output:

```bash
aca-py start \
>         --inbound-transport http 0.0.0.0 8100 \
>         --outbound-transport http \
>         --log-level debug \
>         --endpoint http://localhost:8100 \
>         --label leo \
>         --seed 0123456789ABCDEF0123456789ABCDEF \
>         --genesis-url http://localhost:9000/genesis \
>         --pool-name localindypool \
>         --admin 0.0.0.0 8150 --admin-insecure-mode \
>         --public-invites \
>         --auto-accept-invites \
>         --auto-accept-requests \
>         --auto-ping-connection \
>         --auto-respond-messages \
>         --auto-respond-credential-offer \
>         --auto-respond-presentation-request \
>         --auto-verify-presentation 

2019-08-01 11:44:09,229 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<start_app() done, defined at /Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/commands/start.py:16> exception=TypeError('an integer is required (got type NoneType)')>
Traceback (most recent call last):
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/commands/start.py", line 19, in start_app
    await conductor.start()
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/conductor.py", line 171, in start
    await ledger.update_endpoint_for_did(public_did, endpoint)
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 465, in update_endpoint_for_did
    exist_endpoint = await self.get_endpoint_for_did(did)
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 448, in get_endpoint_for_did
    response_json = await self._submit(request_json, sign=bool(public_did))
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 207, in _submit
    request_result_json = await submit_op
  File "/Data/Code/public/hyperledger/indy/indy-sdk/wrappers/python/indy/ledger.py", line 39, in sign_and_submit_request
    c_wallet_handle = c_int32(wallet_handle)
TypeError: an integer is required (got type NoneType)

```

Attached is the full console output.

```bash
aca-py start \
>         --inbound-transport http 0.0.0.0 8100 \
>         --outbound-transport http \
>         --log-level debug \
>         --endpoint http://localhost:8100 \
>         --label leo \
>         --seed 0123456789ABCDEF0123456789ABCDEF \
>         --genesis-url http://localhost:9000/genesis \
>         --pool-name localindypool \
>         --admin 0.0.0.0 8150 --admin-insecure-mode \
>         --public-invites \
>         --auto-accept-invites \
>         --auto-accept-requests \
>         --auto-ping-connection \
>         --auto-respond-messages \
>         --auto-respond-credential-offer \
>         --auto-respond-presentation-request \
>         --auto-verify-presentation 
2019-08-01 11:44:09,108 asyncio DEBUG Using selector: KqueueSelector
2019-08-01 11:44:09,127 aries_cloudagent.wallet.provider INFO Opening wallet type: basic
2019-08-01 11:44:09,145 aries_cloudagent.ledger.indy DEBUG Opening the pool ledger
2019-08-01 11:44:09,145 indy.pool DEBUG set_protocol_version: >>> protocol_version: 2
2019-08-01 11:44:09,146 indy.pool DEBUG set_protocol_version: Creating callback
2019-08-01 11:44:09,146 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2019-08-01 11:44:09,146 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x10bd65530>
2019-08-01 11:44:09,146 indy.libindy DEBUG do_call: >>> name: indy_set_protocol_version, args: (2, <CFunctionType object at 0x10bd65530>)
2019-08-01 11:44:09,146 indy.libindy DEBUG _load_cdll: >>>
2019-08-01 11:44:09,146 indy.libindy DEBUG _load_cdll: Detected OS name: darwin
2019-08-01 11:44:09,146 indy.libindy DEBUG _load_cdll: Resolved libindy name is: libindy.dylib
2019-08-01 11:44:09,155 indy.libindy DEBUG _load_cdll: <<< res: <CDLL 'libindy.dylib', handle 7fdba145be80 at 0x10bdc9490>
2019-08-01 11:44:09,156 indy.libindy DEBUG set_logger: >>>
2019-08-01 11:44:09,156 indy.libindy DEBUG do_call_sync: >>> name: indy_set_logger, args: (None, None, <CFunctionType object at 0x10bd65600>, None)
2019-08-01 11:44:09,156 indy.libindy DEBUG do_call_sync: <<< 0
2019-08-01 11:44:09,156 indy.libindy DEBUG set_logger: <<<
2019-08-01 11:44:09,157 indy.libindy.native.command_executor INFO 	src/commands/mod.rs:99 | Worker thread started
2019-08-01 11:44:09,157 indy.libindy DEBUG do_call: Function indy_set_protocol_version returned err: 0
2019-08-01 11:44:09,157 indy.libindy DEBUG do_call: <<< <Future pending>
2019-08-01 11:44:09,157 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
2019-08-01 11:44:09,157 indy.libindy.native.pool_command_executor INFO 	src/commands/pool.rs:131 | SetProtocolVersion command received
2019-08-01 11:44:09,158 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:224 | set_protocol_version >>> version: 2
2019-08-01 11:44:09,158 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:232 | set_protocol_version <<<
2019-08-01 11:44:09,158 indy.libindy DEBUG _indy_callback: >>> command_handle: 0, err , args: ()
2019-08-01 11:44:09,158 indy.libindy DEBUG _indy_callback: <<<
2019-08-01 11:44:09,158 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 0, err , args: ()
2019-08-01 11:44:09,158 indy.libindy DEBUG _indy_loop_callback: Function returned None
2019-08-01 11:44:09,158 indy.libindy DEBUG _indy_loop_callback <<<
2019-08-01 11:44:09,158 indy.pool DEBUG set_protocol_version: <<< res: None
2019-08-01 11:44:09,158 aries_cloudagent.ledger.indy DEBUG Creating pool ledger...
2019-08-01 11:44:09,158 indy.pool DEBUG create_pool_ledger_config: >>> config_name: 'default', config: '{"genesis_txn": "/var/folders/w0/gxdpc9094l96snjf_trkgrfm0001z4/T/indy_genesis_transactions.txt"}'
2019-08-01 11:44:09,158 indy.pool DEBUG create_pool_ledger_config: Creating callback
2019-08-01 11:44:09,158 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2019-08-01 11:44:09,158 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x10bd65940>
2019-08-01 11:44:09,159 indy.libindy DEBUG do_call: >>> name: indy_create_pool_ledger_config, args: (c_char_p(4493990032), c_char_p(4493641776), <CFunctionType object at 0x10bd65940>)
2019-08-01 11:44:09,159 indy.libindy DEBUG do_call: Function indy_create_pool_ledger_config returned err: 0
2019-08-01 11:44:09,159 indy.libindy DEBUG do_call: <<< <Future pending>
2019-08-01 11:44:09,159 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
2019-08-01 11:44:09,159 indy.libindy.native.pool_command_executor INFO 	src/commands/pool.rs:62 | Create command received
2019-08-01 11:44:09,159 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:138 | create >>> name: "default", config: Some(PoolConfig { genesis_txn: "/var/folders/w0/gxdpc9094l96snjf_trkgrfm0001z4/T/indy_genesis_transactions.txt" })
2019-08-01 11:44:09,160 indy.libindy DEBUG _get_error_details: >>>
2019-08-01 11:44:09,160 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Pool ledger config already exists\n  Caused by: Pool ledger config file with name "default" already exists\n'}
2019-08-01 11:44:09,160 indy.libindy DEBUG _indy_callback: >>> command_handle: 1, err , args: ()
2019-08-01 11:44:09,160 indy.libindy DEBUG _indy_callback: <<<
2019-08-01 11:44:09,160 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 1, err , args: ()
2019-08-01 11:44:09,160 indy.libindy WARNING _indy_loop_callback: Function returned error 
2019-08-01 11:44:09,160 indy.libindy DEBUG _indy_loop_callback <<<
2019-08-01 11:44:09,161 aries_cloudagent.ledger.indy DEBUG Pool ledger already created.
2019-08-01 11:44:09,161 indy.pool DEBUG open_pool_ledger: >>> config_name: 'default', config: '{}'
2019-08-01 11:44:09,161 indy.pool DEBUG open_pool_ledger: Creating callback
2019-08-01 11:44:09,161 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2019-08-01 11:44:09,161 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x10bd65bb0>
2019-08-01 11:44:09,161 indy.libindy DEBUG do_call: >>> name: indy_open_pool_ledger, args: (c_char_p(4491019760), c_char_p(4493989648), <CFunctionType object at 0x10bd65bb0>)
2019-08-01 11:44:09,162 indy.libindy DEBUG do_call: Function indy_open_pool_ledger returned err: 0
2019-08-01 11:44:09,162 indy.libindy DEBUG do_call: <<< <Future pending>
2019-08-01 11:44:09,162 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
2019-08-01 11:44:09,162 indy.libindy.native.pool_command_executor INFO 	src/commands/pool.rs:70 | Open command received
2019-08-01 11:44:09,162 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:158 | open >>> name: "default", config: Some(PoolOpenConfig { timeout: 20, extended_timeout: 60, conn_limit: 5, conn_active_timeout: 5, preordered_nodes: [] })
2019-08-01 11:44:09,163 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:172 | open <<<
2019-08-01 11:44:09,179 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 0
2019-08-01 11:44:09,179 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 1
2019-08-01 11:44:09,179 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 2
2019-08-01 11:44:09,180 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 3
2019-08-01 11:44:09,226 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
2019-08-01 11:44:09,226 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:74 | OpenAck handle 2, pool_id 2, result Ok(())
2019-08-01 11:44:09,226 indy.libindy DEBUG _indy_callback: >>> command_handle: 2, err , args: (2,)
2019-08-01 11:44:09,226 indy.libindy DEBUG _indy_callback: <<<
2019-08-01 11:44:09,226 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 2, err , args: (2,)
2019-08-01 11:44:09,226 indy.libindy DEBUG _indy_loop_callback: Function returned 2
2019-08-01 11:44:09,226 indy.libindy DEBUG _indy_loop_callback <<<
2019-08-01 11:44:09,226 indy.pool DEBUG open_pool_ledger: <<< res: 2
2019-08-01 11:44:09,227 indy.ledger DEBUG build_get_attrib_request: >>> submitter_did: '3avoBCqDMFHFaKUHug9s8W', target_did: '3avoBCqDMFHFaKUHug9s8W', raw: 'endpoint', xhash: None, enc: None
2019-08-01 11:44:09,227 indy.ledger DEBUG build_get_attrib_request: Creating callback
2019-08-01 11:44:09,227 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2019-08-01 11:44:09,227 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x10bd65e20>
2019-08-01 11:44:09,227 indy.libindy DEBUG do_call: >>> name: indy_build_get_attrib_request, args: (c_char_p(4493632912), c_char_p(4493633040), c_char_p(4493990224), None, None, <CFunctionType object at 0x10bd65e20>)
2019-08-01 11:44:09,227 indy.libindy DEBUG do_call: Function indy_build_get_attrib_request returned err: 0
2019-08-01 11:44:09,227 indy.libindy DEBUG do_call: <<< <Future pending>
2019-08-01 11:44:09,227 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:136 | LedgerCommand command received
2019-08-01 11:44:09,227 indy.libindy.native.ledger_command_executor INFO 	src/commands/ledger.rs:343 | BuildGetAttribRequest command received
2019-08-01 11:44:09,228 indy.libindy.native.indy.commands.ledger DEBUG 	src/commands/ledger.rs:698 | build_get_attrib_request >>> submitter_did: Some("3avoBCqDMFHFaKUHug9s8W"), target_did: "3avoBCqDMFHFaKUHug9s8W", raw: Some("endpoint"), hash: None, enc: None
2019-08-01 11:44:09,228 indy.libindy.native.indy.services.ledger INFO 	src/services/ledger/mod.rs:117 | build_get_attrib_request() => Ok("{\"reqId\":1564681449228407000,\"identifier\":\"3avoBCqDMFHFaKUHug9s8W\",\"operation\":{\"type\":\"104\",\"dest\":\"3avoBCqDMFHFaKUHug9s8W\",\"raw\":\"endpoint\"},\"protocolVersion\":2}")
2019-08-01 11:44:09,228 indy.libindy.native.indy.commands.ledger DEBUG 	src/commands/ledger.rs:710 | build_get_attrib_request <<< res: "{\"reqId\":1564681449228407000,\"identifier\":\"3avoBCqDMFHFaKUHug9s8W\",\"operation\":{\"type\":\"104\",\"dest\":\"3avoBCqDMFHFaKUHug9s8W\",\"raw\":\"endpoint\"},\"protocolVersion\":2}"
2019-08-01 11:44:09,228 indy.libindy DEBUG _indy_callback: >>> command_handle: 3, err , args: (b'{"reqId":1564681449228407000,"identifier":"3avoBCqDMFHFaKUHug9s8W","operation":{"type":"104","dest":"3avoBCqDMFHFaKUHug9s8W","raw":"endpoint"},"protocolVersion":2}',)
2019-08-01 11:44:09,228 indy.libindy DEBUG _indy_callback: <<<
2019-08-01 11:44:09,228 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 3, err , args: (b'{"reqId":1564681449228407000,"identifier":"3avoBCqDMFHFaKUHug9s8W","operation":{"type":"104","dest":"3avoBCqDMFHFaKUHug9s8W","raw":"endpoint"},"protocolVersion":2}',)
2019-08-01 11:44:09,228 indy.libindy DEBUG _indy_loop_callback: Function returned b'{"reqId":1564681449228407000,"identifier":"3avoBCqDMFHFaKUHug9s8W","operation":{"type":"104","dest":"3avoBCqDMFHFaKUHug9s8W","raw":"endpoint"},"protocolVersion":2}'
2019-08-01 11:44:09,229 indy.libindy DEBUG _indy_loop_callback <<<
2019-08-01 11:44:09,229 indy.ledger DEBUG build_get_attrib_request: <<< res: '{"reqId":1564681449228407000,"identifier":"3avoBCqDMFHFaKUHug9s8W","operation":{"type":"104","dest":"3avoBCqDMFHFaKUHug9s8W","raw":"endpoint"},"protocolVersion":2}'
2019-08-01 11:44:09,229 indy.ledger DEBUG sign_and_submit_request: >>> pool_handle: 2, wallet_handle: None, submitter_did: '3avoBCqDMFHFaKUHug9s8W', request_json: '{"reqId":1564681449228407000,"identifier":"3avoBCqDMFHFaKUHug9s8W","operation":{"type":"104","dest":"3avoBCqDMFHFaKUHug9s8W","raw":"endpoint"},"protocolVersion":2}'
2019-08-01 11:44:09,229 indy.ledger DEBUG sign_and_submit_request: Creating callback
2019-08-01 11:44:09,229 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2019-08-01 11:44:09,229 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x10bdb2120>
2019-08-01 11:44:09,229 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<start_app() done, defined at /Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/commands/start.py:16> exception=TypeError('an integer is required (got type NoneType)')>
Traceback (most recent call last):
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/commands/start.py", line 19, in start_app
    await conductor.start()
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/conductor.py", line 171, in start
    await ledger.update_endpoint_for_did(public_did, endpoint)
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 465, in update_endpoint_for_did
    exist_endpoint = await self.get_endpoint_for_did(did)
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 448, in get_endpoint_for_did
    response_json = await self._submit(request_json, sign=bool(public_did))
  File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 207, in _submit
    request_result_json = await submit_op
  File "/Data/Code/public/hyperledger/indy/indy-sdk/wrappers/python/indy/ledger.py", line 39, in sign_and_submit_request
    c_wallet_handle = c_int32(wallet_handle)
TypeError: an integer is required (got type NoneType)
2019-08-01 11:44:14,183 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:555 | socket dropped
2019-08-01 11:44:14,183 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:555 | socket dropped
2019-08-01 11:44:14,183 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:555 | socket dropped
2019-08-01 11:44:14,183 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:555 | socket dropped
2019-08-01 11:44:14,183 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:462 | context dropped
2019-08-01 11:44:14,231 aries_cloudagent.ledger.indy DEBUG Closing pool ledger after timeout
2019-08-01 11:44:14,231 indy.pool DEBUG close_pool_ledger: >>> config_name: 2
2019-08-01 11:44:14,231 indy.pool DEBUG close_pool_ledger: Creating callback
2019-08-01 11:44:14,231 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2019-08-01 11:44:14,231 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x10bdb2390>
2019-08-01 11:44:14,231 indy.libindy DEBUG do_call: >>> name: indy_close_pool_ledger, args: (c_int(2), <CFunctionType object at 0x10bdb2390>)
2019-08-01 11:44:14,232 indy.libindy DEBUG do_call: Function indy_close_pool_ledger returned err: 0
2019-08-01 11:44:14,232 indy.libindy DEBUG do_call: <<< <Future pending>
2019-08-01 11:44:14,232 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
2019-08-01 11:44:14,232 indy.libindy.native.pool_command_executor INFO 	src/commands/pool.rs:94 | Close command received
2019-08-01 11:44:14,232 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:188 | close >>> handle: 2
2019-08-01 11:44:14,232 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:737 | Drop started
2019-08-01 11:44:14,232 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:745 | Drop wait worker
2019-08-01 11:44:14,233 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:555 | socket dropped
2019-08-01 11:44:14,233 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:748 | Drop finished
2019-08-01 11:44:14,234 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:555 | socket dropped
2019-08-01 11:44:14,234 indy.libindy.native.zmq DEBUG 	/Users/samuel/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.3/src/lib.rs:462 | context dropped
2019-08-01 11:44:14,235 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:202 | close <<<
2019-08-01 11:44:14,235 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
2019-08-01 11:44:14,235 indy.libindy.native.pool_command_executor INFO 	src/commands/pool.rs:98 | CloseAck command received
2019-08-01 11:44:14,235 indy.libindy DEBUG _indy_callback: >>> command_handle: 4, err , args: ()
2019-08-01 11:44:14,235 indy.libindy DEBUG _indy_callback: <<<
2019-08-01 11:44:14,235 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 4, err , args: ()
2019-08-01 11:44:14,235 indy.libindy DEBUG _indy_loop_callback: Function returned None
2019-08-01 11:44:14,235 indy.libindy DEBUG _indy_loop_callback <<<
2019-08-01 11:44:14,236 indy.pool DEBUG close_pool_ledger: <<< res: None



```

**Comment by ianco** [comment]
aca-py doesn't register DID's on the ledger so you need to register your DID in advance, before starting aca-py

If you are running von-network you can register your did using the ledger browser UI.

**Comment by SmithSamuelM** [comment]
Sorry for the confusion. I did register the DID on the ledger beforehand. It still creates this error. So maybe its just trying to put the DID it is creating from the seed into its wallet and that fails.

**Comment by SmithSamuelM** [comment]
I need the public did in order to put stuff on the ledger like credentials. Its not clear to me what all the steps are on boot up.

**Comment by ianco** [comment]
I'll have to defer to @andrewwhitehead  or @nrempel  on this question
