### ISSUE TITLE
Shut down ACA-Py agent and rerun it will cause revocation error 

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1173]
I use ACA-Py agents to connect to my PostgreSQL DB as the wallet storage, use von-network as the dev DLT and indy-tails-server as the dev tails server.

After creating credential schema and definition with the revocation flag is on, when the holder agent calls api:  /present-proof/records/{prex-ex-id}/send-presentation, it shows an error in my previous ticket: #1172 . However, after I shut down the agent, and rerun it, and call the same API again, I've got below error:

```
500 Internal Server Error

Server got itself in trouble
```
When checking on the logs of the agent, it gives below error indicating it comes from the tails file.
```
=================
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/admin/server.py", line 164, in ready_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 201, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 317, in check_multitenant_authorization
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 362, in setup_context
    return await task
  File "/home/indy/aries_cloudagent/protocols/present_proof/v1_0/routes.py", line 1002, in presentation_exchange_send_presentation
    comment=body.get("comment"),
  File "/home/indy/aries_cloudagent/protocols/present_proof/v1_0/manager.py", line 372, in create_presentation
    tails_local_path = await rev_reg.get_or_fetch_local_tails_path()
  File "/home/indy/aries_cloudagent/revocation/models/revocation_registry.py", line 198, in get_or_fetch_local_tails_path
    return await self.retrieve_tails()
  File "/home/indy/aries_cloudagent/revocation/models/revocation_registry.py", line 187, in retrieve_tails
    "The hash of the downloaded tails file does not match."
aries_cloudagent.revocation.error.RevocationError: The hash of the downloaded tails file does not match.
2021-05-13 16:07:13,522 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 164, in ready_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 201, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 317, in check_multitenant_authorization
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 362, in setup_context
    return await task
  File "/home/indy/aries_cloudagent/protocols/present_proof/v1_0/routes.py", line 1002, in presentation_exchange_send_presentation
    comment=body.get("comment"),
  File "/home/indy/aries_cloudagent/protocols/present_proof/v1_0/manager.py", line 372, in create_presentation
    tails_local_path = await rev_reg.get_or_fetch_local_tails_path()
  File "/home/indy/aries_cloudagent/revocation/models/revocation_registry.py", line 198, in get_or_fetch_local_tails_path
    return await self.retrieve_tails()
  File "/home/indy/aries_cloudagent/revocation/models/revocation_registry.py", line 187, in retrieve_tails
    "The hash of the downloaded tails file does not match."
aries_cloudagent.revocation.error.RevocationError: The hash of the downloaded tails file does not match.

```
Is there a limitation of the tails file server that doesn't support rerun of the ACA-Py agent or is this a bug of ACA-Py agent?

**Comment by swcurran** [comment]
@ianco -- can you please take a look at this one?  It seems pretty odd.  The tails server is pretty simple, and there is not a lot that could go wrong.  It seems to be mulit-tenant mode, so perhaps something there, but it would be surprising.

@yunxi-zhang if there is any more information you can provide -- notably what CLI commands you ran in the sequence.

**Comment by yunxi-zhang** [comment]
@swcurran, the sequence of CLI commands i've used are shown below:
1. run von-network by killing any existing containers by running `./manage rm`, and then run `./manage up`.
2. run tails file server by killing any existing containers by running `./manage rm`, and then run `./manage up`.
3. Run 3 ACA-Py agent v0.6.0, and each will connect to one of my AWS PostgreSQLs. Below shows the issuer agent only. I've used the variables in the format of {} to replace real info for privacy.
![image](https://user-images.githubusercontent.com/16185797/118500452-b4325a00-b71f-11eb-87ac-ff752e04b241.png)

**Comment by ianco** [comment]
Hi @yunxi-zhang can you post your aca-py startup command as text rather than as an image?  I will try to reproduce your error on my local ...

**Comment by yunxi-zhang** [comment]
[acapy cmd.txt](https://github.com/hyperledger/aries-cloudagent-python/files/6495333/acapy.cmd.txt)
Whenever copying and pasting my command here, it becomes an image. @ianco , please download the file attached here, i've put command in it.

**Comment by ianco** [comment]
Hi @yunxi-zhang , I haven't been able to duplicate your error, and I don't see anywhere in the aca-py code that could be causing this problem.  I suspect it may be due to the ngrok endpoint - if you are using the "free" ngrok then these endpoints will timeout after awhile, or will start returning connection errors if you make too many requests.

Try manually downloading the tails file, using curl.  You can get the full tails url using the aca-py endpoint `/revocation/active-registry/{cred_def_id}` - the `tails_public_uri` us the full url of the tails file and you should be able to curl this.  If your problem is with ngrok then you will get an ngrok error with this curl command.

The "hash" is just a sha256 of the downloaded file, so if the file downloads successfully you can compare the sha256 of your downloaded file vs the `tails_hash` in the `/revocation/active-registry/{cred_def_id}` response.

**Comment by yunxi-zhang** [comment]
Hello @ianco, thanks for your help. I'm not fully understand when you mention "free" ngrok. The ngrok url is auto generated when running the tail server. How can I use a "non-free" ngrok in this case?

**Comment by swcurran** [comment]
By "free" Ian means not paying for an account on the ngrok service.  Non-free means you pay for the service and get a more capable service.

**Comment by yunxi-zhang** [comment]
Thanks for your response @swcurran. I think my next question is if I use a non-free ngrok, how does it link to the ngrok url auto generated in the tails server? Will I expect to configure the ngrok url in my ngrok account to make it stable?

**Comment by yunxi-zhang** [comment]
Hello @ianco, could you help answer my question below? 

If I use a non-free ngrok, how does it link to the ngrok url auto generated in the tails server? Will I expect to configure the ngrok url in my ngrok account to make it stable?

Thanks!

**Comment by ianco** [comment]
Hi @yunxi-zhang , generally you only use ngrok in a development environment (or maybe a test or demo environment) but not production.  In production you would publish any public url's that you need to expose, how you do this would depend on the platform you are running on (AWS, Azure, etc).  We use free ngrok for demo's because that allows you to publish ports that you are running on a local workstation, and then connect to (for example) a mobile app on a phone.

**Comment by swcurran** [comment]
FYI -- here is the pricing page for ngrok: https://ngrok.com/pricing

Would the limitations of the free plan vs. paid likely to have affected your test?

**Comment by esune** [comment]
I have seen this issue before, and it is potentially caused by the URL of the `tails-server` changing between runs: if the revocation registry (and tails file) definition was already created, aca-py will try to use the "old" `ngrok` URL to download the file, getting an error page that does not match the hash of the expected file.

A way to confirm this is to remote into the running agent pod and check the contents of the downloaded tails file, it will be fairly obvious it is not what the agent expected.

What @ianco said about only using `ngrok` for development is correct, as revocation is - unfortunately - affected by this reference issue.
