### ISSUE TITLE
Validation of JSON-LD credentials - should validate on submission

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1205]
Current behaviour is - if a json-ld credential is submitted (`/send` or `send-offer`) it will be validated when the credential is issued.

Expected behaviour - the credential contents should be validated when the `/send` or `/send-offer` endpoint is called (as well as when the credential is issued) so that the issuer knows the credential is not valid.  With the existing validation it fails partway through the issuing process (after the holder has received the offer and requested the credential).

Stack trace at credential issue:

```
Faber      | 2021-05-26 17:26:19,259 aries_cloudagent.core.dispatcher ERROR Handler error: credential_exchange_issue
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1315, in credential_exchange_issue
Faber      |     comment=comment,
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 488, in issue_credential
Faber      |     cred_ex_record
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py", line 399, in issue_credential
Faber      |     purpose=proof_purpose,
Faber      |   File "/home/indy/aries_cloudagent/vc/vc_ld/issue.py", line 58, in issue
Faber      |     document_loader=document_loader,
Faber      |   File "/home/indy/aries_cloudagent/vc/ld_proofs/ld_proofs.py", line 41, in sign
Faber      |     document_loader=document_loader,
Faber      |   File "/home/indy/aries_cloudagent/vc/ld_proofs/ProofSet.py", line 52, in add
Faber      |     document=input, purpose=purpose, document_loader=document_loader
Faber      |   File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020.py", line 71, in create_proof
Faber      |     proof=proof, document=document, document_loader=document_loader
Faber      |   File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020.py", line 150, in _create_verify_data
Faber      |     document=document, document_loader=document_loader
Faber      |   File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020Base.py", line 34, in _create_verify_document_data
Faber      |     c14n_doc = self._canonize(input=document, document_loader=document_loader)
Faber      |   File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/LinkedDataProof.py", line 122, in _canonize
Faber      |     f"{len(missing_properties)} attributes dropped. "
```

**Comment by TimoGlastra** [comment]
I agree!

There are multiple checks performed at different layers. I'll see which checks are done and how easy each of them can be moved to the `send` or `send-offer` endpoints.

For now I can think of the following:
- Attributes dropped
- Valid VC structure (this is already done I believe)
- Valid issuer did (not sure if this is already done)
- Valid Signature Suite (this is already  done I believe)
- issuer did supports signature suite (I think this is done?)

**Comment by swcurran** [comment]
Closing this. If/When we get back to JSON-LD verifiable credentials we can relook at this. Others are welcome to work on designs and PRs for these types of issues.
