### ISSUE TITLE
DIF PE Tests - pyld.jsonld.JsonLdError

### ISSUE THREAD

**Issue by shaangill025** [hyperledger/aries-cloudagent-python#1251]
- DIF PE tests are failing with the following error, as I was working on #1250
`pyld.jsonld.JsonLdError: ('Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin pol....`
With commit a9d818315202030eac2afbd80585260420d579ae [#1250] earlier today, all tests were successful.
- As I was investigating, I found that even running the tests on ACA-Py `main` now triggers the same errors.

@TimoGlastra Any ideas?

```
url = 'https://www.w3.org/2018/credentials/v1', options = {'documentLoader': <function requests_document_loader.<locals>.loader at 0x7f11c13d8730>, 'headers': {'Accept': 'appli...w3.org/ns/json-ld#context, application/ld+json, application/json;q=0.5, text/html;q=0.8, application/xhtml+xml;q=0.8'}}

    def loader(url, options={}):
        """
        Retrieves JSON-LD at the given URL.

        :param url: the URL to retrieve.

        :return: the RemoteDocument.
        """
        try:
            # validate URL
            pieces = urllib_parse.urlparse(url)
            if (not all([pieces.scheme, pieces.netloc]) or
                pieces.scheme not in ['http', 'https'] or
                set(pieces.netloc) > set(
                    string.ascii_letters + string.digits + '-.:')):
                raise JsonLdError(
                    'URL could not be dereferenced; only "http" and "https" '
                    'URLs are supported.',
                    'jsonld.InvalidUrl', {'url': url},
                    code='loading document failed')
            if secure and pieces.scheme != 'https':
                raise JsonLdError(
                    'URL could not be dereferenced; secure mode enabled and '
                    'the URL\'s scheme is not "https".',
                    'jsonld.InvalidUrl', {'url': url},
                    code='loading document failed')
            headers = options.get('headers')
            if headers is None:
                headers = {
                    'Accept': 'application/ld+json, application/json'
                }
            response = requests.get(url, headers=headers, **kwargs)

            content_type = response.headers.get('content-type')
            if not content_type:
                content_type = 'application/octet-stream'
            doc = {
                'contentType': content_type,
                'contextUrl': None,
                'documentUrl': response.url,
                'document': response.json()
            }
            link_header = response.headers.get('link')
            if link_header:
                linked_context = parse_link_header(link_header).get(
                    LINK_HEADER_REL)
                # only 1 related link header permitted
                if linked_context and content_type != 'application/ld+json':
                  if isinstance(linked_context, list):
                      raise JsonLdError(
                          'URL could not be dereferenced, '
                          'it has more than one '
                          'associated HTTP Link Header.',
                          'jsonld.LoadDocumentError',
                          {'url': url},
                          code='multiple context link headers')
                  doc['contextUrl'] = linked_context['target']
                linked_alternate = parse_link_header(link_header).get('alternate')
                # if not JSON-LD, alternate may point there
                if (linked_alternate and
                        linked_alternate.get('type') == 'application/ld+json' and
                        not re.match(r'^application\/(\w*\+)?json$', content_type)):
                    doc['contentType'] = 'application/ld+json'
                    doc['documentUrl'] = jsonld.prepend_base(url, linked_alternate['target'])
            return doc
        except JsonLdError as e:
            raise e
        except Exception as cause:
            raise JsonLdError(
                'Could not retrieve a JSON-LD document from the URL.',
                'jsonld.LoadDocumentError', code='loading document failed',
>               cause=cause)
E           pyld.jsonld.JsonLdError: ('Could not retrieve a JSON-LD document from the URL.',)
E           Type: jsonld.LoadDocumentError
E           Code: loading document failed
E           Cause: Expecting value: line 1 column 1 (char 0)  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/documentloader/requests.py", line 72, in loader
E               'document': response.json()
E             File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/requests/models.py", line 900, in json
E               return complexjson.loads(self.text, **kwargs)
E             File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/__init__.py", line 354, in loads
E               return _default_decoder.decode(s)
E             File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/decoder.py", line 339, in decode
E               obj, end = self.raw_decode(s, idx=_w(s, 0).end())
E             File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/decoder.py", line 357, in raw_decode
E               raise JSONDecodeError("Expecting value", s, err.value) from None

../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/documentloader/requests.py:103: JsonLdError

During handling of the above exception, another exception occurred:

self = <aries_cloudagent.protocols.issue_credential.v2_0.formats.ld_proof.tests.test_handler.TestV20LDProofCredFormatHandler testMethod=test_store_credential>

    async def test_store_credential(self):
        cred_issue = V20CredIssue(
            formats=[
                V20CredFormat(
                    attach_id="0",
                    format_=ATTACHMENT_FORMAT[CRED_20_ISSUE][
                        V20CredFormat.Format.LD_PROOF.api
                    ],
                )
            ],
            credentials_attach=[AttachDecorator.data_base64(LD_PROOF_VC, ident="0")],
        )

        cred_ex_record = V20CredExRecord(
            cred_ex_id="dummy-cxid",
            cred_issue=cred_issue,
        )

        cred_id = "cred_id"
        self.holder.store_credential = async_mock.CoroutineMock()

        with async_mock.patch.object(
            LDProofCredFormatHandler,
            "_get_suite",
            async_mock.CoroutineMock(),
        ) as mock_get_suite, async_mock.patch.object(
            test_module,
            "verify_credential",
            async_mock.CoroutineMock(
                return_value=DocumentVerificationResult(verified=True)
            ),
        ) as mock_verify_credential, async_mock.patch.object(
            LDProofCredFormatHandler,
            "_get_proof_purpose",
        ) as mock_get_proof_purpose:
>           await self.handler.store_credential(cred_ex_record, cred_id)

aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/tests/test_handler.py:871:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py:574: in store_credential
    expanded = jsonld.expand(cred_dict)
../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py:163: in expand
    return JsonLdProcessor().expand(input_, options)
../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py:871: in expand
    inside_list=False)
../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py:2303: in _expand
    active_ctx, element['@context'], options)
../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py:3049: in _process_context
    resolved = options['contextResolver'].resolve(active_ctx, local_ctx, options.get('base', ''))
../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/context_resolver.py:59: in resolve
    active_ctx, ctx, base, cycles)
../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/context_resolver.py:108: in _resolve_remote_context
    context, remote_doc = self._fetch_context(active_ctx, url, cycles)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pyld.context_resolver.ContextResolver object at 0x7f11a7225e48>, active_ctx = frozendict({'_uuid': '008eb45e-d154-11eb-a846-0242ac110002', 'processingMode': 'json-ld-1.1', 'mappings': {}}), url = 'https://www.w3.org/2018/credentials/v1', cycles = {'https://www.w3.org/2018/credentials/v1'}

    def _fetch_context(self, active_ctx, url, cycles):
        # check for max context URLs fetched during a resolve operation
        if len(cycles) > MAX_CONTEXT_URLS:
            raise jsonld.JsonLdError(
                'Maximum number of @context URLs exceeded.',
                'jsonld.ContextUrlError', {'max': MAX_CONTEXT_URLS},
                code=('loading remote context failed'
                      if active_ctx.get('processingMode') == 'json-ld-1.0'
                      else 'context overflow'))

        # check for context URL cycle
        # shortcut to avoid extra work that would eventually hit the max above
        if url in cycles:
            raise jsonld.JsonLdError(
                'Cyclical @context URLs detected.',
                'jsonld.ContextUrlError', {'url': url},
                code=('recursive context inclusion'
                      if active_ctx.get('processingMode') == 'json-ld-1.0'
                      else 'context overflow'))

        # track cycles
        cycles.add(url)

        try:
            remote_doc = jsonld.load_document(url,
                {'documentLoader': self.document_loader},
                requestProfile='http://www.w3.org/ns/json-ld#context')
            context = remote_doc.get('document', url)
        except Exception as cause:
            raise jsonld.JsonLdError(
                'Dereferencing a URL did not result in a valid JSON-LD object. ' +
                'Possible causes are an inaccessible URL perhaps due to ' +
                'a same-origin policy (ensure the server uses CORS if you are ' +
                'using client-side JavaScript), too many redirects, a ' +
                'non-JSON response, or more than one HTTP Link Header was ' +
                'provided for a remote context.',
                'jsonld.InvalidUrl',
                {'url': url, 'cause': cause},
>               code='loading remote context failed')
E           pyld.jsonld.JsonLdError: ('Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.',)
E           Type: jsonld.InvalidUrl
E           Code: loading remote context failed
E           Details: {'url': 'https://www.w3.org/2018/credentials/v1', 'cause': JsonLdError('Could not retrieve a JSON-LD document from the URL.',)}

../.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/context_resolver.py:157: JsonLdError
```

**Comment by shaangill025** [comment]
- Error: issue-credential-v2 workflow
When trying to store a received credential
`Holder` agent
```
=================
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1409, in credential_exchange_store
    cred_ex_record = await cred_manager.store_credential(cred_ex_record, cred_id)
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 592, in store_credential
    f"Credential exchange {cred_ex_record.cred_ex_id} "
aries_cloudagent.protocols.issue_credential.v2_0.manager.V20CredManagerError: Credential exchange 3f0be9ef-c2e4-4efd-85f1-e3ea32c3935f in request-sent state (must be credential-received)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1424, in credential_exchange_store
    outbound_handler,
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/__init__.py", line 60, in report_problem
    raise http_error_class(reason=err.roll_up) from err
aiohttp.web_exceptions.HTTPBadRequest: Credential exchange 3f0be9ef-c2e4-4efd-85f1-e3ea32c3935f in request-sent state (must be credential-received).
2021-06-19 23:53:43,485 aries_cloudagent.utils.tracing INFO   {"msg_id": "d8172d2f-473c-4604-8f8e-04346efa81ad", "thread_id": "7de4f2e4-77df-4db4-bdfe-2b1badbe48d0", "traced_type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/2.0/request-credential", "timestamp": 1624146823.4850147, "str_time": "2021-06-19 23:53:43.485015", "handler": "aca-py.agent", "ellapsed_milli": 39, "outcome": "credential_exchange_send_bound_request.END"}
2021-06-19 23:53:43,486 aries_cloudagent.utils.tracing INFO   {"msg_id": "d8172d2f-473c-4604-8f8e-04346efa81ad", "thread_id": "7de4f2e4-77df-4db4-bdfe-2b1badbe48d0", "traced_type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/2.0/request-credential", "timestamp": 1624146823.4861443, "str_time": "2021-06-19 23:53:43.486144", "handler": "aca-py.agent", "ellapsed_milli": 0, "outcome": "OutboundTransportManager.ENCODE.START"}
2021-06-19 23:53:43,486 aries_cloudagent.utils.tracing INFO   {"msg_id": "d8172d2f-473c-4604-8f8e-04346efa81ad", "thread_id": "7de4f2e4-77df-4db4-bdfe-2b1badbe48d0", "traced_type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/2.0/request-credential", "timestamp": 1624146823.4867232, "str_time": "2021-06-19 23:53:43.486723", "handler": "aca-py.agent", "ellapsed_milli": 0, "outcome": "OutboundTransportManager.ENCODE.END"}
2021-06-19 23:53:43,491 aries_cloudagent.utils.tracing INFO   {"msg_id": "d8172d2f-473c-4604-8f8e-04346efa81ad", "thread_id": "7de4f2e4-77df-4db4-bdfe-2b1badbe48d0", "traced_type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/2.0/request-credential", "timestamp": 1624146823.4915807, "str_time": "2021-06-19 23:53:43.491581", "handler": "aca-py.agent", "ellapsed_milli": 0, "outcome": "OutboundTransportManager.DELIVER.START.http://host.docker.internal:8002"}
2021-06-19 23:53:43,492 aries_cloudagent.utils.tracing INFO   {"msg_id": "d8172d2f-473c-4604-8f8e-04346efa81ad", "thread_id": "7de4f2e4-77df-4db4-bdfe-2b1badbe48d0", "traced_type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/2.0/request-credential", "timestamp": 1624146823.4924905, "str_time": "2021-06-19 23:53:43.492491", "handler": "aca-py.agent", "ellapsed_milli": 0, "outcome": "OutboundTransportManager.DELIVER.END.http://host.docker.internal:8002"}
2021-06-19 23:53:49,851 aries_cloudagent.admin.server ERROR Handler error with exception: Credential exchange 3e59d803-0c9b-4ad6-802c-775e63894f79 in request-sent state (must be credential-received).

=================
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1409, in credential_exchange_store
    cred_ex_record = await cred_manager.store_credential(cred_ex_record, cred_id)
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 592, in store_credential
    f"Credential exchange {cred_ex_record.cred_ex_id} "
aries_cloudagent.protocols.issue_credential.v2_0.manager.V20CredManagerError: Credential exchange 3e59d803-0c9b-4ad6-802c-775e63894f79 in request-sent state (must be credential-received)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1424, in credential_exchange_store
    outbound_handler,
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/__init__.py", line 60, in report_problem
    raise http_error_class(reason=err.roll_up) from err
aiohttp.web_exceptions.HTTPBadRequest: Credential exchange 3e59d803-0c9b-4ad6-802c-775e63894f79 in request-sent state (must be credential-received).
```

`Issuer` agent
```
pyld.jsonld.JsonLdError: ('Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.',)
Type: jsonld.InvalidUrl
Code: loading remote context failed
Details: {'url': 'https://www.w3.org/2018/credentials/v1', 'cause': JsonLdError('Could not retrieve a JSON-LD document from the URL.',)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/core/dispatcher.py", line 198, in handle_message
    await handler(context, responder)
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/handlers/cred_request_handler.py", line 63, in handle
    comment=context.message.comment,
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 488, in issue_credential
    cred_ex_record
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py", line 467, in issue_credential
    purpose=proof_purpose,
  File "/home/indy/aries_cloudagent/vc/vc_ld/issue.py", line 58, in issue
    document_loader=document_loader,
  File "/home/indy/aries_cloudagent/vc/ld_proofs/ld_proofs.py", line 41, in sign
    document_loader=document_loader,
  File "/home/indy/aries_cloudagent/vc/ld_proofs/ProofSet.py", line 52, in add
    document=input, purpose=purpose, document_loader=document_loader
  File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020.py", line 71, in create_proof
    proof=proof, document=document, document_loader=document_loader
  File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020.py", line 147, in _create_verify_data
    proof=proof, document=document, document_loader=document_loader
  File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020Base.py", line 23, in _create_verify_proof_data
    proof=proof, document=document, document_loader=document_loader
  File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/BbsBlsSignature2020.py", line 164, in _canonize_proof
    return self._canonize(input=proof, document_loader=document_loader)
  File "/home/indy/aries_cloudagent/vc/ld_proofs/suites/LinkedDataProof.py", line 118, in _canonize
    missing_properties = get_properties_without_context(input, document_loader)
  File "/home/indy/aries_cloudagent/vc/ld_proofs/check.py", line 93, in get_properties_without_context
    {"documentLoader": document_loader},
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py", line 142, in compact
    return JsonLdProcessor().compact(input_, ctx, options)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py", line 721, in compact
    'jsonld.CompactError', cause=cause)
pyld.jsonld.JsonLdError: ('Could not expand input before compaction.',)
Type: jsonld.CompactError
Cause: ('Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.',)
Type: jsonld.InvalidUrl
Code: loading remote context failed
Details: {'url': 'https://www.w3.org/2018/credentials/v1', 'cause': JsonLdError('Could not retrieve a JSON-LD document from the URL.',)}  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py", line 717, in compact
    expanded = self.expand(input_, options)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py", line 871, in expand
    inside_list=False)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py", line 2303, in _expand
    active_ctx, element['@context'], options)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/jsonld.py", line 3049, in _process_context
    resolved = options['contextResolver'].resolve(active_ctx, local_ctx, options.get('base', ''))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/context_resolver.py", line 59, in resolve
    active_ctx, ctx, base, cycles)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/context_resolver.py", line 108, in _resolve_remote_context
    context, remote_doc = self._fetch_context(active_ctx, url, cycles)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pyld/context_resolver.py", line 157, in _fetch_context
    code='loading remote context failed')
```

**Comment by TimoGlastra** [comment]
Tests are passing for me locally... (both main and the branch of this pr) Are you still running into the issue?

**Comment by shaangill025** [comment]
Double checked that tests are passing now without any changes, not sure what caused the error yesterday.
