### ISSUE TITLE
Error sending BBS+ Credential

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1258]
I ran through the new [Alice Wants a JSON-LD Credential]() and got the following error on the `/credential/send` step.

After doing the connection and create BLS key steps, I submitted this JSON:

``` JSONC
{
  "connection_id": "c299be9e-ffc3-4201-b533-7e87d97e3a36",
  "filter": {
    "ld_proof": {
      "credential": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://www.w3.org/2018/credentials/examples/v1"
        ],
        "type": ["VerifiableCredential", "UniversityDegreeCredential"],
        "issuer": "did:key:zUC79sFqQHjeCrkH78hgGa1ruexJiGkM63Gqns5jHn2CW8S9t5UjWvXqJK59CVQhKKKuYfErw5LMDbXLVUqDEwzPQaGqAeoPn9B4P9zz3WhAiztoLjnP1TSgNc4BLo7DmMsC1ct",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "id": "did:key:zUC73T9PSE81wmwcUNST8kG6ZWJuBHGwyYDQnsfQ7KgmQsQhp9p3XFSAEn1sBs6pnQHayqvHtgCrzPEhD9fQHHgUodD8phyxDB9XwcQSmbaYgWfPcVz4nEtGwVXbPgRmdpnWZxm",
          "givenName": "Sally",
          "familyName": "Student",
          "degree": {
            "type": "BachelorDegree",
            "degreeType": "Undergraduate",
            "name": "Bachelor of Science and Arts"
          },
          "college": "Faber College"
        }
      },
      "options": {
        "proofType": "BbsBlsSignature2020"
      }
    }
  }
}
```

and got the following error in Faber:

```
Faber      | 2021-06-23 15:29:13,070 aries_cloudagent.admin.server ERROR Handler error with exception: Unprocessable Entity
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/webargs/asyncparser.py", line 90, in parse
Faber      |     result = schema.load(parsed)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
Faber      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
Faber      |     raise exc
Faber      | marshmallow.exceptions.ValidationError: {'credential_proposal': ['Missing data for required field.']}
Faber      | 
Faber      | During handling of the above exception, another exception occurred:
Faber      | 
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 162, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 199, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 34, in validation_middleware
Faber      |     schema["schema"], request, locations=schema["locations"]
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/webargs/asyncparser.py", line 95, in parse
Faber      |     error, req, schema, error_status_code, error_headers
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/webargs/asyncparser.py", line 108, in _on_validation_error
Faber      |     await error_handler(error, req, schema, error_status_code, error_headers)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/webargs/aiohttpparser.py", line 166, in handle_error
Faber      |     content_type="application/json",
Faber      | aiohttp.web_exceptions.HTTPUnprocessableEntity: Unprocessable Entity
Faber      | 
```

**Comment by swcurran** [comment]
@shaangill025 -- can you please take a look?

**Comment by shaangill025** [comment]
Are you using the Admin API for Faber? Looking at `credential_proposal` validationError, looks like the `issue-credential v1.0` endpoint was called. I tried a similar credential yesterday, it worked but I called `/issue-credential-2.0/send-offer`.

**Comment by swcurran** [comment]
Doh...user error.  Thanks.

The Swagger UI is terrible.  Is there an alternative that people use?

**Comment by swcurran** [comment]
That was it...closing.
