### ISSUE TITLE
Faber agent in Open API Swagger demo during connection acceptance from Alice produces 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by iamgollum** [hyperledger/aries-cloudagent-python#1269]
Observation
---

During the [Faber Agent Gets The Request](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md#the-faber-agent-gets-the-request) a `NoneType object is not iterable` error is produced yielding a `500: Server to itself in trouble`.

```
aber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable
Faber      | 2021-06-27 18:04:14,949 aries_cloudagent.core.dispatcher ERROR Handler error: connections_accept_invitation
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 617, in connections_accept_invitation
Faber      |     await outbound_handler(request, connection_id=connection.connection_id)
Faber      |   File "/home/indy/aries_cloudagent/messaging/responder.py", line 82, in send
Faber      |     return await self.send_outbound(outbound)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 127, in send_outbound
Faber      |     return await self._send(self._profile, message)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 473, in outbound_message_router
Faber      |     return await self.queue_outbound(profile, outbound, inbound)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 506, in queue_outbound
Faber      |     connection_id=outbound.connection_id
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/manager.py", line 1104, in get_connection_targets
Faber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable
Faber      | 2021-06-27 18:04:14,949 aries_cloudagent.admin.server ERROR Handler error with exception: 'NoneType' object is not iterable
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 162, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 199, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 366, in setup_context
Faber      |     return await task
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 617, in connections_accept_invitation
Faber      |     await outbound_handler(request, connection_id=connection.connection_id)
Faber      |   File "/home/indy/aries_cloudagent/messaging/responder.py", line 82, in send
Faber      |     return await self.send_outbound(outbound)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 127, in send_outbound
Faber      |     return await self._send(self._profile, message)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 473, in outbound_message_router
Faber      |     return await self.queue_outbound(profile, outbound, inbound)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 506, in queue_outbound
Faber      |     connection_id=outbound.connection_id
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/manager.py", line 1104, in get_connection_targets
Faber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable
Faber      | 2021-06-27 18:04:14,949 aiohttp.server ERROR Error handling request
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
Faber      |     resp = await self._request_handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 499, in _handle
Faber      |     resp = await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 162, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 199, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 366, in setup_context
Faber      |     return await task
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 617, in connections_accept_invitation
Faber      |     await outbound_handler(request, connection_id=connection.connection_id)
Faber      |   File "/home/indy/aries_cloudagent/messaging/responder.py", line 82, in send
Faber      |     return await self.send_outbound(outbound)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 127, in send_outbound
Faber      |     return await self._send(self._profile, message)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 473, in outbound_message_router
Faber      |     return await self.queue_outbound(profile, outbound, inbound)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 506, in queue_outbound
Faber      |     connection_id=outbound.connection_id
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/manager.py", line 1104, in get_connection_targets
Faber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable
```

Specs
---

1. Mac Cataline V10.15.7
2. Aries Cloudagent Python - `Main Branch` - Latest Commit - `Support indy 1.16 predicate restrictions` on May 27
3. `Local` docker deployment with `remote dev` Sovrin network 

Connection State
---

**Alice**

```
{
  "results": [
    {
      "invitation_mode": "once",
      "state": "request",
      "their_role": "inviter",
      "connection_id": "f7da9d97-545d-4225-a651-54055815cf15",
      "their_label": "faber.agent",
      "routing_state": "none",
      "invitation_key": "GCmR5NsibXkF22VXDf312RCAyDcmznWKAod7p6DujgJP",
      "rfc23_state": "request-sent",
      "accept": "manual",
      "request_id": "4feafc1a-4941-4553-8e8d-0e97ece26c99",
      "created_at": "2021-06-27 16:56:36.074964Z",
      "my_did": "3i2UJ3SYnVRTnfTm3GaKDy",
      "updated_at": "2021-06-27 17:25:18.216764Z"
    },
    {
      "invitation_mode": "once",
      "state": "invitation",
      "their_role": "invitee",
      "connection_id": "8ce57efa-def9-4955-9e05-c0e8e3b1fda9",
      "routing_state": "none",
      "invitation_key": "5sEYWUi6Baej6N5cFcdoCiQPeexXvkyi43UgWfEy5Uee",
      "rfc23_state": "invitation-sent",
      "accept": "manual",
      "created_at": "2021-06-27 15:31:15.686281Z",
      "updated_at": "2021-06-27 15:31:15.686281Z"
    },
    {
      "invitation_mode": "once",
      "state": "invitation",
      "their_role": "invitee",
      "connection_id": "a863eb1e-4597-4706-8486-09e0f9f64753",
      "routing_state": "none",
      "invitation_key": "GYL2qW87jXCxqoxDvEjtEv9ug8DyxizTbxS5JiEMeB5d",
      "rfc23_state": "invitation-sent",
      "accept": "manual",
      "created_at": "2021-06-27 15:33:30.994783Z",
      "updated_at": "2021-06-27 15:33:30.994783Z",
      "alias": "alice-invitation"
    }
  ]
}
```

**Faber**

```
{
  "results": [
    {
      "routing_state": "none",
      "my_did": "7Z5nUMiwZD2udmxxdhfHjw",
      "their_role": "invitee",
      "rfc23_state": "request-received",
      "accept": "manual",
      "connection_id": "8c5ca088-5cdc-490d-806b-4038ce2757ba",
      "created_at": "2021-06-27 15:17:03.515376Z",
      "invitation_mode": "once",
      "request_id": "99c67544-d76e-46e6-bc4a-d85b49bef14c",
      "state": "request",
      "updated_at": "2021-06-27 18:04:14.943831Z",
      "invitation_key": "Dn7X22QNR77B3TqNm9cfKQPYKxGXLoTaeD7nduYHzAeU"
    },
    {
      "routing_state": "none",
      "my_did": "AoVo6MAx4ciafZpjc4PuyS",
      "their_role": "invitee",
      "rfc23_state": "request-received",
      "accept": "manual",
      "their_did": "3i2UJ3SYnVRTnfTm3GaKDy",
      "alias": "faber-invitation",
      "connection_id": "2c553afb-b585-4bc9-af05-3a7305fd00fe",
      "created_at": "2021-06-27 15:42:01.835079Z",
      "invitation_mode": "once",
      "request_id": "a1c6ae84-9044-4011-8db6-767140bfa99d",
      "state": "request",
      "updated_at": "2021-06-27 17:32:17.603887Z",
      "their_label": "alice.agent",
      "invitation_key": "GCmR5NsibXkF22VXDf312RCAyDcmznWKAod7p6DujgJP"
    }
  ]
}
```

Investigating further and may attempt to run through everything from scratch just to confirm I didn't corrupt state somehow through an incorrect flow - which could also be a bug but not atypical. Faber connection state doesn't look right ...

**Comment by swcurran** [comment]
Tried it out and it (sort of worked) fine. I'm on a linux box, but shouldn't matter.  Not sure what is going on, but suggest (sorry!) that you try again.  It looks like it is looking through the connections, so I wonder if you have used Alice's connection ID instead of Faber's?

The "sort of" worked fine is that I did get an exception on the Alice side.  It didn't break anything, as the connection was established.  I suspect this has to do with the ENUMs around the state names between the "Connections" protocol and "DID Exchange".   @shaangill025 -- could you please take a look at that?

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<AliceAgent.handle_connections() done, defined at /home/indy/demo/runners/alice.py:60> exception=AttributeError("'NoneType' object has no attribute 'done'",)>
Traceback (most recent call last):
  File "/home/indy/demo/runners/alice.py", line 71, in handle_connections
    and not self._connection_ready.done()
AttributeError: 'NoneType' object has no attribute 'done'
alice.agent handle_connections active completed
```

**Comment by shaangill025** [comment]
In my investigation, I went as far back as commit `2a632676b9f314f8860b146ad8d14630478a6c96`, which shows the same exception when accepting request in `faber`.

Can be fixed by either of the following:
- Add the following to `./demo/runners/alice.py`:
```
@connection_id.setter
def connection_id(self, conn_id: str):
    self._connection_id = conn_id
    self._connection_ready = asyncio.Future()

async def detect_connection(self):
    await self._connection_ready
    self._connection_ready = None
```
- Replace `./demo/runners/alice.py - 71`
from `and not self._connection_ready.done()`
to `and (self._connection_ready and not self._connection_ready.done())`

**Comment by swcurran** [comment]
@ianco -- could you please look at this?  You have the best handle on Alice Faber.  Thanks!

**Comment by swcurran** [comment]
Closing as dormant issue.
