### ISSUE TITLE
ACA-Py agent V0.6.0 can't run agent on localhost

### ISSUE THREAD

**Issue by wildnano** [hyperledger/aries-cloudagent-python#1279]
Hi,
 I followed this tuto https://yunxi-zhang-75627.medium.com/hyperledger-aries-aca-py-agents-setup-and-running-tutorials-part-i-i-i-dev-environment-setup-20ab5a32457e

 After running this command
```
 ./run_docker start \
-l Issuer \
-it http 0.0.0.0 {Self-defined Port I} \
-ot http \ 
--admin 0.0.0.0 {Self-defined Port II}\
--admin-insecure-mode \
-e http://{Your VM's public IP}:{Self-defined port I} \
--genesis-url http:// {Your VM's public IP}:9000/genesis \
--wallet-type indy \
--wallet-name issuerwallet \
--wallet-key issuerkey \
--log-level ‘info’ \
--auto-provision \
--auto-accept-invites \
--auto-accept-requests \
--auto-ping-connection \
--tails-server-base-url  {Ngrok URL of the tails file server} \
--seed issuer00000000000000000000000000
```

I get some errors

```
#14 DONE 1.6s
2021-06-29 16:22:23,576 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: http://127.0.0.1:9000/genesis
2021-06-29 16:22:27,601 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 9000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/utils/http.py", line 106, in fetch
    response: ClientResponse = await session.get(url, headers=headers)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:9000 ssl:default [Connect call failed ('127.0.0.1', 9000)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/config/ledger.py", line 32, in fetch_genesis_transactions
    return await fetch(genesis_url, headers=headers)
  File "/home/indy/aries_cloudagent/utils/http.py", line 115, in fetch
    raise FetchError("Exceeded maximum fetch attempts") from e
aries_cloudagent.utils.http.FetchError: Exceeded maximum fetch attempts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/indy/aries_cloudagent/core/conductor.py", line 88, in setup
    await get_genesis_transactions(context.settings)
  File "/home/indy/aries_cloudagent/config/ledger.py", line 43, in get_genesis_transactions
    txns = await fetch_genesis_transactions(settings["ledger.genesis_url"])
  File "/home/indy/aries_cloudagent/config/ledger.py", line 34, in fetch_genesis_transactions
    raise ConfigError("Error retrieving ledger genesis transactions") from e
aries_cloudagent.config.base.ConfigError: Error retrieving ledger genesis transactions

Shutting down
2021-06-29 16:22:27,606 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/aries_cloudagent/commands/start.py:77> exception=AttributeError("'NoneType' object has no attribute 'context'",)>
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/commands/start.py", line 79, in done
    await shutdown
  File "/home/indy/aries_cloudagent/commands/start.py", line 35, in shutdown_app
    await conductor.stop()
  File "/home/indy/aries_cloudagent/core/conductor.py", line 354, in stop
    multitenant_mgr = self.context.inject(MultitenantManager, required=False)
  File "/home/indy/aries_cloudagent/core/conductor.py", line 80, in context
    return self.root_profile.context
AttributeError: 'NoneType' object has no attribute 'context'
```
Thanks for your help

**Comment by esune** [comment]
`127.0.0.1:9000` will not work as it is referring to local IP address of localhost for the container that is running your agent. You will need to use an addressable url/IP instead (the example you linked used a publicly addressable IP address).

If you are running everything on your machine, the url/IP should be the once of your host machine: you can try `host.docker.internal` (unless you're on linux, where I believe it won't work) or use a hosted ledger such as https://test.bcovrin.vonx.io .

**Comment by wildnano** [comment]
Thanks a lot

It works with --genesis-url http://host.docker.internal:9000/genesis

**Comment by wildnano** [comment]
The problem now is that I can't access to Swagger API
(ERR_CONNECTION_REFUSED http://localhost:8001 http://localhost:8001/api/docs/swagger.json)

![image](https://user-images.githubusercontent.com/23073731/124179361-0e5e6300-dab3-11eb-8c83-923a486014fc.png)

**Comment by andrewwhitehead** [comment]
I can't see an obvious reason for this except that there might be another service or docker container using port 8001.

**Comment by wildnano** [comment]
> I can't see an obvious reason for this except that there might be another service or docker container using port 8001.

docker ps - no port for the agent
![image](https://user-images.githubusercontent.com/23073731/124249401-20c4b500-db24-11eb-9670-3ec8e372c0f3.png)

The logs - 2021-07-02 08:51:34,527 indy.libindy WARNING _indy_loop_callback: Function returned error
![image](https://user-images.githubusercontent.com/23073731/124249584-4e116300-db24-11eb-90b4-598ee5bde466.png)

**Comment by esune** [comment]
Can you try replacing `PORTS="8000 8001"` with PORTS="8000:8000 8001:8001"? The agent is runing correctly, is the docker port mapping that is failing.

**Comment by esune** [comment]
Closing due to inactivity, please reopen if necessary.
