### ISSUE TITLE
Error in Starting Faber Agent on local machine

### ISSUE THREAD

**Issue by dndufufu** [hyperledger/aries-cloudagent-python#1290]
Preparing agent image...
sha256:570cf3f7214945158b70e000b01ed4525d454f5168a285675e70a7381643c522
Trying to detect ngrok service endpoint
jq not found
192.168.65.3
Starting [faber] agent with args [--port 8020]
ERROR:runners.support.agent:Error loading genesis transactions:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('159.203.21.90', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 89, in default_genesis_txns
    async with session.get(GENESIS_URL) as resp:
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dev.greenlight.bcovrin.vonx.io:80 ssl:default [Connect call failed ('159.203.21.90', 80)]
Error retrieving ledger genesis transactions

**Comment by swcurran** [comment]
Hmmm...seems to be working fine.  What startup command did you run -- looks like you are trying to use the Greenlight ledger, and there is a mention of SSL.  Greenlight's web server does not have an SSL cert, so perhaps you had used "https" instead of "http"?

Please try again and close this issue if working.

**Comment by esune** [comment]
@dndufufu in your logs it says `jq not found`: do you have it installed on your system?
