### ISSUE TITLE
How to issue an image as part of a credential

### ISSUE THREAD

**Issue by ely459** [hyperledger/aries-cloudagent-python#1310]
Is it actually possible to issue a credential where one of the attributes is an JPEG image?

What has been tried :

```
photo_content = base64.encodebytes(photo_bytes).decode('utf-8')

request_body = {
        "auto_issue": True,
        "connection_id": connection_id,
        "cred_def_id": credential_definition_id,
        "credential_preview": {
            "attributes": [
                 {
                      "name": "Photo",
                      "value": photo_content,
                      "mime-type": "image/jpeg",
                  }
              ]
        }
    }

r = requests.post(f"{AGENT_URL}/issue-credential/send-offer", headers={"x-api-key": API_KEY}, json=request_body)
```

However, a not so descriptive error is raised:
```
aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: https://trinsic-mediator-agent-europe.azurewebsites.net/; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 500, caused by: Internal Server Error',), <traceback object at 0x7f09e6a7fa08>); Re-queue failed message ...

2021-07-10 14:54:18,403 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 86, in handle_message
     f"Unexpected response status {response.status}, "
 aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 500, caused by: Internal Server Error
 2021-07-10 14:54:18,404 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered to https://trinsic-mediator-agent-europe.azurewebsites.net/
 Traceback (most recent call last):
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 86, in handle_message
     f"Unexpected response status {response.status}, "
aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 500, caused by: Internal Server Error

```

Any help on the matter would be highly appreciated !

**Comment by swcurran** [comment]
Sorry you didn't get a response on this.  There are different ways to do this, but that is more of an Aries level issue than ACA-Py.  The most common technique that has been used so far is to encode the image in Base64 and then place that in an attribute. Those receiving the credential or a proof from the credential must know what they need to do with the encoded picture -- somehow. There is not an accepted way to share that information across participants.

Closing this.
