### ISSUE TITLE
Error in Starting Faber Agent on local machine for Open API Demo

### ISSUE THREAD

**Issue by muhammadusman93** [hyperledger/aries-cloudagent-python#139]
Starting faber...

#1 Provision an agent and wallet, get back configuration details
Faber      | Registering Faber Agent with seed d_000000000000000000000000666877
Faber      | Got DID: PkycMbtb1iayz33JgqRgAU
Faber      | 
Faber      | Shutting down
Faber      | 2019-08-13 20:45:54,018 aries_cloudagent.commands.start ERROR Exception during startup:
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 66, in init
Faber      |     await startup
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 22, in start_app
Faber      |     await conductor.start()
Faber      |   File "/home/indy/aries_cloudagent/conductor.py", line 148, in start
Faber      |     await ledger_config(context, public_did)
Faber      |   File "/home/indy/aries_cloudagent/config/ledger.py", line 79, in ledger_config
Faber      |     taa_info = await ledger.get_txn_author_agreement()
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 569, in get_txn_author_agreement
Faber      |     self.taa_cache = await self.fetch_txn_author_agreement()
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 579, in fetch_txn_author_agreement
Faber      |     response_json = await self._submit(get_aml_req, sign=bool(did_info))
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 253, in _submit
Faber      |     f"Ledger rejected transaction request: {request_result['reason']}"
Faber      | aries_cloudagent.ledger.error.LedgerTransactionError: Ledger rejected transaction request: client request invalid: InvalidClientRequest('invalid type: 7',)
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 250, in <module>
    asyncio.get_event_loop().run_until_complete(main(args.port, args.timing))
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 119, in main
    await agent.start_process()
  File "/home/indy/demo/runners/support/agent.py", line 290, in start_process
    await self.detect_process()
  File "/home/indy/demo/runners/support/agent.py", line 385, in detect_process
    + f"Admin URL: {swagger_url}"
Exception: Timed out waiting for agent process to start. Admin URL: http://172.17.0.1:8021/api/docs/swagger.json

**Comment by swcurran** [comment]
Hi @muhammadusman93 

Could you please provide a bit more information about your local environment?   Helpful info would be OS you are using, and the commands you have run to set up your environment and start the demo.

We'll take a look at where your run timed out.

**Comment by swcurran** [comment]
Looks like the timeout occurred with a first call to the ledger (could be ledger not configured properly) and is related to the new Transaction Author Agreement (TAA) that was just added to Indy and ACA-Py. Perhaps the instance of the ledger you are using does not support the TAA.  Either way, I'd be looking at what ledger you are using, how you started it, and how the Faber agent was told where the ledger is to be found.

**Comment by muhammadusman93** [comment]
I am using Linux OS. I am running everything locally on my linux machine. I
first started the VON Network as mentioned in the guidline. I then did
./run_demo faber and ./run_demo alice

**Comment by andrewwhitehead** [comment]
Try running `git pull` and `./manage build` in the `von-network` directory and restarting it. The latest release is on indy-node 1.9 and supports TAA.
