### ISSUE TITLE
/issue-credential-2.0/send-proposal error 'NoneType' object has no attribute 'handler'

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-cloudagent-python#1396]
Using /issue-credential-2.0/send-proposal with connection_id displays the error: `'NoneType' object has no attribute 'handler'`

Post data utilised:

> `curl -X POST http://localhost:11001/issue-credential-2.0/send-proposal \
 -H "Content-Type: application/json" -d '{
  "comment": "I want this",
  "connection_id": "3bf39a11-6e77-4f66-8435-a48642dfe95e",
  "credential_preview": {
    "@type": "issue-credential/2.0/credential-preview",
    "attributes": [
      {
        "mime-type": "plain/text",
        "name": "name", 
        "value": "Bob"
      },
      {
        "mime-type": "plain/text",
        "name": "age", 
        "value": "30"
      }
    ]
  },
  "filter": {
    "dif": {},
    "indy": {}
  }
}'`

Log:

> `=================
Traceback (most recent call last):
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 735, in credential_exchange_send_proposal
    for (fmt_api, filt_by_fmt) in filt_spec.items()
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 128, in create_proposal
    for (fmt, filter) in fmt2filter.items()
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 128, in <listcomp>
    for (fmt, filter) in fmt2filter.items()
AttributeError: 'NoneType' object has no attribute 'handler'
2021-09-05 15:44:07,242 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 735, in credential_exchange_send_proposal
    for (fmt_api, filt_by_fmt) in filt_spec.items()
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 128, in create_proposal
    for (fmt, filter) in fmt2filter.items()
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 128, in <listcomp>
    for (fmt, filter) in fmt2filter.items()
AttributeError: 'NoneType' object has no attribute 'handler'`

**Comment by swcurran** [comment]
Sorry there was not a response provided.  I imagine this was a setup error with an unhelpful error message.

Closing as dormant.  Please reopen if appropriate.
