### ISSUE TITLE
ACA-Py running as AWS ECS Fargate task can't connect to either Sovrin BuilderNet/a local von-network in an Azure VM

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1458]
Hello, I'm running ACA-Py on my AWS ECS Fargate as a task container that tries to connect to both the Sovrin BuilderNet and my own von-network running as containers in my **Azure VM**, but it keeps getting error and shutting down. The errors look similar in both situation.

Below shows the details:
**Environment:** 
- AWS ECS Fargate, Platform version 1.4.0
- Task memory (MiB)8192
- Task CPU (unit)2048
- ACA-Py Docker Image version: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0

**Error Message when connecting to Sovrin BuilderNet:** 
```
2021-10-27 10:23:38,924 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis
--
2021-10-27 10:23:39,107 aries_cloudagent.core.profile INFO Create profile manager: indy
2021-10-27 10:23:39,112 indy.libindy.native.command_executor INFO 	src/commands/mod.rs:127 \| Worker thread started
2021-10-27 10:23:39,113 indy.libindy WARNING _indy_loop_callback: Function returned error
2021-10-27 10:23:41,919 aries_cloudagent.indy.sdk.wallet_setup INFO Creating master secret...
2021-10-27 10:24:41,961 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:75 \| OpenAck handle 4, pool_id 4, result Err(IndyError { inner:
Pool timeout
Pool timeout })
2021-10-27 10:24:41,962 indy.libindy WARNING _indy_loop_callback: Function returned error
2021-10-27 10:24:41,963 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
open_pool_ledger.cb)
indy.error.PoolLedgerTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
await startup
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
await conductor.setup()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 96, in setup
self.root_profile, self.setup_public_did and self.setup_public_did.did
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
async with ledger:
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 272, in __aenter__
await self.pool.context_open()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 205, in context_open
await self.open()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
) from err_value
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
open_pool_ledger.cb)
aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
Caused by: Pool timeout
Shutting down
```

**Error Message when connecting to my local Von-network in my Azure VM:** 
```
2021-10-27 10:40:40,566 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: http://{my von network ip}/genesis
--
2021-10-27 10:40:40,604 aries_cloudagent.core.profile INFO Create profile manager: indy
2021-10-27 10:40:40,610 indy.libindy.native.command_executor INFO 	src/commands/mod.rs:127 \| Worker thread started
2021-10-27 10:40:40,611 indy.libindy WARNING _indy_loop_callback: Function returned error
2021-10-27 10:40:43,239 aries_cloudagent.indy.sdk.wallet_setup INFO Creating master secret...
2021-10-27 10:41:43,270 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:75 \| OpenAck handle 4, pool_id 4, result Err(IndyError { inner:
Pool timeout
Pool timeout })
2021-10-27 10:41:43,271 indy.libindy WARNING _indy_loop_callback: Function returned error
2021-10-27 10:41:43,272 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
open_pool_ledger.cb)
indy.error.PoolLedgerTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
await startup
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
await conductor.setup()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 96, in setup
self.root_profile, self.setup_public_did and self.setup_public_did.did
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
async with ledger:
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 272, in __aenter__
await self.pool.context_open()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 205, in context_open
await self.open()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
) from err_value
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 170, in open
self.handle = await indy.pool.open_pool_ledger(self.name, "{}")
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
open_pool_ledger.cb)
aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
Caused by: Pool timeout
Shutting down
```

Could anyone help me here? Thanks!

**Comment by yunxi-zhang** [comment]
Thanks for the response @ianco  and @swcurran. I've got questions on opening the IP and port numbers.

So far, when I run my **VON-network** in my Azure **VM1,** I've never opened the port range 9701-9708 to the Internet (i.e. specify them in the **inbound rules** of **VM1**), but ACA-Py agents running other Azure VMs can always connect to my VON-network. So,

Q1.When you mentioned opening this port range 9701-9708, do you mean by specifying them in the **inbound rules** of **VM1** to allow traffic to be in or specifying **outbound rules** of **other VMs** to send traffic out?

Q2.If an answer to Q1 is **yes**, why could opening port range 9701-9708 (by specifying them in the **inbound rules** of **VM1**) help to resolve the connection issue?

Q3. The IP address within the genesis file is a **private IP - 10.0.0.4**. Since the VON-network works for my ACA-Py agents on other Azure VMs, how could this impact the traffic from my AWS ECS containers? I see a message given in the VON-network: `The Indy nodes are configured to talk to each other via their "public" address not the Virtual Private Cloud address of the EC2 node.`

Q4. Does Sovrin networks (i.e. BuilderNet, Staging and Main networks) use port range 9701-9708 as well?

Q5. If changing the IP of my VON-network could help, is the below command the one I should look for?
`$0 start <ip_proxy_1>,<ip_proxy_2>,<ip_proxy_3>,<ip_proxy_4> &`

**Comment by yunxi-zhang** [comment]
Hello @ianco  and @swcurran, could you provide answers to my questions above? Thanks!

**Comment by yunxi-zhang** [comment]
Hello @ianco  and @swcurran , could you provide answers to my questions above? In addition, are you aware of any other port numbers that will be used when an ACA-Py agent tries to connect to either a remote VON-network or Sovrin BuilderNet?

**Comment by ianco** [comment]
Hi @yunxi-zhang I'm not an expert on indy node or the required ports or network settings, I suggest you can open ports until you can get a successful connection, or ask the question on the indy-node channel in Hyperledger Rocketchat

**Comment by yunxi-zhang** [comment]
Apologies to keep asking you, @ianco, thought you knew the details. Thanks for the guidance, i've raise this in the indy-node channel.

**Comment by WadeBarnes** [comment]
`aca-py` agents are clients, they connect to the client IPs and ports of the nodes on an indy network.  Only node-to-node communication is performed over the node IPs and ports.

**Comment by yunxi-zhang** [comment]
Thanks for your answer @WadeBarnes, appreciate it. 

Got another question on whether the IPs listed in the BuilderNet's genesis file will be updated constantly?

**Comment by WadeBarnes** [comment]
The IPs and ports listed in a genesis do not change very often, however that does not really matter since your `aca-py` agent uses the genesis file to establish an initial connection with the network whenever it starts, once the connection is established your agent will get the full list of all of the nodes on the network directly from the network's pool configuration.  To clarify, the genesis file typically does not contain a full list of nodes on the network and nodes on a given network can come and go over time.  The nodes listed in the genesis file form the root of the network.

**Comment by WadeBarnes** [comment]
To provide an answer to your question in rocket.chat about which IPs and ports need to be open for your agent to connect to a given ledger:

Outgoing Requests Only - A node will never try to establish a connection with your agent:
- Open to all external IPs, your not going to know the IPs of all of the nodes on the network (other than the few listed in the genesis file) ahead of time, and nodes can come and go over time.
- Ports 9700-9799; which is the valid port range for Hyperledger Indy-Node.  Again you will not know what ports all of the nodes on the network are using ahead of time, and nodes can come and go over time.

**Comment by yunxi-zhang** [comment]
Thanks for answers @WadeBarnes. What impacts will be on the ACA-Py agents if they can't connect to the rest of the nodes whose IPs are not listed in the genesis file?

**Comment by WadeBarnes** [comment]
You could run into performance and availability (leger pool timeout) issues.

**Comment by yunxi-zhang** [comment]
thanks for your answers @WadeBarnes :-).
