### ISSUE TITLE
/present-proof-2.0/send-proposal expects the wrong model for the indy type

### ISSUE THREAD

**Issue by etschelp** [hyperledger/aries-cloudagent-python#1467]
The class [V20PresProposalByFormatSchema](https://github.com/hyperledger/aries-cloudagent-python/blob/31659902475de16118d8322f3cbc9c74f0b85ef5/aries_cloudagent/protocols/present_proof/v2_0/routes.py#L117) links to IndyProofRequestSchema (which is the full proof request) instead of IndyPresPreview which is the desired model for a presentation proposal when using the indy type.

**Comment by swcurran** [comment]
That changed in V2 of Present Proof. In V2 the Indy proposal attachment is a presentation request.

**Comment by etschelp** [comment]
Ah i see, my bad. But still I do not get this to work, so from my naive understanding I now have to send a very specific proof request as a proposal, that will probably be translated back into another proof request from the verifier that the prover will answer with the matching credential.  So I'm sending:

```json
{
    "by_format": {
        "pres_proposal": {
            "indy": {
                "name": "Test V2",
                "version": "2.0",
                "requested_attributes": {
                    "iban": {
                        "name": "iban",
                        "restrictions": [
                            {
                                "schema_id": "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0",
                                "cred_def_id": "EraYCDJUPsChbkw7S1vV96:3:CL:571:bob-bank-04",
                                "attr::iban::value": "mytestvalue"
                            }
                        ]
                    }
                },
                "requested_predicates": {}
            }
        }
    }
}
```

The proofing aca-py accepts this, but the verifier throws the following exception:

```
2021-11-01 14:42:08,959 aries_cloudagent.core.conductor ERROR Exception in message handler:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 197, in handle_message
    await handler(context, responder)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_proposal_handler.py", line 64, in handle
    comment=context.message.comment,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v2_0/manager.py", line 135, in create_bound_request
    request_data,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py", line 117, in create_bound_request
    indy_proof_request["name"] = request_data.get("name") or "proof-request"
AttributeError: 'NoneType' object has no attribute 'get'
```

Which kind of makes sense as None is assigned to the variable that handles the request payload, and there is no assignment afterwards.

```python
    async def create_bound_request(
        self,
        pres_ex_record: V20PresExRecord,
        request_data: dict = None,
    )
        // ...
        indy_proof_request["name"] = request_data.get("name") or "proof-request"
```
[handler.py](https://github.com/hyperledger/aries-cloudagent-python/blob/31659902475de16118d8322f3cbc9c74f0b85ef5/aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py#L117)
