### ISSUE TITLE
ACA-Py throws error 500: No instance provided for class: IndyHolder

### ISSUE THREAD

**Issue by theowlsden** [hyperledger/aries-cloudagent-python#1498]
## Issue
When running an ACA-py instance for a holder (no public DID etc), when trying to get credentials the instance throws an error 500:
"500 Internal Server Error

Server got itself in trouble"

When you look into the logs of the container it logs:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/holder/routes.py", line 313, in credentials_list
    holder = session.inject(IndyHolder)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/profile.py", line 272, in inject
    return self._context.inject(base_cls, settings)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/injection_context.py", line 124, in inject
    return self.injector.inject(base_cls, settings)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/injector.py", line 112, in inject
    "No instance provided for class: {}".format(base_cls.__name__)
aries_cloudagent.config.base.InjectionError: No instance provided for class: IndyHolder

### Reproduce
I used this command to run the instance in docker:

docker run --rm -ti --name test --net=host \
bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1 start \
--admin-insecure-mode \
--endpoint http://10.2.1.77:8003 \
--genesis-url http://greenlight.bcovrin.vonx.io/genesis \
--admin 10.2.1.77 8082 \
--debug-connections \
--auto-provision \
--wallet-local-did \
--wallet-name Holder \
--wallet-key successFull \
--inbound-transport http 10.2.1.77 8003 \
-ot HTTP 

with the API call:

`curl -X GET "http://10.2.1.77:8082/credentials" -H "accept: application/json"`

This also happens when trying to send a credential exchange request to the issuer.

**Comment by ianco** [comment]
You need to specify `--wallet-type indy` to use indy credentials

**Comment by theowlsden** [comment]
Thank you, that fixed it. Is there a way to make that error more descriptive?

**Comment by swcurran** [comment]
Closing this issue.  Sorry we've not gotten to making the error message better.  Please reopen (with a new title) and/or provide a PR.
