### ISSUE TITLE
Two ACA-Py running as containers in my laptop can't communicate with each other

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1514]
Hello,

I've tried to run two ACA-Py agents as containers in my laptop for testing purpose, but they fail to communicate with each other. I wonder whether ACA-Py is designed to communicate with each other when they are running in the same machine? Below shows the environment I use.

- OS: Mac OS 11.6.1
- Docker version: 20.10.8
- ACA-Py docker image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
- DLT network: no-ledger mode
- Docker network: bridge 
- Agent 1 exposes ports 8000 and 8001
- Agent 2 exposes ports 8002 and 8003

Below shows the commands for running both agents.
Agent 1:
![image](https://user-images.githubusercontent.com/16185797/143132624-77796011-ffb7-400e-87b1-1e25c82dfbca.png)

Agent 2:
![image](https://user-images.githubusercontent.com/16185797/143132666-f5322098-71c0-4052-94bc-b62f92a49836.png)

```
Errors in Agent 2 after Agent 2 receives invites from Agent 1.
2021-11-23 21:32:01,562 indy.libindy WARNING _indy_loop_callback: Function returned error 
2021-11-23 21:32:01,578 aiohttp.access INFO 172.17.0.1 [23/Nov/2021:21:32:01 +0000] "POST /connections/receive-invitation HTTP/1.1" 200 632 "-" "PostmanRuntime/7.28.4"
2021-11-23 21:32:01,589 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://localhost:8000/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(99, 'Cannot assign requested address')), <traceback object at 0x7fc640750208>); Re-queue failed message ...
2021-11-23 21:32:11,601 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://localhost:8000/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(99, 'Cannot assign requested address')), <traceback object at 0x7fc640750b48>); Re-queue failed message ...
2021-11-23 21:32:21,654 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://localhost:8000/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(99, 'Cannot assign requested address')), <traceback object at 0x7fc640754708>); Re-queue failed message ...
2021-11-23 21:32:31,693 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://localhost:8000/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='localhost', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(99, 'Cannot assign requested address')), <traceback object at 0x7fc640757308>); Re-queue failed message ...
2021-11-23 21:32:41,680 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 444, in _sock_connect
    sock.connect(address)
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 81, in handle_message
    endpoint, data=payload, headers=headers
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8000 ssl:default [Cannot assign requested address]
2021-11-23 21:32:41,682 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered to http://localhost:8000/
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 444, in _sock_connect
    sock.connect(address)
OSError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 81, in handle_message
    endpoint, data=payload, headers=headers
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8000 ssl:default [Cannot assign requested address]
```

Error in Agent 1:
2021-11-23 21:31:55,599 aiohttp.access INFO 172.17.0.1 [23/Nov/2021:21:31:55 +0000] "POST /connections/create-invitation HTTP/1.1" 200 998 "http://localhost:4200/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
2021-11-23 21:35:14,684 indy.libindy WARNING _indy_loop_callback: Function returned error 

Anyone can help here?

**Comment by ianco** [comment]
You can't use `localhost` for the endpoint for an aca-py that is running in a docker container.  You need to use an IP or host name that is available within the internal docker network.

Options are - use the internal docker IP; use `host.docker.internal` (doesn't work on all platforms); or use ngrok (or similar) to expose you agent's endpoints publicly.

**Comment by estrehle** [comment]
You could also use Docker Compose. On execution, Docker Compose creates a shared network where Docker containers can find each other by container name.

Below is an example `docker-compose.yml`. Run it with `docker-compose up --build --remove-orphans`.

The key lines are the two `ACAPY_ENDPOINT: "http://<container_name>:<ACAPY_PORT>"`. Notice that we do not need to expose the inbound endpoints `8000` and `9000` to our host machine. Communication between the containers happens on the Docker network.

````
version: "3"
services:
  agent-1:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: my-agent-1
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://my-agent-1:8000"
      ACAPY_LABEL: "Agent 1"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http "
    ]
    ports:
      - "8001:8001"

  agent-2:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: my-agent-2
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://my-agent-2:9000"
      ACAPY_LABEL: "Agent 2"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "9001"
      AGENT_PORT: "9000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 9001 \
        --inbound-transport http '0.0.0.0' 9000 \
        --outbound-transport http "
    ]
    ports:
      - "9001:9001"

````

**Comment by yunxi-zhang** [comment]
Thanks for your help @ianco  and @estrehle, using either internal IPs or the docker compose file does work.
