### ISSUE TITLE
cannot create connection with self when using oob with didexchange protocol

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1541]
I can't seem to make a connection with myself (the same agent) when using the OOB + didexchange protocol. It works fine when using OOB + connections protocol. May not be the most common use case to create connections with yourself, but it can useful for testing.

Create an OOB using the following body:

```
{
  "alias": "Larry",
  "label": "Larry on the other side",
  "handshake_protocols": [
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
  ],
  "use_public_did": false
}
```

then receive the invitation (with auto accept enabled on both sides) and an error will show in the acapy logs. If you change `didexchange` to `connections` in the `handshake_protocols` everything will works as exptected.

Stack trace:

```
2021-12-08 12:35:03,394 aries_cloudagent.core.conductor ERROR Exception in message handler:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 198, in handle_message
    await handler(context, responder)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/didexchange/v1_0/handlers/response_handler.py", line 34, in handle
    context.message, context.message_receipt
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 682, in accept_response
    self._session, response._thread_id
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 336, in retrieve_by_request_id
    return await cls.retrieve_by_tag_filter(session, tag_filter)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 270, in retrieve_by_tag_filter
    f", {post_filter}" if post_filter else "",
aries_cloudagent.storage.error.StorageDuplicateError: Multiple ConnRecord records located for {'request_id': '80a1aead-8ca4-4044-b914-e8845f1109de'}
2021-12-08 12:35:03,394 aries_cloudagent.core.conductor ERROR DON'T shutdown on StorageDuplicateError Multiple ConnRecord records located for {'request_id': '80a1aead-8ca4-4044-b914-e8845f1109de'}
2021-12-08 12:35:03,395 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 198, in handle_message
    await handler(context, responder)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/didexchange/v1_0/handlers/response_handler.py", line 34, in handle
    context.message, context.message_receipt
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 682, in accept_response
    self._session, response._thread_id
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 336, in retrieve_by_request_id
    return await cls.retrieve_by_tag_filter(session, tag_filter)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 270, in retrieve_by_tag_filter
    f", {post_filter}" if post_filter else "",
aries_cloudagent.storage.error.StorageDuplicateError: Multiple ConnRecord records located for {'request_id': '80a1aead-8ca4-4044-b914-e8845f1109de'}
```

**Comment by swcurran** [comment]
Looks like a fun one for you, @ianco .  We need this for OrgBook BC, right?

**Comment by ianco** [comment]
> Looks like a fun one for you, @ianco . We need this for OrgBook BC, right?

Yep lots of fun!  (FYI OrgBook uses the connections v1 protocol to self-connect so not impacted by this issue)

**Comment by ianco** [comment]
The difference between the 2 protocols is that didexchange sets the `request_id` on both connection records (invitee and inviter) whereas the connections protocol only sets the `request_id` on the invitee.  With with a didexchange self-connection you wind up with 2 records in the same wallet with the same `request_id`.

**Comment by ianco** [comment]
See https://github.com/hyperledger/aries-cloudagent-python/pull/1544, still needs some testing, I'm not familiar enough with the protocols offhand to know if this is a viable solution.

**Comment by ianco** [comment]
> The difference between the 2 protocols is that didexchange sets the `request_id` on both connection records (invitee and inviter) whereas the connections protocol only sets the `request_id` on the invitee. With with a didexchange self-connection you wind up with 2 records in the same wallet with the same `request_id`.

@andrewwhitehead @TimoGlastra  any thoughts?  An alternative is to qualify the "find by request_id" query to filter based on the connection role (inviter vs invitee)

**Comment by TimoGlastra** [comment]
Sorry for the late reply to this one @ianco!

I think the second approach you mentioned would work better. The `retrieve_by_request_id` is used two times in the didexchange manager, one for each role. So not storing the request id for the inviter means it would break existing code I think

**Comment by TimoGlastra** [comment]
Running into this issue again. Any update on this @ianco? :)

**Comment by ianco** [comment]
Replaced by PR 1670

**Comment by TimoGlastra** [comment]
Did #1670 not fix the issue yet? Or was this issue reopened by mistake?

**Comment by swcurran** [comment]
We can close it now.  #1670 was only merged yesterday.
