### ISSUE TITLE
DatabasePerWalletStrategy + Postgres Storage fails to Recreate Wallet

### ISSUE THREAD

**Issue by PaulWen** [hyperledger/aries-cloudagent-python#1547]
I am using the following parameters to start up the AcaPy and let it recreate the wallet:

```
./scripts/run_docker start \
  --debug \
  --recreate-wallet \
  --auto-provision \
  --inbound-transport http 0.0.0.0 10001 \
  --outbound-transport http \
  --admin 0.0.0.0 10000 \
  --webhook-url 'http://lissi-cloud-controller-institutional:9080/ctrl/webhook' \
  --endpoint 'http://aries-cloud-agent-institutional:10001' \
  --genesis-url http://test-ledger.lissi.id/genesis \
  --ledger-pool-name 'lissi-test' \
  --invite-base-url 'didcomm://aries_connection_invitation' \
  --admin-insecure-mode \
  --label 'test-acapy' \
  --wallet-type indy \
  --wallet-name 'wallet_db' \
  --wallet-key 'key' \
  --wallet-storage-type 'postgres_storage' \
  --wallet-storage-config '{"url":"host.docker.internal:5433","max_connections":5}' \
  --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}' \
  --auto-ping-connection --auto-verify-presentation --preserve-exchange-records --invite-public --public-invites --invite-multi-use \
  --log-level DEBUG \
  --tails-server-base-url 'https://lissi-tails-dev.westeurope.cloudapp.azure.com' \
  --seed SeedToGeneratePublicDid000000Test \
  --debug-connections --debug-presentations --debug-credentials
```

Running it the first time against an empty Postgres DB the database "wallet_db" will be successfully created and initialized.
Running it the second time it **does not look like the wallet is actually deleted and recreated**.

First, postgres logs do not show any "DROP" statements as the [Indy SDK code](https://github.com/hyperledger/indy-sdk/blob/master/experimental/plugins/postgres_storage/src/postgres_storage.rs#L773) would suggest. Second, debugging the AcaPy and[ breaking before the wallet should be recreated](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/indy/sdk/wallet_setup.py#L103), I see that the tables in the `wallet_db` still exist.

**Comment by ianco** [comment]
The `--recreate-wallet` works with the `aca-py provision ...` command, so if you run something like this it should drop & recreate your wallet:

```
./scripts/run_docker provision \
  --debug \
  --recreate-wallet \
  --endpoint 'http://aries-cloud-agent-institutional:10001' \
  --genesis-url http://test-ledger.lissi.id/genesis \
  --ledger-pool-name 'lissi-test' \
  --wallet-type indy \
  --wallet-name 'wallet_db' \
  --wallet-key 'key' \
  --wallet-storage-type 'postgres_storage' \
  --wallet-storage-config '{"url":"host.docker.internal:5433","max_connections":5}' \
  --wallet-storage-creds '{"account":"postgres","password":"postgres","admin_account":"postgres","admin_password":"postgres"}' \
  --log-level DEBUG \
  --tails-server-base-url 'https://lissi-tails-dev.westeurope.cloudapp.azure.com' \
  --seed SeedToGeneratePublicDid000000Test
```

(not 100% sure about the parameters, your mileage may vary)

Note that this is a fairly risky parameter to use, if you've already created credential definitions on the ledger, and you drop & recreate your wallet with the same seed/did, then there's no way to recover your previously published cred defs.

**Comment by PaulWen** [comment]
Also in the context of `aca-py provision` the wallet does not seem to be recreated. Instead, I am receiving the error `Error: Wallet with this name already exists`

```
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/indy/sdk/wallet_setup.py", line 103, in create_wallet
    credentials=json.dumps(self.wallet_access),
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
    create_wallet.cb)
indy.error.WalletAlreadyExistsError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/commands/provision.py", line 52, in provision
    root_profile, public_did = await wallet_config(context, provision=True)
  File "/home/indy/aries_cloudagent/config/wallet.py", line 49, in wallet_config
    profile = await mgr.provision(context, profile_cfg)
  File "/home/indy/aries_cloudagent/indy/sdk/profile.py", line 163, in provision
    opened = await indy_config.create_wallet()
  File "/home/indy/aries_cloudagent/indy/sdk/wallet_setup.py", line 111, in create_wallet
    ) from x_indy
  File "/home/indy/aries_cloudagent/indy/sdk/wallet_setup.py", line 103, in create_wallet
    credentials=json.dumps(self.wallet_access),
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
    create_wallet.cb)
aries_cloudagent.core.error.ProfileDuplicateError: Cannot create wallet 'lissi_agent_wallet', already exists: Error: Wallet with this name already exists
  Caused by: Plugin returned error


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/aries_cloudagent/__main__.py", line 74, in <module>
    main(sys.argv)
  File "/home/indy/aries_cloudagent/__main__.py", line 71, in main
    run(args)
  File "/home/indy/aries_cloudagent/__main__.py", line 64, in run
    run_command(command, args)
  File "/home/indy/aries_cloudagent/commands/__init__.py", line 37, in run_command
    module.execute(argv)
  File "/home/indy/aries_cloudagent/commands/provision.py", line 86, in execute
    loop.run_until_complete(provision(settings))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/aries_cloudagent/commands/provision.py", line 69, in provision
    raise ProvisionError("Error during provisioning") from e
aries_cloudagent.commands.provision.ProvisionError: Error during provisioning

```

**Comment by swcurran** [comment]
Suggestions on what actions should happen?  Should we check and error off to say that "start" and "--recreate-wallet" are not compatible?  Are there code changes needed?   What is the expected behaviour?

I'm going to close this and request that if appropriate, a new issue be opened with expected behaviour.

**Comment by darapich92** [comment]
Hello everyone, I would like to ask for your suggestion. after I run the above code, I received an error which its message is 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/core/conductor.py", line 121, in setup
    self.root_profile, self.setup_public_did = await wallet_config(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/config/wallet.py", line 55, in wallet_config
    profile = await mgr.open(context, profile_cfg)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/indy/sdk/profile.py", line 188, in open
    indy_config = IndyWalletConfig(config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 61, in __init__
    load_postgres_plugin(self.storage_config, self.storage_creds)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aries_cloudagent/indy/sdk/wallet_plugin.py", line 43, in load_postgres_plugin
    stg_lib = cdll.LoadLibrary("libindystrgpostgres" + file_ext())
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libindystrgpostgres.so: cannot open shared object file: No such file or directory
could you help me with this? thank you very much!
