### ISSUE TITLE
Errors when running faber demo with --revocation

### ISSUE THREAD

**Issue by nebucaz** [hyperledger/aries-cloudagent-python#1554]
Trying to follow the script at [The Alice/Faber Python demo](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo). When running the faber-agent in the [play with von](http://play-with-von.vonx.io) environment with the recovation option (`./run_demo faber --revocation `), errors are thrown on both sides:

Starting Faber:

```
Schema ID: BwwzKGiBxDtTXhCC4iyBCw:2:degree schema:98.11.31
Faber      | Revocation registry: (undetermined) state: init
Faber      | Revocation registry: BwwzKGiBxDtTXhCC4iyBCw:4:BwwzKGiBxDtTXhCC4iyBCw:3:CL:109371:faber.agent.degree_schema:CL_ACCUM:ed7bf583-adc5-4c19-bbd6-e963f3cbbf9d state: generated
Faber      | Revocation registry: BwwzKGiBxDtTXhCC4iyBCw:4:BwwzKGiBxDtTXhCC4iyBCw:3:CL:109371:faber.agent.degree_schema:CL_ACCUM:ed7bf583-adc5-4c19-bbd6-e963f3cbbf9d state: posted
Faber      | Revocation registry: BwwzKGiBxDtTXhCC4iyBCw:4:BwwzKGiBxDtTXhCC4iyBCw:3:CL:109371:faber.agent.degree_schema:CL_ACCUM:ed7bf583-adc5-4c19-bbd6-e963f3cbbf9d state: active
Faber      | 2021-12-12 16:12:09,136 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/core/event_bus.py", line 120, in notify
Faber      |     await processor()
Faber      |   File "/home/indy/aries_cloudagent/revocation/routes.py", line 1265, in on_revocation_tails_file_event
Faber      |     f"Tails file for rev reg {revoc_reg_id} " f"failed to upload: {reason}"
Faber      |   File "/home/indy/aries_cloudagent/core/error.py", line 11, in __init__
Faber      |     super().__init__(*args, **kwargs)
Faber      | TypeError: RevocationError does not take keyword arguments
Cred def ID: BwwzKGiBxDtTXhCC4iyBCw:3:CL:109371:faber.agent.degree_schema
Publish schema/cred def duration: 25.45s
```

Alice, receiving a proof request after she has been issued a credential

```
[3/4/X] ERROR:asyncio:Task exception was never retrieved                        
future: <Task finished coro=<AriesAgent.handle_present_proof_v2_0() done, defined at /home/indy/demo/runners/agent_container.py:354> exception=Exception('Error: 400: Error when constructing revocation state: Error: Invalid structure. Caused by: UrsaCryptoError: Invalid len of bytes representation for PoingG2. CommonInvalidStructure.',)>
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 815, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 400, message='Error when constructing revocation state: Error: Invalid structure. Caused by: UrsaCryptoError: Invalid len of bytes representation for PoingG2. CommonInvalidStructure.', url=URL('http://127.0.0.1:8031/present-proof-2.0/records/0c99a38d-7606-4754-8d11-61f3824c9ee0/send-presentation')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/demo/runners/agent_container.py", line 482, in handle_present_proof_v2_0
    request,
  File "/home/indy/demo/runners/support/agent.py", line 916, in admin_POST
    "POST", path, data, text, params, headers=headers
  File "/home/indy/demo/runners/support/agent.py", line 818, in admin_request

#24 Query for credentials in the wallet that satisfy the proof request

#25 Generate the proof

#26 Send the proof to X: {"indy": {"requested_predicates": {"0_birthdate_dateint_GE_uuid": {"cred_id": "cb9299
cb-bf98-44c7-a56c-76afe7653c00"}}, "requested_attributes": {"0_name_uuid": {"cred_id": "cb9299cb-bf98-44c7-a56
c-76afe7653c00", "revealed": true}, "0_date_uuid": {"cred_id": "cb9299cb-bf98-44c7-a56c-76afe7653c00", "revealed": true}, "0_degree_uuid": {"cred_id": "cb9299cb-bf98-44c7-a56c-76afe7653c00", "revealed": true}}, "self_attested_attributes": {}}}
Alice      | Presentation: state = abandoned, pres_ex_id = 0c99a38d-7606-4754-8d11-61f3824c9ee0
Alice      | 2021-12-12 16:20:22,147 aries_cloudagent.protocols.present_proof.indy.pres_exch_handler ERROR Fai
led to create revocation state: None, Error when constructing revocation state: Error: Invalid structure
Alice      |   Caused by: UrsaCryptoError: Invalid len of bytes representation for PoingG2
Alice      | 2021-12-12 16:20:22,171 aries_cloudagent.admin.server ERROR Handler error with exception: Error w
hen constructing revocation state: Error: Invalid structure. Caused by: UrsaCryptoError: Invalid len of bytes 
representation for PoingG2. CommonInvalidStructure.
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/indy/sdk/holder.py", line 480, in create_revocation_state
Alice      |     timestamp=timestamp,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/anoncreds.py", line 18
14, in create_revocation_state
Alice      |     create_revocation_state.cb)
Alice      | indy.error.CommonInvalidStructure
Alice      | 
Alice      | The above exception was the direct cause of the following exception:
Alice      | 
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/v2_0/routes.py", line 1072, in presen
t_proof_send_presentation
Alice      |     comment=comment,
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/v2_0/manager.py", line 264, in create
_pres
Alice      |     request_data,
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py", line 1
60, in create_pres
Alice      |     requested_credentials=requested_credentials,
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/indy/pres_exch_handler.py", line 187,
 in return_presentation
Alice      |     raise e
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/indy/pres_exch_handler.py", line 180,
 in return_presentation
Alice      |     tails_local_path,
Alice      |   File "/home/indy/aries_cloudagent/indy/sdk/holder.py", line 480, in create_revocation_state
Alice      |     timestamp=timestamp,
Alice      |   File "/home/indy/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
Alice      |     ) from err_value
Alice      |   File "/home/indy/aries_cloudagent/indy/sdk/holder.py", line 480, in create_revocation_state
Alice      |     timestamp=timestamp,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/anoncreds.py", line 18
14, in create_revocation_state
Alice      |     create_revocation_state.cb)
Alice      | aries_cloudagent.indy.holder.IndyHolderError: Error when constructing revocation state: Error: In
valid structure
Alice      |   Caused by: UrsaCryptoError: Invalid len of bytes representation for PoingG2
Alice      | 
Alice      | 
Alice      | The above exception was the direct cause of the following exception:
Alice      | 
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 163, in ready_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 200, in debug_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares
.py", line 45, in validation_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 383, in setup_context
Alice      |     return await task
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/v2_0/routes.py", line 1091, in presen
t_proof_send_presentation
Alice      |     outbound_handler,
Alice      |   File "/home/indy/aries_cloudagent/protocols/present_proof/v2_0/__init__.py", line 63, in report
_problem
Alice      |     raise http_error_class(reason=err.roll_up) from err
Alice      | aiohttp.web_exceptions.HTTPBadRequest: Error when constructing revocation state: Error: Invalid s
tructure. Caused by: UrsaCryptoError: Invalid len of bytes representation for PoingG2. CommonInvalidStructure.
Alice      | 
Alice      | =================
```

**Comment by swcurran** [comment]
I think the key error in the stack above is this: `f"Tails file for rev reg {revoc_reg_id} " f"failed to upload: {reason}"`

Did you start a tails server or specify that you were using a public tails server?  I think the fail happened in trying to load a file to the tails server when creating the revokable credential type.

**Comment by nebucaz** [comment]
@swcurran Sorry, I probably missed following line in the [instructions](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo) to run the tails server: 

You need to run a revocation registry in order to support revocation - the details are described in the [Alice gets a Phone ](https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AliceGetsAPhone.md#run-an-instance-of-indy-tails-server)demo instructions.
