### ISSUE TITLE
Error Creating Wallet indy.error.CommonIOError

### ISSUE THREAD

**Issue by naman20sharma** [hyperledger/aries-cloudagent-python#1555]
### Error: IO error Caused by: Permission denied (os error 13)
Hi, 
I tried to run an agent Alice using a docker-compose file, and receiving following errors :

````
Creating aries-cloudagent_Alice ... done
Attaching to aries-cloudagent_Alice
aries-cloudagent_Alice | 2021-12-10 13:15:44,959 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: http://127.0. 0.1:9000/genesis
aries-cloudagent_Alice | 2021-12-10 13:15:44,972 aries_cloudagent.core.profile INFO Create profile manager: indy
aries-cloudagent_Alice | 2021-12-10 13:15:45,062 indy.libindy.native.command_executor INFO      src/commands/mod.rs:101 | Worker thread started
aries-cloudagent_Alice | 2021-12-10 13:15:45,063 indy.libindy WARNING _indy_loop_callback: Function returned error
aries-cloudagent_Alice | 2021-12-10 13:15:52,468 indy.libindy WARNING _indy_loop_callback: Function returned error
aries-cloudagent_Alice | 2021-12-10 13:15:52,470 aries_cloudagent.commands.start ERROR Exception during startup:
aries-cloudagent_Alice | Traceback (most recent call last):
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 105, in create_wallet
aries-cloudagent_Alice |     credentials=json.dumps(self.wallet_access),
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
aries-cloudagent_Alice |     create_wallet.cb)
aries-cloudagent_Alice | indy.error.CommonIOError
aries-cloudagent_Alice |

aries-cloudagent_Alice | The above exception was the direct cause of the following exception:

aries-cloudagent_Alice |
aries-cloudagent_Alice | Traceback (most recent call last):

aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
aries-cloudagent_Alice |     await startup
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
aries-cloudagent_Alice |     await conductor.setup()
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 91, in setup
aries-cloudagent_Alice |     self.root_profile, self.setup_public_did = await wallet_config(context)
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/wallet.py", line 43, in wallet_config
aries-cloudagent_Alice |     profile = await mgr.provision(context, profile_cfg)
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/profile.py", line 153, in provision
aries-cloudagent_Alice |     opened = await indy_config.create_wallet()
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 118, in create_wallet
aries-cloudagent_Alice |     ) from x_indy
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 105, in create_wallet
aries-cloudagent_Alice |     credentials=json.dumps(self.wallet_access),
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
aries-cloudagent_Alice |     create_wallet.cb)
aries-cloudagent_Alice | aries_cloudagent.core.error.ProfileError: Error creating wallet 'Alice1234': Error: IO error
aries-cloudagent_Alice |   Caused by: Permission denied (os error 13)
aries-cloudagent_Alice |
aries-cloudagent_Alice |
aries-cloudagent_Alice | Shutting down
aries-cloudagent_Alice | 2021-12-10 13:15:52,475 asyncio ERROR Task exception was never retrieved
aries-cloudagent_Alice | future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py:77> exception=AttributeError("'NoneType' object has no attribute 'context'",)>
aries-cloudagent_Alice | Traceback (most recent call last):
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 79, in done
aries-cloudagent_Alice |     await shutdown
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 35, in shutdown_app
aries-cloudagent_Alice |     await conductor.stop()
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 354, in stop
aries-cloudagent_Alice |     multitenant_mgr = self.context.inject(MultitenantManager, required=False)
aries-cloudagent_Alice |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 80, in context
aries-cloudagent_Alice |     return self.root_profile.context
aries-cloudagent_Alice | AttributeError: 'NoneType' object has no attribute 'context'`
````
I've attached the docker-compose file:
[docker-compose.txt](https://github.com/hyperledger/aries-cloudagent-python/files/7702235/docker-compose.txt)

**For ACA-Py Image**
I'm using [Aries-Cloudagent-Container](https://github.com/bcgov/aries-cloudagent-container), ACA-Py version 0.6.0.

Can anyone please Help with this IO error for creating wallet? I want a backup of my agent wallet with sqlite db instead of postgres. @frostyfrog @swcurran referred issue #575

**Comment by swcurran** [comment]
Sorry if you didn't get help with this.  It's very likely a docker error.  I suspect that the following occured:

- You have the wallet as a volume
- The wallet folder did not exist on startup
- It got created by docker on startup -- using root
- When the ACA-Py instance, not running as root -- tried to create the wallet, it got permission denied.

The quick'n'dirty fixis to pre-create the folder with the right permissions inherited, and then start things up.

Closing.
