### ISSUE TITLE
Exception when resolving a DID when multi-ledger support is active

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1567]
Resolving a did from a ledger that is not the main (production and write set to true) ledger raises the exception below, and a recent PyDID change (#1562) didn't resolve the issue. From the exception, the guess is that the value that is handed over to pydid is empty.

My next bet is that it's related to the ledger resolution in indy.py https://github.com/hyperledger/aries-cloudagent-python/blob/3fe6715a2bb6ac30ecddf52ec5ad5e03493354df/aries_cloudagent/resolver/default/indy.py#L48

Exception:

```
2021-12-16 15:28:09,214 indy.libindy.native.indy.services.ledger INFO 	src/services/ledger/mod.rs:137 | build_get_attrib_request() => Ok("{\"reqId\":1639668489214330900,\"identifier\":\"F6dB7dMVHUQSC64qemnBi7\",\"operation\":{\"type\":\"104\",\"dest\":\"NBUXM1kVv4yNVc6ezpaa94\",\"raw\":\"endpoint\"},\"protocolVersion\":2}")
 =================
 2021-12-16 15:28:09,240 aries_cloudagent.core.dispatcher ERROR Handler error: resolve_did
 Traceback (most recent call last):
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/resolver/routes.py", line 96, in resolve_did
     context.profile, did
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/resolver/did_resolver.py", line 73, in resolve_with_metadata
     resolver, doc = await self._resolve(profile, did)
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/resolver/did_resolver.py", line 54, in _resolve
     did,
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/resolver/base.py", line 146, in resolve
     return await self._resolve(profile, did)
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/resolver/default/indy.py", line 67, in _resolve
     Ed25519VerificationKey2018, ident="key-1", public_key_base58=recipient_key
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pydid/doc/builder.py", line 49, in add
     vmethod = type_.make(id=self._did.ref(ident), controller=controller, **kwargs)
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pydid/resource.py", line 106, in make
     return cls(**kwargs)
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pydid/verification_method.py", line 49, in __init__
     super().__init__(**data)
   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
 pydantic.error_wrappers.ValidationError: 1 validation error for Ed25519VerificationKey2018
 publicKeyBase58
   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by shaangill025** [comment]
Not able to replicate this:
Used this config
```
- id: localVON
  is_production: false
  is_write: false
  genesis_url: 'http://host.docker.internal:9000/genesis'
- id: bcorvinTest
  is_production: true
  is_write: true
  genesis_url: 'http://test.bcovrin.vonx.io/genesis'
- id: greenlightTest
  is_production: false
  genesis_url: 'http://dev.greenlight.bcovrin.vonx.io/genesis'
```
Startup
```
PORTS="5002 8002" ./scripts/run_docker start --admin 0.0.0.0 5002 --inbound-transport http 0.0.0.0 8002 --outbound-transport http -e http://host.docker.internal:8002 --admin-insecure-mode --public-invites --auto-ping-connection --auto-accept-invites --auto-accept-requests --auto-respond-credential-offer --auto-respond-credential-request --auto-respond-presentation-proposal --auto-verify-presentation --seed 00000000000000000000000000000008 --auto-provision --recreate-wallet --wallet-type indy --wallet-name issuer --wa
llet-key mykey --genesis-transactions-list ./aries_cloudagent/multi_ledger_config.yml
```
On local von network, added a new DID `P9qHs8EYhyZPpKLUReNAWA` from seed `00000000000000000000000000000099` that is not added to other networks. Then executed `/ledger/did-verkey` with DID `P9qHs8EYhyZPpKLUReNAWA` and it successfully resolves it to `localVON`

**Comment by shaangill025** [comment]
I think I have found the cause of the problem within `DIDResolver`. I will provide details here soon.

**Comment by shaangill025** [comment]
@etschelp I would appreciate it if you can check if this fixes the issue.

**Comment by etschelp** [comment]
> @etschelp I will appreciate it if you can check if this fixes the issue.

yes, looks good.

**Comment by etschelp** [comment]
> > @etschelp I will appreciate it if you can check if this fixes the issue.
> 
> yes, looks good.

Sorry, I have to specify. Works with wallet type indy, wallet type askar is broken and throws:

```
2022-01-03 15:02:30,959 aries_cloudagent.core.dispatcher ERROR Handler error: resolve_did
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/resolver/routes.py", line 96, in resolve_did
    context.profile, did
  File "/home/indy/aries_cloudagent/resolver/did_resolver.py", line 73, in resolve_with_metadata
    resolver, doc = await self._resolve(profile, did)
  File "/home/indy/aries_cloudagent/resolver/did_resolver.py", line 54, in _resolve
    did,
  File "/home/indy/aries_cloudagent/resolver/base.py", line 146, in resolve
    return await self._resolve(profile, did)
  File "/home/indy/aries_cloudagent/resolver/default/indy.py", line 51, in _resolve
    txn_record_type=GET_KEY_FOR_DID,
  File "/home/indy/aries_cloudagent/ledger/multiple_ledger/ledger_requests_executor.py", line 59, in get_ledger_for_identifier
    extracted_did, cache_did=cache_did
  File "/home/indy/aries_cloudagent/ledger/multiple_ledger/indy_vdr_manager.py", line 159, in lookup_did_in_configured_ledgers
    result = await coro_future.result()
  File "/home/indy/aries_cloudagent/ledger/multiple_ledger/indy_vdr_manager.py", line 97, in _get_ledger_by_did
    response = json.loads(response_json)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
2022-01-03 15:02:30,959 aries_cloudagent.admin.server ERROR Handler error with exception: the JSON object must be str, bytes or bytearray, not 'dict'
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/admin/server.py", line 163, in ready_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 200, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 391, in setup_context
    return await task
  File "/home/indy/aries_cloudagent/resolver/routes.py", line 96, in resolve_did
    context.profile, did
  File "/home/indy/aries_cloudagent/resolver/did_resolver.py", line 73, in resolve_with_metadata
    resolver, doc = await self._resolve(profile, did)
  File "/home/indy/aries_cloudagent/resolver/did_resolver.py", line 54, in _resolve
    did,
  File "/home/indy/aries_cloudagent/resolver/base.py", line 146, in resolve
    return await self._resolve(profile, did)
  File "/home/indy/aries_cloudagent/resolver/default/indy.py", line 51, in _resolve
    txn_record_type=GET_KEY_FOR_DID,
  File "/home/indy/aries_cloudagent/ledger/multiple_ledger/ledger_requests_executor.py", line 59, in get_ledger_for_identifier
    extracted_did, cache_did=cache_did
  File "/home/indy/aries_cloudagent/ledger/multiple_ledger/indy_vdr_manager.py", line 159, in lookup_did_in_configured_ledgers
    result = await coro_future.result()
  File "/home/indy/aries_cloudagent/ledger/multiple_ledger/indy_vdr_manager.py", line 97, in _get_ledger_by_did
    response = json.loads(response_json)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
 ```

**Comment by shaangill025** [comment]
@etschelp Can you test with PR #1583? I believe I have fixed all `Askar` related issues.

**Comment by etschelp** [comment]
Looks good
