### ISSUE TITLE
HTTPMethodNotAllowed exception when Alice's agent tries to accept the invitation

### ISSUE THREAD

**Issue by jwnicholas99** [hyperledger/aries-cloudagent-python#1572]
While following the steps in the [Aries OpenAPI Demo](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md#using-the-openapiswagger-user-interface), I get the following error at the "Tell Alice's Agent to Accept the Invitation" step when running the demo in Docker:

```
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 163, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 200, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 22, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 383, in setup_context
Faber      |     return await task
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 927, in _handle
Faber      |     raise self._http_exception
Faber      | aiohttp.web_exceptions.HTTPMethodNotAllowed: Method Not Allowed
Faber      | 2021-12-21 20:23:19,831 aries_cloudagent.admin.server ERROR Handler error with exception: Method Not Allowed
```

I do not get this error when running in a browser. What results in this error?

**Reproduction Steps:**

1. Start the Faber Agent by running
```
git clone https://github.com/hyperledger/aries-cloudagent-python
cd aries-cloudagent-python/demo
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --events --no-auto --bg

``
2. Start the Alice agent by running
```
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice --events --no-auto --bg
``
3. Follow steps in the Aries OpenAI demo

**Comment by salmaSof** [comment]
Hello,
I see it is closed but with any response, I have the same issue.

**Comment by Vishwas1** [comment]
Facing the same issue. Someone please help resolve it ? is it because of version ?

**Comment by swcurran** [comment]
Where in the process does it happen. I was able to start alice fine using the command above.
