### ISSUE TITLE
Connection /accept-request returning 404 error.

### ISSUE THREAD

**Issue by johnsonc15** [hyperledger/aries-cloudagent-python#1617]
When trying to accept a connection request, the server returns `404: Record not found.`

Here is the error it returns on the server side: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 665, in connections_accept_request
    response = await connection_mgr.create_response(connection, my_endpoint)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/protocols/connections/v1_0/manager.py", line 688, in create_response
    request = await connection.retrieve_request(session)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/models/conn_record.py", line 472, in retrieve_request
    result = await storage.find_record(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/storage/base.py", line 92, in find_record
    raise StorageNotFoundError("Record not found")
aries_cloudagent.storage.error.StorageNotFoundError: Record not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 163, in ready_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 200, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 391, in setup_context
    return await task
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 668, in connections_accept_request
    raise web.HTTPNotFound(reason=err.roll_up) from err
aiohttp.web_exceptions.HTTPNotFound: Record not found.
```

The connection does have a state of `request`.

Here is the connection body:

```
{
  "routing_state": "none",
  "invitation_key": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV",
  "connection_protocol": "connections/1.0",
  "their_role": "invitee",
  "alias": "FlexAdmin",
  "connection_id": "f501bfd4-0fdd-437b-ad35-56d70f1829e2",
  "updated_at": "2022-01-31T05:07:10.965891Z",
  "rfc23_state": "request-received",
  "invitation_mode": "once",
  "state": "request",
  "accept": "manual",
  "request_id": "1231927e-301b-46ae-b3be-6c2a7b7a5714",
  "created_at": "2022-01-31T05:03:23.318105Z",
  "my_did": "DgnYGhL4VxQwuWuLaytzwn"
}
```

**Comment by swcurran** [comment]
Do you have auto accept on?  I'm wondering if the connection has already been accepted and the protocol state object removed by the time the controller is sending the accept connection.

**Comment by swcurran** [comment]
Closing this issue.  This is a very stable part of the code base, so I suspect that this was an issue with the setup of the agent. Please reopen if there are more details about how to reproduce.
