### ISSUE TITLE
Error when starting agent with postgres. Caused by: Wallet item not found with type: config, id: mediation_invite

### ISSUE THREAD

**Issue by MajdT51** [hyperledger/aries-cloudagent-python#1699]
When i start the agent container with `docker-compose up -d` the agent starts, but I get the following error in the logs : `error_details: {'backtrace': '', 'message': 'Error: Wallet item not found\n  Caused by: Wallet item not found with type: config, id: mediation_invite\n'}`

What does it mean, will it cause errors somewhere else? I have no mediation_invite in my flags

I have built the aca-py image manually: 
  * git clone https://github.com/hyperledger/aries-cloudagent-python.git
  * cd aries-cloudagent-python
  * docker build -t acapy -f ./docker/Dockerfile.run .

And I have the following docker-compose file
```
version: '3'

services:
  my_postgres:
    image: postgres:14.2
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      PGDATA: /data/postgres-data
    volumes:
      - postgres-data:/data/postgres-data
    ports:
      - "5432:5432"
      
  my_acapy:
    image: acapy:latest
    ports:
      - "11000:11000"
      - "8000:8000"
    depends_on:
      - my_postgres
    environment:
      WAIT_HOSTS: "my_postgres:5432"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"
    entrypoint: /bin/bash
    command: [
       "-c",
       "aca-py start \
        -e http://localhost:8000/ \
        --auto-provision \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --admin '0.0.0.0' 11000 \
        --wallet-name myWalletName \
        --wallet-type indy \
        --wallet-key issuerKeySecret19 \
        --wallet-storage-type postgres_storage
        --wallet-storage-config '{\"url\":\"my_postgres:5432\",\"max_connections\":5}'
        --wallet-storage-creds '{\"account\":\"postgres\",\"password\":\"my_password\",\"admin_account\":\"postgres\",\"admin_password\":\"my_password\"}'
        --seed 00000000000000000000000123456789 \
        --genesis-url https://indy-test.bosch-digital.de/genesis \
        --label MyIssuer \
        --admin-insecure-mode \
        --auto-ping-connection \
        --jwt-secret jwtSecret19 \
        --multitenant \
        --multitenant-admin \
        --log-level DEBUG",
    ]

volumes:
  postgres-data:

```
Logs:

```
:: Inbound Transports:                      ::
::                                          ::
::   - http://0.0.0.0:8000                  ::
::                                          ::
:: Outbound Transports:                     ::
::                                          ::
::   - http                                 ::
::   - https                                ::
::                                          ::
:: Public DID Information:                  ::
::                                          ::
::   - DID: B2GsK6RwmQ7KawxYMi8byx          ::
::                                          ::
:: Administration API:                      ::
::                                          ::
::   - http://0.0.0.0:11000                 ::
::                                          ::
::                               ver: 0.7.3 ::
::::::::::::::::::::::::::::::::::::::::::::::

Listening...

2022-03-29 09:29:39,773 indy.non_secrets DEBUG open_wallet_search: >>> wallet_handle: 3, type_: 'acapy_version', query_json: '{}', options_json: '{"retrieveRecords": true, "retrieveTotalCount": false, "retrieveType": false, "retrieveValue": true, "retrieveTags": true}'
2022-03-29 09:29:39,773 indy.libindy DEBUG do_call: >>> name: indy_open_wallet_search, args: (c_int(3), c_char_p(139634044391104), c_char_p(139634104120416), c_char_p(139634061195056), <CFunctionType object at 0x7eff158ada70>)
2022-03-29 09:29:39,774 indy.libindy DEBUG do_call: Function indy_open_wallet_search returned err: 0
2022-03-29 09:29:39,775 indy.libindy DEBUG do_call: <<< <Future pending>
2022-03-29 09:29:39,775 indy.libindy.native.indy.commands DEBUG         src/commands/mod.rs:158 | NonSecretCommand command received
2022-03-29 09:29:39,777 indy.libindy.native.non_secrets_command_executor DEBUG  src/commands/non_secrets.rs:105 | OpenSearch command received
2022-03-29 09:29:39,777 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:901 | executing query: 
2022-03-29 09:29:39,780 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:901 | executing query: 
2022-03-29 09:29:39,781 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:489 | preparing query with name `s5`: SELECT i.id, i.name, i.value, i.key, i.type FROM items as i WHERE i.type = $1
2022-03-29 09:29:39,782 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:901 | executing query: 
2022-03-29 09:29:39,783 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:489 | preparing query with name `s9`: SELECT name, value from tags_plaintext where item_id = $1
2022-03-29 09:29:39,785 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:489 | preparing query with name `s10`: SELECT name, value from tags_encrypted where item_id = $1
2022-03-29 09:29:39,787 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:608 | executing statement s5 with parameters: [[83, 73, 116, 101, 50, 120, 47, 82, 85, 85, 122, 121, 68, 78, 51, 50, 43, 70, 110, 65, 73, 70, 76, 99, 98, 105, 78, 81, 78, 121, 86, 120, 77, 89, 51, 111, 56, 49, 116, 100, 115, 78, 82, 105, 87, 110, 71, 77, 102, 122, 54, 109, 49, 106, 119, 61]]
2022-03-29 09:29:39,790 indy.libindy DEBUG _indy_callback: >>> command_handle: 44, err , args: (13,)
2022-03-29 09:29:39,790 indy.libindy DEBUG _indy_callback: <<<
2022-03-29 09:29:39,791 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 44, err , args: (13,)
2022-03-29 09:29:39,793 indy.libindy DEBUG _indy_loop_callback: Function returned 13
2022-03-29 09:29:39,793 indy.libindy DEBUG _indy_loop_callback <<<
2022-03-29 09:29:39,793 indy.non_secrets DEBUG open_wallet_search: <<< res: 13
2022-03-29 09:29:39,794 indy.non_secrets DEBUG fetch_wallet_search_next_records: >>> wallet_handle: 3, wallet_search_handle: 13, count: 2
2022-03-29 09:29:39,794 indy.libindy DEBUG do_call: >>> name: indy_fetch_wallet_search_next_records, args: (c_int(3), c_int(13), c_uint(2), <CFunctionType object at 0x7eff158adc00>)
2022-03-29 09:29:39,794 indy.libindy DEBUG do_call: Function indy_fetch_wallet_search_next_records returned err: 0
2022-03-29 09:29:39,794 indy.libindy DEBUG do_call: <<< <Future pending>
2022-03-29 09:29:39,794 indy.libindy.native.indy.commands DEBUG         src/commands/mod.rs:158 | NonSecretCommand command received
2022-03-29 09:29:39,795 indy.libindy.native.non_secrets_command_executor DEBUG  src/commands/non_secrets.rs:109 | SearchNextRecords command received
2022-03-29 09:29:39,795 indy.libindy DEBUG _indy_callback: >>> command_handle: 45, err , args: (b'{"totalCount":null,"records":null}',)
2022-03-29 09:29:39,796 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 45, err , args: (b'{"totalCount":null,"records":null}',)
2022-03-29 09:29:39,796 indy.libindy DEBUG _indy_loop_callback: Function returned b'{"totalCount":null,"records":null}'
2022-03-29 09:29:39,796 indy.libindy DEBUG _indy_loop_callback <<<
2022-03-29 09:29:39,796 indy.non_secrets DEBUG fetch_wallet_search_next_records: <<< res: '{"totalCount":null,"records":null}'
2022-03-29 09:29:39,796 indy.non_secrets DEBUG close_wallet_search: >>> wallet_search_handle: 13
2022-03-29 09:29:39,796 indy.libindy DEBUG do_call: >>> name: indy_close_wallet_search, args: (c_int(13), <CFunctionType object at 0x7eff158ade58>)
2022-03-29 09:29:39,797 indy.libindy DEBUG do_call: Function indy_close_wallet_search returned err: 0
2022-03-29 09:29:39,797 indy.libindy DEBUG do_call: <<< <Future pending>
2022-03-29 09:29:39,797 indy.libindy DEBUG _indy_callback: <<<
2022-03-29 09:29:39,797 indy.libindy.native.indy.commands DEBUG         src/commands/mod.rs:158 | NonSecretCommand command received
2022-03-29 09:29:39,797 indy.libindy.native.non_secrets_command_executor DEBUG  src/commands/non_secrets.rs:113 | CloseSearch command received
2022-03-29 09:29:39,798 indy.libindy DEBUG _indy_callback: >>> command_handle: 46, err , args: ()
2022-03-29 09:29:39,798 indy.libindy DEBUG _indy_callback: <<<
2022-03-29 09:29:39,798 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 46, err , args: ()
2022-03-29 09:29:39,799 indy.libindy DEBUG _indy_loop_callback: Function returned None
2022-03-29 09:29:39,799 indy.libindy DEBUG _indy_loop_callback <<<
2022-03-29 09:29:39,799 indy.non_secrets DEBUG close_wallet_search: <<< res: None
2022-03-29 09:29:39,800 indy.non_secrets DEBUG get_wallet_record: >>> wallet_handle: 3, type_: 'config', id: 'mediation_invite', options_json: '{"retrieveType": false, "retrieveValue": true, "retrieveTags": true}'
2022-03-29 09:29:39,800 indy.libindy DEBUG do_call: >>> name: indy_get_wallet_record, args: (c_int(3), c_char_p(139634043518040), c_char_p(139634017795888), c_char_p(139634043893768), <CFunctionType object at 0x7eff158ad110>)
2022-03-29 09:29:39,801 indy.libindy DEBUG do_call: Function indy_get_wallet_record returned err: 0
2022-03-29 09:29:39,801 indy.libindy DEBUG do_call: <<< <Future pending>
2022-03-29 09:29:39,804 indy.libindy.native.indy.commands DEBUG         src/commands/mod.rs:158 | NonSecretCommand command received
2022-03-29 09:29:39,804 indy.libindy.native.non_secrets_command_executor DEBUG  src/commands/non_secrets.rs:101 | GetRecord command received
2022-03-29 09:29:39,804 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:901 | executing query: 
2022-03-29 09:29:39,805 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:489 | preparing query with name ``: SELECT id, value, key FROM items where type = $1 AND name = $2
2022-03-29 09:29:39,807 indy.libindy.native.postgres DEBUG      /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:608 | executing statement  with parameters: [[98, 100, 100, 88, 87, 108, 71, 110, 104, 110, 118, 103, 80, 54, 47, 73, 83, 54, 57, 83, 98, 113, 118, 54, 90, 66, 109, 51, 114, 110, 65, 51, 49, 51, 88, 57, 47, 88, 54, 104, 120, 43, 79, 97, 50, 65, 61, 61], [118, 68, 67, 51, 105, 114, 120, 52, 82, 65, 100, 98, 83, 50, 81, 90, 103, 80, 97, 106, 70, 115, 113, 86, 111, 121, 100, 48, 53, 65, 112, 112, 90, 104, 109, 83, 43, 97, 117, 84, 103, 104, 97, 71, 66, 76, 73, 100, 76, 90, 88, 100, 90, 53, 102, 82, 99, 82, 77, 61]]
2022-03-29 09:29:39,809 indy.libindy DEBUG _get_error_details: >>>
2022-03-29 09:29:39,810 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Wallet item not found\n  Caused by: Wallet item not found with type: config, id: mediation_invite\n'}
2022-03-29 09:29:39,810 indy.libindy DEBUG _indy_callback: >>> command_handle: 47, err , args: (b'',)
2022-03-29 09:29:39,810 indy.libindy DEBUG _indy_callback: <<<
2022-03-29 09:29:39,811 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 47, err , args: (b'',)
2022-03-29 09:29:39,811 indy.libindy WARNING _indy_loop_callback: Function returned error 
2022-03-29 09:29:39,812 indy.libindy DEBUG _indy_loop_callback <<<
2022-03-29 09:29:39,812 aries_cloudagent.core.event_bus DEBUG Notifying subscribers: <Event topic=acapy::core::startup, payload={}>
```

**Comment by ianco** [comment]
I tried running with your doker-compose and I got this error (different than yours):

```
my_acapy_1     | 2022-03-29 15:37:15,136 indy.ledger DEBUG sign_and_submit_request: <<< res: '{"op":"REQNACK","identifier":"B35gcwHjdpWryupjR2pcnp","reqId":1648568234892955000,"reason":"client request invalid: could not authenticate, verkey for B35gcwHjdpWryupjR2pcnp cannot be found"}'
my_acapy_1     | 2022-03-29 15:37:15,136 aries_cloudagent.commands.start ERROR Exception during startup:
my_acapy_1     | Traceback (most recent call last):
my_acapy_1     |   File "/home/indy/aries_cloudagent/config/ledger.py", line 152, in ledger_config
my_acapy_1     |     await wallet.set_did_endpoint(public_did, endpoint, ledger)
my_acapy_1     |   File "/home/indy/aries_cloudagent/wallet/indy.py", line 748, in set_did_endpoint
my_acapy_1     |     endorser_did=endorser_did,
my_acapy_1     |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 953, in update_endpoint_for_did
my_acapy_1     |     await self._submit(request_json, True, True)
my_acapy_1     |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 393, in _submit
my_acapy_1     |     f"Ledger rejected transaction request: {request_result['reason']}"
my_acapy_1     | aries_cloudagent.ledger.error.LedgerTransactionError: Ledger rejected transaction request: client request invalid: could not authenticate, verkey for B35gcwHjdpWryupjR2pcnp cannot be found
my_acapy_1     | 
my_acapy_1     | The above exception was the direct cause of the following exception:
my_acapy_1     | 
my_acapy_1     | Traceback (most recent call last):
my_acapy_1     |   File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init
my_acapy_1     |     await startup
my_acapy_1     |   File "/home/indy/aries_cloudagent/commands/start.py", line 28, in start_app
my_acapy_1     |     await conductor.setup()
my_acapy_1     |   File "/home/indy/aries_cloudagent/core/conductor.py", line 176, in setup
my_acapy_1     |     self.root_profile, self.setup_public_did and self.setup_public_did.did
my_acapy_1     |   File "/home/indy/aries_cloudagent/config/ledger.py", line 154, in ledger_config
my_acapy_1     |     raise ConfigError(x_ledger.message) from x_ledger  # e.g., read-only
my_acapy_1     | aries_cloudagent.config.base.ConfigError: Ledger rejected transaction request: client request invalid: could not authenticate, verkey for B35gcwHjdpWryupjR2pcnp cannot be found
```

**Comment by ianco** [comment]
Make sure when you start up your containers you have cleaned out any persistent volumes

**Comment by MajdT51** [comment]
> I tried running with your doker-compose and I got this error (different than yours):

Sorry 00000000000000000000000123456789 is not the seed that i tried with. it is an example seed that is not registered on ledger.
I registered it now on https://indy-test.bosch-digital.de/register , could you please try again if you have time.

Thanks

**Comment by ianco** [comment]
OK I see the same message now.  I suspect what is happening is ...  aca-py is checking on startup if it should connect to a mediator.  Since there's no mediator record it logs a message.  It shouldn't cause any errors.

**Comment by ianco** [comment]
It's this code:  https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/core/conductor.py#L417

**Comment by MajdT51** [comment]
Thanks
