### ISSUE TITLE
present proof v2 does not support proof request without restrictions

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1755]
Using the same flow in present proof v1 and v2 with indy credentials will give different results. If a proof request has no restrictions it will succeed in v1 and fail in v2. 

I think it should be possible to request a proof without restrictions?

The proof request looks like this for v1:

```json
{
    "connection_id": "{{connectionId}}",
    "proof_request": {
        "name": "Proof Request",
        "version": "1.0.0",
        "requested_attributes": {
            "name": {
                "name": "name",
                "restrictions": []
            }
        },
        "requested_predicates": {}
    }
}
```

and like this for v2:

```json
{
    "connection_id": "{{connectionId}}",
    "presentation_request": {
        "indy": {
            "name": "Proof Request",
            "version": "1.0.0",
            "requested_attributes": {
                "name": {
                    "name": "name",
                    "restrictions": []
                }
            },
            "requested_predicates": {}
        }
    }
}
```

V2 will log errors when validating the received presentation (so no errors returned in the api).

The error:

```
Traceback (most recent call last):
  File "/Users/timo/Developer/Work/Projects/AFJ/aries-cloudagent-python/aries_cloudagent/core/dispatcher.py", line 197, in handle_message
    await handler(context, responder)
  File "/Users/timo/Developer/Work/Projects/AFJ/aries-cloudagent-python/aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_handler.py", line 40, in handle
    pres_ex_record = await pres_manager.receive_pres(
  File "/Users/timo/Developer/Work/Projects/AFJ/aries-cloudagent-python/aries_cloudagent/protocols/present_proof/v2_0/manager.py", line 329, in receive_pres
    receive_pres_return = await pres_format.handler(
  File "/Users/timo/Developer/Work/Projects/AFJ/aries-cloudagent-python/aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py", line 292, in receive_pres
    _check_proof_vs_proposal()
  File "/Users/timo/Developer/Work/Projects/AFJ/aries-cloudagent-python/aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py", line 198, in _check_proof_vs_proposal
    raise V20PresFormatHandlerError(
aries_cloudagent.protocols.present_proof.v2_0.formats.handler.V20PresFormatHandlerError: Presented attribute name does not satisfy proof request restrictions []
```

See here for a full reproduction flow, I can give access if you want to easily be able to run the flow to reproduce: https://www.postman.com/timoanimo/workspace/timo/flow/6270013353dfac45e5b56995

**Comment by swcurran** [comment]
@andrewwhitehead -- this is a weird one.  Can you please take a look?

**Comment by swcurran** [comment]
Assigned this to @shaangill025 for now, but if anyone wanted to learn about the details of how protocols are implemented, this would be a fun investigation...
