### ISSUE TITLE
Urgent! Unable to issue credential from Faber to Multitenancy Alice 

### ISSUE THREAD

**Issue by kobkrit** [hyperledger/aries-cloudagent-python#1758]
I have setup 2 ACA-py agents with running local von-network.

Faber
```
demo/run_demo faber --wallet-type indy
```

Alice
```
demo/run_demo alice --wallet-type indy --multitenant
```

For Alice, I already did
1. (Alice) Create a subwallet by calling Open API "/multitenancy/wallet" 
2. (Alice) Save token and add it to Authorization header for all future Alice's OpenAPI calls.
3. (Faber) Create invitation by  "/out-of-band/create-invitation"
4. (Alice) Connected with Faber using "/out-of-band/receive-invitation" with Authorization token from (2)
5. Already check the connections in both Faber and Alice, their status are both active.
6.  (Faber) Issue credential by calling "/issue-credential-2.0/send"
```JSON
 {
          "connection_id": "d92e7d39-2fc9-4a89-8e93-d26098ac0737", 
          "comment": "comment", 
          "auto_remove": true,
          "credential_preview":{
            "@type": "https://didcomm.org/issue-credential/2.0/credential-preview", 
            "attributes": [
              {"name": "name", "value": "Kobkrit Viriyayudhakorn"},
              {"name": "vaccine_brand", "value": "Shinopham"},
              {"name": "birthdate_dateint", "value": "19870424"},
              {"name": "timestamp", "value": "1650784365"}
            ]
          }, 
          "filter": {
            "indy": {
              "cred_def_id": "CRaUqFbPW5Q1iM3BSdXjnL:3:CL:423:faber.agent.vaccine_schema",
              "issuer_did": "CRaUqFbPW5Q1iM3BSdXjnL",
              "schema_id": "CRaUqFbPW5Q1iM3BSdXjnL:2:vaccine schema:100.58.51",
              "schema_issuer_did": "CRaUqFbPW5Q1iM3BSdXjnL",
              "schema_name": "vaccine schema",
              "schema_version": "100.58.51"
            }
          },
          "trace": false
        }
```
and got the response like this
```
{"created_at": "2022-05-04T14:38:27.208749Z", "trace": false, "cred_ex_id": "9a25953c-4014-4356-9246-136dc30ebfd5", "by_format": {"cred_proposal": {"indy": {"cred_def_id": "CRaUqFbPW5Q1iM3BSdXjnL:3:CL:423:faber.agent.vaccine_schema", "issuer_did": "CRaUqFbPW5Q1iM3BSdXjnL", "schema_id": "CRaUqFbPW5Q1iM3BSdXjnL:2:vaccine schema:100.58.51", "schema_issuer_did": "CRaUqFbPW5Q1iM3BSdXjnL", "schema_name": "vaccine schema", "schema_version": "100.58.51"}}, "cred_offer": {"indy": {"schema_id": "CRaUqFbPW5Q1iM3BSdXjnL:2:vaccine schema:100.58.51", "cred_def_id": "CRaUqFbPW5Q1iM3BSdXjnL:3:CL:423:faber.agent.vaccine_schema", "key_correctness_proof": {"c": "46554167791154882352323336568154599116440049710402790426456561586013080200472", "xz_cap": "1196381624467110317936645037686913129984337334549114639108472297222930378800052923112308929829590068008608179917454747649437423806130661503558549821486169422972067062819610707175123915969849154946990429700472982100346602943454691358113833251918496139673944524474269313498780877046660871112633822366025692377429741624708362254103023029681354220365122597727265627492265714651750316138248137698627981355548838525995009371177137043105039561697834205292607417712726521664464319285864531905041840428420786182980329188730359993783867422962728292209053135169641927335748253782461166875469600501038030678001346320944778507058164766881873242664955639636011044586047403280608135873635091171486808790293920", "xr_cap": [["name", "952287579708440458905817472410209951922406001044010817862371316078892242504584661545626133582531673347918111699561978134645193317478228855948194619095583244565981277941682614679944358192705894305657618574955760537202585870266413866251565518944690707491829329280089541793601711497325672311494702136417430659659360067673406958218852281201168480597682919552997398914143698396117024966485124035143953069921241041312103837927825616717944985920999145690060029643127145015772149115310772485641022432855086549877552013551359691173590936086395058923481299123970584517459630795615793148871754921448616056468593972487580578555392502785314101395359470958365591865866354736771266473602868222309939998154602"], ["birthdate_dateint", "10 ....
```

7. (Alice) Alice terminal show errors as follows.
```
#15 After receiving credential offer, send credential request
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<AriesAgent.handle_issue_credential_v2_0() done, defined at /home/indy/demo/runners/agent_container.py:228> exception=Exception('Error: 404: cred_ex_v20 record not found: 169250b7-adb5-4598-bcd4-a8d243b3687f. WalletItemNotFound.',)>
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 817, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1009, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 404, message='cred_ex_v20 record not found: 169250b7-adb5-4598-bcd4-a8d243b3687f. WalletItemNotFound.', url=URL('http://122.155.177.145:8031/issue-credential-2.0/records/169250b7-adb5-4598-bcd4-a8d243b3687f/send-request')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/demo/runners/agent_container.py", line 250, in handle_issue_credential_v2_0
    f"/issue-credential-2.0/records/{cred_ex_id}/send-request"
  File "/home/indy/demo/runners/support/agent.py", line 918, in admin_POST
    "POST", path, data, text, params, headers=headers
  File "/home/indy/demo/runners/support/agent.py", line 820, in admin_request
    raise Exception(f"Error: {resp_text}") from e
Exception: Error: 404: cred_ex_v20 record not found: 169250b7-adb5-4598-bcd4-a8d243b3687f. WalletItemNotFound.
Alice      | 2022-05-04 14:38:27,302 aries_cloudagent.admin.server ERROR Handler error with exception: cred_ex_v20 record not found: 169250b7-adb5-4598-bcd4-a8d243b3687f. WalletItemNotFound.
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/storage/indy.py", line 105, in get_record
Alice      |     self._wallet.handle, record_type, record_id, options_json
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/non_secrets.py", line 319, in get_wallet_record
Alice      |     get_wallet_record.cb)
Alice      | indy.error.WalletItemNotFound
Alice      | 
Alice      | The above exception was the direct cause of the following exception:
Alice      | 
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1220, in credential_exchange_send_bound_request
Alice      |     cred_ex_id,
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base_record.py", line 233, in retrieve_by_id
Alice      |     cls.RECORD_TYPE, record_id, {"retrieveTags": False}
Alice      |   File "/home/indy/aries_cloudagent/storage/indy.py", line 111, in get_record
Alice      |     ) from x_indy
Alice      | aries_cloudagent.storage.error.StorageNotFoundError: cred_ex_v20 record not found: 169250b7-adb5-4598-bcd4-a8d243b3687f
Alice      | 
Alice      | The above exception was the direct cause of the following exception:
Alice      | 
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 159, in ready_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 196, in debug_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 339, in check_multitenant_authorization
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 383, in setup_context
Alice      |     return await task
Alice      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 1223, in credential_exchange_send_bound_request
Alice      |     raise web.HTTPNotFound(reason=err.roll_up) from err
Alice      | aiohttp.web_exceptions.HTTPNotFound: cred_ex_v20 record not found: 169250b7-adb5-4598-bcd4-a8d243b3687f. WalletItemNotFound.
```

I have try all above again with single user Alice (Running Alice WITHOUT Multitenancy mode). They are working perfectly.

How can I make it work with Multitenancy mode?

Please help.

**Comment by ianco** [comment]
The controllers in the alice/faber demo need to know the sub-wallet that is "in context".

When you create the sub-wallet through the demo code (option "w" I think) then the controller sets some internal context so that it knows which wallet is "in context" to process any received webhooks.

If you create the sub-wallet through the admin api, then the alice controller doesn't "know" about the new wallet and is running in context of a different wallet.

Solution is to either:
- do everything through the alice/faber menu (i.e. use "w" to create a new sub-wallet)
- or do everything through the admin api (run your aca-py agents standalone not through the alice/faber code)
