### ISSUE TITLE
Copying invitations from the Faber agent to the Alice agent throws an error( It was working before)

### ISSUE THREAD

**Issue by chetanapujari** [hyperledger/aries-cloudagent-python#1760]
aries_cloudagent.messaging.models.base ERROR Service message valid
ation error:
Alice      |
Alice      | =================
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 137, in deserialize
Alice      |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
Shutting down agent ...
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 904, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'recipientKeys': {0: ['Value did:key:z6Mkqnc77xet
gw2GFYiE4kSCw5hKzUp3vyWw6Q xT7Y3XYY8j is not in W3C did:key format']}}
Alice      | 2022-05-05 09:59:35,356 aries_cloudagent.admin.server ERROR Handler error with exception:
Service schema validation failed
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 137, in deserialize
Alice      |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 904, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'recipientKeys': {0: ['Value did:key:z6Mkqnc77xet
gw2GFYiE4kSCw5hKzUp3vyWw6Q xT7Y3XYY8j is not in W3C did:key format']}}
Alice      |
Alice      | The above exception was the direct cause of the following exception:
Alice      |
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 159, in ready_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 196, in debug_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/midd
lewares.py", line 34, in validation_middleware
Alice      |     schema["schema"], request, locations=schema["locations"]
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/webargs/asyncparser.
py", line 90, in parse
Alice      |     result = schema.load(parsed)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 861, in _do_load
Alice      |     unknown=unknown,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 669, in _deserialize
Alice      |     index=index,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 493, in _call_and_store
Alice      |     value = getter_func(data)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 662, in <lambda>
Alice      |     val, field_name, data, **d_kwargs
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/fields.p
y", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/fields.p
y", line 713, in _deserialize
Alice      |     result.append(self.inner.deserialize(each, **kwargs))
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/fields.p
y", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/aries_cloudagent/protocols/out_of_band/v1_0/messages/invitation.py", li
ne 98, in _deserialize
Alice      |     return Service.deserialize(value)
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 140, in deserialize
Alice      |     raise BaseModelError(f"{cls.__name__} schema validation failed") from err
Alice      | aries_cloudagent.messaging.models.base.BaseModelError: Service schema validation failed
Alice      | 2022-05-05 09:59:35,363 aiohttp.server ERROR Error handling request
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 137, in deserialize
Alice      |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 904, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'recipientKeys': {0: ['Value did:key:z6Mkqnc77xet
gw2GFYiE4kSCw5hKzUp3vyWw6Q xT7Y3XYY8j is not in W3C did:key format']}}
Alice      |
Alice      | The above exception was the direct cause of the following exception:
Alice      |
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol
.py", line 435, in _handle_request
Alice      |     resp = await request_handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py",
 line 504, in _handle
Alice      |     resp = await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewa
res.py", line 117, in impl
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 159, in ready_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 196, in debug_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/midd
lewares.py", line 34, in validation_middleware
Alice      |     schema["schema"], request, locations=schema["locations"]
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/webargs/asyncparser.
py", line 90, in parse
Alice      |     result = schema.load(parsed)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 861, in _do_load
Alice      |     unknown=unknown,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 669, in _deserialize
Alice      |     index=index,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 493, in _call_and_store
Alice      |     value = getter_func(data)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.p
y", line 662, in <lambda>
Alice      |     val, field_name, data, **d_kwargs
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/fields.p
y", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/fields.p
y", line 713, in _deserialize
Alice      |     result.append(self.inner.deserialize(each, **kwargs))
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/fields.p
y", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/aries_cloudagent/protocols/out_of_band/v1_0/messages/invitation.py", li
ne 98, in _deserialize
Alice      |     return Service.deserialize(value)
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 140, in deserialize
Alice      |     raise BaseModelError(f"{cls.__name__} schema validation failed") from err
Alice      | aries_cloudagent.messaging.models.base.BaseModelError: Service schema validation failed
Alice      |
Alice      | Shutting down
Alice      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 824, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1
009, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://ho
st.docker.internal:8031/out-of-band/receive-invitation?use_existing_connection=true')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/alice.py", line 242, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until
_complete
    return future.result()
  File "/home/indy/demo/runners/alice.py", line 138, in main
    await input_invitation(alice_agent)
  File "/home/indy/demo/runners/alice.py", line 103, in input_invitation
    connection = await agent_container.input_invitation(details, wait=True)
  File "/home/indy/demo/runners/agent_container.py", line 984, in input_invitation
    return await self.agent.input_invitation(invite_details, wait)
  File "/home/indy/demo/runners/agent_container.py", line 578, in input_invitation
    connection = await self.receive_invite(invite_details)
  File "/home/indy/demo/runners/support/agent.py", line 1203, in receive_invite
    params=params,
  File "/home/indy/demo/runners/support/agent.py", line 925, in admin_POST
    "POST", path, data, text, params, headers=headers
  File "/home/indy/demo/runners/support/agent.py", line 827, in admin_request
    raise Exception(f"Error: {resp_text}") from e
Exception: Error: 500 Internal Server Error

Server got itself in trouble

**Comment by shaangill025** [comment]
@chetanapujari I am not able to replicate the error. For me, I am able to create a successful connection [Faber->Alice]. Can you share any arguments you are using when starting up Faber and Alice.

**Comment by chetanapujari** [comment]
> 
@shaangill025 Thank you for your response

I am following this
Terminal 1:
git clone https://github.com/hyperledger/aries-cloudagent-python
cd aries-cloudagent-python/demo
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber

Terminal 2:
cd aries-cloudagent-python/demo
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice


Previously, it was working, but since a few days, it is giving me an error

**Comment by chetanapujari** [comment]
Initially, when I tried to copy the invitation, it was adding space for every new line, which resulted in an error. However, it has now started working, thank you
