### ISSUE TITLE
OOB invitation: only works with auto_respond_presentation_request configured?

### ISSUE THREAD

**Issue by docmanni** [hyperledger/aries-cloudagent-python#1764]
I am using aca-py 0.7.4-rc1 and try to get the OOB invitations with a presentation request attached running. I have noticed that only auto-responding to presentation requests leads to some useful result. However, I don't want that. I want to present the request to the user and let the user decide whether to answer it or not. It actually works, as aca-py does post data to ".../topic/present_proof_v2_0/" where I can initiate the presentation request/response cycle. However, before that, there is an exception thrown which leads to the answer of the out-of-band/receive-invitation to be http code 500:

<pre>
2022-05-07 00:14:04,291 aries_cloudagent.core.dispatcher ERROR Handler error: invitation_receive
Traceback (most recent call last):
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 221, in invitation_receive
    result = await oob_mgr.receive_invitation(
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 565, in receive_invitation
    await self._process_pres_request_v2(
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 832, in _process_pres_request_v2
    raise OutOfBandManagerError(
aries_cloudagent.protocols.out_of_band.v1_0.manager.OutOfBandManagerError: Configuration set auto_present false: cannot respond automatically to presentation requests
2022-05-07 00:14:04,314 aries_cloudagent.admin.server ERROR Handler error with exception: Configuration set auto_present false: cannot respond automatically to presentation requests
Traceback (most recent call last):
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 159, in ready_middleware
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 196, in debug_middleware
    return await handler(request)
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 340, in check_multitenant_authorization
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 384, in setup_context
    return await task
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 221, in invitation_receive
    result = await oob_mgr.receive_invitation(
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 565, in receive_invitation
    await self._process_pres_request_v2(
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 832, in _process_pres_request_v2
    raise OutOfBandManagerError(
aries_cloudagent.protocols.out_of_band.v1_0.manager.OutOfBandManagerError: Configuration set auto_present false: cannot respond automatically to presentation requests
2022-05-07 00:14:04,355 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 159, in ready_middleware
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 196, in debug_middleware
    return await handler(request)
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 340, in check_multitenant_authorization
    return await handler(request)
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 384, in setup_context
    return await task
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/routes.py", line 221, in invitation_receive
    result = await oob_mgr.receive_invitation(
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 565, in receive_invitation
    await self._process_pres_request_v2(
  File "/home/user/projects/hyperledger/aries-cloudagent-python/aries_cloudagent/protocols/out_of_band/v1_0/manager.py", line 832, in _process_pres_request_v2
    raise OutOfBandManagerError(
aries_cloudagent.protocols.out_of_band.v1_0.manager.OutOfBandManagerError: Configuration set auto_present false: cannot respond automatically to presentation requests
</pre>

And, sure enough, that's what the code says in manager.py:

<pre>
        pres_ex_record = V20PresExRecord(
            connection_id=conn_rec.connection_id,
            thread_id=pres_request_msg["@id"],
            initiator=V20PresExRecord.INITIATOR_EXTERNAL,
            role=V20PresExRecord.ROLE_PROVER,
            pres_request=pres_request_msg,
            auto_present=self.profile.context.settings.get(
                "debug.auto_respond_presentation_request"                                    <------------
            ),
            trace=trace,
        )

        pres_ex_record = await pres_mgr.receive_pres_request(pres_ex_record)
        if pres_ex_record.auto_present:                                                      <------------
            (pres_ex_record, pres_msg) = await pres_mgr.create_pres(
                pres_ex_record=pres_ex_record,
                comment=(
                    f"auto-presented for proof requests"
                    f", pres_ex_record: {pres_ex_record.pres_ex_id}"
                ),
            )
            responder = self.profile.inject_or(BaseResponder)
            if responder:
                await responder.send(
                    message=pres_msg,
                    target_list=await self.fetch_connection_targets(
                        connection=conn_rec
                    ),
                )
        else:
            raise OutOfBandManagerError(
                (
                    "Configuration set auto_present false: cannot "
                    "respond automatically to presentation requests"
                )
            )
</pre>

From what I understand in this code snippet, if the flag "--auto-respond-presentation-request" is not set, the OOB invitation with attached presentation requests will not work as intended. Is that right?

This exception leads to the server answer:
<pre>
<html><head><title>500 Internal Server Error</title></head><body>
<h1>500 Internal Server Error</h1>
Server got itself in trouble
</body></html>
</pre>

...instead of a connection record.

Any ideas? I don't want any auto-response, not in this case, not for any other presentation requests. I want to let the user decide what to do with such requests (as in "self-sovereign" ;-) ).

Thanks for your kind help! Any idea how to do this is appreciated. Should I just ignore this error message?

**Comment by TimoGlastra** [comment]
This has been addressed I think in https://github.com/hyperledger/aries-cloudagent-python/pull/1710

**Comment by swcurran** [comment]
Closing as addressed in #1710 . Please let me know if this should be re-opened. It would be great to get a formal confirmation that issue is addressed.

**Comment by docmanni** [comment]
I have upgraded to 0.7.4-rc2 and can confirm that this error does not come up any longer. Thank you very much, everyone!
