### ISSUE TITLE
Bug: Error in integration test in testing an unrelated PR

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1832]
We had an error in one of the integration tests during the testing of an unrelated PR.  Here is the [run](https://github.com/hyperledger/aries-cloudagent-python/runs/6993946190?check_suite_focus=true).

Perhaps an intermittent error?  Anything we can do to fix it?

```
Failing scenarios:
  features/0453-issue-credential.feature:55  Issue a credential with revocation, with the Issuer beginning with an offer, and then revoking the credential -- @1.1 

3 features passed, 1 failed, 1 skipped
22 scenarios passed, 1 failed, 28 skipped
169 steps passed, 1 failed, 375 skipped, 0 undefined
Took 14m16.479s
```

```
#3/4 Create a new schema/cred def on the ledger
INFO:aiohttp.access:172.17.0.1 [21/Jun/2022:22:18:44 +0000] "POST /webhooks/topic/connections/ HTTP/1.1" 200 149 "-" "Python/3.6 aiohttp/3.8.1"
INFO:aiohttp.access:172.17.0.1 [21/Jun/2022:22:18:44 +0000] "POST /webhooks/topic/connections/ HTTP/1.1" 200 149 "-" "Python/3.6 aiohttp/3.8.1"
7hSchema:
7h{
"sent":{
"schema_id":"KHczvURkcnuwEkGwfZi4gj:2:Schema_DriversLicense:1.0.1",
"schema":{
"ver":"1.0",
"id":"KHczvURkcnuwEkGwfZi4gj:2:Schema_DriversLicense:1.0.1",
"name":"Schema_DriversLicense",
"version":"1.0.1",
"attrNames":[
"age",
"expiry",
"address",
"DL_number",
"id"
],
"seqNo":null
}
},
"schema_id":"KHczvURkcnuwEkGwfZi4gj:2:Schema_DriversLicense:1.0.1",
"schema":{
"ver":"1.0",
"id":"KHczvURkcnuwEkGwfZi4gj:2:Schema_DriversLicense:1.0.1",
"name":"Schema_DriversLicense",
"version":"1.0.1",
"attrNames":[
"age",
"expiry",
"address",
"DL_number",
"id"
],
"seqNo":null
}
}
7hSchema ID: KHczvURkcnuwEkGwfZi4gj:2:Schema_DriversLicense:1.0.1
7hAries      | 2022-06-21 22:18:48,893 aries_cloudagent.admin.server ERROR Handler error with exception: Ledger default has no schema KHczvURkcnuwEkGwfZi4gj:2:Schema_DriversLicense:1.0.1
7hAries      | Traceback (most recent call last):
7hAries      |   File "/home/indy/aries_cloudagent/messaging/credential_definitions/routes.py", line 262, in credential_definitions_send_credential_definition
7hAries      |     endorser_did=endorser_did,
7hAries      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
      Assertion Failed: FAILED SUB-STEP: Given "Acme" is ready to issue a credential for driverslicense
      Substep info: Traceback (most recent call last):
        File "/home/indy/demo/runners/support/agent.py", line 848, in admin_request
          resp.raise_for_status()
        File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1009, in raise_
```

**Comment by swcurran** [comment]
The test passed on the second try...  

Not good.  It would be good if you could take a quick look, but feel free to close if not obvious.  We can reopen if this is really a problem.

**Comment by shaangill025** [comment]
While testing PR #1761 [--wallet-type askar], there are inconsistencies in integration test results. With local von-network [--taa-sample], local tails-server, and running `./run_bdd -t @taa_required`, out of 6 test runs I have the following:
- 4 successful runs
- 2 runs failed with `@T003-TAA`
  ```
  Aries      | 2022-06-22 15:16:12,258 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
  Aries      | Traceback (most recent call last):
  Aries      |   File "/home/indy/aries_cloudagent/core/event_bus.py", line 120, in notify
  Aries      |     await processor()
  Aries      |   File "/home/indy/aries_cloudagent/revocation/routes.py", line 1331, in on_revocation_registry_event
  Aries      |     max_cred_num=rev_reg_size,
  Aries      |   File "/home/indy/aries_cloudagent/revocation/indy.py", line 51, in init_issuer_registry
  Aries      |     raise RevocationNotSupportedError("Credential definition not found")
  Aries      | aries_cloudagent.revocation.error.RevocationNotSupportedError: Credential definition not found
  ``` 
  And 1 out of these also had `@T001a-TAA` failing with:
  ```
  Aries      | Traceback (most recent call last):
  Aries      |   File "/home/indy/aries_cloudagent/wallet/routes.py", line 449, in wallet_set_public_did
  Aries      |     connection_id=connection_id,
  Aries      |   File "/home/indy/aries_cloudagent/wallet/routes.py", line 513, in promote_wallet_public_did
  Aries      |     raise LookupError(f"DID {did} is not posted to the ledger")
  Aries      | LookupError: DID 29ZCzHQdMZcngW7NHw9HDJ is not posted to the ledger

  ```
  
With `LEDGER_URL=http://test.bcovrin.vonx.io PUBLIC_TAILS_URL=https://tails-test.vonx.io ./run_bdd -t @GHA`, I haven't been able to trigger an error with repetitive testing.

**Comment by swcurran** [comment]
FYI -- for the run today, a test failed, but this time it was the test after the one first reported (original comment above).  This time it was:

```
features/0453-issue-credential.feature:56  Issue a credential with revocation, with the Issuer beginning with an offer, and then revoking the credential -- @1.2 
```

**Comment by swcurran** [comment]
I believe this has been resolved. Closing.
