### ISSUE TITLE
Askar error encountered on first startup when upgrading an agent from `0.7.4-rc4` to `0.7.4`

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#1855]
The following error was encountered when upgrading an agent already configured to use Askar from `0.7.4-rc4` to `0.7.4`.  This error only occurred on the first startup.  Subsequent restarts occurred successfully without error.  The agent is configured to use Askar storage, and is hosted in OCP.

```
2022-07-08 17:43:35,904 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/askar/store.py", line 160, in open_store
    self.key,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/store.py", line 328, in open
    return Store(await bindings.store_open(uri, key_method, pass_key, profile), uri)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/bindings/__init__.py", line 91, in store_open
    return_type=StoreHandle,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/bindings/lib.py", line 355, in invoke_async
    name, argtypes, *args, return_type=return_type
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
aries_askar.error.AskarError: Backend error
Caused by: error communicating with database: No route to host (os error 113)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 121, in setup
    self.root_profile, self.setup_public_did = await wallet_config(context)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/wallet.py", line 55, in wallet_config
    profile = await mgr.open(context, profile_cfg)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/askar/profile.py", line 261, in open
    opened = await store_config.open_store(provision=False)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/askar/store.py", line 171, in open_store
    raise ProfileError("Error opening store") from err
aries_cloudagent.core.error.ProfileError: Error opening store

Shutting down
```

**Comment by swcurran** [comment]
This is resolved. It looks like it was an environmental issue.

**Comment by iamjeho** [comment]
How could You solve this problem?
