### ISSUE TITLE
Send credential definition fails in ACAPy with request timed out

### ISSUE THREAD

**Issue by tdiesler** [hyperledger/aries-cloudagent-python#1999]
Recently the getting started test keeps failing with a request timed out

In ACAPy-0.7.5 I see ...
```
acapy  | 2022-11-02 12:30:20,222 indy.libindy.native.indy.services.ledger INFO 	src/services/ledger/mod.rs:241 | build_revoc_reg_entry_request() => Ok("{\"reqId\":1667392220222165525,\"identifier\":\"HALJ6zGdkkWVS28tRTMntC\",\"operation\":{\"type\":\"114\",\"revocRegDefId\":\"HALJ6zGdkkWVS28tRTMntC:4:HALJ6zGdkkWVS28tRTMntC:3:CL:118:default:CL_ACCUM:098a8108-ed63-414f-a318-6d72def3b589\",\"revocDefType\":\"CL_ACCUM\",\"value\":{\"accum\":\"21 124160E750AF0C97057CBCC9C84D3CD75E2BF4DBAEDF13C0498EABA8C7A32D4B9 21 122A76139F4C39E7876B38A704E709B87B7C6B027B6759C10B1557B483706C40E 6 7A9D0347E23CC34DB973206998FFED4861DDB20279BD5018DC08EDB451C95F4A 4 20EA523FA568D5D9237D21B81BC77F5D2170509D68C7286A5E23836833311243 6 56788113EFC464F383AD6950FD055593958FE5709831AC54B1F03450A4B3FF5B 4 38D481C88655BB6415D34A0388CCB6FE947FA8071C469D2FD09C500E2BF7AE80\"}},\"protocolVersion\":2}")
acapy  | 2022-11-02 12:30:28,226 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:749 | Drop started
acapy  | 2022-11-02 12:30:28,226 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:757 | Drop wait worker
acapy  | 2022-11-02 12:30:28,228 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:760 | Drop finished
acapy  | 2022-11-02 12:30:33,233 aries_cloudagent.utils.http WARNING Upload error: request timed out
acapy  | 2022-11-02 12:30:44,038 aries_cloudagent.utils.http WARNING Upload error: request timed out
acapy  | 2022-11-02 12:30:54,936 aries_cloudagent.utils.http WARNING Upload error: request timed out
acapy  | 2022-11-02 12:31:05,939 aries_cloudagent.utils.http WARNING Upload error: request timed out
```

which suggest that ACAPy can't reach a certain endpoint. This may well be a configuration bad on my side, however I'd like the acapy error message to be more descriptive about what endpoint it cannot reach. Is it perhaps the tails-server that cannot get reached?

**Comment by tdiesler** [comment]
In the tails-server I see

```
2022-11-02 13:04:41,026 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/indy/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/indy/tails_server/web.py", line 85, in put_file
    genesis_txn_bytes, revocation_reg_id, storage_path
  File "/home/indy/tails_server/ledger.py", line 29, in get_rev_reg_def
    pool = await indy_vdr.open_pool(transactions_path=tmp_file.name)
  File "/home/indy/.local/lib/python3.7/site-packages/indy_vdr/pool.py", line 173, in open_pool
    await pool.refresh()
  File "/home/indy/.local/lib/python3.7/site-packages/indy_vdr/pool.py", line 58, in refresh
    await bindings.pool_refresh(self.handle)
indy_vdr.error.VdrError: Pool timeout: Request was interrupted
2022-11-02 13:04:41,031 aiohttp.access INFO 172.22.0.8 [02/Nov/2022:13:04:20 +0000] "PUT /8XwrAmugANgtsVJ8ScvBfo:4:8XwrAmugANgtsVJ8ScvBfo:3:CL:132:default:CL_ACCUM:c3a8d83b-cf6e-4978-a3fe-5ebca075289d HTTP/1.1" 500 244 "-" "Python/3.6 aiohttp/3.8.3"
```

**Comment by ianco** [comment]
Which tails server are you using?

**Comment by tdiesler** [comment]
bcgov/indy-tails-server-1.0.0

https://github.com/tdiesler/nessus-aries/blob/main/build-images.sh#L85

**Comment by tdiesler** [comment]
@WadeBarnes would you perhaps have an idea what is going on here?

**Comment by WadeBarnes** [comment]
Can the tails-server resolve the network (von-network) addresses and do you know what it's getting for that address?

**Comment by tdiesler** [comment]
It can resolve the named hosts from the compose file e.g. 

```
indy@a22d5999d096:~$ curl -s --write-out '%{http_code}' --output /dev/null http://webserver:8000
200
```

The tails-server, would however not know how to connect to any of the other containers (i.e. there is no config for it)
https://github.com/tdiesler/nessus-aries/blob/main/docker-compose.yml#L125

**Comment by WadeBarnes** [comment]
There is no ledger config for a tails-server it gets it's info from the agents when they post info, AFAIK.  Tails servers are not tied to a network.  A single tails server can be used for multiple networks.

**Comment by tdiesler** [comment]
acapy, gets the genesis txs from 'host.docker.internal' like this ...

```
indy@10123eeca73d:~$ curl -s http://host.docker.internal:9000/genesis
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaL....
```

still, the tails-server fails to connect to something

```
  File "/home/indy/.local/lib/python3.7/site-packages/indy_vdr/pool.py", line 58, in refresh
    await bindings.pool_refresh(self.handle)
indy_vdr.error.VdrError: Pool timeout: Request was interrupted
2022-11-02 13:04:41,031 aiohttp.access INFO 172.22.0.8 [02/Nov/2022:13:04:20 +0000] "PUT /8XwrAmugANgtsVJ8ScvBfo:4:8XwrAmugANgtsVJ8ScvBfo:3:CL:132:default:CL_ACCUM:c3a8d83b-cf6e-4978-a3fe-5ebca075289d HTTP/1.1" 500 244 "-" "Python/3.6 aiohttp/3.8.3"
```

Is it perhaps trying to reach back to acapy on that IP?

**Comment by WadeBarnes** [comment]
What addresses are listed for the nodes in the genesis file?

**Comment by tdiesler** [comment]
```
[core@vmd94237 nessus-aries]$ curl -s http://localhost:9000/genesis | jq . | grep node_ip
        "node_ip": "host.docker.internal",
        "node_ip": "host.docker.internal",
        "node_ip": "host.docker.internal",
        "node_ip": "host.docker.internal",
```

**Comment by tdiesler** [comment]
Unlike acapy, the tails-server cannot resolve `host.docker.internal` for some reason

```
curl: (6) Could not resolve host: host.docker.internal
```

**Comment by tdiesler** [comment]
Ok, that works. Thanks for your help @ianco @WadeBarnes
