### ISSUE TITLE
Error when verifying non valid predicate proof

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#200]
I've played with the OpenAPI Demo and changed the predicate of the proof request to an age such that the condition is false ( 24 >= 30). This leads to the following error message:

```
#28 Check if proof is valid
Faber      | 2019-09-25 21:00:54,091 aiohttp.server ERROR Error handling request
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
Faber      |     resp = await task
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
Faber      |     resp = await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/messaging/present_proof/v1_0/routes.py", line 692, in presentation_exchange_verify_presentation
Faber      |     presentation_exchange_record
Faber      |   File "/home/indy/aries_cloudagent/messaging/present_proof/v1_0/manager.py", line 397, in verify_presentation
Faber      |     indy_proof_request, indy_proof, schemas, credential_definitions
Faber      |   File "/home/indy/aries_cloudagent/verifier/indy.py", line 44, in verify_presentation
Faber      |     json.dumps({}),
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/anoncreds.py", line 1533, in verifier_verify_proof
Faber      |     verifier_verify_proof.cb)
Faber      | indy.error.CommonInvalidStructure
```

Seems that the resulting JSON document is unexpected.

**Comment by swcurran** [comment]
Thanks for the submission @domwoe. I suspect this is in a lower level than ACA-Py, but we can look.

Can you please post the issued credential and the proof request that you provided in the call that failed?

Thanks

**Comment by domwoe** [comment]
The Credential:
`{
      "referent": "f7656a34-d74f-4509-982d-aa1d2a0fa9c6",
      "attrs": {
        "name": "Alice Smith",
        "date": "2018-05-28",
        "degree": "Maths",
        "age": "24"
      },
      "schema_id": "DeipsSP85X438k9boJ8viK:2:degree schema:71.33.26",
      "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default",
      "rev_reg_id": null,
      "cred_rev_id": null
    }`

And the proof request:
`{
  "connection_id": "979deb47-da9c-4f29-93cf-ba6fbbc4d661",
  "proof_request": {
    "name": "Proof of Education",
    "version": "1.0",
    "requested_attributes": {
      "0_name_uuid": {
        "name": "name",
        "restrictions": [
          {
            "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
          }
        ]
      },
      "0_date_uuid": {
        "name": "date",
        "restrictions": [
          {
            "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
          }
        ]
      },
      "0_degree_uuid": {
        "name": "degree",
        "restrictions": [
          {
            "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
          }
        ]
      },
      "0_self_attested_thing_uuid": {
        "name": "self_attested_thing"
      }
    },
    "requested_predicates": {
      "0_age_GE_uuid": {
        "name": "age",
        "p_type": ">=",
        "p_value": 30,
        "restrictions": [
          {
            "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
          }
        ]
      }
    }
  }
}`

The relevant object in the response of preset-proof/records:
`{
      "presentation_exchange_id": "7be51985-9e5d-44cc-85f9-48e96d6ba7e8",
      "state": "presentation_received",
      "initiator": "self",
      "updated_at": "2019-09-25 21:00:23.811366Z",
      "auto_present": false,
      "connection_id": "979deb47-da9c-4f29-93cf-ba6fbbc4d661",
      "thread_id": "450a5b9f-f148-47b6-83df-948664096dba",
      "created_at": "2019-09-25 21:00:23.630028Z",
      "presentation_request": {
        "name": "Proof of Education",
        "version": "1.0",
        "requested_attributes": {
          "0_name_uuid": {
            "name": "name",
            "restrictions": [
              {
                "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
              }
            ]
          },
          "0_date_uuid": {
            "name": "date",
            "restrictions": [
              {
                "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
              }
            ]
          },
          "0_degree_uuid": {
            "name": "degree",
            "restrictions": [
              {
                "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
              }
            ]
          },
          "0_self_attested_thing_uuid": {
            "name": "self_attested_thing"
          }
        },
        "requested_predicates": {
          "0_age_GE_uuid": {
            "name": "age",
            "p_type": ">=",
            "p_value": 30,
            "restrictions": [
              {
                "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default"
              }
            ]
          }
        },
        "nonce": "136234703949313199272547557878147672871"
      },
      "presentation": {
        "proof": {
          "proofs": [
            {
              "primary_proof": {
                "eq_proof": {
                  "revealed_attrs": {
                    "date": "23402637423876324098256519317695433196813217785795317220680415812348801086586",
                    "degree": "460273229220408542178729328948548235132905393400001582342944147813984660772",
                    "name": "62816810226936654797779705000772968058283780124309077049681734835796332704413"
                  },
                  "a_prime": "46725806044568624898415589641887765423081890317450082492319327702788254905342926619828914776556123169467801607888861984695570107523548248064211859134719805142115658082619034496820072161476982706819289972332690445771337911160511776484389367664767588012666076889567248879739466100995561301334810013771484611110296972211559186768291551847890146940729234552797871102662931633731307379818371570035365913291277371591341037447180973551158291498021255104667881138021664928020303241132096109886088364250429602146123991927778876425888826165490701254186891133190233418960914012298035586717193017562488267649848994923426674144048",
                  "e": "160129881973937795711416058593693439656105513332226741316270331156324639487649684532920628285079943009112853416417958538429914701200240082",
                  "v": "1166220432389707789989676054887821616736187106344883678260047048253559951692112317315200780234971717611366955037162257396603428722590231127153238860942102511599419253847514287311905083452144843670189469485059325946634746139565157882822589015606113592594787301500517318001455894901394835023475610767277263678081796875492533273520611804357328439978826690541161672999682310744273697407539876186375710385745577394417202053088851637779861137617296378237264077021308965557976300775924729020628797698191738680527027586774077457550935028558286346083643304328244066404329269931484588382682331130836412426394551340588774497742292802256186858829140518607537757602672271228374504233613578429767864371024708479922901800449489926710673196057024735261036691676345740378166430439073644772565596524408520802695683290522873362483667659394596543293807420175864141000577010746291790776022496037530988963550023485328240028929234783878143793530",
                  "m": {
                    "age": "10478319407183710239640541284418055545811889168580872335193740566227623183720299927862873724923030951405306334721119365950360509767957630741513458108894766666073204705276672786992",
                    "master_secret": "8895278664177593949863847091881164697934725789335560259342814567042568896673356173124774846749693927849737511573011285763701390653080049283182611273902254773648132113013435078113"
                  },
                  "m2": "13926836554438529048107301443121407264946119593198843572736898823316827166850954972527018146124304926234025253004763522182109665287244814438288859122737764277165587842212760385210"
                },
                "ge_proofs": []
              },
              "non_revoc_proof": null
            }
          ],
          "aggregated_proof": {
            "c_hash": "38325549371893902457585813209854016545711548199487551817084304597322869439913",
            "c_list": [
              [
                1,
                114,
                35,
                194,
                49,
                132,
                205,
                145,
                30,
                242,
                100,
                136,
                80,
                171,
                190,
                78,
                102,
                6,
                217,
                97,
                42,
                75,
                116,
                86,
                248,
                254,
                185,
                173,
                175,
                114,
                73,
                127,
                79,
                66,
                36,
                132,
                183,
                45,
                46,
                48,
                75,
                37,
                138,
                96,
                34,
                136,
                50,
                235,
                235,
                159,
                75,
                151,
                60,
                9,
                86,
                0,
                186,
                40,
                105,
                138,
                164,
                34,
                162,
                246,
                106,
                49,
                242,
                0,
                192,
                7,
                145,
                202,
                120,
                105,
                83,
                242,
                145,
                1,
                30,
                116,
                34,
                6,
                168,
                242,
                208,
                135,
                244,
                39,
                187,
                141,
                231,
                25,
                39,
                84,
                242,
                110,
                204,
                61,
                68,
                101,
                192,
                38,
                231,
                4,
                10,
                46,
                36,
                105,
                81,
                91,
                231,
                59,
                92,
                117,
                231,
                207,
                31,
                3,
                40,
                173,
                250,
                78,
                197,
                143,
                33,
                142,
                214,
                123,
                216,
                152,
                190,
                106,
                51,
                129,
                74,
                49,
                8,
                157,
                227,
                133,
                188,
                198,
                154,
                190,
                64,
                75,
                29,
                224,
                94,
                73,
                209,
                211,
                26,
                165,
                41,
                197,
                188,
                126,
                143,
                130,
                212,
                201,
                30,
                168,
                79,
                211,
                238,
                178,
                94,
                177,
                52,
                0,
                26,
                102,
                145,
                92,
                123,
                38,
                205,
                151,
                191,
                123,
                223,
                163,
                29,
                205,
                209,
                205,
                143,
                147,
                184,
                32,
                162,
                54,
                240,
                82,
                164,
                167,
                123,
                65,
                244,
                84,
                47,
                229,
                131,
                143,
                245,
                95,
                84,
                176,
                214,
                95,
                166,
                125,
                198,
                235,
                174,
                209,
                88,
                30,
                52,
                190,
                209,
                55,
                255,
                18,
                42,
                50,
                35,
                238,
                70,
                138,
                213,
                115,
                245,
                109,
                167,
                117,
                209,
                176,
                128,
                125,
                141,
                56,
                21,
                77,
                39,
                178,
                228,
                220,
                130,
                234,
                189,
                91,
                128,
                115,
                48
              ]
            ]
          }
        },
        "requested_proof": {
          "revealed_attrs": {
            "0_name_uuid": {
              "sub_proof_index": 0,
              "raw": "Alice Smith",
              "encoded": "62816810226936654797779705000772968058283780124309077049681734835796332704413"
            },
            "0_degree_uuid": {
              "sub_proof_index": 0,
              "raw": "Maths",
              "encoded": "460273229220408542178729328948548235132905393400001582342944147813984660772"
            },
            "0_date_uuid": {
              "sub_proof_index": 0,
              "raw": "2018-05-28",
              "encoded": "23402637423876324098256519317695433196813217785795317220680415812348801086586"
            }
          },
          "self_attested_attrs": {
            "0_self_attested_thing_uuid": "my self-attested value"
          },
          "unrevealed_attrs": {},
          "predicates": {}
        },
        "identifiers": [
          {
            "schema_id": "DeipsSP85X438k9boJ8viK:2:degree schema:71.33.26",
            "cred_def_id": "DeipsSP85X438k9boJ8viK:3:CL:40:default",
            "rev_reg_id": null,
            "timestamp": null
          }
        ]
      }
    }`

What would be a good way to debug the indy anoncreds implementation?

**Comment by sklump** [comment]
verifier/indy.py pre_verify() checks now.
