### ISSUE TITLE
Cannot publish transactions to ledger when both multi ledger and multi tenant enabled

### ISSUE THREAD

**Issue by 6U-U9** [hyperledger/aries-cloudagent-python#2002]
Hello, I am trying to build a demo project with von-network and aca-py. It works fine when I tried multi ledger or multi tenant separately, unfortunately it turns out failed when I tried to enable both option. Please help me to fix it. Thank you very much.

My environment: 
**Ubuntu 20.04  & python 3.6.15**

First I start two von-network on local machine, each have four indy node, they runs on port 7701-7708 and 9701-9708.  It's a little complicated to modify von-network to running on different ports. The original version runs on 9701-9708, and my version here [[(von-network-7000s)](https://github.com/6U-U9/von-network-7000s)] runs on 7701-7708.

I started aca-py with following command

```shell
/home/whr/aries-cloudagent-python/venv/bin/python -m aries_cloudagent start \
--tails-server-base-url http://tails-server:6543 \
--endpoint http://127.0.0.1:8020 \
--label base.agent \
--auto-ping-connection \
--auto-respond-messages \
--inbound-transport http 0.0.0.0 8020 \
--outbound-transport http \
--admin 0.0.0.0 8021 \
--admin-insecure-mode \
--multitenant \
--multitenant-admin \
--jwt-secret 123456 \
--wallet-type indy \
--wallet-name base \
--wallet-key base \
--preserve-exchange-records \
--auto-provision \
--genesis-transactions-list /home/whr/multi_ledger_config.yml \
--trace-target log \
--trace-tag acapy.events \
--trace-label base.agent.trace \
--auto-accept-invites \
--auto-accept-requests \
--auto-store-credential 
```

And the multi_ledger_config.yml below

```yml
- id: localVON_7000
  is_production: false
  is_write: true
  genesis_url: 'http://localhost:7000/genesis'
- id: localVON_9000
  is_production: false
  genesis_url: 'http://localhost:9000/genesis'
```

Error ** 400 Cannot update endpoint at ledger without a public DID** occurs when I tries to publish a did to ledger.

First I called `/multitenancy/wallet` to create a sub wallet.
Then create a local DID in sub wallet.
After I registered the DID on ledger running on port 7000s, I published the DID. And it broke here.
400: Cannot update endpoint at ledger without a public DID.
Note that the new DID is already posted on ledger, it throws error when tries to update endpoint on ledger, after it marked the DID as posted. This can be verified by calling `Get /wallet/did/public`.

I traced the code and found something wrong, wish this could help you a little bit.

```python
# wallet/indy.py set_did_endpoint() line 744
wallet_public_didinfo = await self.get_public_did()
# here I got the right did L8p6CWUNCX5eS8MzHqtudm

# ledger/indy.py update_endpoint_for_did() line 757
public_info = await self.get_wallet_public_did()
# here I got null
```

Thanks again for your help. 

<details>

  <summary>**Here is the detail information of my actions. **</summary>
First called `/multitenancy/wallet` to create a sub wallet.

```shell
curl -X 'POST' \
  'http://localhost:8021/multitenancy/wallet' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "label": "test",
  "wallet_key": "MySecretKey123",
  "wallet_name": "test",
  "wallet_type": "indy",
  "wallet_webhook_urls": [
    "http://localhost:8022/webhooks"
  ]
}'
```

```json
{
    "wallet_id": "7d7d3ccd-7738-4bcf-9fd8-024d6d593d98",
    "settings": {
        "wallet.type": "indy",
        "wallet.name": "test",
        "wallet.webhook_urls": [
            "http://localhost:8022/webhooks"
        ],
        "wallet.dispatch_type": "default",
        "default_label": "test",
        "wallet.id": "7d7d3ccd-7738-4bcf-9fd8-024d6d593d98"
    },
    "key_management_mode": "managed",
    "created_at": "2022-11-04T08:43:57.237852Z",
    "updated_at": "2022-11-04T08:43:59.216324Z",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiI3ZDdkM2NjZC03NzM4LTRiY2YtOWZkOC0wMjRkNmQ1OTNkOTgiLCJpYXQiOjE2Njc1MjI2Mzl9.Wx9DFJNUd0T7Gcb6Se_3N149Kk2XNp87HddhJDcNgT0"
}
```

Then create a local DID in sub wallet.

```shell
curl -X 'POST' \
  'http://localhost:8021/wallet/did/create' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiI0NTEwN2MwNi0wMGI3LTQ1ODItYThlZi02NTljNGM4NzI3ZjgiLCJpYXQiOjE2Njc1MTkwNzN9.JgPldTNNM-_WKYGbU3sEKf0CrC2b29ZYXTQi-UvQRGs' \
  -H 'Content-Type: application/json' \
  -d '{
  "method": "sov",
  "options": {
    "key_type": "ed25519"
  }
}'
```

```json
{
  "result": {
    "did": "L8p6CWUNCX5eS8MzHqtudm",
    "verkey": "BRtLpXnboEm6GVkDJ8DbMsrobcZ4JCMg8zaGjRVhCT9X",
    "posture": "wallet_only",
    "key_type": "ed25519",
    "method": "sov"
  }
}
```

After I registered the DID on ledger running on port 7000s, I published the DID. And it broke here.

```shell
curl -X 'POST' \
  'http://localhost:8021/wallet/did/public?did=L8p6CWUNCX5eS8MzHqtudm' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiI3ZDdkM2NjZC03NzM4LTRiY2YtOWZkOC0wMjRkNmQ1OTNkOTgiLCJpYXQiOjE2Njc1MjI2Mzl9.Wx9DFJNUd0T7Gcb6Se_3N149Kk2XNp87HddhJDcNgT0' \
  -d ''
```

```
400: Cannot update endpoint at ledger without a public DID.
```

Note that the new DID is already posted on ledger, it throws error when tries to update endpoint on ledger, after it marked the DID as posted. This can be verified by calling `Get /wallet/did/public`.

```shell
curl -X 'GET' \
  'http://localhost:8021/wallet/did/public' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiI3ZDdkM2NjZC03NzM4LTRiY2YtOWZkOC0wMjRkNmQ1OTNkOTgiLCJpYXQiOjE2Njc1MjI2Mzl9.Wx9DFJNUd0T7Gcb6Se_3N149Kk2XNp87HddhJDcNgT0'
```

```json
{
  "result": {
    "did": "L8p6CWUNCX5eS8MzHqtudm",
    "verkey": "BRtLpXnboEm6GVkDJ8DbMsrobcZ4JCMg8zaGjRVhCT9X",
    "posture": "posted",
    "key_type": "ed25519",
    "method": "sov"
  }
}
```

</details>

**Comment by ianco** [comment]
Looking at this now ...

**Comment by ianco** [comment]
OK as far as I can tell, when in both multi-tenant and multi-ledger modes, the `wallet.get_public_did()` method is always pulling the public DID from the main/parent wallet rather than the sub-wallet.

So for the sub-wallet, when trying to set the endpoint, aca-py is signing the transaction with the sub-wallet's did but trying to write to the ledger in the context of the parent wallet, so the signature is getting rejected.  (Or, in @6U-U9 's scenario, the parent wallet doesn't even have a did so the transaction isn't even getting to the point of getting signed.)

Still investigating why this is (multi-tenant works but not when combined with multi-ledger???) and what the fix is ...

**Comment by 6U-U9** [comment]
Thanks for your reply very much. Hope we can fix this soom.

**Comment by ianco** [comment]
@6U-U9  the fix is in the `main` branch can you check it out and see if it fixes your issue?

**Comment by 6U-U9** [comment]
Thanks very much, it now works well to publish a public DID. 
But unfortunately, when I tried to send credential definitions to ledger or issue credentials, aca-py threw some error.

After I assigned the DID public, I created a schema like this.
```json 
{
    "schema_name": "transcript",
    "schema_attrs": [
        "name",
        "score"
    ]
}
```
It works well and I got the `schema_id`.
Then I called `/credential-definitions` with body below
```json
{
    "revocation_registry_size":100,
    "support_revocation":true,
    "schema_id":"CzB95VqF8kNRheoKB9buFb:2:transcript:1.0",
    "tag":"school.transcript"
}
```
It successfully register a credential definition to the ledger, but **not the revocation registry**.
**ERROR MESSAGE:**
```
2022-11-25 06:49:55,547 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
Traceback (most recent call last):
  File "/aries-cloudagent-python/aries_cloudagent/core/event_bus.py", line 121, in notify
    await processor()
  File "/aries-cloudagent-python/aries_cloudagent/messaging/credential_definitions/routes.py", line 527, in on_cred_def_event
    endorser_connection_id=endorser_connection_id,
  File "/aries-cloudagent-python/aries_cloudagent/revocation/indy.py", line 58, in init_issuer_registry
    txn_record_type=GET_CRED_DEF,
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/ledger_requests_executor.py", line 59, in get_ledger_for_identifier
    extracted_did, cache_did=cache_did
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 159, in lookup_did_in_configured_ledgers
    result = await coro_future.result()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 90, in _get_ledger_by_did
    async with indy_sdk_ledger:
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 318, in __aenter__
    await self.pool.context_open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 239, in context_open
    await self.open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 183, in open
    await self.create_pool_config(self.genesis_transactions, True)
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 162, in create_pool_config
    await indy.pool.delete_pool_ledger_config(self.name)
  File "/usr/local/lib/python3.6/dist-packages/indy/pool.py", line 184, in delete_pool_ledger_config
    delete_pool_ledger_config.cb)
  File "/usr/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
indy.error.CommonInvalidState
```

As the credential definition is already on the ledger, I tried to issue a credential with it. And it turns out breaks with the same reason.
I called `/issue-credential-2.0/send-offer` with json body :
```json
{
    "auto_remove": false,
    "filter": {
        "indy": {
            "cred_def_id": "CzB95VqF8kNRheoKB9buFb:3:CL:11:school.transcript"
        }
    },
    "trace": false,
    "connection_id": "47bb76f0-0761-404c-b050-a4ee205c452d",
    "credential_preview": {
        "@type": "https://didcomm.org/issue-credential/2.0/credential-preview",
        "attributes": [
            {
                "name": "score",
                "value": "100"
            },
            {
                "name": "name",
                "value": "math"
            }
        ]
    },
    "comment": "Offer on cred def id 47bb76f0-0761-404c-b050-a4ee205c452d"
}
```
And the **ERROR MESSAGE**
```
2022-11-25 07:02:11,896 aries_cloudagent.core.dispatcher ERROR Handler error: credential_exchange_send_free_offer
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 960, in credential_exchange_send_free_offer
    trace_msg=trace_msg,
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 829, in _create_free_offer
    comment=comment,
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 232, in create_offer
    cred_proposal_message
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/formats/indy/handler.py", line 211, in create_offer
    txn_record_type=GET_CRED_DEF,
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/ledger_requests_executor.py", line 59, in get_ledger_for_identifier
    extracted_did, cache_did=cache_did
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 159, in lookup_did_in_configured_ledgers
    result = await coro_future.result()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 90, in _get_ledger_by_did
    async with indy_sdk_ledger:
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 318, in __aenter__
    await self.pool.context_open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 239, in context_open
    await self.open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 183, in open
    await self.create_pool_config(self.genesis_transactions, True)
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 162, in create_pool_config
    await indy.pool.delete_pool_ledger_config(self.name)
  File "/usr/local/lib/python3.6/dist-packages/indy/pool.py", line 184, in delete_pool_ledger_config
    delete_pool_ledger_config.cb)
  File "/usr/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
indy.error.CommonInvalidState
2022-11-25 07:02:11,907 aries_cloudagent.admin.server ERROR Handler error with exception: 
Traceback (most recent call last):
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 171, in ready_middleware
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 208, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 377, in check_multitenant_authorization
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 421, in setup_context
    return await task
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 960, in credential_exchange_send_free_offer
    trace_msg=trace_msg,
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 829, in _create_free_offer
    comment=comment,
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 232, in create_offer
    cred_proposal_message
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/formats/indy/handler.py", line 211, in create_offer
    txn_record_type=GET_CRED_DEF,
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/ledger_requests_executor.py", line 59, in get_ledger_for_identifier
    extracted_did, cache_did=cache_did
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 159, in lookup_did_in_configured_ledgers
    result = await coro_future.result()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 90, in _get_ledger_by_did
    async with indy_sdk_ledger:
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 318, in __aenter__
    await self.pool.context_open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 239, in context_open
    await self.open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 183, in open
    await self.create_pool_config(self.genesis_transactions, True)
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 162, in create_pool_config
    await indy.pool.delete_pool_ledger_config(self.name)
  File "/usr/local/lib/python3.6/dist-packages/indy/pool.py", line 184, in delete_pool_ledger_config
    delete_pool_ledger_config.cb)
  File "/usr/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
indy.error.CommonInvalidState
2022-11-25 07:02:11,912 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 171, in ready_middleware
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 208, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 377, in check_multitenant_authorization
    return await handler(request)
  File "/aries-cloudagent-python/aries_cloudagent/admin/server.py", line 421, in setup_context
    return await task
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 960, in credential_exchange_send_free_offer
    trace_msg=trace_msg,
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/routes.py", line 829, in _create_free_offer
    comment=comment,
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 232, in create_offer
    cred_proposal_message
  File "/aries-cloudagent-python/aries_cloudagent/protocols/issue_credential/v2_0/formats/indy/handler.py", line 211, in create_offer
    txn_record_type=GET_CRED_DEF,
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/ledger_requests_executor.py", line 59, in get_ledger_for_identifier
    extracted_did, cache_did=cache_did
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 159, in lookup_did_in_configured_ledgers
    result = await coro_future.result()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/multiple_ledger/indy_manager.py", line 90, in _get_ledger_by_did
    async with indy_sdk_ledger:
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 318, in __aenter__
    await self.pool.context_open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 239, in context_open
    await self.open()
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 183, in open
    await self.create_pool_config(self.genesis_transactions, True)
  File "/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 162, in create_pool_config
    await indy.pool.delete_pool_ledger_config(self.name)
  File "/usr/local/lib/python3.6/dist-packages/indy/pool.py", line 184, in delete_pool_ledger_config
    delete_pool_ledger_config.cb)
  File "/usr/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
indy.error.CommonInvalidState
```

**Comment by ianco** [comment]
Hi @6U-U9 thanks for the info, I'll look into this error.

FYI if you use `--wallet-type askar` it seems to work, so this error is specific to indy.  If you can, while I'm looking into this, if you switch to `askar` everything should work.'

**Comment by ianco** [comment]
@shaangill025 @swcurran FYI wallet type `askar` is working fine but `indy` is broken under multi-ledger.

I get inconsistent errors (sometimes it even works), I get errors regardless of whether I include the `bind_instance()`  calls Shaanjot and I were discussing yesterday.  Seems like some kind of a timing issue between different instances of the Ledger class.

**Comment by ianco** [comment]
Closing, should be fixed now
