### ISSUE TITLE
 aries-cloudagent issue

### ISSUE THREAD

**Issue by msingh1304** [hyperledger/aries-cloudagent-python#2143]
Hello Team,

All the containers are running fine except aries cloud agent, getting this error message

Error Message: [main] TRACE AriesClient - aca-py not ready yet, reason: Failed to connect to myssilab-aries-agent/192.xxxx.xxx.4:11708

And we have opened all the ports, don't really know what is the issue. 

Additional logs:

  at org.hyperledger.bpa.impl.StartupTasks$ApplicationEventListener$onServiceStartedEvent1$Intercepted.onApplicationEvent(Unknown Source) ~[business-partner-agent.jar:?]
        at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262) ~[business-partner-agent.jar:?]
        at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60) ~[business-partner-agent.jar:?]
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1650) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:258) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181) ~[business-partner-agent.jar:?]
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71) [business-partner-agent.jar:?]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311) [business-partner-agent.jar:?]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297) [business-partner-agent.jar:?]
        at org.hyperledger.bpa.Application.main(Application.java:34) [business-partner-agent.jar:?]

More

******************************************************************************************************

Do we need to set these value also

WARN[0000] The "ACAPY_ADMIN_URL_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "ACAPY_READ_ONLY_MODE" variable is not set. Defaulting to a blank string.
WARN[0000] The "ACAPY_ADMIN_URL_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "ACAPY_READ_ONLY_MODE" variable is not set. Defaulting to a blank string.

Please confirm

**Comment by msingh1304** [comment]
I see this in the logs when I see :

docker logs mylab-bpa-controller

13:00:26.356 [main] TRACE AriesClient - aca-py not ready yet, reason: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
13:00:26.455 [scheduled-executor-thread-3] TRACE HolderCredentialManager - Running revocation checks
13:00:26.457 [main] TRACE AriesClient - aca-py not ready yet, reason: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
13:00:26.558 [main] TRACE AriesClient - aca-py not ready yet, reason: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
13:00:26.571 [io-executor-thread-3] ERROR HealthResult - Health indicator [aca-py-readiness] reported exception: java.lang.RuntimeException: java.net.ConnectException: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
java.lang.RuntimeException: java.net.ConnectException: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
        at org.hyperledger.bpa.client.AcaPyReadinessCheck.getHealthInformation(AcaPyReadinessCheck.java:51) ~[business-partner-agent.jar:?]
        at org.hyperledger.bpa.client.AcaPyReadinessCheck.getHealthInformation(AcaPyReadinessCheck.java:34) ~[business-partner-agent.jar:?]
        at io.micronaut.management.health.indicator.AbstractHealthIndicator.getHealthResult(AbstractHealthIndicator.java:72) ~[business-partner-agent.jar:?]
        at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100) ~[business-partner-agent.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.net.ConnectException: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[business-partner-agent.jar:?]
        at org.hyperledger.aries.BaseClient.call(BaseClient.java:86) ~[business-partner-agent.jar:?]
        at org.hyperledger.aries.BaseClient.call(BaseClient.java:81) ~[business-partner-agent.jar:?]
        at org.hyperledger.aries.AriesClient.statusReady(AriesClient.java:1976) ~[business-partner-agent.jar:?]
        at org.hyperledger.bpa.client.AcaPyReadinessCheck.getHealthInformation(AcaPyReadinessCheck.java:44) ~[business-partner-agent.jar:?]
        ... 8 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:660) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
        at java.net.Socket.connect(Socket.java:648) ~[?:?]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[business-partner-agent.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[business-partner-agent.jar:?]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[business-partner-agent.jar:?]
        at org.hyperledger.aries.BaseClient.call(BaseClient.java:86) ~[business-partner-agent.jar:?]
        at org.hyperledger.aries.BaseClient.call(BaseClient.java:81) ~[business-partner-agent.jar:?]
        at org.hyperledger.aries.AriesClient.statusReady(AriesClient.java:1976) ~[business-partner-agent.jar:?]
        at org.hyperledger.bpa.client.AcaPyReadinessCheck.getHealthInformation(AcaPyReadinessCheck.java:44) ~[business-partner-agent.jar:?]
        ... 8 more
13:00:26.659 [main] TRACE AriesClient - aca-py not ready yet, reason: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
13:00:26.761 [main] TRACE AriesClient - aca-py not ready yet, reason: Failed to connect to mylab-aries-agent/192.168.xxx.xxx:11708
13:00:26.861 [main] ERROR AriesClient - Timeout exceeded, aca-py not ready after: PT1M
13:00:26.862 [main] ERROR Micronaut - Error starting Micronaut server: Timeout exceeded, aca-py not ready after: PT1M
org.hyperledger.aries.api.exception.AriesException: Timeout exceeded, aca-py not ready after: PT1M
        at org.hyperledger.aries.AriesClient.statusWaitUntilReady(AriesClient.java:2004) ~[business-partner-agent.jar:?]
        at org.hyperledger.bpa.impl.StartupTasks.onServiceStartedEvent(StartupTasks.java:89) ~[business-partner-agent.jar:?]
        at org.hyperledger.bpa.impl.$StartupTasks$Definition$Exec.dispatch(Unknown Source) ~[business-partner-agent.jar:?]
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:338) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3915) ~[business-partner-agent.jar:?]
        at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:83) ~[business-partner-agent.jar:?]
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[business-partner-agent.jar:?]
        at org.hyperledger.bpa.impl.StartupTasks$ApplicationEventListener$onServiceStartedEvent1$Intercepted.onApplicationEvent(Unknown Source) ~[business-partner-agent.jar:?]
        at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262) ~[business-partner-agent.jar:?]
        at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60) ~[business-partner-agent.jar:?]
        at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1650) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:258) ~[business-partner-agent.jar:?]
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181) ~[business-partner-agent.jar:?]
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71) [business-partner-agent.jar:?]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311) [business-partner-agent.jar:?]
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297) [business-partner-agent.jar:?]
        at org.hyperledger.bpa.Application.main(Application.java:34) [business-partner-agent.jar:?]
Listening for transport dt_socket at address: 1044
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.0)
