### ISSUE TITLE
"manual" transactions for register-nym

### ISSUE THREAD

**Issue by usingtechnology** [hyperledger/aries-cloudagent-python#2167]
version: aries-cloudagent-python-1.0.0-rc1
multitenant = true
wallet type = askar

I was using `aries-cloudagent-python-1.0.0-rc1` and turned off all auto endorsement flags; I have successfully connected an agent/wallet (in multitenant) to an endorser that is known to work (configured against `http://test.bcovrin.vonx.io/genesis`).

With auto flags on for both the endorser and the agent, I can call `ledger/register-nym` and will get the did written and I can subsequently call `POST /wallet/did/public` and then carry on with creating schemas and cred. defs... 

However, if I turn the auto endorse flags off for my agent (endorser still on auto), when I call `ledger/register-nym` with `create_transaction_for_endorser=true,` the call returns successfully, but I cannot really continue. The data in the response does not contain a `transaction_id` which I need to call `transaction/create-request`. So issue 1 is that the transaction returned from register-nym is not the full transaction (no transaction_id).

In my tests, I know there is only one transaction, so I can call `GET /transactions` and grab the first (and only) record, giving me a `transaction_id`... When I do call `transaction/create-request`, I end up failing with `aries_cloudagent.ledger.error.BadLedgerRequestError: Cannot endorse invalid request`.

From logging the events (and looking at the source code) the transaction created for "manual" and the transaction sent if the auto flags are on are different.

In the demo (this repo) endorsement runs in auto mode, and in [aries endorser service bdd tests](https://github.com/hyperledger/aries-endorser-service/tree/642950e636b2dae587ee76d05246e340432dce75/bdd-tests) it also runs in auto mode, so unsure if a full manual run through has been tested? Or I am definitely missing something...

Some notes and log out puts follow from my testing.

#### "auto" create transaction ok

```
ACAPY_AUTO_REQUEST_ENDORSEMENT=true
ACAPY_AUTO_WRITE_TRANSACTIONS=true
ACAPY_AUTO_PROMOTE_AUTHOR_DID=false
```

register nym response:
```
{
  'success': False,
  'txn': {
    'meta_data': {
      'did': 'WcWUsqMLv6AtxdHt9ewJQE',
      'verkey': 'H96pix8BLyaSEJaGNFZkhwZsw2hUsGm45HVuaTpXso6i',
      'alias': 'foundrous',
      'role': None
    },
    'signature_response': [],
    'created_at': '2023-03-08T01:34:57.764879Z',
    'timing': {
      'expires_time': None
    },
    '_type': 'http://didcomm.org/sign-attachment/%VER/signature-request',
    'signature_request': [
      {
        'context': 'did:sov',
        'method': 'add-signature',
        'signature_type': '<requested signature type>',
        'signer_goal_code': 'aries.transaction.ledger.write_did',
        'author_goal_code': 'aries.transaction.register_public_did'
      }
    ],
    'messages_attach': [
      {
        '@id': '8cf62b61-24bf-43dd-9c27-c9e09872654e',
        'mime-type': 'application/json',
        'data': {
          'json': '{"did": "WcWUsqMLv6AtxdHt9ewJQE", "verkey": "H96pix8BLyaSEJaGNFZkhwZsw2hUsGm45HVuaTpXso6i", "alias": "foundrous", "role": null}'
        }
      }
    ],
    'formats': [
      {
        'attach_id': '8cf62b61-24bf-43dd-9c27-c9e09872654e',
        'format': 'dif/endorse-transaction/request@v1.0'
      }
    ],
    'endorser_write_txn': True,
    'trace': False,
    'connection_id': 'a93eaf1b-47fd-468d-9a4b-9a930da6e47b',
    'state': 'request_sent',
    'transaction_id': '7acfdaeb-42c9-42f2-ad26-7f2b5a708ec3',
    'updated_at': '2023-03-08T01:34:57.777079Z'
  }
}
```

create transaction event:

```
{
  'meta_data': {
    'did': 'WcWUsqMLv6AtxdHt9ewJQE',
    'verkey': 'H96pix8BLyaSEJaGNFZkhwZsw2hUsGm45HVuaTpXso6i',
    'alias': 'foundrous',
    'role': None
  },
  'signature_response': [],
  'created_at': '2023-03-08T01:34:57.764879Z',
  'timing': {},
  'signature_request': [],
  'messages_attach': [
    {
      '@id': '8cf62b61-24bf-43dd-9c27-c9e09872654e',
      'mime-type': 'application/json',
      'data': {
        'json': '{"did": "WcWUsqMLv6AtxdHt9ewJQE", "verkey": "H96pix8BLyaSEJaGNFZkhwZsw2hUsGm45HVuaTpXso6i", "alias": "foundrous", "role": null}'
      }
    }
  ],
  'formats': [
    {
      'attach_id': '8cf62b61-24bf-43dd-9c27-c9e09872654e',
      'format': 'dif/endorse-transaction/request@v1.0'
    }
  ],
  'trace': False,
  'connection_id': 'a93eaf1b-47fd-468d-9a4b-9a930da6e47b',
  'state': 'transaction_created',
  'transaction_id': '7acfdaeb-42c9-42f2-ad26-7f2b5a708ec3',
  'updated_at': '2023-03-08T01:34:57.764879Z'
}
```

next event (request_sent):

```
{
  'meta_data': {
    'did': 'WcWUsqMLv6AtxdHt9ewJQE',
    'verkey': 'H96pix8BLyaSEJaGNFZkhwZsw2hUsGm45HVuaTpXso6i',
    'alias': 'foundrous',
    'role': None
  },
  'signature_response': [],
  'created_at': '2023-03-08T01:34:57.764879Z',
  'timing': {
    'expires_time': None
  },
  '_type': 'http://didcomm.org/sign-attachment/%VER/signature-request',
  'signature_request': [
    {
      'context': 'did:sov',
      'method': 'add-signature',
      'signature_type': '<requested signature type>',
      'signer_goal_code': 'aries.transaction.ledger.write_did',
      'author_goal_code': 'aries.transaction.register_public_did'
    }
  ],
  'messages_attach': [
    {
      '@id': '8cf62b61-24bf-43dd-9c27-c9e09872654e',
      'mime-type': 'application/json',
      'data': {
        'json': '{"did": "WcWUsqMLv6AtxdHt9ewJQE", "verkey": "H96pix8BLyaSEJaGNFZkhwZsw2hUsGm45HVuaTpXso6i", "alias": "foundrous", "role": null}'
      }
    }
  ],
  'formats': [
    {
      'attach_id': '8cf62b61-24bf-43dd-9c27-c9e09872654e',
      'format': 'dif/endorse-transaction/request@v1.0'
    }
  ],
  'endorser_write_txn': True,
  'trace': False,
  'connection_id': 'a93eaf1b-47fd-468d-9a4b-9a930da6e47b',
  'state': 'request_sent',
  'transaction_id': '7acfdaeb-42c9-42f2-ad26-7f2b5a708ec3',
  'updated_at': '2023-03-08T01:34:57.777079Z'
}
```
carries on, all good...

#### "Manual" create transaction failure

run:

```
ACAPY_AUTO_REQUEST_ENDORSEMENT=false
ACAPY_AUTO_WRITE_TRANSACTIONS=true
ACAPY_AUTO_PROMOTE_AUTHOR_DID=false
```

register nym response:
```
{
  'success': False,
  'txn': {
    'signed_txn': '{"did": "BuoCGJ8MRENfHLQvuMzQ4z", "verkey": "6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe", "alias": "busheller", "role": null}'
  }
}
```
***NOTE: this does not return a transaction id, so we have to find the transaction we want to request for endorsement***

find register nym transaction:

```
{
  'updated_at': '2023-03-08T00:29:08.417919Z',
  'signature_response': [],
  'meta_data': {
    'did': 'BuoCGJ8MRENfHLQvuMzQ4z',
    'verkey': '6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe',
    'alias': 'busheller',
    'role': None
  },
  'messages_attach': [
    {
      '@id': 'e5161a63-8345-4f72-bcc6-006875d44c82',
      'mime-type': 'application/json',
      'data': {
        'json': '{"did": "BuoCGJ8MRENfHLQvuMzQ4z", "verkey": "6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe", "alias": "busheller", "role": null}'
      }
    }
  ],
  'signature_request': [],
  'formats': [
    {
      'attach_id': 'e5161a63-8345-4f72-bcc6-006875d44c82',
      'format': 'dif/endorse-transaction/request@v1.0'
    }
  ],
  'trace': False,
  'transaction_id': 'a662ecc3-8bc5-4c99-bde0-d9b8b4b998e1',
  'timing': {},
  'state': 'transaction_created',
  'connection_id': 'db933e5d-156a-47e3-a057-2e077076179a',
  'created_at': '2023-03-08T00:29:08.417919Z'
}
```
***NOTE: there is no way in the REST API to find a particular transaction, it's just iterate over the list.***

create transaction event:

```
{
  'updated_at': '2023-03-08T00:29:08.417919Z',
  'signature_response': [],
  'meta_data': {
    'did': 'BuoCGJ8MRENfHLQvuMzQ4z',
    'verkey': '6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe',
    'alias': 'busheller',
    'role': None
  },
  'messages_attach': [
    {
      '@id': 'e5161a63-8345-4f72-bcc6-006875d44c82',
      'mime-type': 'application/json',
      'data': {
        'json': '{"did": "BuoCGJ8MRENfHLQvuMzQ4z", "verkey": "6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe", "alias": "busheller", "role": null}'
      }
    }
  ],
  'signature_request': [],
  'formats': [
    {
      'attach_id': 'e5161a63-8345-4f72-bcc6-006875d44c82',
      'format': 'dif/endorse-transaction/request@v1.0'
    }
  ],
  'trace': False,
  'transaction_id': 'a662ecc3-8bc5-4c99-bde0-d9b8b4b998e1',
  'timing': {},
  'state': 'transaction_created',
  'connection_id': 'db933e5d-156a-47e3-a057-2e077076179a',
  'created_at': '2023-03-08T00:29:08.417919Z'
}
```

next event (request_sent):

```
{
  'updated_at': '2023-03-08T00:29:09.497607Z',
  'signature_response': [],
  'meta_data': {
    'did': 'BuoCGJ8MRENfHLQvuMzQ4z',
    'verkey': '6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe',
    'alias': 'busheller',
    'role': None
  },
  'endorser_write_txn': True,
  'messages_attach': [
    {
      '@id': 'e5161a63-8345-4f72-bcc6-006875d44c82',
      'mime-type': 'application/json',
      'data': {
        'json': '{"did": "BuoCGJ8MRENfHLQvuMzQ4z", "verkey": "6wtwiMKQvAQDfumpa1UjMW8UbdKUU2GUf8abiUNkLGFe", "alias": "busheller", "role": null}'
      }
    }
  ],
  '_type': 'http://didcomm.org/sign-attachment/%VER/signature-request',
  'signature_request': [
    {
      'context': 'did:sov',
      'method': 'add-signature',
      'signature_type': '<requested signature type>',
      'signer_goal_code': 'aries.transaction.endorse',
      'author_goal_code': 'aries.transaction.ledger.write'
    }
  ],
  'formats': [
    {
      'attach_id': 'e5161a63-8345-4f72-bcc6-006875d44c82',
      'format': 'dif/endorse-transaction/request@v1.0'
    }
  ],
  'trace': False,
  'transaction_id': 'a662ecc3-8bc5-4c99-bde0-d9b8b4b998e1',
  'timing': {
    'expires_time': '2030-03-31T05:22:19Z'
  },
  'state': 'request_sent',
  'connection_id': 'db933e5d-156a-47e3-a057-2e077076179a',
  'created_at': '2023-03-08T00:29:08.417919Z'
}
```

***NOTE:  the signer_goal_code and author_goal_code are different than when done auto. manually, there doesn't seem to be a way to set it like it is done automatically.***

failure (request JSON: protocolVersion not found):

```
scripts-endorser-agent-1                | Traceback (most recent call last):
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1160, in txn_endorse
scripts-endorser-agent-1                |     request = ledger.build_custom_request(request_json)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/ledger.py", line 159, in build_custom_request
scripts-endorser-agent-1                |     do_call("indy_vdr_build_custom_request", body_p, byref(handle))
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/bindings.py", line 132, in do_call
scripts-endorser-agent-1                |     raise get_current_error(True)
scripts-endorser-agent-1                | indy_vdr.error.VdrError: Invalid request JSON: protocolVersion not found
scripts-endorser-agent-1                |
scripts-endorser-agent-1                | The above exception was the direct cause of the following exception:
scripts-endorser-agent-1                |
scripts-endorser-agent-1                | Traceback (most recent call last):
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 182, in _step
scripts-endorser-agent-1                |     result = coro.throw(exc)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 265, in handle_message
scripts-endorser-agent-1                |     await handler(context, responder)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/handlers/transaction_request_handler.py", line 52, in handle
scripts-endorser-agent-1                |     state=TransactionRecord.STATE_TRANSACTION_ENDORSED,
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 285, in create_endorse_response
scripts-endorser-agent-1                |     ledger.txn_endorse(transaction_json, endorse_did=endorser_did_info)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
scripts-endorser-agent-1                |     yield self  # This tells Task to wait for completion.
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
scripts-endorser-agent-1                |     future.result()
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
scripts-endorser-agent-1                |     raise self._exception
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 180, in _step
scripts-endorser-agent-1                |     result = coro.send(None)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1162, in txn_endorse
scripts-endorser-agent-1                |     raise BadLedgerRequestError("Cannot endorse invalid request") from err
scripts-endorser-agent-1                | aries_cloudagent.ledger.error.BadLedgerRequestError: Cannot endorse invalid request
scripts-endorser-agent-1                | 2023-03-08 00:29:10,025 aries_cloudagent.core.conductor ERROR DON'T shutdown on BadLedgerRequestError Cannot endorse invalid request
scripts-endorser-agent-1                | 2023-03-08 00:29:10,027 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
scripts-endorser-agent-1                | Traceback (most recent call last):
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1160, in txn_endorse
scripts-endorser-agent-1                |     request = ledger.build_custom_request(request_json)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/ledger.py", line 159, in build_custom_request
scripts-endorser-agent-1                |     do_call("indy_vdr_build_custom_request", body_p, byref(handle))
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/bindings.py", line 132, in do_call
scripts-endorser-agent-1                |     raise get_current_error(True)
scripts-endorser-agent-1                | indy_vdr.error.VdrError: Invalid request JSON: protocolVersion not found
scripts-endorser-agent-1                |
scripts-endorser-agent-1                | The above exception was the direct cause of the following exception:
scripts-endorser-agent-1                |
scripts-endorser-agent-1                | Traceback (most recent call last):
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 182, in _step
scripts-endorser-agent-1                |     result = coro.throw(exc)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 265, in handle_message
scripts-endorser-agent-1                |     await handler(context, responder)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/handlers/transaction_request_handler.py", line 52, in handle
scripts-endorser-agent-1                |     state=TransactionRecord.STATE_TRANSACTION_ENDORSED,
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 285, in create_endorse_response
scripts-endorser-agent-1                |     ledger.txn_endorse(transaction_json, endorse_did=endorser_did_info)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
scripts-endorser-agent-1                |     yield self  # This tells Task to wait for completion.
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
scripts-endorser-agent-1                |     future.result()
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
scripts-endorser-agent-1                |     raise self._exception
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 180, in _step
scripts-endorser-agent-1                |     result = coro.send(None)
scripts-endorser-agent-1                |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1162, in txn_endorse
scripts-endorser-agent-1                |     raise BadLedgerRequestError("Cannot endorse invalid request") from err
scripts-endorser-agent-1                | aries_cloudagent.ledger.error.BadLedgerRequestError: Cannot endorse invalid request
```

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
