### ISSUE TITLE
Critical - Error during startup using v0.8.0-rc1

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2195]
The following error occurs during startup, causing the container to shutdown.  ~The operation being performed is a rolling deployment of an `aca-py` agent in OpenShift, something we've been able to do up to this point.  During a rolling deployment, the existing `aca-py` instances stay running until their replacement is fully running.~

EDIT:
This error happens on startup regardless of whether there is another instance of `aca-py` running or not.  In other words `aca-py v0.8.0-rc1` can't start at all.

```
2023-04-03 13:20:36,407 indy.libindy DEBUG do_call: >>> name: indy_open_wallet, args: (c_char_p(140447513633072), c_char_p(140447551682320), <CFunctionType object at 0x7fbc7e704c40>)
2023-04-03 13:20:36,407 indy.libindy DEBUG do_call: Function indy_open_wallet returned err: 0
2023-04-03 13:20:36,407 indy.libindy DEBUG do_call: <<< <Future pending>
2023-04-03 13:20:36,500 indy.libindy DEBUG _get_error_details: >>>
2023-04-03 13:20:36,501 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Wallet already opened\n  Caused by: Wallet aries-mediator-agent-wallet already opened\n'}
2023-04-03 13:20:36,501 indy.libindy DEBUG _indy_callback: >>> command_handle: 7, err , args: (0,)
2023-04-03 13:20:36,501 indy.libindy DEBUG _indy_callback: <<<
2023-04-03 13:20:36,501 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 7, err , args: (0,)
2023-04-03 13:20:36,501 indy.libindy WARNING _indy_loop_callback: Function returned error 
2023-04-03 13:20:36,502 indy.libindy DEBUG _indy_loop_callback <<<
2023-04-03 13:20:36,502 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 167, in open_wallet
    handle = await indy.wallet.open_wallet(
  File "/usr/local/lib/python3.9/site-packages/indy/wallet.py", line 124, in open_wallet
    res = await do_call('indy_open_wallet',
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
indy.error.WalletAlreadyOpenedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/upgrade.py", line 150, in upgrade
    root_profile, _ = await wallet_config(context)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/config/wallet.py", line 54, in wallet_config
    profile = await mgr.open(context, profile_cfg)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/indy/sdk/profile.py", line 195, in open
    opened = await indy_config.open_wallet()
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 184, in open_wallet
    raise IndyErrorHandler.wrap_error(
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 167, in open_wallet
    handle = await indy.wallet.open_wallet(
  File "/usr/local/lib/python3.9/site-packages/indy/wallet.py", line 124, in open_wallet
    res = await do_call('indy_open_wallet',
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
aries_cloudagent.core.error.ProfileError: Wallet 'aries-mediator-agent-wallet' is already open: Error: Wallet already opened
  Caused by: Wallet aries-mediator-agent-wallet already opened


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/start.py", line 29, in start_app
    await conductor.start()
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 343, in start
    await upgrade(self.root_profile.settings)
  File "/home/indy/.local/lib/python3.9/site-packages/aries_cloudagent/commands/upgrade.py", line 294, in upgrade
    raise UpgradeError(f"Error during upgrade: {e}")
aries_cloudagent.commands.upgrade.UpgradeError: Error during upgrade: Wallet 'aries-mediator-agent-wallet' is already open: Error: Wallet already opened
  Caused by: Wallet aries-mediator-agent-wallet already opened


Shutting down
2023-04-03 13:20:36,504 aries_cloudagent.core.event_bus DEBUG Notifying subscribers: <Event topic=acapy::core::shutdown, payload={}>
2023-04-03 13:20:36,505 indy.wallet DEBUG close_wallet: >>> handle: 2
2023-04-03 13:20:36,505 indy.wallet DEBUG close_wallet: Creating callback
2023-04-03 13:20:36,506 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2023-04-03 13:20:36,506 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x7fbc7e6a7d00>
2023-04-03 13:20:36,506 indy.libindy DEBUG do_call: >>> name: indy_close_wallet, args: (c_int(2), <CFunctionType object at 0x7fbc7e6a7d00>)
2023-04-03 13:20:36,506 indy.libindy DEBUG do_call: Function indy_close_wallet returned err: 0
2023-04-03 13:20:36,506 indy.libindy DEBUG do_call: <<< <Future pending>
2023-04-03 13:20:36,506 indy.libindy DEBUG _indy_callback: >>> command_handle: 8, err , args: ()
2023-04-03 13:20:36,507 indy.libindy DEBUG _indy_callback: <<<
2023-04-03 13:20:36,507 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 8, err , args: ()
2023-04-03 13:20:36,507 indy.libindy DEBUG _indy_loop_callback: Function returned None
2023-04-03 13:20:36,507 indy.libindy DEBUG _indy_loop_callback <<<
2023-04-03 13:20:36,507 indy.wallet DEBUG close_wallet: <<<
2023-04-03 13:20:36,507 aries_cloudagent.indy.sdk.profile DEBUG Profile finalizer called; closing wallet
```
[full-log.txt](https://github.com/hyperledger/aries-cloudagent-python/files/11138729/full-log.txt)

**Comment by WadeBarnes** [comment]
cc @shaangill025, @swcurran

**Comment by shaangill025** [comment]
To fix the WalletAlreadyOpenedError, I have made changes to update upgrade function to accept either settings dict [when calling upgrade offline] or profile [when being called from conductor automatically]. When profile is provided, it does not call wallet_config again which will avoid triggering the wallet error. I believe this should fix the issue. Right now I am testing it out, first to replicate the error with Indy wallet without my changes and then check if the changes fixes it.

@WadeBarnes Did you call the upgrade command offline or was it automatically during startup? Can you share the upgrade startup args you used? And in your case, version record is set at `v8.0.0` but the upgrade was never applied?

**Comment by WadeBarnes** [comment]
> @WadeBarnes Did you call the upgrade command offline or was it automatically during startup? Can you share the upgrade startup args you used? And in your case, version record is set at `v8.0.0` but the upgrade was never applied?

That was during an automatic upgrade; on `aca-py` startup.

It looks like the version record is set to `v0.8.0`.  It's difficult to tell for sure since there is no definitive log message indicating what was found, only debug messages containing `"value":"v0.8.0"`.  It would be good if there was more logging.  Anyway, yes, I'm trying to update and upgrade the mediator instance I first attempted the upgrade on.  The upgrade attempts so far have failed, so there is no indication the upgrade has been successfully applied yet.

**Comment by shaangill025** [comment]
> It looks like the version record is set to `v0.8.0`. It's difficult to tell for sure since there is no definitive log message indicating what was found, only debug messages containing `"value":"v0.8.0"`. It would be good if there was more logging. Anyway, yes, I'm trying to update and upgrade the mediator instance I first attempted the upgrade on. The upgrade attempts so far have failed, so there is no indication the upgrade has been successfully applied yet.
 
@WadeBarnes I believe version `v8.0.0` was added to wallet previously but no upgrade was applied at that time. So you have to include `--from-version=v0.7.5` and `--force-upgrade` argument in ACA-Py startup. With these additions, the upgrade can be applied either during startup or offline.

PR#2196 should fix the triggering of Indy's `WalletAlreadyOpenedError`.

**Comment by swcurran** [comment]
> > @shaangill025 — what happens when there is no version found in storage, and no “—from-version” passed on the command line? We need to make sure that scenario is covered. I’ll create an issue if that is not already implemented.
> 
> @swcurran It will add the version from `version.py` to storage and log a warning with a detailed message in `conductor.py`

OK — I think that is the wrong behaviour.  Proposing a new issue to added this.

**Comment by shaangill025** [comment]
> > > @shaangill025 — what happens when there is no version found in storage, and no “—from-version” passed on the command line? We need to make sure that scenario is covered. I’ll create an issue if that is not already implemented.
> > 
> > 
> > @swcurran It will add the version from `version.py` to storage and log a warning with a detailed message in `conductor.py`
> 
> OK — I think that is the wrong behaviour. Proposing a new issue to added this.

I gathered that understanding from this feedback on the original PR:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/9292265/229556683-ca1d3e37-fa11-40e6-b0b6-72fdd50fad6e.png">

**Comment by swcurran** [comment]
Yes — that is why I added the new issue.  I think that limitation is a bit dangerous, and we can be more proactive about applying the upgrade.
