### ISSUE TITLE
Error running performance demo with “—trace-log” parameter set

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2205]
When running the performance demo with:

`./run_demo performance -c 1 --mediation --timing --trace-log`

Many errors were generated like the following. Likely to do with the `—trace-log` parameter as without that, the run works correctly.

```
AssertionError
Exception in default exception handler
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 94, in step_next
    new_f = coroutine.send(f.result())
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/application/run_in_terminal.py", line 104, in _run_in_t
    result = yield From(async_func())
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/application/run_in_terminal.py", line 47, in async_func
    result = func()
  File "/home/indy/demo/runners/support/agent.py", line 665, in handle_output
    log_msg(*output, color=color, prefix=self.prefix_str, end=end, **kwargs)
  File "/home/indy/demo/runners/support/utils.py", line 120, in log_msg
    run_in_terminal(lambda: print_ext(*msg, color=color, **kwargs))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/application/run_in_terminal.py", line 50, in run_in_terminal
    return run_coroutine_in_terminal(async_func, render_cli_done=render_cli_done)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/application/run_in_terminal.py", line 71, in run_coroutine_in_terminal
    assert app._is_running
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/eventloop/base.py", line 132, in call_exception_handler
    self._exception_handler(context)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 729, in handle_exception
    run_coroutine_in_terminal(print_exception)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prompt_toolkit/application/run_in_terminal.py", line 71, in run_coroutine_in_terminal
    assert app._is_running
```

**Comment by swcurran** [comment]
@usingtechnology — adding this to your list since this is related to what you are working on right now. Worst case you ask @ianco about it when you are talking with him.

**Comment by ianco** [comment]
@swcurran I wonder if this is a timing issue ...  the agents seem to all start up ok, but the errors are generated in the logging to the terminal
