### ISSUE TITLE
Error in JSON-LD Lab

### ISSUE THREAD

**Issue by janesp** [hyperledger/aries-cloudagent-python#2214]
Found this while doing the EdX course:

Alice      | 2023-04-22 22:05:11,159 aries_cloudagent.messaging.base_handler ERROR Error processing issue-credential v2.0 problem report message
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/handlers/cred_problem_report_handler.py", line 43, in handle
Alice      |     context.connection_record.connection_id,
Alice      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/manager.py", line 740, in receive_problem_report
Alice      |     message._thread_id,
Alice      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v2_0/models/cred_ex_record.py", line 268, in retrieve_by_conn_and_thread
Alice      |     post_filter,
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base_record.py", line 286, in retrieve_by_tag_filter
Alice      |     cls.__name__, tag_filter, f", {post_filter}" if post_filter else ""
Alice      | aries_cloudagent.storage.error.StorageNotFoundError: V20CredExRecord record not found for {'thread_id': '6a585e79-759a-470a-8ca7-00767b1ad14c'}, {'connection_id': 'fb2bde97-50fc-4e18-a7d4-2149c298d18e'}

**Comment by janesp** [comment]
proofType corrected
