### ISSUE TITLE
VdrError: Pool timeout - Aca-Py 0.8.1

### ISSUE THREAD

**Issue by Durai46** [hyperledger/aries-cloudagent-python#2226]
Can anyone please help on the cause of the VDR error?

Using the Agent version : bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1

Error logs:

2023-05-08 06:05:42,705 aries_askar.native.aries_askar.backend.db_utils INFO 	src/backend/db_utils.rs:146 | Commit transaction on close
2023-05-08 06:05:42,710 aries_askar.native.sqlx.query DEBUG 	None:0 | COMMIT; rows affected: 0, rows returned: 0, elapsed: 4.327ms
2023-05-08 06:05:42,710 aries_askar.native.aries_askar.backend.db_utils INFO 	src/backend/db_utils.rs:168 | Dropped pool connection
2023-05-08 06:05:42,710 aries_askar.native.aries_askar.ffi.store INFO 	src/ffi/store.rs:1010 | Closed session SessionHandle(1)
2023-05-08 06:05:42,712 aries_askar.native.aries_askar.ffi.store INFO 	src/ffi/store.rs:528 | Started session SessionHandle(2) on store StoreHandle(1) (txn: false)
2023-05-08 06:05:42,713 aries_cloudagent.ledger.indy_vdr DEBUG Opening the pool ledger
2023-05-08 06:05:42,717 aries_cloudagent.ledger.indy_vdr DEBUG Wrote pool ledger config 'default'
2023-05-08 06:06:02,749 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 185, in setup
    self.root_profile, self.setup_public_did and self.setup_public_did.did
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 136, in ledger_config
    async with ledger:
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 307, in __aenter__
    await self.pool.context_open()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 228, in context_open
    await self.open()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 191, in open
    self.handle = await open_pool(transactions=txns, socks_proxy=self.socks_proxy)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/pool.py", line 177, in open_pool
    await pool.refresh()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/pool.py", line 58, in refresh
    await bindings.pool_refresh(self.handle)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
indy_vdr.error.VdrError: Pool timeout: Request was interrupted

Shutting down
2023-05-08 06:06:02,754 aries_cloudagent.core.event_bus DEBUG Notifying subscribers: <Event topic=acapy::core::shutdown, payload={}>
2023-05-08 06:06:02,764 aries_askar.native.aries_askar.backend.db_utils INFO 	src/backend/db_utils.rs:168 | Dropped pool connection
2023-05-08 06:06:02,765 aries_askar.native.aries_askar.ffi.store INFO 	src/ffi/store.rs:413 | Closed store StoreHandle(1)
2023-05-08 06:06:02,767 aries_askar.native.aries_askar.ffi.log DEBUG 	src/ffi/log.rs:130 | Removing custom logger
2023-05-08 06:06:02,768 aries_askar.native.aries_askar.ffi.store INFO 	src/ffi/store.rs:1012 | Session not found for closing: SessionHandle(2)

**Comment by alperari** [comment]
This is already closed but any solutions you would suggest? @jamshale

**Comment by WadeBarnes** [comment]
@alperari,
This might help https://github.com/hyperledger/aries-cloudagent-python/issues/2592#issuecomment-1792487825

**Comment by alperari** [comment]
After a long hustle finally figure it out.
* In my case i was running `von-network` and two `aries-cloudagent-python` agents, Alice and Faber, in docker.
* Genesis file provided that i provided agents with had `127.0.0.1` as node ip address.

Running agent containers in the same `von_von` network did the magic:
```sh
DOCKER_NET=von_von ./run_demo alice
DOCKER_NET=von_von ./run_demo faber
```
And finally i established communication between agents, created and issued schemas, etc.
