### ISSUE TITLE
Pool timeout acquiring db connection with Askar and Postgres wallet in Multitenant mode

### ISSUE THREAD

**Issue by dheerajbudhiraja** [hyperledger/aries-cloudagent-python#2257]
Intermittently getting pool timeout acquiring db connection with Askar and Postgres wallet.

aca-py version: 0.8.1
Postgres version: 13.1

Below are logs from Aries cloud agent python: 
```
172.31.14.20 [08/Jun/2023:07:32:05 +0000] "GET /status/live HTTP/1.1" 200 191 "-" "ELB-HealthChecker/2.0"
        src/ffi/store.rs:1010 | Closed session SessionHandle(1406)
        src/backend/db_utils.rs:168 | Dropped pool connection
Handler error with exception: Error when fetching storage record
Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/storage/askar.py", line 90, in get_record
    record_type, record_id, for_update=for_update
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/store.py", line 419, in fetch
    self._handle, category, name, for_update
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/bindings/__init__.py", line 224, in session_fetch
    return_type=EntryListHandle,
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/bindings/lib.py", line 359, in invoke_async
    name, argtypes, *args, return_type=return_type
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
aries_askar.error.AskarError: Backend error
Caused by: pool timed out while waiting for an open connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 173, in ready_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 210, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 330, in check_token
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 379, in check_multitenant_authorization
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 398, in setup_context
    self.context, token
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/multitenant/base.py", line 348, in get_profile_for_token
    wallet = await WalletRecord.retrieve_by_id(session, wallet_id)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 240, in retrieve_by_id
    cls.RECORD_TYPE, record_id, {"forUpdate": for_update, "retrieveTags": False}
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/storage/askar.py", line 93, in get_record
    raise StorageError("Error when fetching storage record") from err
aries_cloudagent.storage.error.StorageError: Error when fetching storage record
```

**Comment by dheerajbudhiraja** [comment]
Also getting JSON Decode error intermittently: 

`
Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/pack_format.py", line 213, in get_recipient_keys
    message_dict = json.loads(message_body)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/inbound/http.py", line 94, in inbound_message_handler
    inbound = await session.receive(body)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/inbound/session.py", line 218, in receive
    await self.handle_relay_context(payload_enc)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/inbound/session.py", line 166, in handle_relay_context
    payload_enc, self.wire_format
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/multitenant/base.py", line 412, in get_wallets_by_message
    recipient_keys = wire_format.get_recipient_keys(message_body)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/pack_format.py", line 220, in get_recipient_keys
    "Error trying to extract recipient keys from JWE", e
aries_cloudagent.transport.error.RecipientKeysError: ('Error trying to extract recipient keys from JWE', JSONDecodeError('Extra data: line 1 column 2 (char 1)',))
`

**Comment by swcurran** [comment]
Sorry this didn't get answered, but presumably you are past this. This does work...not sure what happened in your environment.
