### ISSUE TITLE
Unable to launch AcaPy agent using public ledger

### ISSUE THREAD

**Issue by louislouislouislouis** [hyperledger/aries-cloudagent-python#2408]
Hi,

I have some trouble when launching an acapy agent.

Everything is working fine when I use a local von-network, with this parmeters

```
python -m aries_cloudagent start \
--endpoint http://192.168.65.4:8020 \
--label faber.agent  \
--auto-ping-connection \
--auto-respond-messages \
--inbound-transport http 0.0.0.0 8020 \
--outbound-transport http \
--admin 0.0.0.0 8021 \
--admin-insecure-mode \
--wallet-type askar \
--wallet-name faber.agent872351 \
--wallet-key faber.agent872351 \
--preserve-exchange-records \
--auto-provision \
--public-invites \
--emit-new-didcomm-prefix \
--genesis-url http://192.168.65.4:9000/genesis \
--seed d_000000000000000000000000872351 \
--webhook-url http://192.168.65.4:8022/webhooks \
--debug-webhooks \
--monitor-revocation-notification \
--trace-target log \
--trace-tag acapy.events \
--trace-label faber.agent.trace \
--auto-accept-invites \
--auto-accept-requests \
--auto-store-credential
```

But when I try using the test public ledger by doing so

```
python -m aries_cloudagent start \
--endpoint http://192.168.65.4:8020 \
--label faber.agent  \
--auto-ping-connection \
--auto-respond-messages \
--inbound-transport http 0.0.0.0 8020 \
--outbound-transport http \
--admin 0.0.0.0 8021 \
--admin-insecure-mode \
--wallet-type askar \
--wallet-name faber.agent872351 \
--wallet-key faber.agent872351 \
--preserve-exchange-records \
--auto-provision \
--public-invites \
--emit-new-didcomm-prefix \
--genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis \
--seed d_000000000000000000000000872351 \
--webhook-url http://192.168.65.4:8022/webhooks \
--debug-webhooks \
--monitor-revocation-notification \
--trace-target log \
--trace-tag acapy.events \
--trace-label faber.agent.trace \
--auto-accept-invites \
--auto-accept-requests \
--auto-store-credential
```

(only change the `--genesis-url`)

it ended up with this 
```
indy_vdr.error.VdrError: Pool timeout: Request was interrupted
```

Full trace

```
vscode ➜ /workspaces/aries-cloudagent-python (main) $  /usr/bin/env /usr/local/bin/python /home/vscode/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 52801 -- -m aries_cloudagent start --endpoint http://192.168.65.4:8020 --label faber.agent --auto-ping-connection --auto-respond-messages --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin 0.0.0.0 8021 --admin-insecure-mode --wallet-type askar --wallet-name faber.agent872351 --wallet-key faber.agent872351 --preserve-exchange-records --auto-provision --public-invites --emit-new-didcomm-prefix --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --seed d_000000000000000000000000872351 --webhook-url http://192.168.65.4:8022/webhooks --debug-webhooks --monitor-revocation-notification --trace-target log --trace-tag acapy.events --trace-label faber.agent.trace --auto-accept-invites --auto-accept-requests --auto-store-credential 
2023-08-10 10:59:33,643 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/core/conductor.py", line 181, in setup
    if not await ledger_config(
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/config/ledger.py", line 137, in ledger_config
    async with ledger:
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/ledger/indy_vdr.py", line 308, in __aenter__
    await self.pool.context_open()
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/ledger/indy_vdr.py", line 229, in context_open
    await self.open()
  File "/workspaces/aries-cloudagent-python/aries_cloudagent/ledger/indy_vdr.py", line 192, in open
    self.handle = await open_pool(transactions=txns, socks_proxy=self.socks_proxy)
  File "/home/vscode/.local/lib/python3.9/site-packages/indy_vdr/pool.py", line 177, in open_pool
    await pool.refresh()
  File "/home/vscode/.local/lib/python3.9/site-packages/indy_vdr/pool.py", line 58, in refresh
    await bindings.pool_refresh(self.handle)
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
indy_vdr.error.VdrError: Pool timeout: Request was interrupted

Shutting down

```

but my container is able to reach the url because

```


vscode ➜ /workspaces/aries-cloudagent-python (main) $ curl http://dev.greenlight.bcovrin.vonx.io/genesis
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"159.203.21.90","client_port":9702,"node_ip":"159.203.21.90","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"159.203.21.90","client_port":9704,"node_ip":"159.203.21.90","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"159.203.21.90","client_port":9706,"node_ip":"159.203.21.90","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"159.203.21.90","client_port":9708,"node_ip":"159.203.21.90","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}
{"reqSignature":{"type":"ED25519","values":[{"from":"2dZN1uUvDt68K9CKu9CJM2","value":"47m26iub4kiS1LX6hKEruqPN3DeSg5Znw2fvnNvWxfpryvs6QqGxdpGCzJARxG5CC7jTSew6F5zGRoBcyt9QVWnt"}]},"txn":{"data":{"data":{"alias":"Node5","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"127.0.0.2","client_port":9711,"node_ip":"127.0.0.1","node_port":9710,"services":["VALIDATOR"]},"dest":"4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe"},"metadata":{"digest":"200976d2f8a99130e38eb6ea4fa68910c274ecfea1fbc39c866c05af2d891d5a","from":"2dZN1uUvDt68K9CKu9CJM2","payloadDigest":"7242e7b337c4670e8e33bb9748a6017670896f7ce6d34fe1acfd54b32a9968bd","reqId":1581887172448041000},"protocolVersion":2,"type":"0"},"txnMetadata":{"seqNo":5,"txnTime":1581887174},"ver":"1"}
{"reqSignature":{"type":"ED25519","values":[{"from":"V4SGRU86Z58d6TV7PBUe6f","value":"4qEZWAWoEqpqa36yUiJWVRaHL9s5e2ua4TZNoJu2MUcWtGrsTi8uNMbedx9vp98pg9YhTVy8Yz7ZmujvXXQF1tAF"}]},"txn":{"data":{"data":{"alias":"Node5","services":[]},"dest":"4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe"},"metadata":{"digest":"219f193e4dcfeb622b724cf47f38f5aaf4372f7b4038cf42df58fbc520640b4a","from":"V4SGRU86Z58d6TV7PBUe6f","payloadDigest":"fe5710e5733390a04ecb83fc832de8c2859f57c7a9cff68576b212c795459704","reqId":1587649729343646804},"protocolVersion":2,"type":"0"},"txnMetadata":{"seqNo":6,"txnTime":1587649804},"ver":"1"}
```

Tried to remove seed, it seems not to be the problem.

So  I am wondering if I am doing wrong (Is this possible that I have firewall issue, do the protocol to connect to the ledger involve special port or protocol that can be cut by the firewall ? (I try to stop my local von-network. I also check if the port 9701-9708) are available...)

**Comment by swcurran** [comment]
I would bet on a firewall issue as you are guessing.  With a local network, the 9701-9708 are internal. With an external ledger that is going out from your network to the internet, and those ports might be blocked.

**Comment by louislouislouislouis** [comment]
You were totally right, thanks !
