### ISSUE TITLE
New AATH Connection Issues between ACA-Py and AF-Go and Findy Agent

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2449]
New errors were introduced in the AATH test run from last night for ACA-Py and AFGo and ACA-Py and Findy Agent, likely caused by Aries Cloud Agent Python PR #2409 -- refactoring of the DIDComm DID handling.  Newly failing tests were found by going from https://aries-interop.info following the links into Allure and seeing the tests that passed last run, failed on this one.

@dbluhm -- I hope this gives you all you need.

ACA-Py - AFGo Logs from the run are below, and I think they have what you need, but if not, the logs were produced using these steps:

- Clone the https://github.com/hyperledger/aries-agent-test-harness
- Build: `./manage build -a acapy-main -a afgo-interop`
- Run the services: `./manage service start von-network; ./manage service start indy-tails; ./manage service start uniresolver; ./manage service start orb`
- Run Failing Test: `./manage run -d acapy-main -b afgo-interop -t AIP20 -t RFC0023 -t T001-RFC0023 -t AcceptanceTest`
- Stop the services: `./manage service stop von-network; ./manage service stop indy-tails; ./manage service stop uniresolver; ./manage service stop orb`
- Logs are in .logs for ACA-Py (Acme) and AF-Go (Bob)

[acapy-afgo-logs.zip](https://github.com/hyperledger/aries-cloudagent-python/files/12445550/acapy-afgo-logs.zip)

ACA-Py - Findy Agent Logs from the run are below, and I think they have what you need, but if not, the logs were produced using these steps:

- Build: `./manage build -a acapy-main -a findy`
- Run the services: `./manage service start von-network; ./manage service start indy-tails; ./manage service start uniresolver; ./manage service start orb`
- Run Failing Test: `./manage run -d acapy-main -b findy -t AIP10 -t RFC0160 -t T001-RFC0160 -t MobileTest -t AcceptanceTest`
- Stop the services: `./manage service stop von-network; ./manage service stop indy-tails; ./manage service stop uniresolver; ./manage service stop orb`
- Logs are in .logs for ACA-Py (Acme) and Findy (Bob)

[acapy-findy-logs.zip](https://github.com/hyperledger/aries-cloudagent-python/files/12445574/acapy-findy-logs.zip)

**Comment by dbluhm** [comment]
# Extracted details

## ACA-Py <-> AFGo

```mermaid
sequenceDiagram
participant acapy
participant afgo

afgo -->> acapy: out-of-band/1.0/invitation
acapy ->> afgo: didexchange/1.0/request
afgo -x acapy: didexchange/1.0/response
```

ACA-Py Received Response:

```json
{
  "@type": "https://didcomm.org/didexchange/1.0/response",
  "@id": "5e0b3da8-1901-46a3-bd5a-c3b577a15477",
  "~thread": {
    "thid": "d4bb53fa-573c-433d-aaec-75c146c9744f",
    "pthid": "9fffcde5-8edf-4f30-9b27-96fe519780bf"
  },
  "did": "1H6d1WS29Bcfr7Bb9tZxA",
  "did_doc~attach": {
    "mime-type": "application/json",
    "lastmod_time": "0001-01-01T00:00:00Z",
    "data": {
      "base64": "eyJAY29udGV4dCI6WyJodHRwczovL3czaWQub3JnL2RpZC92MSJdLCJpZCI6ImRpZDpzb3Y6MUg2ZDFXUzI5QmNmcjdCYjl0WnhBIiwidmVyaWZpY2F0aW9uTWV0aG9kIjpbeyJjb250cm9sbGVyIjoiZGlkOnNvdjoxSDZkMVdTMjlCY2ZyN0JiOXRaeEEiLCJpZCI6IiNrZXktMSIsInB1YmxpY0tleUJhc2U1OCI6ImdNeGRWTXlGOFJha2FwdHhGc0R6SEF4ZlE1aUVLWmtDRVFjU3dzRGJTV2YiLCJ0eXBlIjoiRWQyNTUxOVZlcmlmaWNhdGlvbktleTIwMTgifSx7ImNvbnRyb2xsZXIiOiJkaWQ6c292OjFINmQxV1MyOUJjZnI3QmI5dFp4QSIsImlkIjoiI2tleS0yIiwicHVibGljS2V5QmFzZTU4IjoicWdYVTFiSlY4b2JIREtLSzEyZGZRVDlmaXR2Qkt2YmUxQlpVNkd3Q1pucCIsInR5cGUiOiJYMjU1MTlLZXlBZ3JlZW1lbnRLZXkyMDE5In1dLCJzZXJ2aWNlIjpbeyJpZCI6IjBmNTU1YTgwLWM5NTAtNGIyYy1iOGVjLTYzMmM3MmZmZDc4MCIsInByaW9yaXR5IjowLCJyZWNpcGllbnRLZXlzIjpbImdNeGRWTXlGOFJha2FwdHhGc0R6SEF4ZlE1aUVLWmtDRVFjU3dzRGJTV2YiXSwicm91dGluZ0tleXMiOltdLCJzZXJ2aWNlRW5kcG9pbnQiOiJodHRwOi8vMTcyLjE3LjAuMTo5MDMxIiwidHlwZSI6IkluZHlBZ2VudCJ9XSwiYXV0aGVudGljYXRpb24iOlt7InB1YmxpY0tleSI6IiNrZXktMSJ9XSwiYXNzZXJ0aW9uTWV0aG9kIjpbeyJwdWJsaWNLZXkiOiIja2V5LTEifV0sImtleUFncmVlbWVudCI6W3sicHVibGljS2V5IjoiI2tleS0yIn1dLCJjcmVhdGVkIjoiMjAyMy0wOC0yNlQxNDoxNzo0Mi4wMDU1NjM2NTlaIiwidXBkYXRlZCI6IjIwMjMtMDgtMjZUMTQ6MTc6NDIuMDA1NTYzNjU5WiJ9",
      "jws": {
        "header": {
          "kid": "did:key:z6MktR4HLoWtKmxpjB8FMJigVoxf7ScqSA1nnTQHbr6urL82"
        },
        "signature": "gsczKP6XXuHBmQBlUJVPmQCMn4ejSGEg0kWuC1ZAjh7cQXmnvhQrZIDWCRaqW2e80HEmiGReVnvSgoGVXMOPDg",
        "protected": "eyJqd2siOnsia3R5IjoiT0tQIiwia2lkIjoiZGlkOmtleTp6Nk1rdFI0SExvV3RLbXhwakI4Rk1KaWdWb3hmN1NjcVNBMW5uVFFIYnI2dXJMODIiLCJjcnYiOiJFZDI1NTE5IiwieCI6InozTW5yTmppeTZJT1pZTE9zTEN6QWpCRll1QXhHZS1LdTBvTG55YWlUWXMifSwiYWxnIjoiRWREU0EifQ"
      }
    }
  }
}
```

Extracted DID Document:
```json
{
  "@context": [
    "https://w3id.org/did/v1"
  ],
  "id": "did:sov:1H6d1WS29Bcfr7Bb9tZxA",
  "verificationMethod": [
    {
      "controller": "did:sov:1H6d1WS29Bcfr7Bb9tZxA",
      "id": "#key-1",
      "publicKeyBase58": "gMxdVMyF8RakaptxFsDzHAxfQ5iEKZkCEQcSwsDbSWf",
      "type": "Ed25519VerificationKey2018"
    },
    {
      "controller": "did:sov:1H6d1WS29Bcfr7Bb9tZxA",
      "id": "#key-2",
      "publicKeyBase58": "qgXU1bJV8obHDKKK12dfQT9fitvBKvbe1BZU6GwCZnp",
      "type": "X25519KeyAgreementKey2019"
    }
  ],
  "service": [
    {
      "id": "0f555a80-c950-4b2c-b8ec-632c72ffd780",
      "priority": 0,
      "recipientKeys": [
        "gMxdVMyF8RakaptxFsDzHAxfQ5iEKZkCEQcSwsDbSWf"
      ],
      "routingKeys": [],
      "serviceEndpoint": "http://172.17.0.1:9031",
      "type": "IndyAgent"
    }
  ],
  "authentication": [
    {
      "publicKey": "#key-1"
    }
  ],
  "assertionMethod": [
    {
      "publicKey": "#key-1"
    }
  ],
  "keyAgreement": [
    {
      "publicKey": "#key-2"
    }
  ],
  "created": "2023-08-26T14:17:42.005563659Z",
  "updated": "2023-08-26T14:17:42.005563659Z"
}
```

Relevant error logs:
```python
2023-08-26 14:17:42,082 aries_cloudagent.connections.base_manager ERROR Failed to resolve service details while determining connection targets; skipping service
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/resolver/did_resolver.py", line 142, in dereference
    return document.dereference(parsed)
  File "/usr/local/lib/python3.9/site-packages/pydid/doc/doc.py", line 145, in dereference
    raise IDNotFoundError("ID {} not found in document".format(reference))
pydid.doc.doc.IDNotFoundError: ID did:sov:1H6d1WS29Bcfr7Bb9tZxA#1 not found in document

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 368, in resolve_connection_targets
    recips, routing = await self.verification_methods_for_service(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 296, in verification_methods_for_service
    recipient_keys: List[VerificationMethod] = [
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 297, in <listcomp>
    await resolver.dereference_verification_method(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/resolver/did_resolver.py", line 156, in dereference_verification_method
    dereferenced = await self.dereference(profile, did_url, document=document)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/resolver/did_resolver.py", line 144, in dereference
    raise ResolverError(
aries_cloudagent.resolver.base.ResolverError: Failed to dereference DID URL: ID did:sov:1H6d1WS29Bcfr7Bb9tZxA#1 not found in document
```

**Comment by dbluhm** [comment]
## ACA-Py <-> Findy

```mermaid
sequenceDiagram
participant acapy
participant findy

acapy -->> findy: connections/1.0/invitation
findy -x acapy: connections/1.0/request
```

Received request:
```json
{
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/request",
  "@id": "2f6aae0c-6b04-40ff-a25e-faecaea39f83",
  "label": "findy-agent-backchannel-1693060638249248339",
  "connection": {
    "DID": "5qXMeLdyWEQhieFUBNw5ux",
    "DIDDoc": {
      "@context": "https://w3id.org/did/v1",
      "id": "did:sov:5qXMeLdyWEQhieFUBNw5ux",
      "publicKey": [
        {
          "id": "did:sov:5qXMeLdyWEQhieFUBNw5ux#1",
          "type": "Ed25519VerificationKey2018",
          "controller": "did:sov:5qXMeLdyWEQhieFUBNw5ux",
          "publicKeyBase58": "3dtu2WWtd5ELwRTJEPzmEJUYEp8Qq36N2QA24g9tFXK9"
        }
      ],
      "service": [
        {
          "id": "did:sov:5qXMeLdyWEQhieFUBNw5ux",
          "type": "IndyAgent",
          "recipientKeys": [
            "3dtu2WWtd5ELwRTJEPzmEJUYEp8Qq36N2QA24g9tFXK9"
          ],
          "serviceEndpoint": "http://172.17.0.1:9031/a2a/5b6dyY6PndLaCnWxZbeEYW/5b6dyY6PndLaCnWxZbeEYW/2f6aae0c-6b04-40ff-a25e-faecaea39f83"
        }
      ],
      "authentication": [
        {
          "type": "Ed25519SignatureAuthentication2018",
          "publicKey": "did:sov:5qXMeLdyWEQhieFUBNw5ux#1"
        }
      ]
    }
  },
  "~thread": {
    "thid": "2f6aae0c-6b04-40ff-a25e-faecaea39f83"
  }
}
```

Relevant error logs:

```python
[0m2023-08-26 14:37:32,560 aries_cloudagent.core.dispatcher ERROR Handler error: BaseConnectionManager.get_connection_targets
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 13, in wrap_validation_error
    yield
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 609, in get_connection_targets
    targets = await self.fetch_connection_targets(connection)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 570, in fetch_connection_targets
    return await self.resolve_connection_targets(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 362, in resolve_connection_targets
    doc, didcomm_services = await self.resolve_didcomm_services(did)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 269, in resolve_didcomm_services
    doc: ResolvedDocument = pydid.deserialize_document(doc_dict, strict=True)
  File "/usr/local/lib/python3.9/site-packages/pydid/__init__.py", line 63, in deserialize_document
    return cls.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/doc/doc.py", line 171, in deserialize
    DIDDocumentRoot.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 15, in wrap_validation_error
    raise error_to_raise(
ValueError: Failed to deserialize DIDDocumentRoot:
1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)
2023-08-26 14:37:32,561 aries_cloudagent.core.dispatcher ERROR Handler error: connections_accept_request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 13, in wrap_validation_error
    yield
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 797, in connections_accept_request
    await outbound_handler(response, connection_id=connection.connection_id)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/messaging/responder.py", line 101, in send
    return await self.send_outbound(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 147, in send_outbound
    return await self._send(profile, message)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 637, in outbound_message_router
    status: OutboundSendStatus = await self._outbound_message_router(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 665, in _outbound_message_router
    return await self.queue_outbound(profile, outbound, inbound)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 697, in queue_outbound
    outbound.target_list = await self.dispatcher.run_task(
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 609, in get_connection_targets
    targets = await self.fetch_connection_targets(connection)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 570, in fetch_connection_targets
    return await self.resolve_connection_targets(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 362, in resolve_connection_targets
    doc, didcomm_services = await self.resolve_didcomm_services(did)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 269, in resolve_didcomm_services
    doc: ResolvedDocument = pydid.deserialize_document(doc_dict, strict=True)
  File "/usr/local/lib/python3.9/site-packages/pydid/__init__.py", line 63, in deserialize_document
    return cls.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/doc/doc.py", line 171, in deserialize
    DIDDocumentRoot.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 15, in wrap_validation_error
    raise error_to_raise(
ValueError: Failed to deserialize DIDDocumentRoot:
1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)
2023-08-26 14:37:32,562 aries_cloudagent.admin.server ERROR Handler error with exception: Failed to deserialize DIDDocumentRoot:
1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)

=================
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 13, in wrap_validation_error
    yield
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 181, in ready_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 218, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 450, in setup_context
    return await task
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 797, in connections_accept_request
    await outbound_handler(response, connection_id=connection.connection_id)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/messaging/responder.py", line 101, in send
    return await self.send_outbound(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 147, in send_outbound
    return await self._send(profile, message)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 637, in outbound_message_router
    status: OutboundSendStatus = await self._outbound_message_router(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 665, in _outbound_message_router
    return await self.queue_outbound(profile, outbound, inbound)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 697, in queue_outbound
    outbound.target_list = await self.dispatcher.run_task(
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 609, in get_connection_targets
    targets = await self.fetch_connection_targets(connection)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 570, in fetch_connection_targets
    return await self.resolve_connection_targets(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 362, in resolve_connection_targets
    doc, didcomm_services = await self.resolve_didcomm_services(did)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 269, in resolve_didcomm_services
    doc: ResolvedDocument = pydid.deserialize_document(doc_dict, strict=True)
  File "/usr/local/lib/python3.9/site-packages/pydid/__init__.py", line 63, in deserialize_document
    return cls.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/doc/doc.py", line 171, in deserialize
    DIDDocumentRoot.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 15, in wrap_validation_error
    raise error_to_raise(
ValueError: Failed to deserialize DIDDocumentRoot:
1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)
2023-08-26 14:37:32,563 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 13, in wrap_validation_error
    yield
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 181, in ready_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 218, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 450, in setup_context
    return await task
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/protocols/connections/v1_0/routes.py", line 797, in connections_accept_request
    await outbound_handler(response, connection_id=connection.connection_id)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/messaging/responder.py", line 101, in send
    return await self.send_outbound(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 147, in send_outbound
    return await self._send(profile, message)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 637, in outbound_message_router
    status: OutboundSendStatus = await self._outbound_message_router(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 665, in _outbound_message_router
    return await self.queue_outbound(profile, outbound, inbound)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 697, in queue_outbound
    outbound.target_list = await self.dispatcher.run_task(
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 609, in get_connection_targets
    targets = await self.fetch_connection_targets(connection)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 570, in fetch_connection_targets
    return await self.resolve_connection_targets(
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 362, in resolve_connection_targets
    doc, didcomm_services = await self.resolve_didcomm_services(did)
  File "/usr/local/lib/python3.9/site-packages/aries_cloudagent/connections/base_manager.py", line 269, in resolve_didcomm_services
    doc: ResolvedDocument = pydid.deserialize_document(doc_dict, strict=True)
  File "/usr/local/lib/python3.9/site-packages/pydid/__init__.py", line 63, in deserialize_document
    return cls.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/doc/doc.py", line 171, in deserialize
    DIDDocumentRoot.deserialize(value)
  File "/usr/local/lib/python3.9/site-packages/pydid/resource.py", line 68, in deserialize
    return parse_obj_as(cls, value)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/pydid/validation.py", line 15, in wrap_validation_error
    raise error_to_raise(
ValueError: Failed to deserialize DIDDocumentRoot:
1 validation error for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 0 -> id
  did:sov:5qXMeLdyWEQhieFUBNw5ux is not a valid absolute or relative DID URL (type=value_error.invaliddidurl)
2023-08-26 14:37:32,565 aiohttp.access INFO 174.96.0.1 [26/Aug/2023:14:37:32 +0000] "POST /connections/002895ff-1f46-4a0d-80a7-caf22d75bb10/accept-request HTTP/1.1" 500 244 "-" "Python/3.9 aiohttp/3.8.5"
[0m[?7h[0;35mReceived a Connection Webhook message: {"state": "response", "created_at": "2023-08-26T14:37:29.929560Z", "updated_at": "2023-08-26T14:37:32.534670Z", "connection_id": "002895ff-1f46-4a0d-80a7-caf22d75bb10", "my_did": "CRHevK15VwKudZkSXHMSMD", "their_did": "5qXMeLdyWEQhieFUBNw5ux", "their_label": "findy-agent-backchannel-1693060638249248339", "their_role": "invitee", "connection_protocol": "connections/1.0", "rfc23_state": "response-sent", "invitation_key": "7v9ihCsG7zZBCJWvRrgs7JN89JDQpuBu5Bxb5ZpBfDPv", "routing_state": "none", "accept": "manual", "invitation_mode": "once"}[0m
[0m[0m[?7h[0;35m500 500 Internal Server Error

Server got itself in trouble[0m
```

**Comment by dbluhm** [comment]
I will of course fix this so that we restore interop to what it was but as we move to did:peer, ACA-Py should take a stronger position on correctly formatting DID Documents. Not both of the errors were caused by  non-conformant docs but both docs received in the requests/responses are non-conformant.

**Comment by dbluhm** [comment]
Of course, so are the docs ACA-Py was sending out -- we need to be careful about the kind of pressure we're exerting on the interop of the community.

**Comment by dbluhm** [comment]
I've submitted #2450 to address these errors. I haven't run AATH myself yet though.

**Comment by dbluhm** [comment]
Thanks for the detailed reports, @swcurran! That made it much easier to diagnose these issues and (hopefully) correct them.
