### ISSUE TITLE
Pool timeout when connecting to a VON-network hosted on another machine 

### ISSUE THREAD

**Issue by MandSFun** [hyperledger/aries-cloudagent-python#2592]
Hi, 

I am trying to host VON-network on machine A and run ACA-py on machine B. I have configured the docker compose of ACA-py to change the addresses of the genesis files and ledger urls, however I am still unable to connect to the VON-network, it will show this error:

acapy_1         | 2023-11-03 07:33:32,175 indy.libindy.native.indy.commands.pool INFO   src/commands/pool.rs:75 | OpenAck handle 5, pool_id 5, result Err(IndyError { inner:
acapy_1         |
acapy_1         | Pool timeout
acapy_1         |
acapy_1         | Pool timeout })
acapy_1         | 2023-11-03 07:33:32,176 indy.libindy WARNING _indy_loop_callback: Function returned error
acapy_1         | 2023-11-03 07:33:32,179 aries_cloudagent.commands.start ERROR Exception during startup:
acapy_1         | Traceback (most recent call last):
acapy_1         |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 204, in open
acapy_1         |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
acapy_1         |     open_pool_ledger.cb)
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
acapy_1         |     yield self  # This tells Task to wait for completion.
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
acapy_1         |     future.result()
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
acapy_1         |     raise self._exception
acapy_1         | indy.error.PoolLedgerTimeout
acapy_1         |
acapy_1         | The above exception was the direct cause of the following exception:
acapy_1         |
acapy_1         | Traceback (most recent call last):
acapy_1         |   File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init
acapy_1         |     await startup
acapy_1         |   File "/home/indy/aries_cloudagent/commands/start.py", line 28, in start_app
acapy_1         |     await conductor.setup()
acapy_1         |   File "/home/indy/aries_cloudagent/core/conductor.py", line 185, in setup
acapy_1         |     self.root_profile, self.setup_public_did and self.setup_public_did.did
acapy_1         |   File "/home/indy/aries_cloudagent/config/ledger.py", line 136, in ledger_config
acapy_1         |     async with ledger:
acapy_1         |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 318, in __aenter__
acapy_1         |     await self.pool.context_open()
acapy_1         |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 239, in context_open
acapy_1         |     await self.open()
acapy_1         |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 204, in open
acapy_1         |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
acapy_1         |   File "/home/indy/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
acapy_1         |     ) from err_value
acapy_1         |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 204, in open
acapy_1         |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
acapy_1         |     open_pool_ledger.cb)
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
acapy_1         |     yield self  # This tells Task to wait for completion.
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
acapy_1         |     future.result()
acapy_1         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
acapy_1         |     raise self._exception
acapy_1         | aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
acapy_1         |   Caused by: Pool timeout
acapy_1         |
acapy_1         |
acapy_1         | Shutting down

Is aca-py configured to allow connections to remote networks?

**Comment by WadeBarnes** [comment]
Use the syntax found here to start `von-network` and have it expose the ledger from the machine's IP address.  FYI, info can be found [here](https://github.com/bcgov/von-network#running-the-network-on-a-vps).

```
./manage start public_ip_address WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=My Ledger"
```

A real world example, this is how http://test.bcovrin.vonx.io/ is started:
```
./manage start 138.197.138.255 LOG_LEVEL=info RUST_LOG=error POOL_CONNECTION_DELAY=20 POOL_CONNECTION_ATTEMPTS=30 WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=BCovrin Test" "INFO_SITE_TEXT=digital.gov.bc.ca/digital-trust" "INFO_SITE_URL=https://digital.gov.bc.ca/digital-trust/" "LEDGER_CACHE_PATH=/home/indy/.indy_client/ledger-cache/ledger-cache-db"
```

**Comment by WadeBarnes** [comment]
How do you have your aca-py instance configured from a ledger/genesis perspective?

**Comment by MandSFun** [comment]
Hi Wade, thank you so much for your prompt reply.  Aca-py is now started using a docker compose as follows:

```
version: '3'
services:
  acapy:
    image: aortz1999/aries-cloudagent-run:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    ports:
      - "${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}"
      - "${ACAPY_ENDPOINT_PORT}:${ACAPY_ENDPOINT_PORT}"
    environment:
      WAIT_HOSTS: "db:5432"
      WAIT_HOSTS_TIMEOUT: "300"
      WAIT_SLEEP_INTERVAL: "5"
      WAIT_HOST_CONNECT_TIMEOUT: "3"
      AGENT_WALLET_SEED: "bobby000000000000000000000000001"
      LABEL: "Bobby"
      ACAPY_ENDPOINT_PORT: "8002"
      ACAPY_ENDPOINT_URL: "http://localhost:8002/"
      ACAPY_ADMIN_PORT: "${ACAPY_ADMIN_PORT}"
      LEDGER_URL: "http://<host_IP_V4_address>"
      TAILS_SERVER_URL: "http://tails-server:6543"
      CONTROLLER_PORT: "${CONTROLLER_PORT}"
      WALLET_NAME: "Bobby"
      WALLET_KEY: "secret"
    entrypoint: /bin/bash
    command: [
       "-c",
       "sleep 5; \
        /wait; \
        aca-py start \
        --auto-provision \
        -e ${ACAPY_ENDPOINT_URL} \
        -it http '0.0.0.0' ${ACAPY_ENDPOINT_PORT} \
        -ot http \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --wallet-type indy \
        --wallet-name ${WALLET_NAME} \
        --wallet-key ${WALLET_KEY} \
        --seed ${AGENT_WALLET_SEED} \
        --genesis-url http://<host_IP_V4_address>/genesis \
        --tails-server-base-url ${TAILS_SERVER_URL} \
        --label ${LABEL} \
        --auto-accept-invites \
        --admin-insecure-mode \
        --log-level info"
    ]
    
     
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ./.postgres:/var/lib/postgresql
    ports:
      - "5432:5432"

  tails-server:
   image: aortz1999/tails-server:latest
   ports:
     - 6543:6543
   volumes:
     - /issuer/tails-files:/tails-files/
   environment:
     GENESIS_URL: "http://<host_IP_V4_address>/genesis"
     TAILS_SERVER_URL: "${TAILS_SERVER_URL}"
   command: >
     tails-server
       --host 0.0.0.0
       --port 6543
       --storage-path /tails-files
       --log-level INFO   
```

This docker compose works when the <host_IP_V4_address> is my own IPv4 address with Von-network running as per "./manage start public_ip_address WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=My Ledger" but does not work when the Von-network is hosted on docker on another machine within the same local network that is started with the same ./manage start command as above.

Thank you so much for your help and time, really appreciate it.
