### ISSUE TITLE
Fix - Intermittently failing integration tests

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-cloudagent-python#2826]
There are a few tests mostly involving revocation and endorsement that fail quite often when resources are being consumed by multiple runs. 

- `features/0586-sign-transaction.feature:229  endorse a schema and cred def transaction, write to the ledger, issue and revoke a credential, with auto endorsing workflow -- @1.1 `
- `features/0586-sign-transaction.feature:236  endorse a schema and cred def transaction, write to the ledger, issue and revoke a credential, with auto endorsing workflow -- @2.2`
- `features/revocation-api.feature:140  Using revocation api, fill registry (need to run with "TAILS_FILE_COUNT": "4" env var) -- @1.1 `
- I think there is another couple tests as well I will try and find and update the list.

These are likely do to timing issues where the objects aren't being written to the ledger in time.

One common error is.

```
7hBob.agent  | Traceback (most recent call last):
7hBob.agent  |   File "/home/aries/aries_cloudagent/wallet/routes.py", line 684, in wallet_set_public_did
7hBob.agent  |     info, attrib_def = await promote_wallet_public_did(
7hBob.agent  |   File "/home/aries/aries_cloudagent/wallet/routes.py", line 771, in promote_wallet_public_did
7hBob.agent  |     raise LookupError(f"DID {did} is not posted to the ledger")
7hBob.agent  | LookupError: DID AqesiGCRdB2fofVcCPxHDq is not posted to the ledger
```

Originating in `demo/features/steps/0586-sign-transaction.py` step line 27 `@when('"{agent_name}" has a DID with role "{did_role}"')`

Other errors are likely similar problems. These never seem to happen locally against a local ledger.

**Comment by jamshale** [comment]
Going to close for now. There are still some tests that fail but the ones described, and that are failing quite often should be fixed.
