### ISSUE TITLE
Issuer cred_def_id randomly corrupted? 

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/aries-cloudagent-python#295]
I am going to do my best to describe this error as it is very odd.

a handful of times now we have experienced an error where a cred_def_id will suddenly become seemingly invalid. What I mean by this is that at some point it seems the cred_def_id is (for lack of a better word) corrupted (at least the cred_def_id seems to be where the issue lies), where the issuer is able to 'send' the credential but the receiver will not be able to accept the offer. Moreover any other agent that has already received a credential with that cred_def_id in the past will no longer be able to create successful proofs with that credential. Here is where it gets very odd as at first we thought that the issue lied in the holders wallet as that is where the error surfaced (in terms of when we finally saw an error code show up), however we found that the issue was solved by having the issuer wallet create a new cred_def_id and re-issue a credential. Holders could accept this and also create valid proofs, but the old cred_def_id just stopped working all together.

Here is the sequence leading to the error message of an issuer sending what we believe to be a credential with a ?corrupted? cred_def_id:

Both issuer and holder are aca-py agents

issuer sends the offer:
```
{'credential_definition_id': 'Qc6xKigXqWoK95PpveGbZg:3:CL:78954:default', 'credential_exchange_id': '9a5ef040-f50f-489e-b845-ceb06236c6ea', 'updated_at': '2019-12-06 19:44:50.808780Z', 'schema_id': 'Qc6xKigXqWoK95PpveGbZg:2:Phone_Number:1.0', 'auto_issue': True, 'created_at': '2019-12-06 19:44:50.808780Z', 'credential_offer': {'cred_def_id': 'Qc6xKigXqWoK95PpveGbZg:3:CL:78954:default', 'nonce': '925046847786474586767186', 'key_correctness_proof': {'xr_cap': [['phone_number', '142313055804377189194476858719844200278553507798863015882707267683270121605182867066354084726633623788231531527844500605024226852639162803652171866388704729642573040931071666571610403437801588522831053349457846524830427592220372660874438785216341425075851735784841403580829031970901706398137596131939387315180498752643407769913210810029757174498505843582142048370422436988664784552366898994942294252404909174012654634157011062898110701145675231294703842376453931748108165957508782551277158260504769032884355510380251803511078616340424075618363439644647927478052592989530058255992654627211586125197112970965443862219076641119939909711732726095579446437783805024653211220400940810129831754198858'], ['master_secret', '360343650620209589602653036726714702104322472483118201147244635334137339328185600957265691524618977124510223331557070100925380912256957070052440568865005579700078684277523989882691406281526854965513770493578435515506206271229861785428297088398967365748767979420994756281809451258552111425089411888861898772529488995792720008952064332751410130628491571684957376825579627857742117989614714981330105923604852191824840009743623772660288259276515914538640007755022730027971737341594484597521029879997849239589310761013743311154036242703056088339112627258214219049146919046880038312369523381757312183733298353708060480150253385794610086649478380262194128227740564170896442770197376320820237200350595']], 'xz_cap': '2214040947841605446663291612917206316241666976829609761439208368600317402403349192941225158490292518180492195045997774686761877220042313085794558134011828071650081875082162529213880032808928593940995734383489773586470909732318335845280119624112490550810494765727370003231731411206281366136987942955903344108704635964267794844496997196015979544727648462295313873146306081264360900635221925655845150682822494270722434939353605651207703462478582034062362656376633964512386585551332078301281812743345342048009927475357423584050841358717078080864475871617633722654608816904705339621758317034701342563127195104665210670479820712601053322448196405932677378727003436649454287544603702410300787880792924', 'c': '109318811144480476036869300929890880822062511194653112451997242996029848511834'}, 'schema_id': 'Qc6xKigXqWoK95PpveGbZg:2:Phone_Number:1.0'}, 'state': 'offer_sent', 'thread_id': '0285746a-c390-43bf-b0b0-c5017b2d2e55', 'connection_id': '25357d44-7bc0-4bb7-b963-e2f3273fd394', 'initiator': 'self', 'credential_values': {'phone_number': '13129344262'}}

```

holder recieves offer as such:
```
{'offer_json': '{"schema_id": "Qc6xKigXqWoK95PpveGbZg:2:Phone_Number:1.0", "cred_def_id": "Qc6xKigXqWoK95PpveGbZg:3:CL:78954:default", "key_correctness_proof": {"c": "109318811144480476036869300929890880822062511194653112451997242996029848511834", "xz_cap": "2214040947841605446663291612917206316241666976829609761439208368600317402403349192941225158490292518180492195045997774686761877220042313085794558134011828071650081875082162529213880032808928593940995734383489773586470909732318335845280119624112490550810494765727370003231731411206281366136987942955903344108704635964267794844496997196015979544727648462295313873146306081264360900635221925655845150682822494270722434939353605651207703462478582034062362656376633964512386585551332078301281812743345342048009927475357423584050841358717078080864475871617633722654608816904705339621758317034701342563127195104665210670479820712601053322448196405932677378727003436649454287544603702410300787880792924", "xr_cap": [["phone_number", "142313055804377189194476858719844200278553507798863015882707267683270121605182867066354084726633623788231531527844500605024226852639162803652171866388704729642573040931071666571610403437801588522831053349457846524830427592220372660874438785216341425075851735784841403580829031970901706398137596131939387315180498752643407769913210810029757174498505843582142048370422436988664784552366898994942294252404909174012654634157011062898110701145675231294703842376453931748108165957508782551277158260504769032884355510380251803511078616340424075618363439644647927478052592989530058255992654627211586125197112970965443862219076641119939909711732726095579446437783805024653211220400940810129831754198858"], ["master_secret", "360343650620209589602653036726714702104322472483118201147244635334137339328185600957265691524618977124510223331557070100925380912256957070052440568865005579700078684277523989882691406281526854965513770493578435515506206271229861785428297088398967365748767979420994756281809451258552111425089411888861898772529488995792720008952064332751410130628491571684957376825579627857742117989614714981330105923604852191824840009743623772660288259276515914538640007755022730027971737341594484597521029879997849239589310761013743311154036242703056088339112627258214219049146919046880038312369523381757312183733298353708060480150253385794610086649478380262194128227740564170896442770197376320820237200350595"]]}, "nonce": "925046847786474586767186"}', '@id': '0285746a-c390-43bf-b0b0-c5017b2d2e55', '@type': 'did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/credential-issuance/0.1/credential-offer'}
```

When trying to accept this received offer and make the request this error surfaces:
```
2019-12-06 19:45:15,415 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aries_cloudagent/messaging/credentials/routes.py", line 446, in credential_exchange_send_request
    credential_exchange_record, connection_record
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aries_cloudagent/messaging/credentials/manager.py", line 179, in create_request
    credential_offer, credential_definition, did
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 60, in create_credential_request
    self.wallet.master_secret_id,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/indy/anoncreds.py", line 734, in prover_create_credential_req
    prover_create_credential_req.cb)
indy.error.CommonInvalidStructure
```

For what it's worth some additional info is that the storage and wallet types being used for both are indy (sql). If any additional information may be helpful to investigate why this may be happening let me know.

**Comment by Alexis-Falquier** [comment]
we have a new lead to a possible source for this and it might not be aca-py related. Closing for now until I can confirm it is indeed aca-py related.
