### ISSUE TITLE
Present proof problem report handler throws exception for OOB proof requests

### ISSUE THREAD

**Issue by loneil** [hyperledger/aries-cloudagent-python#3069]
When an abandoned state triggers on a 2.0 proof (in our BC Gov VCAuth-N ecosystem implementation, when a user declines the proof in their wallet) it invokes the `V20PresProblemReportHandler`. But if this is an OOB proof request with no connection an unhandled exception happens due to `context.connection_record.connection_id`

This was addressed for the 1.0 protocol  here https://github.com/hyperledger/aries-cloudagent-python/pull/2723 but I think should be added for the equivalent problem report handler for 2.0

Error:
```
2024-06-25 15:08:19 2024-06-25 22:08:19,935 aries_cloudagent.core.conductor ERROR Exception in message handler:
2024-06-25 15:08:19 Traceback (most recent call last):
2024-06-25 15:08:19   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
2024-06-25 15:08:19     result = coro.send(None)
2024-06-25 15:08:19   File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/core/dispatcher.py", line 210, in handle_message
2024-06-25 15:08:19     await handler(context, responder)
2024-06-25 15:08:19   File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_problem_report_handler.py", line 32, in handle
2024-06-25 15:08:19     context.connection_record.connection_id,
2024-06-25 15:08:19 AttributeError: 'NoneType' object has no attribute 'connection_id'
2024-06-25 15:08:19 2024-06-25 22:08:19,936 aries_cloudagent.core.conductor ERROR DON'T shutdown on AttributeError 'NoneType' object has no attribute 'connection_id'
2024-06-25 15:08:19 2024-06-25 22:08:19,936 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
2024-06-25 15:08:19 Traceback (most recent call last):
2024-06-25 15:08:19   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
2024-06-25 15:08:19     result = coro.send(None)
2024-06-25 15:08:19   File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/core/dispatcher.py", line 210, in handle_message
2024-06-25 15:08:19     await handler(context, responder)
2024-06-25 15:08:19   File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/present_proof/v2_0/handlers/pres_problem_report_handler.py", line 32, in handle
2024-06-25 15:08:19     context.connection_record.connection_id,
2024-06-25 15:08:19 AttributeError: 'NoneType' object has no attribute 'connection_id'
```

**Comment by loneil** [comment]
Addressed here https://github.com/hyperledger/aries-cloudagent-python/pull/3068

**Comment by loneil** [comment]
@Gavinok @esune as discussed the issue with VCAuth-N erroring on decline with 2.0 proofs.
