### ISSUE TITLE
Exception in Faber ACA-Py instance when executing the credential send

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#419]
Following the instructions (currently being revised) for the OpenAPI/Swagger demo, the issue credential `send` worked (200 response, credential exchange record sent), but there was an exception visible on the Faber terminal session:

```
Faber      | 2020-03-15 21:58:50,926 aries_cloudagent.core.conductor ERROR Exception in message handler:
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/issuer/indy.py", line 193, in create_credential
Faber      |     credential_value = credential_values[attribute]
Faber      | KeyError: 'timestamp'
Faber      | 
Faber      | During handling of the above exception, another exception occurred:
Faber      | 
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 169, in handle_message
Faber      |     await handler(context, responder)
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/handlers/credential_request_handler.py", line 54, in handle
Faber      |     cred_exchange_rec.credential_proposal_dict
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 523, in issue_credential
Faber      |     tails_path,
Faber      |   File "/home/indy/aries_cloudagent/issuer/indy.py", line 197, in create_credential
Faber      |     + f"for the schema attribute '{attribute}'"
Faber      | aries_cloudagent.issuer.base.IssuerError: Provided credential values are missing a value for the schema attribute 'timestamp'
Faber      | 2020-03-15 21:58:50,927 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/issuer/indy.py", line 193, in create_credential
Faber      |     credential_value = credential_values[attribute]
Faber      | KeyError: 'timestamp'
Faber      | 
Faber      | During handling of the above exception, another exception occurred:
Faber      | 
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 169, in handle_message
Faber      |     await handler(context, responder)
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/handlers/credential_request_handler.py", line 54, in handle
Faber      |     cred_exchange_rec.credential_proposal_dict
Faber      |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 523, in issue_credential
Faber      |     tails_path,
Faber      |   File "/home/indy/aries_cloudagent/issuer/indy.py", line 197, in create_credential
Faber      |     + f"for the schema attribute '{attribute}'"
Faber      | aries_cloudagent.issuer.base.IssuerError: Provided credential values are missing a value for the schema attribute 'timestamp'
```

**Comment by swcurran** [comment]
This is happening on the "issue" call and looks to be a problem in ACA-Py. The state of the exchange is in `request-received`, meaning that the `issue` step did not happen.  Trying the `issue` again causes the same error.

**Comment by ianco** [comment]
"Provided credential values are missing a value for the schema attribute"

You need to make sure all of the attributes in the schema are included in the credential.

**Comment by swcurran** [comment]
Got it - the timestamp is indeed missing.  Must have been added when the revocation work went in?  I'll give it a try again.  Thanks.  I had checked the schema, but not very carefully :-).  Missed the extra field.

I'm updating the instructions so will fix from there.

**Comment by swcurran** [comment]
Resolved.  Thanks!
