### ISSUE TITLE
ConnectionManagerError when establishing initial connection between agents on local aca-py

### ISSUE THREAD

**Issue by james-cohen** [hyperledger/aries-cloudagent-python#444]
I've been trying to run agents locally outside of the demo and have been struggling to get them to connect initially. Had no problems running the Faber-Alice demo and was able to customise their web handlers and work correctly with no issue. I have a few ideas of what it might be but don't know how to solve it in any case.

Here is how I've been attempting to run it:

1) Setting up dockerised Von network running on localhost:9000

2) Register two new wallets to the ledger using the seeds
00000000000000000000000000faber1 and 00000000000000000000000000alice1

2) Install aca-py locally and run two terminals running the following scripts: 
```
aca-py start --wallet-type indy --seed 00000000000000000000000000faber1 --wallet-name faberWallet --wallet-key faber123 --genesis-url http://127.0.0.1:9000/genesis -it http 127.0.0.1 8020 -ot http --admin 127.0.0.1 8021 --admin-insecure-mode -e 127.0.0.1:8020 -l FaberAgent
```
```
aca-py start --wallet-type indy --seed 00000000000000000000000000alice1 --wallet-name aliceWallet --wallet-key alice123 --genesis-url http://127.0.0.1:9000/genesis -it http 127.0.0.1 8030 -ot http --admin 127.0.0.1 8031 --admin-insecure-mode -e 127.0.0.1:8030 -l AliceAgent
```

Both launch fine and allow me to confirm the did is on the ledger using GET ledger/did-verkey on the Swagger UI on localhost:8021/8031 respectively.

I then try and follow the same steps as the OpenAPIDemo i.e.
Faber POST connections/create-invitation
Alice POST connections/receive-invitation
Alice POST connections/{id}/accept-invitation (all works fine until this point, Alice connection status becomes 'request')

However, when I try and have Faber POST connections/{id}/accept-request, I get the following error in the terminal:
```
2020-04-02 21:43:52,444 aries_cloudagent.core.dispatcher ERROR Handler error: connections_accept_request
Traceback (most recent call last):
  File "/home/jamesc91/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/connections/routes.py", line 407, in connections_accept_request
    response = await connection_mgr.create_response(connection, my_endpoint)
  File "/home/jamesc91/.local/lib/python3.6/site-packages/aries_cloudagent/protocols/connections/manager.py", line 443, in create_response
    "Connection is not in the request or response state"
aries_cloudagent.protocols.connections.manager.ConnectionManagerError: Connection is not in the request or response state
```
For some reason the state changes are not being communicated back to Faber and his connection statuses are remaining as 'invitation'. I've tried to emulate the attributes of the demo by additionally including
```
--auto-respond-messages --ledger-url http://127.0.0.1:8032/webhooks
```
But it makes no difference. Interestingly, with the webhooks URL included the terminal also produces this error after each POST request:
```
2020-04-02 21:09:57,809 aries_cloudagent.transport.outbound.manager ERROR >>> Posting error: http://127.0.0.1:8022/webhooks/topic/connections/; Re-queue failed message ...
```
I'm assuming because the functions included in the demos e.g. listen_webhooks, handle_connections etc are not present in this case.

Is there anything in the script attributes that I'm setting up incorrectly or missing?

**Comment by andrewwhitehead** [comment]
It's not clear that the Faber agent is receiving any requests from Alice at all. You could try increasing the log level for one or both of the agents using `--log-level debug`. What is it you're trying to do ultimately?

**Comment by james-cohen** [comment]
The aim is to set my own agents up independent of the demo pre-configurations in order to develop a specific application for credential distribution.

Turned log-level debug on and acts in the same way as previously described. However, within a few seconds both agents show the same log:

```
2020-04-08 22:46:59,502 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:489 | socket dropped
2020-04-08 22:46:59,502 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:489 | socket dropped
2020-04-08 22:46:59,503 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:489 | socket dropped
2020-04-08 22:46:59,503 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:489 | socket dropped
2020-04-08 22:46:59,503 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:396 | context dropped
2020-04-08 22:46:59,794 aries_cloudagent.ledger.indy DEBUG Closing pool ledger after timeout
2020-04-08 22:46:59,794 indy.pool DEBUG close_pool_ledger: >>> config_name: 3
2020-04-08 22:46:59,794 indy.pool DEBUG close_pool_ledger: Creating callback
2020-04-08 22:46:59,795 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
2020-04-08 22:46:59,795 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x7f094c35d750>
2020-04-08 22:46:59,795 indy.libindy DEBUG do_call: >>> name: indy_close_pool_ledger, args: (c_int(3), <CFunctionType object at 0x7f094c35d750>)
2020-04-08 22:46:59,795 indy.libindy DEBUG do_call: Function indy_close_pool_ledger returned err: 0
2020-04-08 22:46:59,795 indy.libindy DEBUG do_call: <<< <Future pending>
2020-04-08 22:46:59,796 indy.libindy.native.indy.commands DEBUG 	src/commands/mod.rs:142 | PoolCommand command received
2020-04-08 22:46:59,796 indy.libindy.native.pool_command_executor DEBUG 	src/commands/pool.rs:95 | Close command received
2020-04-08 22:46:59,796 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:189 | close >>> handle: 3
2020-04-08 22:46:59,796 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:749 | Drop started
2020-04-08 22:46:59,797 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:757 | Drop wait worker
2020-04-08 22:46:59,797 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:489 | socket dropped
2020-04-08 22:46:59,798 indy.libindy.native.indy.services.pool.pool INFO 	src/services/pool/pool.rs:760 | Drop finished
2020-04-08 22:46:59,798 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:489 | socket dropped
2020-04-08 22:46:59,798 indy.libindy.native.zmq DEBUG 	/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.9.2/src/lib.rs:396 | context dropped
2020-04-08 22:46:59,799 indy.libindy.native.indy.commands.pool DEBUG 	src/commands/pool.rs:203 | close <<<
2020-04-08 22:46:59,799 indy.libindy.native.indy.commands DEBUG 	src/commands/mod.rs:142 | PoolCommand command received
2020-04-08 22:46:59,799 indy.libindy.native.pool_command_executor DEBUG 	src/commands/pool.rs:99 | CloseAck command received
2020-04-08 22:46:59,799 indy.libindy DEBUG _indy_callback: >>> command_handle: 31, err , args: ()
2020-04-08 22:46:59,799 indy.libindy DEBUG _indy_callback: <<<
2020-04-08 22:46:59,800 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 31, err , args: ()
2020-04-08 22:46:59,800 indy.libindy DEBUG _indy_loop_callback: Function returned None
2020-04-08 22:46:59,800 indy.libindy DEBUG _indy_loop_callback <<<
2020-04-08 22:46:59,801 indy.pool DEBUG close_pool_ledger: <<< res: None

```

Does this help explain anything?

**Comment by andrewwhitehead** [comment]
That's all ledger-related and normal, there's a few seconds of keepalive for the ledger connection.

I just noticed that your endpoints don't have `http://` in front of them, that might make a difference.

**Comment by james-cohen** [comment]
Ah, embarrasingly it did make a difference... After the same process both agents status' are at 'response' but not progressing to 'active' Interestingly they can both send messages to each other now even though their connection status isn't set as 'active'. Am I missing a step still?

**Comment by andrewwhitehead** [comment]
The connection status should be automatically promoted to active after any incoming agent message. If you reload the connections list and it's not, that's probably a bug.

**Comment by swcurran** [comment]
My favourite complaint about the Connections protocol.  There is no "ACK" after the "response" message, so there is no way to know if the connection is complete.  Sigh.

We're going to fix that with DID-Exchange!

**Comment by james-cohen** [comment]
> The connection status should be automatically promoted to active after any incoming agent message. If you reload the connections list and it's not, that's probably a bug.

Indeed it has. Many thanks for your help

**Comment by james-cohen** [comment]
Sorry, new issue on this same topic!

I then tried the same setup with Dockerized agents and ran into the same error but this time with a different setup:

```
PORTS="8020:8020 8021:8021" ./scripts/run_docker start --seed 00000000000000000000000000faber1 \
--wallet-type indy --wallet-name FaberWallet --wallet-key faber123 \
--genesis-url http://greenlight.bcovrin.vonx.io/genesis \
-it http 0.0.0.0 8020 -ot http --admin 0.0.0.0 8021 -e http://0.0.0.0:8020 \
--admin-insecure-mode -l FaberAgent
```
and
```
PORTS="8030:8030 8031:8031" ./scripts/run_docker start --seed 00000000000000000000000000alice1 \
--wallet-type indy --wallet-name AliceWallet --wallet-key alice123 \
--genesis-url http://greenlight.bcovrin.vonx.io/genesis \
-it http 0.0.0.0 8030 -ot http --admin 0.0.0.0 8031 -e http://0.0.0.0:8030 \
--admin-insecure-mode -l AliceAgent
```

This creates the same error as before when trying to accept the invitation:
```
2020-04-18 09:37:09,025 aries_cloudagent.transport.outbound.manager ERROR >>> Posting error: http://0.0.0.0:8020; Re-queue failed message ...
```

This time I managed to partially solve the issue by changing the endpoint to my local IP address, which now allows the status to go to active for both agents.
```
-it http 0.0.0.0 8030 -ot http --admin 0.0.0.0 8031 -e http://192.XXX.X.XX:8030
```
But now if I send a message, it doesn't appear in the other agent's console even though there is a 200 response. This occurs regardless of which agent is sending the message. So where is the message going...?

I'm sure this is a Docker setup issue; using 127.0.0.1 for inbound/outbound transports blocks access to the Swagger API and using local IP isn't allowed at all.

**Comment by james-cohen** [comment]
Apologies, just realised that the endpoint needs to be the Docker bridge network. Same issue persists though with endpoint set to 172.17.0.1 although now this error appears during the connection setup on both agents

```
2020-04-18 11:04:13,548 aries_cloudagent.core.dispatcher ERROR Handler error: StaticResource._handle
concurrent.futures._base.CancelledError: Task was cancelled
```

Is this to do with no webhooks being established?

**Comment by andrewwhitehead** [comment]
There is no default behaviour when receiving a BasicMessage (what the send-message endpoint sends). The Alice and Faber agents have controllers that receive the webhook for that message and print it out, your controller would need to do the same.
