### ISSUE TITLE
NotImplementedError when running aca-py start on windows (add_signal_handler)

### ISSUE THREAD

**Issue by Riff451** [hyperledger/aries-cloudagent-python#489]
Hi all, I've installed the agent locally with pip and I'm now trying to run it with this command. I'm not sure this is the correct command as I've just started learning about the project. I'm using the genesis file for the Sovrin BuilderNet.

```shell
aca-py start \
--admin 0.0.0.0 8080 \
--admin-insecure-mode \
--storage-type basic \
--genesis-file pool_transactions_builder_genesis.txn \
--log-file agent-logs.txt \
--log-level info \
-it http 0.0.0.0 8000 \
-ot http \
--wallet-key aA123456 \
--wallet-name sampleWallet \
--wallet-type basic \
--wallet-storage-type basic
```

The error I've got is:

```
Traceback (most recent call last):
  File "/Python/Python38-32/Scripts/aca-py", line 49, in <module>
    run_command(command, args)
  File "\python\python38-32\lib\site-packages\aries_cloudagent\commands\__init__.py", line 35, in run_command
    module.execute(argv)
  File "\python\python38-32\lib\site-packages\aries_cloudagent\commands\start.py", line 68, in execute
    run_loop(start_app(conductor), shutdown_app(conductor))
  File "\python\python38-32\lib\site-packages\aries_cloudagent\commands\start.py", line 98, in run_loop
    loop.add_signal_handler(signal.SIGTERM, cleanup)
  File "\python\python38-32\lib\asyncio\events.py", line 536, in add_signal_handler
    raise NotImplementedError
NotImplementedError
sys:1: RuntimeWarning: coroutine 'run_loop.<locals>.done' was never awaited
sys:1: RuntimeWarning: coroutine 'shutdown_app' was never awaited
sys:1: RuntimeWarning: coroutine 'start_app' was never awaited
```
Apparently in Windows the `loop.add_signal_handler()` is not available:
https://docs.python.org/3/library/asyncio-platforms.html#windows

My python version is 3.8.2 and I'm running the command from Git Bash.

Am I doing something wrong?
Thank you!

**Comment by Riff451** [comment]
Hi, I realized that this is running on Windows only inside a docker linux container. So... yeah, that was a stupid question. Sorry about that :)
