### ISSUE TITLE
Internal Server Error when running the routing messages demo

### ISSUE THREAD

**Issue by jceb** [hyperledger/aries-cloudagent-python#512]
git version: 2e874b905d8626151ec61c02c9a7b687174c8849

I ran the performance demo with the following settings and it crashed with an internal server error. The demo runs successfully without the `--routing` switch:

```
➤ ./run_demo performance --routing --timing --count 100
Preparing agent image...
sha256:a1ca3446bee6bc8dbe25a54c10721c11ce593dd9369af42825a09dfaaf680b21
10.199.0.1
Starting performance...
Faber      | Registering Faber with seed d_000000000000000000000000914339
Faber      | Got DID: F5McjQbNKh8RhF6t6b73As
Router     | Registering Router with seed d_000000000000000000000000706677
Router     | Got DID: WUdfgJgfmY2Ar2xBhfwAej
Router     |
Router     | ::::::::::::::::::::::::::::::::::::::::::::::
Router     | :: Router                                   ::
Router     | ::                                          ::
Router     | ::                                          ::
Router     | :: Inbound Transports:                      ::
Router     | ::                                          ::
Router     | ::   - http://0.0.0.0:8036                  ::
Router     | ::                                          ::
Router     | :: Outbound Transports:                     ::
Router     | ::                                          ::
Router     | ::   - http                                 ::
Router     | ::   - https                                ::
Router     | ::                                          ::
Router     | :: Public DID Information:                  ::
Router     | ::                                          ::
Router     | ::   - DID: WUdfgJgfmY2Ar2xBhfwAej          ::
Router     | ::                                          ::
Router     | :: Administration API:                      ::
Router     | ::                                          ::
Router     | ::   - http://0.0.0.0:8037                  ::
Router     | ::                                          ::
Router     | ::                               ver: 0.5.1 ::
Router     | ::::::::::::::::::::::::::::::::::::::::::::::
Router     |
Router     | Listening...
Router     |
Alice      |
Alice      | ::::::::::::::::::::::::::::::::::::::::::::::
Alice      | :: Alice                                    ::
Alice      | ::                                          ::
Alice      | ::                                          ::
Alice      | :: Inbound Transports:                      ::
Alice      | ::                                          ::
Alice      | ::   - http://0.0.0.0:8030                  ::
Alice      | ::                                          ::
Alice      | :: Outbound Transports:                     ::
Alice      | ::                                          ::
Alice      | ::   - http                                 ::
Alice      | ::   - https                                ::
Alice      | ::                                          ::
Alice      | :: Administration API:                      ::
Alice      | ::                                          ::
Alice      | ::   - http://0.0.0.0:8031                  ::
Alice      | ::                                          ::
Alice      | ::                               ver: 0.5.1 ::
Alice      | ::::::::::::::::::::::::::::::::::::::::::::::
Alice      |
Alice      | Listening...
Alice      |
Faber      |
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      | :: Faber                                    ::
Faber      | ::                                          ::
Faber      | ::                                          ::
Faber      | :: Inbound Transports:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8033                  ::
Faber      | ::                                          ::
Faber      | :: Outbound Transports:                     ::
Faber      | ::                                          ::
Faber      | ::   - http                                 ::
Faber      | ::   - https                                ::
Faber      | ::                                          ::
Faber      | :: Public DID Information:                  ::
Faber      | ::                                          ::
Faber      | ::   - DID: F5McjQbNKh8RhF6t6b73As          ::
Faber      | ::                                          ::
Faber      | :: Administration API:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8034                  ::
Faber      | ::                                          ::
Faber      | ::                               ver: 0.5.1 ::
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      |
Faber      | Listening...
Faber      |
Startup duration: 12.09s
Faber      | Publishing test schema
Faber      | Schema ID: F5McjQbNKh8RhF6t6b73As:2:degree schema:76.7.38
Faber      | Publishing test credential definition
Faber      | 2020-05-19 13:08:41,747 aries_cloudagent.core.dispatcher ERROR Handler error: credential_definitions_send_credential_definition
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/messaging/credential_definitions/routes.py", line 134, in credential_definitions_send_credential_definition
Faber      | Error during POST /credential-definitions: 500, message='Internal Server Error', url=URL('http://10.199.0.1:8034/credential-definitions')
Faber      |     support_revocation=support_revocation,
Alice      |
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 568, increate_and_send_credential_definition
Alice      | Shutting down
Faber      |     assert wallet_cred_def["value"] == ledger_cred_def["value"]
Faber      | TypeError: 'NoneType' object is not subscriptable
Faber      | 2020-05-19 13:08:41,749 aiohttp.server ERROR Error handling request
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
Faber      |     resp = await task
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
Faber      |     resp = await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 192, in apply_limiter
Faber      |     return await task
Faber      |   File "/home/indy/aries_cloudagent/messaging/credential_definitions/routes.py", line 134, in credential_definitions_send_credential_definition
Faber      |     support_revocation=support_revocation,
Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 568, in create_and_send_credential_definition
Faber      |     assert wallet_cred_def["value"] == ledger_cred_def["value"]
Faber      | TypeError: 'NoneType' object is not subscriptable
Alice      | Exited with return code 0
Faber      |
Faber      | Shutting down
Faber      | Exited with return code 0
Router     |
Router     | Shutting down
Router     | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/performance.py", line 548, in <module>
    args.count,
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/performance.py", line 286, in main
    await faber.publish_defs(revoc)
  File "/home/indy/demo/runners/performance.py", line 195, in publish_defs
    "/credential-definitions", credential_definition_body
  File "/home/indy/demo/runners/support/agent.py", line 518, in admin_POST
    response = await self.admin_request("POST", path, data, text, params)
  File "/home/indy/demo/runners/support/agent.py", line 486, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 946, in raise_f
or_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://10.199.0.1:8034
/credential-definitions')
```

**Comment by swcurran** [comment]
@andrewwhitehead -- please take a look at this one.

**Comment by andrewwhitehead** [comment]
I believe this was a temporary issue that is resolved now
