### ISSUE TITLE
Internal server error when running without --endpoint

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#519]
When running the software without an endpoint configured (no `--endpoint` option passed on startup), an unhelpful error is produced when trying to accept an invitation.

The following command is used to run the server:
`PORTS="5000:5000" ./scripts/run_docker start -it http 0.0.0.0 8000 -ot http --admin 0.0.0.0 5000 --admin-insecure-mode --seed 255h235iu2yg354uiyg234i5iu2yg54i --wallet-type indy --genesis-url http://test.bcovrin.vonx.io/genesis`

First, create an invitation by calling `POST` `/connections/create-invitation` and receive something like:

```json
  "connection_id": "dd7c48e4-963c-4769-9dd5-aabadf100c70",
  "invitation": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
    "@id": "23b09fbe-5b93-47fe-8b7c-1a45d4ef9fdb",
    "label": "Aries Cloud Agent",
    "recipientKeys": [
      "FCK6EMemHRG7eJXBCCdgH51HAtqoTDjRXGM4Jc9s4nbG"
    ]
  },
  "invitation_url": "?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMjNiMDlmYmUtNWI5My00N2ZlLThiN2MtMWE0NWQ0ZWY5ZmRiIiwgImxhYmVsIjogIkFyaWVzIENsb3VkIEFnZW50IiwgInJlY2lwaWVudEtleXMiOiBbIkZDSzZFTWVtSFJHN2VKWEJDQ2RnSDUxSEF0cW9URGpSWEdNNEpjOXM0bmJHIl19"
}
```

Make a request to `POST` `​/connections​/receive-invitation` and include the `invitation` block from the call above in the body.

The response is:

```
500 Internal Server Error

Server got itself in trouble
```

And the following error is produced in the logs:

```
2020-05-21 17:37:33,393 aries_cloudagent.messaging.models.base ERROR ConnectionInvitation message validation error:
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/messaging/models/base.py", line 127, in deserialize
    return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {('did', 'recipientKeys', 'serviceEndpoint'): ['Missing required field(s)']}
2020-05-21 17:37:33,397 aries_cloudagent.core.dispatcher ERROR Handler error: connections_receive_invitation
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/messaging/models/base.py", line 127, in deserialize
    return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {('did', 'recipientKeys', 'serviceEndpoint'): ['Missing required field(s)']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 336, in connections_receive_invitation
    invitation = ConnectionInvitation.deserialize(invitation_json)
  File "/home/indy/aries_cloudagent/messaging/models/base.py", line 130, in deserialize
    raise BaseModelError(f"{cls.__name__} schema validation failed") from e
aries_cloudagent.messaging.models.base.BaseModelError: ConnectionInvitation schema validation failed
2020-05-21 17:37:33,398 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/messaging/models/base.py", line 127, in deserialize
    return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {('did', 'recipientKeys', 'serviceEndpoint'): ['Missing required field(s)']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 192, in apply_limiter
    return await task
  File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 336, in connections_receive_invitation
    invitation = ConnectionInvitation.deserialize(invitation_json)
  File "/home/indy/aries_cloudagent/messaging/models/base.py", line 130, in deserialize
    raise BaseModelError(f"{cls.__name__} schema validation failed") from e
aries_cloudagent.messaging.models.base.BaseModelError: ConnectionInvitation schema validation failed
```
We should return a more helpful error to the user.

**Comment by shaangill025** [comment]
With version 0.5.6, --endpoint or -e is a required startup parameter. Unable to replicate the error.

`Traceback (most recent call last):
  File "/home/indy/bin/aca-py", line 49, in <module>
    run_command(command, args)
  File "/home/indy/aries_cloudagent/commands/__init__.py", line 34, in run_command
    module.execute(argv)
  File "/home/indy/aries_cloudagent/commands/start.py", line 47, in execute
    settings = get_settings(args)
  File "/home/indy/aries_cloudagent/config/argparse.py", line 82, in get_settings
    raise e
  File "/home/indy/aries_cloudagent/config/argparse.py", line 79, in get_settings
    settings.update(group.get_settings(args))
  File "/home/indy/aries_cloudagent/config/argparse.py", line 468, in get_settings
    raise ArgsParseError("-e/--endpoint is required")
aries_cloudagent.config.error.ArgsParseError: -e/--endpoint is required`

**Comment by swcurran** [comment]
So we can close?  I'll assume so -- please reopen if necessary.
