### ISSUE TITLE
500 Error when store credential offer into wallet

### ISSUE THREAD

**Issue by lijiachuan1982** [hyperledger/aries-cloudagent-python#530]
Hi all, I encountered one error when I tried to store the new issued credential(generated via /issue-credential/send) into the wallet via /issue-credential/records/{cred_ex_id}/store, below is the error in log:

```2020-05-27 14:25:01,336 aiohttp.access INFO 175.167.154.193 [27/May/2020:14:25:01 +0000] "OPTIONS /issue-credential/records/92a447b6-ad80-44b2-a5b1-8b0071ea4c21/store HTTP/1.1" 200 335 "http://localhost:4200/credentials/offers" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
2020-05-27 14:25:01,817 aries_cloudagent.core.dispatcher ERROR Handler error: credential_exchange_store
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 762, in credential_exchange_store
    V10CredentialExchange.STATE_CREDENTIAL_RECEIVED
AssertionError
2020-05-27 14:25:01,818 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 192, in apply_limiter
    return await task
  File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 762, in credential_exchange_store
    V10CredentialExchange.STATE_CREDENTIAL_RECEIVED
AssertionError
2020-05-27 14:25:01,818 aiohttp.access INFO 175.167.154.193 [27/May/2020:14:25:01 +0000] "POST /issue-credential/records/92a447b6-ad80-44b2-a5b1-8b0071ea4c21/store HTTP/1.1" 500 369 "http://localhost:4200/credentials/offers" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"```

**Comment by mahendra-panchal** [comment]
Hi @lijiachuan1982,

You passing wrong `credential_exchange_id`

You have to pass `credential_exchange_id` received from `${AGENT_URL_DOCKER}/issue-credential/records/${credential_exchange_id}/send-request`.

Basically, I am tracing credential_exchange_id, when my webhook detect `state=credential_received`. then able to store the credential into wallet succesfully.

**Comment by lijiachuan1982** [comment]
hi @mahendra-panchal , thanks for your reply, firstly from the holder side, I used "/issue-credential/records" to query all of current available received credentials, then there is only the one offer received, and I used the credential_exchange_id `"credential_exchange_id": "f3ecc01c-e8b3-47e7-82e2-e3779d4b91b2"` in that object, and post it to holder's "http://OpenAPI/issue-credential/records/f3ecc01c-e8b3-47e7-82e2-e3779d4b91b2/store", whether this is correct steps?
