### ISSUE TITLE
Pool error:  "Pool with the same name is already opened"

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#538]
Agent gets into a state and fails with this error on every request.

Expectation:  Agent should be able to recover from this error.

2020-06-01 18:20:53,140 indy.libindy WARNING _indy_loop_callback: Function returned error 
2020-06-01 18:20:53,140 aries_cloudagent.core.dispatcher ERROR Handler error: credential_exchange_store
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 130, in open
    self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
    open_pool_ledger.cb)
indy.error.PoolLedgerInvalidPoolHandle

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 728, in credential_exchange_store
    credential_exchange_record, credential_id
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 614, in store_credential
    async with ledger:
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 179, in __aenter__
    await self._context_open()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 148, in _context_open
    await self.open()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 130, in open
    self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/error.py", line 27, in __exit__
    ) from err_value
aries_cloudagent.ledger.error.LedgerConfigError: Exception when opening pool ledger: Error: Invalid pool handle
  Caused by: Pool with the same name is already opened

**Comment by sklump** [comment]
I can look into it tomorrow morning

**Comment by sklump** [comment]
Could some external code run this call inside an `async with ledger:` block?

**Comment by swcurran** [comment]
Closing -- please reopen if necessary.

**Comment by srbms23** [comment]
Hi @ianco,

I get the same error:
`400: Exception opening pool ledger default: Error: Invalid pool handle. Caused by: Pool with the same name is already opened. PoolLedgerInvalidPoolHandle.`
once I use `/present-proof/records/{pres_ex_id}/verify-presentation`.

Is there a way to recover agent from this error without restarting it?
In case that I have to restart the agent I would lose all my wallets and data.. 

Please let me know if there is a way to do that :)

**Comment by FlixKo** [comment]
We get the same Error also when using `/issue-credential/send`

**Comment by swcurran** [comment]
@ianco @andrewwhitehead -- can you please connect with the folks here on this issue?  Thanks.

**Comment by DaevMithran** [comment]
Facing the same issue, additionally when a ledger is not available for sometime, and any api which queries data from the ledger returns `500 Internal server error` and now when I use any other api we get `503: Shutdown in progress`
