### ISSUE TITLE
ACA-PY provide appropriate handling if agent API method is called twice with same parameters

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#557]
Due to the retry logic in aca-py, agents are getting called multiple times with the same parameters/protocol exchange, even if work has been completed on a previous call.  This is resulting in 500 server error and spurious error messages.

Examples are provided in comments.

Ensure that these situations result in problem reports (if unrecoverable errors).

**Comment by ianco** [comment]
Example stack trace:

2020-06-11 17:42:27,094 aries_cloudagent.core.dispatcher ERROR Handler error: credential_exchange_store
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 709, in credential_exchange_store
    V10CredentialExchange.STATE_CREDENTIAL_RECEIVED
AssertionError
2020-06-11 17:42:27,097 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 174, in check_token
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 187, in apply_limiter
    return await task
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 709, in credential_exchange_store
    V10CredentialExchange.STATE_CREDENTIAL_RECEIVED
AssertionError

**Comment by ianco** [comment]
Example stack trace:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 704, in credential_exchange_store
    context, credential_exchange_id
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 213, in retrieve_by_id
    cls.RECORD_TYPE, record_id, {"retrieveTags": False}
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/storage/indy.py", line 108, in get_record
    raise StorageNotFoundError("Record not found: {}".format(record_id))
aries_cloudagent.storage.error.StorageNotFoundError: Record not found: 4910da54-ebec-44c0-83b8-41ffa9734d4f
2020-06-11 18:41:31,372 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/storage/indy.py", line 104, in get_record
    self._wallet.handle, record_type, record_id, options_json
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/non_secrets.py", line 319, in get_wallet_record
    get_wallet_record.cb)
indy.error.WalletItemNotFound

**Comment by sklump** [comment]
Would it be possible to get a stack trace with current master? This code has changed significantly over the last couple of weeks.

**Comment by sklump** [comment]
I don't know how it's possible to know what events are due to glitches in the matrix and what are events due to having been called twice.

I could generate problem reports on all internal-looking errors - would that address the issue?

**Comment by swcurran** [comment]
Closing this issue. It may come up again as we work on Persistent Queues, but for now we'll leave it.
