### ISSUE TITLE
Setting `wallet_scheme` for postgres storage not working correctly

### ISSUE THREAD

**Issue by msembinelli** [hyperledger/aries-cloudagent-python#568]
Hi All,

## Background

I am currently using the `bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1` dockerhub image to stand up an instance of aries cloudagent. My understanding is the version of libindy/indysdk that comes with this image is version 1.14.0.

As a result of our infrastructure with postgres, we cannot use the default postgres scheme that creates a database per wallet, so we opted for `MultiWalletSingleTable`. Our other reason is that this particular strategy will skip the database/schema creation if it already exists and is set up (We have a scenario where we will be provisioning the postgres wallet DB before spinning up the cloud agents to improve security and not give the postgres user database creation roles).

Based off what I can see in the 1.14.0 indy sdk, using this strategy will attempt to create a database called `wallets` on the postgres instance (the `database_name` parameter in the config does not exist until indy sdk 1.15.0). 

```
// _WALLETS_DB === 'wallets'
 let url_base = PostgresStorageType::_admin_postgres_url(&config, &credentials);
        let url = PostgresStorageType::_postgres_url(_WALLETS_DB, &config, &credentials);

        let conn = postgres::Connection::connect(&url_base[..], postgres::TlsMode::None)?;

        if let Err(error) = conn.execute(&_CREATE_WALLETS_DATABASE, &[]) {
            if error.code() != Some(&postgres::error::DUPLICATE_DATABASE) {
                conn.finish()?;
                return Err(WalletStorageError::IOError(format!("Error occurred while creating the database: {}", error)))
            } else {
                // if database already exists, assume tables are created already and return
                conn.finish()?;
                return Ok(());
            }
        }
        conn.finish()?;
```

If the database already exists, the code assumes the tables/schemas are created already. If the database doesn't exist the `CREATE_MULTI_SCHEMA` query will be run to set up the tables/schemas within the database. 

```
        let conn = match postgres::Connection::connect(&url[..], postgres::TlsMode::None) {
            Ok(conn) => conn,
            Err(error) => {
                return Err(WalletStorageError::IOError(format!("Error occurred while connecting to wallet schema: {}", error)));
            }
        };

        for sql in &_CREATE_SCHEMA_MULTI {
            if let Err(error) = conn.execute(sql, &[]) {
                conn.finish()?;
                return Err(WalletStorageError::IOError(format!("Error occurred while creating wallet schema: {}", error)));
            }
        }
        conn.finish()?;
        Ok(())
```

## The Problem

Any time we try to set the wallet scheme, the cloud agent fails to start up and returns:
```
E 2020-06-19T22:22:14.452583499Z 2020-06-19 22:22:14,452 aries_cloudagent.wallet.provider INFO Opening wallet type: indy
 
E 2020-06-19T22:22:14.461212446Z 2020-06-19 22:22:14,461 aries_cloudagent.wallet.plugin INFO Initializing postgres wallet
 
E 2020-06-19T22:22:14.478151798Z 2020-06-19 22:22:14,476 aries_cloudagent.wallet.plugin ERROR **Error unable to configure postgres stg: 210**
```

If we remove `wallet_scheme`, the agent successfully starts up and creates the wallet database.

Error code 210 as far as I know is a really generic `WalletStorageError`, so that does not help narrow down the issue.

## My Configuration

Our wallet storage config is as follows:
```
// Unstringified
{
   "url":"localhost:5432",
   "wallet_scheme":"MultiWalletSingleTable"
}
```
```
// Stringified for command line input
--wallet-storage-config "{\"url\":\"localhost:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}"
```

We have `--wallet_storage_creds` properly passing and include all 4 parametes (`account`, `password`, `admin_account`, and `admin_password`) as this was verified with the default strategy already.

## Plans Going Forward & Questions

In version 1.14.0 of the indy sdk, the postgres plugin seems to have very little if any logging. As a secondary issue on top of that, I'm fairly certain that `bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1` (based off of von-image base image) does not turn on `RUST_LOG`, making it really hard to tell where its failing.

I would love to turn on `RUST_LOG` but I assume I would need access to the von-image py36 dockerfile so that I could rebuild the images/library myself with the logging turned on. However I can't seem to locate any up to date dockerfiles used to create the base von image that contains indy.

I have tried setting `RUST_LOG` as an environment variable on the container but that also does not work.

- Does anyone have a link to/can provide the Dockerfile for `bcgovimages/von-image:py36-1.14-1` ? Or is there a debug image floating around that has rust logging enabled?
- Is there a future release of the cloud agent container planned soon, which pulls in libindy 1.15.0? The `database_name` feature is something I will absolutely need after this issue is solved.
- Can anyone confirm that `wallet_scheme` is actually working correctly? Is there an easy way for me to run the test with a local postgres instance?
- Its possible that it could be failing at the database creation stage since the error code returned might not be `DUPLICATE_DATABASE` but I have no idea if this is true or not based on the lack of logging

**Comment by WadeBarnes** [comment]
The source for `von-image` is here; https://github.com/PSPC-SPAC-buyandsell/von-image.  There is a link to the source on the Docker Hub page; https://hub.docker.com/r/bcgovimages/von-image.

The source for `` is here; https://github.com/bcgov/aries-cloudagent-container.  Similarily there is a link to the source on the Docker Hub page; https://hub.docker.com/r/bcgovimages/aries-cloudagent.

Examples of fully functional postgres wallet configurations can be found in the Docker configurations here;
- https://github.com/bcgov/aries-vcr
  - https://github.com/bcgov/aries-vcr/blob/master/docker/docker-compose.yml#L156

- https://github.com/bcgov/aries-vcr-issuer-controller
  - https://github.com/bcgov/aries-vcr-issuer-controller/blob/master/docker/docker-compose.yml#L72

The `aries-vcr` example also shows how to set the log levels for the agent.

**Comment by msembinelli** [comment]
Hi @WadeBarnes Thanks for the info, I'll take a look through and write back if I have any issues.

I did end up testing a local deployment and got everything working so it may have something to do with postgres roles/permissions of the admin/db users. I was able to get tracing turned on for the postgres plugin so I'm able to better debug it now.

**Comment by msembinelli** [comment]
Closing this as I solved my own issue.

Aries cloud agent is expecting escaped JSON strings, which can be a huge pita if you are using kubernetes k8 yaml files. In the end I had to use a configmap or a secret resource to properly pass the JSON, rather than defining it in the k8 file itself.
```
"{\"url\":\"localhost:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}"
```

The second larger issue in my opinion, is that the plugin requires that you have an admin DB user with CREATEDB permissions. I think in many scenarios, you would not want to have a db user with this permission for security reasons, and you would want to pre-provision the wallet DB. This is currently unsupported as the code is checking for `DUPLICATE_DATABASE` error return, however if the user does not have `CREATEDB` then it will return a different error code. This is something I will take up on the indy sdk issue side.

**Comment by andrewwhitehead** [comment]
@ianco

**Comment by WadeBarnes** [comment]
@msembinelli, If I had of known you were using k8s, I would have pointed you at our OpenShift deployment configurations;
- https://github.com/bcgov/orgbook-configurations/blob/master/openshift/templates/agent/agent-deploy.yaml
- https://github.com/bcgov/von-bc-registries-agent-configurations/blob/master/openshift/templates/agent/agent-deploy.yaml

**Comment by Sarangc1203** [comment]
I was trying to set up my wallet using postgres by:

```
sudo PORTS="11020:11020 11021:11021" ./scripts/run_docker start \
    --admin 0.0.0.0 11021 --admin-insecure-mode \
    --endpoint http://10.0.2.15:11020 \
    --genesis-url http://localhost/genesis \
    --ledger-pool-name sandbox \
    --inbound-transport http 0.0.0.0 11020 \
    --outbound-transport http \
    --label Faber \
    --log-level debug \
    --storage-type indy \
    --wallet-type indy \
    --wallet-storage-type postgres_storage \
    --wallet-storage-config "{\"url\":\"localhost:5432\",\"wallet_scheme\":\"DatabasePerWallet\"}" \
    --wallet-storage-creds "{\"account\":\"postgres\",\"password\":\"mysecretpassword\",\"admin_account\":\"postgres\",\"admin_password\":\"mysecretpassword\"}" \
    --wallet-name my_wallet \
    --wallet-key my_key \
```

But I keep getting this error: `IO error during storage operation: IO error`.
My complete logs are:
```
Sending build context to Docker daemon  18.03MB



Step 1/11 : FROM bcgovimages/von-image:py36-1.15-0

 ---> 00027bd43124

Step 2/11 : ENV ENABLE_PTVSD 0

 ---> Using cache

 ---> a27128eeda55

Step 3/11 : ADD requirements*.txt ./

 ---> Using cache

 ---> 0d9a1fcbe8a9

Step 4/11 : RUN pip3 install --no-cache-dir -r requirements.txt -r requirements.dev.txt

 ---> Using cache

 ---> bf6805ab868d

Step 5/11 : ADD aries_cloudagent ./aries_cloudagent

 ---> Using cache

 ---> 14d75cc347cd

Step 6/11 : ADD bin ./bin

 ---> Using cache

 ---> 3cd19b40d6c6

Step 7/11 : ADD README.md ./

 ---> Using cache

 ---> 0406d273a892

Step 8/11 : ADD setup.py ./

 ---> Using cache

 ---> 0d1592cc07d5

Step 9/11 : RUN pip3 install --no-cache-dir -e .

 ---> Using cache

 ---> 482b7d745cba

Step 10/11 : RUN mkdir logs && chown -R indy:indy logs && chmod -R ug+rw logs

 ---> Using cache

 ---> b9b30d71950d

Step 11/11 : ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]

 ---> Using cache

 ---> 13c589140782

Successfully built 13c589140782

Successfully tagged aries-cloudagent-run:latest

2020-07-18 19:12:53,816 asyncio DEBUG Using selector: EpollSelector

2020-07-18 19:12:53,819 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.out_of_band

2020-07-18 19:12:53,822 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.trustping

2020-07-18 19:12:53,823 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.routing

2020-07-18 19:12:53,824 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.connections

2020-07-18 19:12:53,826 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.issue_credential

2020-07-18 19:12:53,828 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.present_proof

2020-07-18 19:12:53,830 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.problem_report

2020-07-18 19:12:53,832 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.discovery

2020-07-18 19:12:53,833 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.introduction

2020-07-18 19:12:53,835 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.basicmessage

2020-07-18 19:12:53,836 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.protocols.actionmenu

2020-07-18 19:12:53,837 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.holder

2020-07-18 19:12:53,848 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.ledger

2020-07-18 19:12:53,877 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.messaging.credential_definitions

2020-07-18 19:12:53,881 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.messaging.schemas

2020-07-18 19:12:53,886 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.revocation

2020-07-18 19:12:53,899 aries_cloudagent.core.plugin_registry DEBUG Loaded module: aries_cloudagent.wallet

2020-07-18 19:12:53,918 aries_cloudagent.wallet.provider INFO Opening wallet type: indy

2020-07-18 19:12:53,918 aries_cloudagent.wallet.plugin INFO Checking input postgres storage_config and storage_creds arguments

2020-07-18 19:12:53,918 aries_cloudagent.wallet.plugin INFO Initializing postgres wallet

2020-07-18 19:12:53,927 aries_cloudagent.wallet.plugin INFO Success, loaded postgres wallet storage

2020-07-18 19:12:53,928 indy.wallet DEBUG open_wallet: >>> config: '{"id": "my_wallet", "freshness_time": false, "storage_type": "postgres_storage", "storage_config": {"url": "localhost:5432", "wallet_scheme": "DatabasePerWallet"}}', credentials: '{"key": "my_key", "key_derivation_method": "ARGON2I_MOD", "storage_credentials": {"account": "postgres", "password": "mysecretpassword", "admin_account": "postgres", "admin_password": "mysecretpassword"}}'

2020-07-18 19:12:53,928 indy.wallet DEBUG open_wallet: Creating callback

2020-07-18 19:12:53,928 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>

2020-07-18 19:12:53,936 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x7fda75c79a70>

2020-07-18 19:12:53,937 indy.libindy DEBUG do_call: >>> name: indy_open_wallet, args: (c_char_p(140576255613760), c_char_p(140576255103056), <CFunctionType object at 0x7fda75c79a70>)

2020-07-18 19:12:53,937 indy.libindy DEBUG _load_cdll: >>>

2020-07-18 19:12:53,937 indy.libindy DEBUG _load_cdll: Detected OS name: linux

2020-07-18 19:12:53,937 indy.libindy DEBUG _load_cdll: Resolved libindy name is: libindy.so

2020-07-18 19:12:53,937 indy.libindy DEBUG _load_cdll: <<< res: <CDLL 'libindy.so', handle 55c800c3e430 at 0x7fda75bef3c8>

2020-07-18 19:12:53,939 indy.libindy DEBUG set_logger: >>>

2020-07-18 19:12:53,943 indy.libindy DEBUG do_call_sync: >>> name: indy_set_logger, args: (None, None, <CFunctionType object at 0x7fda75c79c00>, None)

2020-07-18 19:12:53,943 indy.libindy DEBUG do_call_sync: <<< 0

2020-07-18 19:12:53,945 indy.libindy DEBUG set_logger: <<<

2020-07-18 19:12:53,946 indy.libindy DEBUG do_call: Function indy_open_wallet returned err: 0

2020-07-18 19:12:53,946 indy.libindy.native.indy.commands DEBUG 	src/commands/mod.rs:150 | WalletCommand command received

2020-07-18 19:12:53,947 indy.libindy DEBUG do_call: <<< <Future pending>

2020-07-18 19:12:53,948 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:142 | Open command received

2020-07-18 19:12:53,954 indy.libindy DEBUG _get_error_details: >>>

2020-07-18 19:12:53,955 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Wallet not found\n  Caused by: Plugin returned error\n'}

2020-07-18 19:12:53,955 indy.libindy DEBUG _indy_callback: >>> command_handle: 0, err , args: (0,)

2020-07-18 19:12:53,956 indy.libindy DEBUG _indy_callback: <<<

2020-07-18 19:12:53,956 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 0, err , args: (0,)

2020-07-18 19:12:53,956 indy.libindy WARNING _indy_loop_callback: Function returned error 

2020-07-18 19:12:53,959 indy.libindy DEBUG _indy_loop_callback <<<

2020-07-18 19:12:53,959 indy.wallet DEBUG create_wallet: >>> config: '{"id": "my_wallet", "freshness_time": false, "storage_type": "postgres_storage", "storage_config": {"url": "localhost:5432", "wallet_scheme": "DatabasePerWallet"}}', credentials: '{"key": "my_key", "key_derivation_method": "ARGON2I_MOD", "storage_credentials": {"account": "postgres", "password": "mysecretpassword", "admin_account": "postgres", "admin_password": "mysecretpassword"}}'

2020-07-18 19:12:53,959 indy.wallet DEBUG create_wallet: Creating callback

2020-07-18 19:12:53,960 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>

2020-07-18 19:12:53,960 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x7fda75c798e0>

2020-07-18 19:12:53,962 indy.libindy DEBUG do_call: >>> name: indy_create_wallet, args: (c_char_p(140576255614760), c_char_p(140576255103296), <CFunctionType object at 0x7fda75c798e0>)

2020-07-18 19:12:53,963 indy.libindy DEBUG do_call: Function indy_create_wallet returned err: 0

2020-07-18 19:12:53,963 indy.libindy DEBUG do_call: <<< <Future pending>

2020-07-18 19:12:53,963 indy.libindy.native.indy.commands DEBUG 	src/commands/mod.rs:150 | WalletCommand command received

2020-07-18 19:12:53,964 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:134 | Create command received

2020-07-18 19:12:53,964 indy.libindy.native.indy.commands DEBUG 	src/commands/mod.rs:150 | WalletCommand command received

2020-07-18 19:12:53,964 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:182 | DeriveKey command received

2020-07-18 19:12:55,222 indy.libindy.native.indy.commands DEBUG 	src/commands/mod.rs:150 | WalletCommand command received

2020-07-18 19:12:55,222 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:138 | CreateContinue command received

2020-07-18 19:12:55,287 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG 	src/postgres_storage.rs:658 | Entering create_wallet

2020-07-18 19:12:55,287 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG 	src/postgres_storage.rs:659 | setting up the admin_postgres_url

2020-07-18 19:12:55,287 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG 	src/postgres_storage.rs:663 | connecting to postgres, url_base: "postgresql://postgres:mysecretpassword@localhost:5432"

2020-07-18 19:12:55,289 indy.libindy.native.indystrgpostgres ERROR 	src/lib.rs:190 | Create storage failed: IOError("IO error during storage operation: IO error")

2020-07-18 19:12:55,289 indy.libindy DEBUG _get_error_details: >>>

2020-07-18 19:12:55,290 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Wallet storage error occurred\n  Caused by: Plugin returned error\n'}

2020-07-18 19:12:55,291 indy.libindy DEBUG _indy_callback: >>> command_handle: 1, err , args: ()

2020-07-18 19:12:55,291 indy.libindy DEBUG _indy_callback: <<<

2020-07-18 19:12:55,292 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 1, err , args: ()

2020-07-18 19:12:55,292 indy.libindy WARNING _indy_loop_callback: Function returned error 

2020-07-18 19:12:55,295 indy.libindy DEBUG _indy_loop_callback <<<

2020-07-18 19:12:55,296 aries_cloudagent.commands.start ERROR Exception during startup:

Traceback (most recent call last):

  File "/home/indy/aries_cloudagent/wallet/indy.py", line 188, in create

    credentials=json.dumps(self._wallet_access),

  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet

    create_wallet.cb)

indy.error.WalletStorageError



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/home/indy/aries_cloudagent/commands/start.py", line 77, in init

    await startup

  File "/home/indy/aries_cloudagent/commands/start.py", line 27, in start_app

    await conductor.start()

  File "/home/indy/aries_cloudagent/core/conductor.py", line 144, in start

    public_did = await wallet_config(context)

  File "/home/indy/aries_cloudagent/config/wallet.py", line 16, in wallet_config

    wallet: BaseWallet = await context.inject(BaseWallet)

  File "/home/indy/aries_cloudagent/config/injection_context.py", line 126, in inject

    return await self.injector.inject(base_cls, settings, required=required)

  File "/home/indy/aries_cloudagent/config/injector.py", line 77, in inject

    result = await provider.provide(ext_settings, self)

  File "/home/indy/aries_cloudagent/config/provider.py", line 83, in provide

    self._instance = await self._provider.provide(config, injector)

  File "/home/indy/aries_cloudagent/config/provider.py", line 106, in provide

    instance = await self._provider.provide(config, injector)

  File "/home/indy/aries_cloudagent/wallet/provider.py", line 42, in provide

    await wallet.open()

  File "/home/indy/aries_cloudagent/wallet/indy.py", line 259, in open

    await self.create(self._auto_remove)

  File "/home/indy/aries_cloudagent/wallet/indy.py", line 197, in create

    ) from x_indy

  File "/home/indy/aries_cloudagent/wallet/indy.py", line 188, in create

    credentials=json.dumps(self._wallet_access),

  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet

    create_wallet.cb)

aries_cloudagent.wallet.error.WalletError: Exception while performing indy operation: Error: Wallet storage error occurred

  Caused by: Plugin returned error


Shutting down
```

Does anyone have an idea about what the problem might be?

**Comment by ianco** [comment]
@Sarangc1203 this issue is closed so you should probably open a new issue (I think your error is different than the issue that was originally logged anyways).

When you open a new issue, can you also describe how you are starting your local indy network and postgres database?  The aca-py agent you are starting is running in a docker container so it may or may not be having issues connecting to your postgres sever.

**Comment by kapilkathuria** [comment]
@Sarangc1203 did you posted this as separate issue and happened to find any solution?

**Comment by Sarangc1203** [comment]
Yeah, I figured out how to get it working. Using the configuration mentioned above, the aca-py was looking for a postgres service inside the aca-py's docker container itself. The problem was that my postgres service was running as an independent service in another container. So to get it working I just had to expose and map the ports so aca-py could interface with the postgres service.
Apologies for not following up on this earlier, my laptop ran into some trouble.

**Comment by kapilkathuria** [comment]
thanks for revert @Sarangc1203 . been struggling with this for some time and not able to find solution. Have tried various things (i.e. run postgres on local machine, map ports of postgres container, run all containers with docker compose so that they are in same network etc.)

possible for you to post step by step instructions worked for you? 

I also posted this as separate issue here - #720 to see if someone is able to advise what i am missing.

thanks again!
