### ISSUE TITLE
Error encountered in openshift

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#592]
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 186, in check_token
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in apply_limiter
    return await task
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 559, in credential_exchange_send
    outbound_handler,
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 340, in internal_error
    err.roll_up, record.connection_id, record.thread_id, outbound_handler
AttributeError: 'ConnectionRecord' object has no attribute 'thread_id'

**Comment by sklump** [comment]
Hey, you're right. My mistake, I think. If you like I can look into it tomorrow.

There really is no thread_id in ConnectionRecord. There is in other kinds of records - maybe only protocol records?

**Comment by sklump** [comment]
A little finessing with `internal_error()` and `send_problem_report()` in issue-credential v1.0 routes.py ought to fix it, 15 minutes tomorrow first thing in the morning if you can wait that long.

**Comment by ianco** [comment]
ok @sklump I'll leave it for you

**Comment by ianco** [comment]
I notice the logic is slightly different in proof request handling, probably makes sense to look at that one at the same time and update to be consistent with the credential error handling.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/595
