### ISSUE TITLE
Update health/liveliness endpoints to check agent execution status 

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#638]
The health/liveliness checks should detect if the agent has reached a state where it cannot process requests.

One example is as follows - when the agent is in this state *every* requests returns this error:

```
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 178, in handle_message
    await handler(context, responder)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/handlers/credential_offer_handler.py", line 55, in handle
    holder_did=context.connection_record.my_did,
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 400, in create_request
    cred_req_result = await _create()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 367, in _create
    async with ledger:
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 244, in __aenter__
    await self._context_open()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 213, in _context_open
    await self.open()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 178, in open
    self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/error.py", line 27, in __exit__
    ) from err_value
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 178, in open
    self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
    open_pool_ledger.cb)
aries_cloudagent.ledger.error.LedgerConfigError: Exception when opening pool ledger: Error: Invalid pool handle
  Caused by: Pool with the same name is already opened
```

**Comment by sklump** [comment]
Could this be an indicator of the failure of the retry-close (https://github.com/hyperledger/aries-cloudagent-python/pull/541 and https://github.com/hyperledger/aries-cloudagent-python/pull/542) strategy we threw in and forgot about?

**Comment by ianco** [comment]
Hmmm thanks for the reminder, I'll take a look.

2 issues then:

1.  Is this change causing our ledger issue?
2. If we have a ledger issue, we need to "go offline" and ask openshift to restart the aca-py pod
