### ISSUE TITLE
Incorrect Cred id on send_presentation on Admin API is returning a 500 Internal Server Error

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-cloudagent-python#696]
## Issue
Tested thought the Admin API and setup and sent through the send-presentation operation, where the cred_id is incorrect for the credential.
```
{
   "presentation": {
      "comment": "This is a comment for the send presentation.",
      "requested_attributes": {
         "address_attrs": {
            "cred_type_name": "Schema_DriversLicense",
            "revealed": true,
            "cred_id": "d413f359-9595-4ab6-94cf-1aa191d2c884"
         }
      }
   }
}
```

## Outcome
The response from the Admin API is 500 Internal Server Error. 
However, the logs in the agent is showing the errors below. 
```
2020-08-26 22:04:38,911 aries_cloudagent.core.dispatcher ERROR Handler error: presentation_exchange_send_presentation
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/holder/indy.py", line 275, in get_credential
    self.wallet.handle, credential_id
  File "/usr/local/lib/python3.7/site-packages/indy/anoncreds.py", line 923, in prover_get_credential
    prover_get_credential.cb)
indy.error.WalletItemNotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/present_proof/v1_0/routes.py", line 927, in presentation_exchange_send_presentation
    comment=body.get("comment"),
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/present_proof/v1_0/manager.py", line 297, in create_presentation
    await holder.get_credential(credential_id)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/holder/indy.py", line 281, in get_credential
    credential_id, self.wallet.name
aries_cloudagent.wallet.error.WalletNotFoundError: Credential d413f359-9595-4ab6-94cf-1aa191d2c884 not found in wallet aca-py352817
2020-08-26 22:04:38,912 aries_cloudagent.admin.server ERROR Handler error with exception: Credential d413f359-9595-4ab6-94cf-1aa191d2c884 not found in wallet aca-py352817
2020-08-26 22:04:38,912 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/holder/indy.py", line 275, in get_credential
    self.wallet.handle, credential_id
  File "/usr/local/lib/python3.7/site-packages/indy/anoncreds.py", line 923, in prover_get_credential
    prover_get_credential.cb)
indy.error.WalletItemNotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 146, in ready_middleware
    raise e
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 136, in ready_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 161, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/admin/server.py", line 253, in apply_limiter
    return await task
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/present_proof/v1_0/routes.py", line 927, in presentation_exchange_send_presentation
    comment=body.get("comment"),
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/protocols/present_proof/v1_0/manager.py", line 297, in create_presentation
    await holder.get_credential(credential_id)
  File "/usr/local/lib/python3.7/site-packages/aries_cloudagent/holder/indy.py", line 281, in get_credential
    credential_id, self.wallet.name
aries_cloudagent.wallet.error.WalletNotFoundError: Credential d413f359-9595-4ab6-94cf-1aa191d2c884 not found in wallet aca-py352817
```

## Expected Outcome
The Admin API would return the `Credential d413f359-9595-4ab6-94cf-1aa191d2c884 not found in wallet aca-py352817' instead of the Internal Server error.

## Workaround
Use the correct cred id, or if the purpose is to cause an error, then watch the logs in the agent instead. 

## Test Cases Found or Affected
T005-AIP10-RFC0037 - Present Proof where the verifier rejects the presentation of the proof

## Severity
Medium

## Business Priority
Medium

@sklump

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/700 addresses.
