### ISSUE TITLE
Aiohttp can't reach the test.bcvorin.vonx.io with proxy network

### ISSUE THREAD

**Issue by anhem115** [hyperledger/aries-cloudagent-python#697]
I tried to run the agent(docker version from issuer kit of BC government) with the ledger url at : test.bcovrin.vonx.io and I got the error of aio http:

```
2020-08-27 13:37:04,864 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('138.197.138.255', 80)

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/utils/http.py", line 96, in fetch
    response: ClientResponse = await session.get(url, headers=headers)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host test.bcovrin.vonx.io:80 ssl:default [Connect call failed ('138.197.138.255', 80)]

 

The above exception was the direct cause of the following exception:
}
Shutting down

 

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 28, in fetch_genesis_transactions
    return await fetch(genesis_url, headers=headers)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/utils/http.py", line 104, in fetch
    raise FetchError("Exceeded maximum fetch attempts") from e
aries_cloudagent.utils.http.FetchError: Exceeded maximum fetch attempts

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 77, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 27, in start_app
    await conductor.start()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 147, in start
    if not await ledger_config(context, public_did):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 43, in ledger_config
    ] = await fetch_genesis_transactions(context.settings["ledger.genesis_url"])
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 30, in fetch_genesis_transactions
    raise ConfigError("Error retrieving ledger genesis transactions") from e
aries_cloudagent.config.base.ConfigError: Error retrieving ledger genesis transactions
issuer-kit_agent_1 exited with code 0
```
I could see the error is the aiohttp got problem to reach the test.bcovrin.vonx.io. However, I could run `curl text.bcvorin.vonx.io` without any error. I did have a proxy setup on my network so I think that maybe the problem?

**Comment by WadeBarnes** [comment]
In the case of the BCovrin ledgers you'll want to configure your agent with the genesis URL for the ledger; http://test.bcovrin.vonx.io/genesis

**Comment by anhem115** [comment]
Thank @WadeBarnes , yes, I did provide the `export LEDGER_URL= http://test.bcovin.vonx.io` for the start-demo. It works normally without proxy network, but in my situation I have to make it work under proxy environment.

**Comment by WadeBarnes** [comment]
Ah, you'll have to inject the proxy settings into the docker container.  I'll try to find an example.

**Comment by anhem115** [comment]
I also found on the documentation of the aiohttp that I need to pass the `trust_env=True` inside the aiohttp.ClientSession constructor so that it will read the proxy configuration in `$HTTP_PROXY` or `$HTTPS_PROXY` at: https://docs.aiohttp.org/en/stable/client_advanced.html
But I'm not sure how could we achieve that with the current docker setup for the agent?

**Comment by WadeBarnes** [comment]
Here is an example of how it's done with docker builds; https://github.com/bcgov/aries-vcr/blob/master/docker/manage#L199.  The process is the same with running containers.  You need to inject the `$HTTP_PROXY` and `$HTTPS_PROXY` settings into the container.

**Comment by WadeBarnes** [comment]
There are Docker level ways of doing this too; https://github.com/bcgov/aries-vcr/blob/master/docker/PROXY.md

**Comment by anhem115** [comment]
Thank @WadeBarnes , but even if I could inject the HTTP_PROXY variable, the aiohttp will still not read that variable by default (from the documentation link above)?

**Comment by WadeBarnes** [comment]
Yes, you'll also need to inject some indication the env is to be trusted, and there are likely code updates needed to support what's described.

**Comment by anhem115** [comment]
Thank @WadeBarnes , I have modified the agent image to support the proxy. I could get the transaction genesis now. However, I got a new problem when opening the pool:

```
agent_1             | 2020-08-31 03:09:41,615 aries_cloudagent.commands.start ERROR Exception during startup:
agent_1             | Traceback (most recent call last):
agent_1             |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 178, in open
agent_1             |     self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
agent_1             |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
agent_1             |     open_pool_ledger.cb)
agent_1             | indy.error.PoolLedgerTimeout
agent_1             | 
agent_1             | The above exception was the direct cause of the following exception:
agent_1             | 
agent_1             | Traceback (most recent call last):
agent_1             |   File "/home/indy/aries_cloudagent/commands/start.py", line 77, in init
agent_1             |     await startup
agent_1             |   File "/home/indy/aries_cloudagent/commands/start.py", line 27, in start_app
agent_1             |     await conductor.start()
agent_1             |   File "/home/indy/aries_cloudagent/core/conductor.py", line 147, in start
agent_1             |     if not await ledger_config(context, public_did):
agent_1             |   File "/home/indy/aries_cloudagent/config/ledger.py", line 63, in ledger_config
agent_1             |     async with ledger:
agent_1             |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 244, in __aenter__
agent_1             |     await self._context_open()
agent_1             |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 213, in _context_open
agent_1             |     await self.open()
agent_1             |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 178, in open
agent_1             |     self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
agent_1             |   File "/home/indy/aries_cloudagent/indy/error.py", line 27, in __exit__
agent_1             |     ) from err_value
agent_1             |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 178, in open
agent_1             |     self.pool_handle = await indy.pool.open_pool_ledger(self.pool_name, "{}")
agent_1             |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
agent_1             |     open_pool_ledger.cb)
agent_1             | aries_cloudagent.ledger.error.LedgerConfigError: Exception when opening pool ledger: Error: Pool timeout
agent_1             |   Caused by: Pool timeout
agent_1             | 
agent_1             | 
agent_1             | Shutting down
issuer-kit_agent_1 exited with code 0

```

Do you know what is the possible reason of that error

**Comment by WadeBarnes** [comment]
The error indicates the agent is not getting a response from the ledger.  Agents and nodes communicate on ports 9700-9799.  Check to see if your proxy/firewall is blocking those ports.

**Comment by anhem115** [comment]
I used the command `ss -lntu | grep ':970'` to see the current list of port, and I found that I have some ports open ?

![image](https://user-images.githubusercontent.com/11781639/91730913-f9036a00-eb6b-11ea-8577-7e00380b152d.png)

Is that the port range you mentioned @WadeBarnes ?

**Comment by WadeBarnes** [comment]
Yes, those are the ports.  On which machine was the command run?  It could be your corporate firewall or proxy blocking the ports.

**Comment by anhem115** [comment]
Yes, I run that on the machine where I run the issuer kit and the agent. I will check that proxy and firewall again.

**Comment by swcurran** [comment]
Please reopen if appropriate.

**Comment by vitalrev** [comment]
we have the same problem... and solution
