### ISSUE TITLE
Large credentials can't be stored in Postgres Wallet

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#733]
When storing a credential with an attribute that holds a long string (approx. 30000 characters in this case), the holder is not able to store the credential and fails with the following error.

This error only occurs with Postgres wallet storage.

```
postgres_1       | 2020-09-29 17:16:03.366 UTC [59] ERROR:  index row requires 32224 bytes, maximum size is 8191
postgres_1       | 2020-09-29 17:16:03.366 UTC [59] STATEMENT:  INSERT INTO tags_encrypted (item_id, name, value) VALUES ($1, $2, $3)
aca-py_1         | 2020-09-29 17:16:03,367 indy.libindy.native.indystrgpostgres ERROR   src/lib.rs:279 | Error adding a record. Error details: IOError("IO error during storage operation: database error")
aca-py_1         | 2020-09-29 17:16:03,368 indy.libindy WARNING _indy_loop_callback: Function returned error 
aca-py_1         | 2020-09-29 17:16:03,368 aries_cloudagent.protocols.issue_credential.v1_0.manager ERROR Error storing credential. None: Error when storing credential in wallet: Error: Wallet storage error occurred
aca-py_1         |   Caused by: Plugin returned error
aca-py_1         | 2020-09-29 17:16:03,369 aries_cloudagent.core.dispatcher ERROR Handler error: credential_exchange_store
aca-py_1         | Traceback (most recent call last):
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 110, in store_credential
aca-py_1         |     rev_reg_def_json=json.dumps(rev_reg_def) if rev_reg_def else None,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/anoncreds.py", line 883, in prover_store_credential
aca-py_1         |     prover_store_credential.cb)
aca-py_1         | indy.error.WalletStorageError
aca-py_1         | 
aca-py_1         | The above exception was the direct cause of the following exception:
aca-py_1         | 
aca-py_1         | Traceback (most recent call last):
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 1127, in credential_exchange_store
aca-py_1         |     ) = await credential_manager.store_credential(cred_ex_record, credential_id)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 740, in store_credential
aca-py_1         |     raise e
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 736, in store_credential
aca-py_1         |     rev_reg_def=revoc_reg_def,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 110, in store_credential
aca-py_1         |     rev_reg_def_json=json.dumps(rev_reg_def) if rev_reg_def else None,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/error.py", line 27, in __exit__
aca-py_1         |     ) from err_value
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 110, in store_credential
aca-py_1         |     rev_reg_def_json=json.dumps(rev_reg_def) if rev_reg_def else None,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/anoncreds.py", line 883, in prover_store_credential
aca-py_1         |     prover_store_credential.cb)
aca-py_1         | aries_cloudagent.holder.base.HolderError: Error when storing credential in wallet: Error: Wallet storage error occurred
aca-py_1         |   Caused by: Plugin returned error
aca-py_1         | 
aca-py_1         | 2020-09-29 17:16:03,370 aries_cloudagent.admin.server ERROR Handler error with exception: Error when storing credential in wallet: Error: Wallet storage error occurred
aca-py_1         |   Caused by: Plugin returned error
aca-py_1         | 
aca-py_1         | 2020-09-29 17:16:03,371 aiohttp.server ERROR Error handling request
aca-py_1         | Traceback (most recent call last):
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 110, in store_credential
aca-py_1         |     rev_reg_def_json=json.dumps(rev_reg_def) if rev_reg_def else None,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/anoncreds.py", line 883, in prover_store_credential
aca-py_1         |     prover_store_credential.cb)
aca-py_1         | indy.error.WalletStorageError
aca-py_1         | 
aca-py_1         | The above exception was the direct cause of the following exception:
aca-py_1         | 
aca-py_1         | Traceback (most recent call last):
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
aca-py_1         |     resp = await task
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
aca-py_1         |     resp = await handler(request)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
aca-py_1         |     return await handler(request)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 144, in ready_middleware
aca-py_1         |     return await handler(request)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 177, in debug_middleware
aca-py_1         |     return await handler(request)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
aca-py_1         |     return await handler(request)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 262, in check_token
aca-py_1         |     return await handler(request)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 275, in apply_limiter
aca-py_1         |     return await task
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/routes.py", line 1127, in credential_exchange_store
aca-py_1         |     ) = await credential_manager.store_credential(cred_ex_record, credential_id)
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 740, in store_credential
aca-py_1         |     raise e
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 736, in store_credential
aca-py_1         |     rev_reg_def=revoc_reg_def,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 110, in store_credential
aca-py_1         |     rev_reg_def_json=json.dumps(rev_reg_def) if rev_reg_def else None,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/error.py", line 27, in __exit__
aca-py_1         |     ) from err_value
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/holder/indy.py", line 110, in store_credential
aca-py_1         |     rev_reg_def_json=json.dumps(rev_reg_def) if rev_reg_def else None,
aca-py_1         |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/anoncreds.py", line 883, in prover_store_credential
aca-py_1         |     prover_store_credential.cb)
aca-py_1         | aries_cloudagent.holder.base.HolderError: Error when storing credential in wallet: Error: Wallet storage error occurred
aca-py_1         |   Caused by: Plugin returned error
```

**Comment by ianco** [comment]
This is due to the restriction on the size of an index supported by postgres.

Note that this is addressed by this PR in indy-sdk:  https://github.com/hyperledger/indy-sdk/pull/2232

... which replaces the offending index with an md5 (which is a fixed size).

This is in the latest indy-sdk master branch but is not available in an indy-sdk release.

Note that you can manually make the change in your postgres wallet as follows (this is on the encrypted tags table, you need to make similar changes on the unencrypted tags indexes if you need):

drop index ix_tags_encrypted_name;
drop index ix_tags_encrypted_value;
CREATE INDEX IF NOT EXISTS ix_tags_encrypted_name ON tags_encrypted(md5(name));
CREATE INDEX IF NOT EXISTS ix_tags_encrypted_value ON tags_encrypted(md5(value));

**Comment by swcurran** [comment]
Closing this as a non-ACA-Py issue.  We could document it, but...it's here at least.
