### ISSUE TITLE
Issue with public invitations and short verkeys

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#756]
When a connection request is created based on a public invitation (.i.e. containing a public DID instead of verkey and endpoint info) sent to `/connections/receive-invitation`, and the verkey on the ledger is in short form (starting with `~`) ACA-PY throws the following error while trying to create the connection request message:
```
2020-10-19 15:27:39,808 aries_cloudagent.core.dispatcher ERROR Handler error: PackWireFormat.pack
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 682, in pack_message
    self.handle, message, to_verkeys, from_verkey
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/crypto.py", line 448, in pack_message
    pack_message.cb)
indy.error.CommonInvalidStructure

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/transport/pack_format.py", line 180, in pack
    message_json, recipient_keys, sender_key
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 687, in pack_message
    ) from x_indy
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 682, in pack_message
    self.handle, message, to_verkeys, from_verkey
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/crypto.py", line 448, in pack_message
    pack_message.cb)
aries_cloudagent.wallet.error.WalletError: Exception when packing message: Error: Invalid structure
  Caused by: The base58 input contained a character not part of the base58 alphabet

```

**Comment by swcurran** [comment]
@andrewwhitehead @sklump --- could one or both of you please take a look?  Thanks!

**Comment by sklump** [comment]
I can take this first thing tomorrow morning

**Comment by sklump** [comment]
... I will post a fix tomorrow morning first thing
