### ISSUE TITLE
Current pypi install of aries-cloudagent gives indy.blob_storage error

### ISSUE THREAD

**Issue by daidoji** [hyperledger/aries-cloudagent-python#776]
I saw in the README that there was a pypi install instruction but probably more should be added there because the current version (0.5.6) doesn't seem to work even with installing the `indy` package (which might not even be the right step either).  Fixing the README to add a note about any kind of indy dependencies this package has or adjusting the package so that it does work on an install from pypi would probably be the solution to this issue.

```
daidoji@worklaptop:~/python_homes$ python3 -m venv foo
daidoji@worklaptop:~/python_homes$ source foo/bin/activate
(foo) daidoji@worklaptop:~/python_homes$ pip install aries-cloudagent
Collecting aries-cloudagent
  Using cached aries_cloudagent-0.5.6-py3-none-any.whl (677 kB)
Collecting Markdown~=3.1.1
  Using cached Markdown-3.1.1-py2.py3-none-any.whl (87 kB)
Collecting pyyaml~=5.3.1
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting py-multicodec==0.2.1
  Using cached py_multicodec-0.2.1-py2.py3-none-any.whl (8.5 kB)
Collecting pynacl~=1.3.0
  Using cached PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759 kB)
Collecting msgpack~=0.6.1
  Using cached msgpack-0.6.2.tar.gz (119 kB)
Collecting ConfigArgParse~=1.2.3
  Using cached ConfigArgParse-1.2.3.tar.gz (42 kB)
Collecting async-timeout~=3.0.1
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Processing /home/daidoji/.cache/pip/wheels/b6/9c/bd/6b99bc6ec9dab11f3756d31fb8506d3ecf07aea58b6201f539/aiohttp-3.6.3-cp39-cp39-linux_x86_64.whl
Collecting aiohttp-cors~=0.7.0
  Using cached aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting requests~=2.23.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting base58~=2.0.0
  Using cached base58-2.0.1-py3-none-any.whl (4.3 kB)
Collecting pyld==2.0.1
  Using cached PyLD-2.0.1.tar.gz (69 kB)
Collecting marshmallow==3.5.1
  Using cached marshmallow-3.5.1-py2.py3-none-any.whl (45 kB)
Collecting aiohttp-apispec==2.2.1
  Using cached aiohttp-apispec-2.2.1.tar.gz (2.3 MB)
Collecting apispec~=3.3.0
  Using cached apispec-3.3.2-py2.py3-none-any.whl (27 kB)
Collecting prompt-toolkit~=2.0.9
  Using cached prompt_toolkit-2.0.10-py3-none-any.whl (340 kB)
Requirement already satisfied: setuptools>=36 in ./foo/lib/python3.9/site-packages (from Markdown~=3.1.1->aries-cloudagent) (49.2.1)
Collecting morphys<2.0,>=1.0
  Using cached morphys-1.0-py2.py3-none-any.whl (5.6 kB)
Collecting varint<2.0.0,>=1.0.2
  Using cached varint-1.0.2.tar.gz (1.9 kB)
Collecting six<2.0,>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cffi>=1.4.1
  Using cached cffi-1.14.3-cp39-cp39-manylinux1_x86_64.whl (405 kB)
Collecting chardet<4.0,>=2.0
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting attrs>=17.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Processing /home/daidoji/.cache/pip/wheels/43/3a/a8/d7bf95ae763a7a2057cb502ff2da094763c166f253624afc63/multidict-4.7.6-cp39-cp39-linux_x86_64.whl
Processing /home/daidoji/.cache/pip/wheels/74/4d/d1/5511819b1cac11762fc38bb1d57808c8aa139ddd94dc35a37b/yarl-1.5.1-cp39-cp39-linux_x86_64.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 2.5 MB/s
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting cachetools
  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting frozendict
  Using cached frozendict-1.2.tar.gz (2.6 kB)
Collecting lxml
  Using cached lxml-4.6.1-cp39-cp39-manylinux1_x86_64.whl (5.4 MB)
Collecting webargs<6.0
  Using cached webargs-5.5.3-py3-none-any.whl (29 kB)
Collecting jinja2<3.0
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
Using legacy 'setup.py install' for pyyaml, since package 'wheel' is not installed.
Using legacy 'setup.py install' for msgpack, since package 'wheel' is not installed.
Using legacy 'setup.py install' for ConfigArgParse, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pyld, since package 'wheel' is not installed.
Using legacy 'setup.py install' for aiohttp-apispec, since package 'wheel' is not installed.
Using legacy 'setup.py install' for varint, since package 'wheel' is not installed.
Using legacy 'setup.py install' for frozendict, since package 'wheel' is not installed.
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Installing collected packages: Markdown, pyyaml, morphys, varint, six, py-multicodec, pycparser, cffi, pynacl, msgpack, ConfigArgParse, async-timeout, chardet, attrs, multidict, idna, yarl, aiohttp, aiohttp-cors, urllib3, certifi, requests, base58, cachetools, frozendict, lxml, pyld, marshmallow, apispec, webargs, MarkupSafe, jinja2, aiohttp-apispec, wcwidth, prompt-toolkit, aries-cloudagent
    Running setup.py install for pyyaml ... done
    Running setup.py install for varint ... done
    Running setup.py install for msgpack ... done
    Running setup.py install for ConfigArgParse ... done
    Running setup.py install for frozendict ... done
    Running setup.py install for pyld ... done
    Running setup.py install for MarkupSafe ... done
    Running setup.py install for aiohttp-apispec ... done
Successfully installed ConfigArgParse-1.2.3 Markdown-3.1.1 MarkupSafe-1.1.1 aiohttp-3.6.3 aiohttp-apispec-2.2.1 aiohttp-cors-0.7.0 apispec-3.3.2 aries-cloudagent-0.5.6 async-timeout-3.0.1 attrs-20.3.0 base58-2.0.1 cachetools-4.1.1 certifi-2020.11.8 cffi-1.14.3 chardet-3.0.4 frozendict-1.2 idna-2.10 jinja2-2.11.2 lxml-4.6.1 marshmallow-3.5.1 morphys-1.0 msgpack-0.6.2 multidict-4.7.6 prompt-toolkit-2.0.10 py-multicodec-0.2.1 pycparser-2.20 pyld-2.0.1 pynacl-1.3.0 pyyaml-5.3.1 requests-2.23.0 six-1.15.0 urllib3-1.25.11 varint-1.0.2 wcwidth-0.2.5 webargs-5.5.3 yarl-1.5.1
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/home/daidoji/python_homes/foo/bin/python3 -m pip install --upgrade pip' command.
(foo) daidoji@worklaptop:~/python_homes$ ac
ac            aca-py        accessdb      accton        aclocal       aclocal-1.16  aconnect      acpi_listen   acpid
(foo) daidoji@worklaptop:~/python_homes$ aca-py --version
Traceback (most recent call last):
  File "/home/daidoji/python_homes/foo/bin/aca-py", line 49, in <module>
    run_command(command, args)
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/__init__.py", line 34, in run_command
    module.execute(argv)
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/help.py", line 24, in execute
    module = load_command(cmd["name"])
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/__init__.py", line 28, in load_command
    return import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/provision.py", line 7, in <module>
    from ..config import argparse as arg
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/config/argparse.py", line 11, in <module>
    from ..utils.tracing import trace_event
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/utils/tracing.py", line 12, in <module>
    from ..transport.outbound.message import OutboundMessage
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/transport/outbound/message.py", line 5, in <module>
    from ...connections.models.connection_target import ConnectionTarget
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/connections/models/connection_target.py", line 8, in <module>
    from ...messaging.valid import INDY_DID, INDY_RAW_PUBLIC_KEY
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/messaging/valid.py", line 14, in <module>
    from ..revocation.models.revocation_registry import RevocationRegistry
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/revocation/models/revocation_registry.py", line 12, in <module>
    from ...indy.util import indy_client_dir
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/indy/__init__.py", line 7, in <module>
    import indy.blob_storage
ModuleNotFoundError: No module named 'indy'
(foo) daidoji@worklaptop:~/python_homes$ pip install indy
Collecting indy
  Using cached indy-0.1.tar.gz (2.7 kB)
Using legacy 'setup.py install' for indy, since package 'wheel' is not installed.
Installing collected packages: indy
    Running setup.py install for indy ... done
Successfully installed indy-0.1
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/home/daidoji/python_homes/foo/bin/python3 -m pip install --upgrade pip' command.
(foo) daidoji@worklaptop:~/python_homes$ aca-py --version
Traceback (most recent call last):
  File "/home/daidoji/python_homes/foo/bin/aca-py", line 49, in <module>
    run_command(command, args)
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/__init__.py", line 34, in run_command
    module.execute(argv)
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/help.py", line 24, in execute
    module = load_command(cmd["name"])
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/__init__.py", line 28, in load_command
    return import_module(module_path)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/commands/provision.py", line 7, in <module>
    from ..config import argparse as arg
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/config/argparse.py", line 11, in <module>
    from ..utils.tracing import trace_event
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/utils/tracing.py", line 12, in <module>
    from ..transport.outbound.message import OutboundMessage
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/transport/outbound/message.py", line 5, in <module>
    from ...connections.models.connection_target import ConnectionTarget
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/connections/models/connection_target.py", line 8, in <module>
    from ...messaging.valid import INDY_DID, INDY_RAW_PUBLIC_KEY
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/messaging/valid.py", line 14, in <module>
    from ..revocation.models.revocation_registry import RevocationRegistry
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/revocation/models/revocation_registry.py", line 12, in <module>
    from ...indy.util import indy_client_dir
  File "/home/daidoji/python_homes/foo/lib64/python3.9/site-packages/aries_cloudagent/indy/__init__.py", line 7, in <module>
    import indy.blob_storage
ModuleNotFoundError: No module named 'indy.blob_storage'

(foo) daidoji@worklaptop:~/python_homes$ pip freeze
aiohttp==3.6.3
aiohttp-apispec==2.2.1
aiohttp-cors==0.7.0
apispec==3.3.2
aries-cloudagent==0.5.6
async-timeout==3.0.1
attrs==20.3.0
base58==2.0.1
cachetools==4.1.1
certifi==2020.11.8
cffi==1.14.3
chardet==3.0.4
ConfigArgParse==1.2.3
frozendict==1.2
idna==2.10
indy==0.1
Jinja2==2.11.2
lxml==4.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
marshmallow==3.5.1
morphys==1.0
msgpack==0.6.2
multidict==4.7.6
prompt-toolkit==2.0.10
py-multicodec==0.2.1
pycparser==2.20
PyLD==2.0.1
PyNaCl==1.3.0
PyYAML==5.3.1
requests==2.23.0
six==1.15.0
urllib3==1.25.11
varint==1.0.2
wcwidth==0.2.5
webargs==5.5.3
yarl==1.5.1
(foo) daidoji@worklaptop:~/python_homes$ python -V
Python 3.9.0
```

**Comment by daidoji** [comment]
Oh `python3-indy` is required not `indy`
