### ISSUE TITLE
Error in revocation demo

### ISSUE THREAD

**Issue by guilherme-funchal** [hyperledger/aries-cloudagent-python#794]
I get error in demo of revogation, If anyone can help me:

**1)I start the tails-server** 

ngrok-tails-server_1  | t=2020-11-20T18:44:37+0000 lvl=info msg="no configuration paths supplied"
ngrok-tails-server_1  | t=2020-11-20T18:44:37+0000 lvl=info msg="using configuration at default config path" path=/home/ngrok/.ngrok2/ngrok.yml
ngrok-tails-server_1  | t=2020-11-20T18:44:37+0000 lvl=info msg="open config file" path=/home/ngrok/.ngrok2/ngrok.yml err=nil
ngrok-tails-server_1  | t=2020-11-20T18:44:37+0000 lvl=info msg="starting web service" obj=web addr=0.0.0.0:4040
ngrok-tails-server_1  | t=2020-11-20T18:44:37+0000 lvl=info msg="tunnel session started" obj=tunnels.session
ngrok-tails-server_1  | t=2020-11-20T18:44:37+0000 lvl=info msg="client session established" obj=csess id=6531d33d7870
ngrok-tails-server_1  | t=2020-11-20T18:44:38+0000 lvl=info msg="started tunnel" obj=tunnels name="command_line (http)" addr=http://tails-server:6543 url=http://7f11e8dcfa44.ngrok.io
ngrok-tails-server_1  | t=2020-11-20T18:44:38+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://tails-server:6543 url=https://7f11e8dcfa44.ngrok.io

**2)Im start the demo Faber with command** 
./run_demo faber --revocation --tails-server-base-url  http://7f11e8dcfa44.ngrok.io

**3)I can see files in /tmp/tails-file of tails-server container** 
ls -l
total 112
-rw-r--r-- 1 indy indy 25730 Nov 20 18:46 7QCxPquEgR74aiQWDs7pAt:4:7QCxPquEgR74aiQWDs7pAt:3:CL:65:default:CL_ACCUM:8dac64ee-7420-4ce4-b00c-247945616829
-rw-r--r-- 1 indy indy 25730 Nov 20 18:46 7QCxPquEgR74aiQWDs7pAt:4:7QCxPquEgR74aiQWDs7pAt:3:CL:65:default:CL_ACCUM:e8ad37ad-9c72-494f-b1c6-b4c5c6bf2da7
-rw-r--r-- 1 indy indy 25730 Nov 20 18:51 N497WfjU6YJWNjWq449FYA:4:N497WfjU6YJWNjWq449FYA:3:CL:81:default:CL_ACCUM:4eedfa7b-d2ad-49b2-b211-e04af7dfd9b8
-rw-r--r-- 1 indy indy 25730 Nov 20 18:51 N497WfjU6YJWNjWq449FYA:4:N497WfjU6YJWNjWq449FYA:3:CL:81:default:CL_ACCUM:87ee50a3-c16f-4026-a911-77bd0cb98cd6

**4)Im start the demo Alice with command**
 ./run_demo alice

**5)Whem Im try to aprove the invite in Alice I get the error** 

Preparing agent image...
sha256:19eb263cdf6acb8755b61e8727b3e6516bd6fe7cdca9d8b78ce9d82c2c1b6172
Trying to detect ngrok service endpoint
Detected ngrok agent endpoint [https://7f11e8dcfa44.ngrok.io]
172.17.0.1
Starting [alice] agent with args [--port 8030]

#7 Provision an agent and wallet, get back configuration details
Alice      | 
Alice      | ::::::::::::::::::::::::::::::::::::::::::::::
Alice      | :: Alice.Agent                              ::
Alice      | ::                                          ::
Alice      | ::                                          ::
Alice      | :: Inbound Transports:                      ::
Alice      | ::                                          ::
Alice      | ::   - http://0.0.0.0:8030                  ::
Alice      | ::                                          ::
Alice      | :: Outbound Transports:                     ::
Alice      | ::                                          ::
Alice      | ::   - http                                 ::
Alice      | ::   - https                                ::
Alice      | ::                                          ::
Alice      | :: Administration API:                      ::
Alice      | ::                                          ::
Alice      | ::   - http://0.0.0.0:8031                  ::
Alice      | ::                                          ::
Alice      | ::                               ver: 0.5.6 ::
Alice      | ::::::::::::::::::::::::::::::::::::::::::::::
Alice      | 
Alice      | Listening...
Alice      | 
Startup duration: 5.04s
Admin URL is at: http://172.17.0.1:8031
Endpoint URL is at: https://7f11e8dcfa44.ngrok.io

#9 Input faber.py invitation details
Invite details: {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation", "@id": "05fce839-f32a-4696-947a-4809252f5f30", "serviceEndpoint": "http://7f11e8dcfa44.ngrok.io", "label": "Faber.Agent
", "recipientKeys": ["CntVKykYCkz2zqivoszMBUVZLN1iv3fxvAabfFim849r"]}                                                                                                                                              
Invitation response:
  {
    "state": "request",
    "my_did": "16mzXdXL1fnBNkch6cuB8V",
    "connection_id": "864e61d5-5364-4e91-9bfd-517231e6efa3",
    "initiator": "external",
    "created_at": "2020-11-20 18:47:21.016895Z",
    "updated_at": "2020-11-20 18:47:21.046567Z",
    "invitation_key": "CntVKykYCkz2zqivoszMBUVZLN1iv3fxvAabfFim849r",
    "routing_state": "none",
    "their_label": "Faber.Agent",
    "request_id": "99435ff4-5e93-4749-9942-1dace9f071c0",
    "invitation_mode": "once",
    "accept": "auto"
  }
  
Alice      | 2020-11-20 18:47:21,763 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://7f11e8dcfa44.ngrok.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 404, caused by: Not Found',), <traceback object at 0x7f3842cef108>); Re-queue failed message ...
Alice      | 2020-11-20 18:47:32,199 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://7f11e8dcfa44.ngrok.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 404, caused by: Not Found',), <traceback object at 0x7f3842cef808>); Re-queue failed message ...
Alice      | 2020-11-20 18:47:42,746 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://7f11e8dcfa44.ngrok.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 404, caused by: Not Found',), <traceback object at 0x7f3842deac48>); Re-queue failed message ...
Alice      | 2020-11-20 18:47:53,191 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://7f11e8dcfa44.ngrok.io; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTransportError('Unexpected response status 404, caused by: Not Found',), <traceback object at 0x7f3850064f48>); Re-queue failed message ...
Alice      | 2020-11-20 18:48:03,664 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/transport/outbound/http.py", line 72, in handle_message
Alice      |     f"Unexpected response status {response.status}, "
Alice      | aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 404, caused by: Not Found
Alice      | 2020-11-20 18:48:03,665 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered to http://7f11e8dcfa44.ngrok.io
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/transport/outbound/http.py", line 72, in handle_message
Alice      |     f"Unexpected response status {response.status}, "
Alice      | aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 404, caused by: Not Found

**Comment by guilherme-funchal** [comment]
After I'm updated my Docker installation and reinstall all containers it's works.

thanks
