### ISSUE TITLE
Error while using Postgres as database for Aries Agent

### ISSUE THREAD

**Issue by Knightmare25** [hyperledger/aries-cloudagent-python#806]
I am trying to run aries agent with postgres as database deployed on azure. I am getting below error

```
2020-11-26 04:49:28,020 indy.libindy.native.indy.commands DEBUG         src/commands/mod.rs:150 | WalletCommand command received
2020-11-26 04:49:28,021 indy.libindy.native.wallet_command_executor DEBUG       src/commands/wallet.rs:138 | CreateContinue command received
2020-11-26 04:49:28,021 indy.libindy.native.indystrgpostgres ERROR      src/lib.rs:190 | Create storage failed: IOError("IO error during storage operation: invalid connection parameters")
2020-11-26 04:49:28,021 indy.libindy DEBUG _get_error_details: >>>
2020-11-26 04:49:28,021 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Wallet storage error occurred\n  Caused by: Plugin returned error\n'}
2020-11-26 04:49:28,021 indy.libindy DEBUG _indy_callback: >>> command_handle: 1, err , args: ()
2020-11-26 04:49:28,022 indy.libindy DEBUG _indy_callback: <<<
2020-11-26 04:49:28,025 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 1, err , args: ()
2020-11-26 04:49:28,025 indy.libindy WARNING _indy_loop_callback: Function returned error
2020-11-26 04:49:28,026 indy.libindy DEBUG _indy_loop_callback <<<
2020-11-26 04:49:28,027 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 179, in create
    credentials=json.dumps(self._wallet_access),
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
    create_wallet.cb)
indy.error.WalletStorageError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 77, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 27, in start_app
    await conductor.start()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 146, in start
    public_did = await wallet_config(context)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/wallet.py", line 16, in wallet_config
    wallet: BaseWallet = await context.inject(BaseWallet)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/injection_context.py", line 126, in inject
    return await self.injector.inject(base_cls, settings, required=required)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/injector.py", line 77, in inject
    result = await provider.provide(ext_settings, self)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/provider.py", line 83, in provide
    self._instance = await self._provider.provide(config, injector)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/provider.py", line 106, in provide
    instance = await self._provider.provide(config, injector)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/provider.py", line 40, in provide
    await wallet.open()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 244, in open
    await self.create(self._auto_remove)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 188, in create
    ) from x_indy
aries_cloudagent.wallet.error.WalletError: Exception while performing indy operation: Error: Wallet storage error occurred
  Caused by: Plugin returned error


Shutting down
```
Its say ```IO error during storage operation: invalid connection parameters```, but  i am able to connect to database using the credential from DBbeaver. I am using the below command for running the python agent 

```
docker run -d -p 5000:5000 -p 10000:10000 --name postgrearies bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1 start -it http 0.0.0.0 10000 -ot http --admin 0.0.0.0 5000 --admin-insecure-mode --seed 00000000000000000000111111111110 --endpoint http://localhost:10000 --genesis-url http://test.bcovrin.vonx.io/genesis --wallet-type indy --log-level debug --storage-type indy --wallet-type indy --wallet-storage-type postgres_storage --wallet-storage-config "{\"url\":\"myurl.postgres.database.azure.com:5432\",\"wallet_scheme\":\"DatabasePerWallet\"}" --wallet-storage-creds "{\"account\":\"myaries@myurl\",\"password\":\"mysecretpassword\",\"admin_account\":\"myaries@myurl\",\"admin_password\":\"mysecretpassword\"}"

```

**Comment by ianco** [comment]
When you connect using DBbeaver, are you connecting from the aries agent pod?

Your connection parameters look ok, possibly the db hostname ("myurl.postgres.database.azure.com:5432") is not reachable from the aries pod?

**Comment by paliwalg** [comment]
I am also facing similar issue. When the wallet DB is postgres and is configured to run on the ubuntu instance it works fine.
But when I create the Postgres instance in the azure cloud using "Azure Database for PostgreSQL" I am seeing exactly same error.
Postgres version used here is 10.
Does the postgres_storage plugin (https://github.com/hyperledger/indy-sdk/tree/master/experimental/plugins/postgres_storage) supports postgres for windows also ?
Not sure if this error is because of that.

**Comment by andrewwhitehead** [comment]
It looks like the account and password parts of the connection URL might
need to be URL-escaped. There might additionally be an issue with the TLS
connection.

**Comment by ianco** [comment]
The postgres plug-in doesn't support tls.  There's an outstanding PR to add this (you can give it a try but I couldn't get it to build):  https://github.com/hyperledger/indy-sdk/pull/2157

**Comment by paliwalg** [comment]
I have disabled TLS for now. 
I got it working now to an extent. 

I see following in the logs 
---------------------------------------------------------------------------------------
aca-py_1  | 2020-12-01 18:07:31,883 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG         src/postgres_storage.rs:663 | connecting to postgres, url_base: "postgresql://user%40host:password@host.postgres.database.azure.com:5432"
aca-py_1  | 2020-12-01 18:07:31,898 indy.libindy.native.indystrgpostgres ERROR  src/lib.rs:190 | Create storage failed: IOError("IO error during storage operation: database error")
---------------------------------------------------------------------------------------
I think the url_base should also include postgres database as url_base: "postgresql://user%40host:password@host.postgres.database.azure.com:5432/postgres"
To get this URL I end up specifying port :   5432/postgres.

With these changes, it is able to connect to the postgres database and is able to create the wallet database as well, but it fails while opening the wallet with the error database does not exist. Below is the extract from the logs.

-----------------------------------------------------------------------------------------
ca-py_1  | 2020-12-01 18:15:17,907 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG         src/postgres_storage.rs:663 | connecting to postgres, url_base: "postgresql://user%40host:password@host.postgres.database.azure.com:5432/postgres"
aca-py_1  | 2020-12-01 18:15:18,160 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG         src/postgres_storage.rs:666 | creating wallets DB
aca-py_1  | 2020-12-01 18:15:18,160 indy.libindy.native.postgres DEBUG  /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:489 | preparing query with name ``: CREATE DATABASE "oidc_agent_wallet"
aca-py_1  | 2020-12-01 18:15:18,162 indy.libindy.native.postgres DEBUG  /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/lib.rs:608 | executing statement  with parameters: []
aca-py_1  | 2020-12-01 18:15:19,831 indy.libindy.native.indystrgpostgres.postgres_storage DEBUG         src/postgres_storage.rs:676 | connecting to wallet as user
aca-py_1  | 2020-12-01 18:15:20,026 indy.libindy.native.indystrgpostgres ERROR  src/lib.rs:190 | Create storage failed: IOError("Error occurred while connecting to wallet schema: database error: FATAL: database \"postgres/oidc_agent_wallet\" does not exist")
-------------------------------------------------------------------------------------

After connecting to postgres database, I can see that a database with name oidc_agent_wallet is getting created.

Thoughts !!!

Thanks

**Comment by paliwalg** [comment]
It might be related to postgres autodiscover db flag defaulting to true. Not sure how to turn it off so that I don't have to specify the DB Name in the connection string.

**Comment by andrewwhitehead** [comment]
I believe the `postgres` database always exists and it might make sense to change the admin URL (used when connecting for the purpose of creating a new database) to connect to this database instead of leaving it unspecified.

**Comment by swcurran** [comment]
Closing issue.
