### ISSUE TITLE
Running the demo on a raspberry pi - agent not starting

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#88]
A user reporting running ACA-Py demo on a raspberry pi. The user has the demo running on a regular system, but it's failing to start up on the Pi, with the following details:

> First I started a von-network on my PC (raspberry pi was in the same network) following the guide here: https://github.com/bcgov/von-network#running-the-network-locally

> Then on pi in Aries-cloud-agent directory I execute:

```
python3.6 -m venv env source env/bin/activate pip3 install wheel pip3 install -e .
pip3 install prompt_toolkit pygments python3-indy
cd demo
LEDGER_URL=http://192.168.31.186:9000 python3.6 -m runners.faber -p 8020
```

On the Pi I run:

```
LEDGER_URL=http://192.168.31.186:9000 python3.6 -m runners.faber -p 8020
```

Resulting Log:

```
#1 Provision an agent and wallet, get back configuration details
Faber | Registering Faber Agent with seed d_000000000000000000000000459545
Faber | Got DID: UyUZWxhdbonVygFjy1ZLWy
Faber |
Faber | Shutting down
Faber | Exited with return code 0
Traceback (most recent call last):
File "/usr/local/lib/python3.6/runpy.py", line 193, in runmodule_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.6/runpy.py", line 85, in runcode
exec(code, run_globals)
File "/home/pi/aries-cloudagent-python/demo/runners/faber.py", line 248, in <module>
asyncio.get_event_loop().run_until_complete(main(args.port, args.timing))
File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
return future.result()
File "/home/pi/aries-cloudagent-python/demo/runners/faber.py", line 117, in main
await agent.start_process()
File "/home/pi/aries-cloudagent-python/demo/runners/support/agent.py", line 286, in start_process
await self.detect_process()
File "/home/pi/aries-cloudagent-python/demo/runners/support/agent.py", line 373, in detect_process
raise Exception(f"Timed out waiting for agent process to start")
Exception: Timed out waiting for agent process to start
```

**Comment by swcurran** [comment]
Suggestions from the team:

> It could mean that the URL it's using to access the admin API is wrong. It looks like outside of docker/pwd that defaults to 127.0.0.1:admin_port
> Or could be a firewall issue I suppose
> It registered the DID so it seems to be able to contact the local von-network
> Oh, I just noticed it's silently shutting down without printing the banner. That's odd
> Maybe run it with LOG_LEVEL=debug in the environment

Another thought to confirm access to the ledger:

Try: `curl http://192.168.31.186:9000/genesis` from the PI. It will either give you the genesis file or not (if for example it's an IP only visible on the docker network)

**Comment by swcurran** [comment]
A further follow up on this from one of the devs:

> My guess about the admin URL isn't relevant, the agent doesn't seem to be getting far enough to test that

**Comment by zzx02** [comment]
Thanks for opening this issue, I tried `curl http://192.168.31.186:9000/genesis` and it returns the genesis file.
Using LOG_LEVEL=debug, I get the following:

```
(env) pi@raspberrypi:~/aries-cloudagent-python/demo $ LEDGER_URL=http://192.168.31.186:9000 LOG_LEVEL=debug python3.6 -m runners.faber -p 8020
#1 Provision an agent and wallet, get back configuration details
Faber      | Registering Faber Agent with seed d_000000000000000000000000573764
Faber      | Got DID: BZVgRaN2Whg3hmMZ4U8sm7
Faber      | 2019-07-19 03:42:00,186 asyncio DEBUG Using selector: EpollSelector
Faber      | 2019-07-19 03:42:00,204 aries_cloudagent.wallet.provider INFO Opening wallet type: indy
Faber      | 2019-07-19 03:42:00,242 indy.wallet DEBUG open_wallet: >>> config: '{"id": "faberagent573764", "freshness_time": false, "storage_type": null}', credentials: '{"key": "Faber Agent573764"}'
Faber      | 2019-07-19 03:42:00,243 indy.wallet DEBUG open_wallet: Creating callback
Faber      | 2019-07-19 03:42:00,243 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
Faber      | 2019-07-19 03:42:00,250 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x757a0dc0>
Faber      | 2019-07-19 03:42:00,257 indy.libindy DEBUG do_call: >>> name: indy_open_wallet, args: (c_char_p(1970767408), c_char_p(1968411296), <CFunctionType object at 0x757a0dc0>)
Faber      | 2019-07-19 03:42:00,257 indy.libindy DEBUG _load_cdll: >>>
Faber      | 2019-07-19 03:42:00,258 indy.libindy DEBUG _load_cdll: Detected OS name: linux
Faber      | 2019-07-19 03:42:00,258 indy.libindy DEBUG _load_cdll: Resolved libindy name is: libindy.so
Faber      | 2019-07-19 03:42:00,262 indy.libindy DEBUG _load_cdll: <<< res: <CDLL 'libindy.so', handle a9fe80 at 0x7551bad0>
Faber      | 2019-07-19 03:42:00,268 indy.libindy DEBUG set_logger: >>>
Faber      | 2019-07-19 03:42:00,270 indy.libindy DEBUG do_call_sync: >>> name: indy_set_logger, args: (None, None, <CFunctionType object at 0x757a0ea0>, None)
Faber      | 2019-07-19 03:42:00,271 indy.libindy DEBUG do_call_sync: <<< 0
Faber      | 2019-07-19 03:42:00,277 indy.libindy DEBUG set_logger: <<<
Faber      | 2019-07-19 03:42:00,278 indy.libindy.native.command_executor INFO 	src/commands/mod.rs:99 | Worker thread started
Faber      | 2019-07-19 03:42:00,279 indy.libindy DEBUG do_call: Function indy_open_wallet returned err: 0
Faber      | 2019-07-19 03:42:00,285 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:148 | WalletCommand command received
Faber      | 2019-07-19 03:42:00,280 indy.libindy DEBUG do_call: <<< <Future pending>
Faber      | 2019-07-19 03:42:00,286 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:141 | Open command received
Faber      | 2019-07-19 03:42:00,288 indy.libindy DEBUG _get_error_details: >>>
Faber      | 2019-07-19 03:42:00,288 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Wallet not found\n  Caused by: No wallet database exists\n'}
Faber      | 2019-07-19 03:42:00,289 indy.libindy DEBUG _indy_callback: >>> command_handle: 0, err (<ErrorCode.WalletNotFoundError: 204>, {'backtrace': '', 'message': 'Error: Wallet not found\n  Caused by: No wallet database exists\n'}), args: (0,)
Faber      | 2019-07-19 03:42:00,289 indy.libindy DEBUG _indy_callback: <<<
Faber      | 2019-07-19 03:42:00,290 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 0, err (<ErrorCode.WalletNotFoundError: 204>, {'backtrace': '', 'message': 'Error: Wallet not found\n  Caused by: No wallet database exists\n'}), args: (0,)
Faber      | 2019-07-19 03:42:00,290 indy.libindy WARNING _indy_loop_callback: Function returned error (<ErrorCode.WalletNotFoundError: 204>, {'backtrace': '', 'message': 'Error: Wallet not found\n  Caused by: No wallet database exists\n'})
Faber      | 2019-07-19 03:42:00,297 indy.libindy DEBUG _indy_loop_callback <<<
Faber      | 2019-07-19 03:42:00,297 indy.wallet DEBUG create_wallet: >>> config: '{"id": "faberagent573764", "freshness_time": false, "storage_type": null}', credentials: '{"key": "Faber Agent573764"}'
Faber      | 2019-07-19 03:42:00,298 indy.wallet DEBUG create_wallet: Creating callback
Faber      | 2019-07-19 03:42:00,298 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
Faber      | 2019-07-19 03:42:00,299 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x75546030>
Faber      | 2019-07-19 03:42:00,305 indy.libindy DEBUG do_call: >>> name: indy_create_wallet, args: (c_char_p(1970767504), c_char_p(1968476304), <CFunctionType object at 0x75546030>)
Faber      | 2019-07-19 03:42:00,306 indy.libindy DEBUG do_call: Function indy_create_wallet returned err: 0
Faber      | 2019-07-19 03:42:00,306 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:148 | WalletCommand command received
Faber      | 2019-07-19 03:42:00,306 indy.libindy DEBUG do_call: <<< <Future pending>
Faber      | 2019-07-19 03:42:00,307 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:133 | Create command received
Faber      | 2019-07-19 03:42:00,308 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:148 | WalletCommand command received
Faber      | 2019-07-19 03:42:00,308 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:181 | DeriveKey command received
Faber      | 2019-07-19 03:42:13,560 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:148 | WalletCommand command received
Faber      | 2019-07-19 03:42:13,561 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:137 | CreateContinue command received
Faber      | 2019-07-19 03:42:13,655 indy.libindy DEBUG _indy_callback: >>> command_handle: 1, err ErrorCode.Success, args: ()
Faber      | 2019-07-19 03:42:13,656 indy.libindy DEBUG _indy_callback: <<<
Faber      | 2019-07-19 03:42:13,656 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 1, err ErrorCode.Success, args: ()
Faber      | 2019-07-19 03:42:13,656 indy.libindy DEBUG _indy_loop_callback: Function returned None
Faber      | 2019-07-19 03:42:13,657 indy.libindy DEBUG _indy_loop_callback <<<
Faber      | 2019-07-19 03:42:13,657 indy.wallet DEBUG create_wallet: <<<
Faber      | 2019-07-19 03:42:13,658 indy.wallet DEBUG open_wallet: >>> config: '{"id": "faberagent573764", "freshness_time": false, "storage_type": null}', credentials: '{"key": "Faber Agent573764"}'
Faber      | 2019-07-19 03:42:13,658 indy.libindy DEBUG do_call: >>> name: indy_open_wallet, args: (c_char_p(1970767408), c_char_p(1968459328), <CFunctionType object at 0x757a0dc0>)
Faber      | 2019-07-19 03:42:13,659 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:148 | WalletCommand command received
Faber      | 2019-07-19 03:42:13,659 indy.libindy DEBUG do_call: Function indy_open_wallet returned err: 0
Faber      | 2019-07-19 03:42:13,659 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:141 | Open command received
Faber      | 2019-07-19 03:42:13,660 indy.libindy DEBUG do_call: <<< <Future pending>
Faber      | 2019-07-19 03:42:13,691 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:148 | WalletCommand command received
Faber      | 2019-07-19 03:42:13,691 indy.libindy.native.wallet_command_executor DEBUG 	src/commands/wallet.rs:181 | DeriveKey command received
Faber      |
Faber      | Shutting down
Faber      | Exited with return code 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/aries-cloudagent-python/demo/runners/faber.py", line 248, in <module>
    asyncio.get_event_loop().run_until_complete(main(args.port, args.timing))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/pi/aries-cloudagent-python/demo/runners/faber.py", line 117, in main
    await agent.start_process()
  File "/home/pi/aries-cloudagent-python/demo/runners/support/agent.py", line 286, in start_process
    await self.detect_process()
  File "/home/pi/aries-cloudagent-python/demo/runners/support/agent.py", line 373, in detect_process
    raise Exception(f"Timed out waiting for agent process to start")
Exception: Timed out waiting for agent process to start
```

**Comment by andrewwhitehead** [comment]
It looks like the wallet's DeriveKey just runs very slowly on the Raspberry pi (13+ seconds) and the demo is timing out waiting for the agent to start. The `detect_process` method in `agent.py` currently waits 20 seconds but we could probably add a command line argument to adjust this.

**Comment by zzx02** [comment]
I tried increasing the timeout, it works for that problem, but I meet another problem, which shows
```
Faber      | 2019-07-25 14:48:07,951 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 0
Faber      | 2019-07-25 14:48:07,953 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 1
Faber      | 2019-07-25 14:48:07,953 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 2
Faber      | 2019-07-25 14:48:07,954 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 3
Faber      | 2019-07-25 14:49:08,015 indy.libindy.native.zmq DEBUG 	/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:503 | socket dropped
Faber      | 2019-07-25 14:49:08,016 indy.libindy.native.zmq DEBUG 	/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:503 | socket dropped
Faber      | 2019-07-25 14:49:08,017 indy.libindy.native.zmq DEBUG 	/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:503 | socket dropped
Faber      | 2019-07-25 14:49:08,017 indy.libindy.native.zmq DEBUG 	/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:503 | socket dropped
Faber      | 2019-07-25 14:49:08,018 indy.libindy.native.zmq DEBUG 	/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:410 | context dropped
Faber      | 2019-07-25 14:49:08,020 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
Faber      | 2019-07-25 14:49:08,021 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:74 | OpenAck handle 4, pool_id 4, result Err(IndyError { inner:
Faber      |
Faber      | Pool timeout
Faber      |
Faber      | Pool timeout })
Faber      | 2019-07-25 14:49:08,022 indy.libindy DEBUG _get_error_details: >>>
Faber      | 2019-07-25 14:49:08,022 indy.libindy DEBUG _get_error_details: <<< error_details: {'backtrace': '', 'message': 'Error: Pool timeout\n  Caused by: Pool timeout\n'}
Faber      | 2019-07-25 14:49:08,023 indy.libindy DEBUG _indy_callback: >>> command_handle: 11, err (<ErrorCode.PoolLedgerTimeout: 307>, {'backtrace': '', 'message': 'Error: Pool timeout\n  Caused by: Pool timeout\n'}), args: (0,)
Faber      | 2019-07-25 14:49:08,024 indy.libindy DEBUG _indy_callback: <<<
Faber      | 2019-07-25 14:49:08,024 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 11, err (<ErrorCode.PoolLedgerTimeout: 307>, {'backtrace': '', 'message': 'Error: Pool timeout\n  Caused by: Pool timeout\n'}), args: (0,)
Faber      | 2019-07-25 14:49:08,025 indy.libindy WARNING _indy_loop_callback: Function returned error (<ErrorCode.PoolLedgerTimeout: 307>, {'backtrace': '', 'message': 'Error: Pool timeout\n  Caused by: Pool timeout\n'})
Faber      | 2019-07-25 14:49:08,026 indy.libindy DEBUG _indy_loop_callback <<<
Faber      | 2019-07-25 14:49:08,027 asyncio ERROR Task exception was never retrieved
Faber      | future: <Task finished coro=<start_app() done, defined at /home/pi/aries-cloudagent-python/aries_cloudagent/__init__.py:27> exception=IndyError(<ErrorCode.PoolLedgerTimeout: 307>, {'backtrace': '', 'message': 'Error: Pool timeout\n  Caused by: Pool timeout\n'})>
Faber      | Traceback (most recent call last):
Faber      |   File "/home/pi/aries-cloudagent-python/aries_cloudagent/__init__.py", line 30, in start_app
Faber      |     await conductor.start()
Faber      |   File "/home/pi/aries-cloudagent-python/aries_cloudagent/conductor.py", line 174, in start
Faber      |     async with ledger:
Faber      |   File "/home/pi/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 172, in __aenter__
Faber      |     await self._context_open()
Faber      |   File "/home/pi/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 142, in _context_open
Faber      |     await self.open()
Faber      |   File "/home/pi/aries-cloudagent-python/aries_cloudagent/ledger/indy.py", line 124, in open
Faber      |     self.pool_handle = await indy.pool.open_pool_ledger(self.name, "{}")
Faber      |   File "/home/pi/aries-cloudagent-python/env/lib/python3.6/site-packages/indy/pool.py", line 82, in open_pool_ledger
Faber      |     open_pool_ledger.cb)
Faber      | indy.error.IndyError: (<ErrorCode.PoolLedgerTimeout: 307>, {'backtrace': '', 'message': 'Error: Pool timeout\n  Caused by: Pool timeout\n'})
```
I guess if it related to the genesis file or ip settings and what is the best practice to configure these things? But even if I execute `GENESIS_URL=http://192.168.31.186:9000/genesis LEDGER_URL=http://192.168.31.186:9000 LOG_LEVEL=debug python3.6 -m runners.faber -p 8020`, the error persists the same.

**Comment by ianco** [comment]
"Pool timeout" usually means the indy sdk is tryong to connect to the pool using the wrong IP

Check the output from http://192.168.31.186:9000/genesis (should contain the IP's of the indy nodes) and then make sure wherever you are running aca-py can connect to these IP's

**Comment by andrewwhitehead** [comment]
It could be the same issue with crypto operations just taking too long, especially if the ledger is running on the same machine. I've seen some talk about kernel extensions and custom OpenSSL builds for the Pi to take advantage of hardware support for the crypto operations, but I don't remember any specifics, or if the current CPU or graphics chips even have such support.

**Comment by zzx02** [comment]
Thanks for updating, I configured the IPs, and now it should have connections to pool nodes. However, I am getting another error, which doesn't exist when I was running the demo on PC, below are the some of the latest logs:

```
Faber      | 2019-08-13 04:10:28,944 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 0
Faber      | 2019-08-13 04:10:28,946 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 1
Faber      | 2019-08-13 04:10:28,947 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 2
Faber      | 2019-08-13 04:10:28,948 indy.libindy.native.indy.services.pool.networker DEBUG 	src/services/pool/networker.rs:332 | _get_socket: open new socket for node 3
Faber      | 2019-08-13 04:10:29,615 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:140 | PoolCommand command received
Faber      | 2019-08-13 04:10:29,616 indy.libindy.native.indy.commands.pool INFO 	src/commands/pool.rs:75 | OpenAck handle 4, pool_id 4, result Ok(())
Faber      | 2019-08-13 04:10:29,617 indy.libindy DEBUG _indy_callback: >>> command_handle: 13, err ErrorCode.Success, args: (4,)
Faber      | 2019-08-13 04:10:29,617 indy.libindy DEBUG _indy_callback: <<<
Faber      | 2019-08-13 04:10:29,618 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 13, err ErrorCode.Success, args: (4,)
Faber      | 2019-08-13 04:10:29,618 indy.libindy DEBUG _indy_loop_callback: Function returned 4
Faber      | 2019-08-13 04:10:29,618 indy.libindy DEBUG _indy_loop_callback <<<
Faber      | 2019-08-13 04:10:29,619 indy.pool DEBUG open_pool_ledger: <<< res: 4
Faber      | 2019-08-13 04:10:29,619 indy.did DEBUG list_my_dids_with_meta: >>> wallet_handle: 3
Faber      | 2019-08-13 04:10:29,620 indy.libindy DEBUG do_call: >>> name: indy_list_my_dids_with_meta, args: (c_long(3), <CFunctionType object at 0x74fb3ce0>)
Faber      | 2019-08-13 04:10:29,621 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:144 | DidCommand command received
Faber      | 2019-08-13 04:10:29,621 indy.libindy.native.indy.commands.did INFO 	src/commands/did.rs:144 | ListMyDidsWithMeta command received
Faber      | 2019-08-13 04:10:29,621 indy.libindy.native.indy.commands.did DEBUG 	src/commands/did.rs:290 | list_my_dids_with_meta >>> wallet_handle: 3
Faber      | 2019-08-13 04:10:29,623 indy.libindy.native.indy.commands.did DEBUG 	src/commands/did.rs:321 | list_my_dids_with_meta <<< res: "[{\"did\":\"Gnp6wjnxYHmETewcx8dptc\",\"verkey\":\"9c9dKmtkwkb3J72M2oABbqKfV55sJkuZruPbGdviFPU6\",\"tempVerkey\":null,\"metadata\":\"{\\\"public\\\": true}\"}]"
Faber      | 2019-08-13 04:10:29,623 indy.libindy DEBUG _indy_callback: >>> command_handle: 14, err ErrorCode.Success, args: (b'[{"did":"Gnp6wjnxYHmETewcx8dptc","verkey":"9c9dKmtkwkb3J72M2oABbqKfV55sJkuZruPbGdviFPU6","tempVerkey":null,"metadata":"{\\"public\\": true}"}]',)
Faber      | 2019-08-13 04:10:29,624 indy.libindy DEBUG _indy_callback: <<<
Faber      | 2019-08-13 04:10:29,624 indy.libindy DEBUG do_call: Function indy_list_my_dids_with_meta returned err: 0
Faber      | 2019-08-13 04:10:29,625 indy.libindy DEBUG do_call: <<< <Future pending>
Faber      | 2019-08-13 04:10:29,625 indy.libindy DEBUG _indy_loop_callback: >>> command_handle: 14, err ErrorCode.Success, args: (b'[{"did":"Gnp6wjnxYHmETewcx8dptc","verkey":"9c9dKmtkwkb3J72M2oABbqKfV55sJkuZruPbGdviFPU6","tempVerkey":null,"metadata":"{\\"public\\": true}"}]',)
Faber      | 2019-08-13 04:10:29,625 indy.libindy DEBUG _indy_loop_callback: Function returned b'[{"did":"Gnp6wjnxYHmETewcx8dptc","verkey":"9c9dKmtkwkb3J72M2oABbqKfV55sJkuZruPbGdviFPU6","tempVerkey":null,"metadata":"{\\"public\\": true}"}]'
Faber      | 2019-08-13 04:10:29,626 indy.libindy DEBUG _indy_loop_callback <<<
Faber      | 2019-08-13 04:10:29,626 indy.did DEBUG list_my_dids_with_meta: <<< res: '[{"did":"Gnp6wjnxYHmETewcx8dptc","verkey":"9c9dKmtkwkb3J72M2oABbqKfV55sJkuZruPbGdviFPU6","tempVerkey":null,"metadata":"{\\"public\\": true}"}]'
Faber      | 2019-08-13 04:10:29,627 indy.ledger DEBUG build_get_acceptance_mechanisms_request: >>> submitter_did: 'Gnp6wjnxYHmETewcx8dptc', timestamp: None, version: None
Faber      | 2019-08-13 04:10:29,627 indy.ledger DEBUG build_get_acceptance_mechanisms_request: Creating callback
Faber      | 2019-08-13 04:10:29,627 indy.libindy DEBUG create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
Faber      | 2019-08-13 04:10:29,628 indy.libindy DEBUG create_cb: <<< res: <CFunctionType object at 0x74f84650>
Faber      | 2019-08-13 04:10:29,628 indy.libindy DEBUG do_call: >>> name: indy_build_get_acceptance_mechanisms_request, args: (c_char_p(1962469056), c_long(-1), None, <CFunctionType object at 0x74f84650>)
Faber      | 2019-08-13 04:10:29,629 indy.libindy.native.indy.commands INFO 	src/commands/mod.rs:136 | LedgerCommand command received
Faber      | 2019-08-13 04:10:29,629 indy.libindy.native.ledger_command_executor INFO 	src/commands/ledger.rs:490 | BuildGetAcceptanceMechanismsRequest command received
Faber      | 2019-08-13 04:10:29,630 indy.libindy.native.indy.commands.ledger DEBUG 	src/commands/ledger.rs:1144 | build_get_acceptance_mechanisms_request >>> submitter_did: Some("Gnp6wjnxYHmETewcx8dptc"), timestamp: Some(4294967295), version: Some("\u{f}")
Faber      | 2019-08-13 04:10:29,630 indy.libindy.native.indy.services.ledger INFO 	src/services/ledger/mod.rs:461 | build_get_acceptance_mechanisms_request() => Err(IndyError { inner:
Faber      |
Faber      | timestamp and version cannot be specified together.
Faber      |
Faber      | Invalid structure })
```

**Comment by arner** [comment]
I get the same last error on a Raspberry Pi 4 in Docker. See the installation process here:
https://github.com/arner/arm32v7-aries-cloud-agent/blob/061342b0d0ff550c2d11af8998532199aa9cb73c/agent/Dockerfile

And here:
https://github.com/arner/arm32v7-aries-cloud-agent/blob/061342b0d0ff550c2d11af8998532199aa9cb73c/demo/Dockerfile

**Comment by andrewwhitehead** [comment]
I think this could happen if the python wrapper version doesn't match the indy-sdk version, but I can't reproduce it myself. Please check the output of `pip freeze` for the python3-indy version.

**Comment by arner** [comment]
aries-cloudagent==0.3.2
indy-sdk==0.0.1.post152
python3-indy==1.11.1

Besides installing indy-sdk with pip3, built the library v1.11.1 from source with libsodium statically linked (cargo build --release --features sodium_static).

**Comment by swcurran** [comment]
Developer reported that they got this working as part of a Hyperledger Internship. Closing for now.

**Comment by eorituz** [comment]
Unfortunately, the issue still persists @swcurran.
I'm running in the same error on my RPi 4 as arner and zzx02. While using the latest versions/releases of indy-sdk, python3-indy and aries-cloudagent:
```
python3-indy==1.15.0
aries-cloudagent==0.5.1
indy-sdk release 0.15.0
```
Could you point me/us towards the fix?

**Comment by WadeBarnes** [comment]
@eorituz, The related `Raspberry-Pi-Indy` repositories are here; https://github.com/zzx02?tab=repositories.  The related tutorial is here; https://wiki.hyperledger.org/display/INTERN/Collaboration%3A+Raspberry+Pi+Indy+Agent

That said, running all of this on bare metal can be a challenge to say the least.  I'm working with (providing guidance) another fellow on a containerized implementation for the RPi.  I've asked if there is any material that can be shared so we can promote collaboration on this topic.  I'm also looking at a Hyperledger Chat channel for such collaboration.

**Comment by WadeBarnes** [comment]
@eorituz, The new [Hyperledger Chat](https://chat.hyperledger.org/) channel is `#aries-embedded`

**Comment by eorituz** [comment]
The timestamp error is fixed with https://github.com/hyperledger/indy-sdk/pull/2210 
The issue was with a wrong cast in the python wrapper.
CC @arner

**Comment by WadeBarnes** [comment]
@eorituz, Thanks for the update on the resolution.

**Comment by arner** [comment]
> is any material that can be shared so we can promote collaboration on this topic. I'm also looking into a Hyperledger Chat channel for such collaboration.

In this thread, I linked two dockerfiles that I created for dockerizing it (will need some updating by now, I haven't looked into it since this bug came up). Feel free to use them and let me know if you find more people working on it, running your own agent on a Pi can be great for exploring and testing.

**Comment by WadeBarnes** [comment]
> @eorituz, The new [Hyperledger Chat](https://chat.hyperledger.org/) channel is `#aries-embedded`

@arner, We started a channel here ^

**Comment by srbms23** [comment]
Hi @eorituz and @arner ,

I am struggling to make Agent work on my Pi. Have you managed to do that somehow?

I explained the steps that I´ve done and errors that I get here: [von-network with Raspberry Pi 4 #140](https://github.com/bcgov/von-network/issues/140).
Could you take a look (if you have time) and tell me if something is missing or even better write down the steps that you´ve done to make it work.
 
I would really appreciate your help!

Thanks a lot for your time!
