### ISSUE TITLE
400: Connection is not in the request or response state.

### ISSUE THREAD

**Issue by frogman** [hyperledger/aries-cloudagent-python#885]
Hi everyone,

I am testing initial communication between two ubuntu VPS servers (without firewalls) and I am getting the following error on accepting the request: 400: Connection is not in the request or response state.

The server acting as a connection receiver after calling the /connections/{conn_id}/accept-invitation I get the following:

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/aries-cloudagent-python/aries_cloudagent/transport/outbound/http.py", line 71, in handle_message
    async with self.client_session.post(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host xxxx.xxxx.xxx.xxx:80 ssl:default [Connect call failed ('xxxx.xxx.xxx.xxx', 80)] 

Then on the server that has sent the connection I have got the following:
Creating connection response
    connection_id: f533fd68-f677-47d7-9aa6-9e9bfe3476c0

2020-12-25 08:43:15,837 aries_cloudagent.admin.server ERROR Handler error with exception: Connection is not in the request or response state.

The version of aca-py is: 0.6.0-pre and I am using the Sovrin Builder Net

Thanks in advance.

**Comment by frogman** [comment]
Hi,

When I have changed the ACA-py parameter on both of the agents (vps servers) to have: --inbound-transport http 0.0.0.0 80 \  
on http port 80, then the connections went trough. Before I have had 10001 and 10000 ports. 
Seems that on default the aiohttp server is pushing the communication over port 80 (which is not optimal and should be some of the higher ports).

When making the /connections/create-invitation I have also tried to add in the json the: {
  "service_Endpoint": "http://xx.xx.x.xx:10001"
}

to somehow explicit say the port, but not sure if aiohttp server will get this.

Any insights would be great , to be able to test with higher ports (rather then port 80).

Kind regard.

There are my settings now:
--inbound-transport http 0.0.0.0 80 \
  --outbound-transport http \
  --debug --log-level DEBUG \
  --admin 0.0.0.0 9090 \
  --public-invites \
  --debug-connections \
  --admin-api-key

**Comment by TimoGlastra** [comment]
I think you're missing the `--endpoint` parameter to indicate where the messages should be sent to. ACA-Py will use this in invitations:

```
start 
--endpoint http://192.168.65.3:20000 
--inbound-transport http 0.0.0.0 20000 
--inbound-transport ws 0.0.0.0 20002 
--admin 0.0.0.0 20001 
--admin-insecure-mode 
--outbound-transport http 
--outbound-transport ws 
--auto-provision --recreate-wallet
```

**Comment by frogman** [comment]
Thanks a lot TimoG. I have used the endpoint but without a port. Now I can confirm this works fine.
