### ISSUE TITLE
Running Alice Faber Demo locally on macOS

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#90]
I am following the instructions here
https://github.com/hyperledger/aries-cloudagent-python/tree/master/demo#Running-Locally

The place where I get stuck is  here:

"
Alternately, you can run the ledger using von-network mechanism, or some other instance of the ledger. In those cases, you must provide the agents access to the ledger genesis file, and you must ensure that the agents have write access on that ledger.
"
Because I was able to get a von-network ledger in docker running fine I want to run the ledger that way. But its not clear how I provide agents access to the ledger genesis file in this case.??

I am assuming its not  cloudagentpy/demo/local-genesis.txt which the agents already have access too.

When I cd to my clone of the  von-network repo and run
$ ./manage start

The first message the console prints out is

WARNING: The GENESIS_URL variable is not set. Defaulting to a blank string.
WARNING: The ANONYMOUS variable is not set. Defaulting to a blank string.
WARNING: The LEDGER_SEED variable is not set. Defaulting to a blank string.
WARNING: The LEDGER_CACHE_PATH variable is not set. Defaulting to a blank string.
WARNING: The WEB_ANALYTICS_SCRIPT variable is not set. Defaulting to a blank string.
WARNING: The INFO_SITE_TEXT variable is not set. Defaulting to a blank string.
WARNING: The INFO_SITE_URL variable is not set. Defaulting to a blank string.

These warnings do not prevent the von-network ledger from running correctly and the docker versions of alice and faber apparently are able to use the same genesis file.

But when running alice and faber locally its not clear how to have both the von-network and the agents use the same genesis file.

Indeed what gets stored where is not documented. It would be helpful to have some description of what is being persisted on disk and where.

**Comment by SmithSamuelM** [comment]
If I just go ahead and run the faber agent without doing anything to setup the genesis file I get the following error.

#1 Provision an agent and wallet, get back configuration details
Faber      | Registering Faber Agent with seed d_000000000000000000000000655415
Faber      | Got DID: dTdsPpQPWxUxmDDM9TP1i
Faber      | 2019-07-20 14:51:40,854 asyncio ERROR Task exception was never retrieved
Faber      | future: <Task finished coro=<start_app() done, defined at /Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/__init__.py:27> exception=IndyError(<ErrorCode.CommonInvalidState: 112>, {'backtrace': '', 'message': 'Error: Invalid library state\n  Caused by: Ledger merkle tree is not acceptable for current tree.\n'})>
Faber      | Traceback (most recent call last):
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/__init__.py", line 30, in start_app
Faber      |     await conductor.start()
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/conductor.py", line 175, in start
Faber      |     async with ledger:
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 172, in __aenter__
Faber      |     await self._context_open()
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 142, in _context_open
Faber      |     await self.open()
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 124, in open
Faber      |     self.pool_handle = await indy.pool.open_pool_ledger(self.name, "{}")
Faber      |   File "/Data/Code/public/hyperledger/indy/indy-sdk/wrappers/python/indy/pool.py", line 82, in open_pool_ledger
Faber      |     open_pool_ledger.cb)
Faber      | indy.error.IndyError: (<ErrorCode.CommonInvalidState: 112>, {'backtrace': '', 'message': 'Error: Invalid library state\n  Caused by: Ledger merkle tree is not acceptable for current tree.\n'})
Faber      | 


This is the same error I got before.  So I suspect it is that the agent and the von-network are not using the same genesis file.

Do I find the default genesis-file in the von-network container?
Is there a parameter I pass into the docker ./manage start script for the Genesis. I could see a parameter for web_start but not start.

**Comment by SmithSamuelM** [comment]
I also tried running the pool using the indy-sdk
Use instructions in the indy-sdk repo to run a local ledger. 

https://github.com/hyperledger/aries-cloudagent-python/tree/master/demo#Running-Locally
$ cd indy-sdk/
1) Starting the test pool on localhost
Start the pool of local nodes on 127.0.0.1:9701-9708 with Docker by running:
$ docker build -f ci/indy-pool.dockerfile -t indy_pool .
$ docker run -itd -p 9701-9708:9701-9708 indy_pool

$ docker container ls
...  indy_pool


But the faber demo is looking for the pool on at different port 9000 and I couldn't change the ports properly to get it to work. Doubt that it would because the local genesis file would likely be wrong as well.

**Comment by SmithSamuelM** [comment]
I tried setting environment variables for the faber runner to point to the von-network url

The demo/run_demo  bash script looks for the environment variable LEDGER_URL
and the sets up the agent to use that and creates the associate GENESIS_URL
so maybe the .py files expect these

$ cd cloudagentpy/demo/
$ export LEDGER_URL="http://localhost:9000"
$ echo $LEDGER_URL
http://localhost:9000

$ export GENESIS_URL="http://localhost:9000/genesis"
$ echo $GENESIS_URL
http://localhost:9000/genesis


But still get this error

$ python3 -m runners.faber --port 8020

#1 Provision an agent and wallet, get back configuration details
Faber      | Registering Faber Agent with seed d_000000000000000000000000395464
Faber      | Got DID: 9cEs8TVxuCJSTn4nxLifzn
Faber      | 2019-07-20 20:02:22,266 asyncio ERROR Task exception was never retrieved
Faber      | future: <Task finished coro=<start_app() done, defined at /Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/__init__.py:27> exception=IndyError(<ErrorCode.CommonInvalidState: 112>, {'backtrace': '', 'message': 'Error: Invalid library state\n  Caused by: Ledger merkle tree is not acceptable for current tree.\n'})>
Faber      | Traceback (most recent call last):
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/__init__.py", line 30, in start_app
Faber      |     await conductor.start()
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/conductor.py", line 175, in start
Faber      |     async with ledger:
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 172, in __aenter__
Faber      |     await self._context_open()
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 142, in _context_open
Faber      |     await self.open()
Faber      |   File "/Data/Code/public/hyperledger/aries/cloudagentpy/aries_cloudagent/ledger/indy.py", line 124, in open
Faber      |     self.pool_handle = await indy.pool.open_pool_ledger(self.name, "{}")
Faber      |   File "/Data/Code/public/hyperledger/indy/indy-sdk/wrappers/python/indy/pool.py", line 82, in open_pool_ledger
Faber      |     open_pool_ledger.cb)
Faber      | indy.error.IndyError: (<ErrorCode.CommonInvalidState: 112>, {'backtrace': '', 'message': 'Error: Invalid library state\n  Caused by: Ledger merkle tree is not acceptable for current tree.\n'})
Faber      | 
Faber      | Shutting down
Faber      | Exited with return code 0


I also removed the wallets  in ~/.indy_client/wallet/faber*

I did run the postgres docker container but not sure that the faber client is using it because when I run the faber demo is creates new wallet directories. I assume if its using postgres it wouldn't

**Comment by SmithSamuelM** [comment]
So it seems to be stuck at the same point.

**Comment by ianco** [comment]
Hi @SmithSamuelM 

To run the demo locally I do the following:

1. Run the indy ledger as per the sdk:

$ docker build -f ci/indy-pool.dockerfile -t indy_pool .
$ docker run -itd -p 9701-9708:9701-9708 indy_pool

2. Run a local postgres database (if you want to use postgres wallets, you need to make a code change to pass "postgres=True" when initializing the agent):

docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres

3. Run the von-network ledger browser (note don't run the full von network, just run a local web server):

GENESIS_FILE=/.../local-genesis.txt PORT=9000 REGISTER_NEW_DIDS=true python -m server.server

Note that the ledger browser provides the services on port 9000 (to get genesis transactions, register DID's, etc)  Note also your local-genesis.txt should contain 127.0.0.1 as the node IP's

4. Then run the demo:

LEDGER_URL=http://localhost:9000 python3 -m runners.faber --port 8020

etc ...

This will use the local-genesis.txt by default.  You don't need to provide both LEDGER_URL and GENESIS_URL because the demo will figure out GENESIS_URL by default.  (You need to provide GENESIS_URL if you are using, for example, one of the Sovrin networks (they keep the genesis files on github))

Note that the Indy nodes are running on 127.0.0.1, but the ledger browser is running on port 9000

**Comment by swcurran** [comment]
@ianco - I think those are the same instructions as in the readme file, and I think Sam's following them.  The error is later, so worth a look at the stack trace.  Where is the error happening?  Perhaps ledger/wallet mismatch?

Sam, obviously we need to document the env. variables - here is a clarification, although I think you have it working.  If you run with von-network it provides a server and the genesis file is served at http://<ip>:9000/genesis so the LEDGER_URL (without the "genesis" part).  <ip> is usually localhost, but of course can vary based on your set up. If you run from the indy-sdk docker images, the local genesis file will work using the GENESIS_FILE env variable.

**Comment by ianco** [comment]
The error "Caused by: Ledger merkle tree is not acceptable for current tree." is a genesis file mis-match

**Comment by swcurran** [comment]
Ah... Thanks @ianco. Well there you go.

**Comment by SmithSamuelM** [comment]
Yippe it works.

Some corrections and additions to the instructions

Python 3
GENESIS_FILE=/.../local-genesis.txt PORT=9000 REGISTER_NEW_DIDS=true python3 -m server.server

Also the von network server has a couple of dependencies that need to be installed

$ pip3 install aiohttp_jinja2  
$ pip3 install aiosqlite


Too use postgres in the agents the environment variable is 
DEFAULT_POSGRES=true


running Faber

$ cd cloudagentpy/demo/
$ LEDGER_URL=http://localhost:9000 DEFAULT_POSTGRES=true python3 -m runners.faber --port 8020 

running alice
$ cd cloudagentpy/demo/
$ LEDGER_URL=http://localhost:9000 DEFAULT_POSTGRES=true python3 -m runners.alice --port 8030

**Comment by SmithSamuelM** [comment]
thanks.  I have some questions as too why this works and the other doesn't.

**Comment by swcurran** [comment]
Hi Sam - @ianco sent you a note via hyperledger rocketchat to connect and have a zoom session.
