### ISSUE TITLE
Storage for 0.6.0 not compatible with 0.5.6

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-cloudagent-python#958]
Connection records in ACA-Py 0.5.6 had an `initiator` prop. This property is removed in 0.6.0 / main branch. Retrieving connections now gives an error about an unknown property `initiator`. I know 0.6.0 introduces breaking changes, but the change of the storage voids all data persisted in previous version of ACA-Py.

So the question is whether it is expected that data persisted in 0.5.6 of ACA-Py is not valid anymore in 0.6.0? 

See error below, thanks!

```
2021-02-12 16:38:23,403 aries_cloudagent.core.dispatcher ERROR Handler error: connections_list
Traceback (most recent call last):
  File "/home/beri/Git/aries-cloudagent-python/aries_cloudagent/protocols/connections/v1_0/routes.py", line 336, in connections_list
    records = await ConnRecord.query(
  File "/home/beri/Git/aries-cloudagent-python/aries_cloudagent/messaging/models/base_record.py", line 295, in query
    result.append(cls.from_storage(record.id, vals))
  File "/home/beri/Git/aries-cloudagent-python/aries_cloudagent/messaging/models/base_record.py", line 111, in from_storage
    return cls(**params)
  File "/home/beri/Git/aries-cloudagent-python/aries_cloudagent/connections/models/conn_record.py", line 187, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'initiator'
2021-02-12 16:38:23,403 aries_cloudagent.admin.server ERROR Handler error with exception: __init__() got an unexpected keyword argument 'initiator'

```

**Comment by swcurran** [comment]
@andrewwhitehead @sklump @shaangill025 -- please take a look at this ASAP.  Is this something to be adjusted before 0.6.0?

Thanks for documenting this.

**Comment by sklump** [comment]
initiator was redundant vs. role, for what it's worth

**Comment by swcurran** [comment]
FYI - @sklump  is looking at restoring the property.  Lots of "fun" -- particularly with marshmallow to get the API defined.
